<?php

namespace Database\Seeders;

use App\Models\Prospect;
use Illuminate\Database\Seeder;

/**
 * Generated seeder — batch research-dentistas-ags-dedup-20260423.
 *
 * 58 dentistas descubiertos vía WebSearch + WebFetch, deduplicados contra prod.
 * Todos con teléfono MX de 10 dígitos. Asignados a Omar (user_id=100) con
 * source='prospecting' para que el cron send-prospect-emails los tome automático.
 * El batch identifier vive en notes.batch = 'research-dentistas-ags-dedup-20260423' para analytics.
 *
 * Ejecutar: php artisan db:seed --class=ProspectDentistasAGSPilotSeeder --force
 */
class ProspectDentistasAGSPilotSeeder extends Seeder
{
    public function run(): void
    {
        $prospects = [
            [
                'name' => 'Clínica Dental Aguascalientes CDEA',
                'clinic_name' => 'Clínica Dental Aguascalientes CDEA',
                'specialty' => 'Ortodoncia',
                'city' => 'Aguascalientes',
                'address' => 'Av. Siglo XXI No. 513, Municipio Libre, 20199 Aguascalientes, Ags.',
                'phone' => '4491940726',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Municipio Libre","website":"https:\/\/clinicadentalags.com\/","source_channel":"website","notes":"20+ años servicio; multi-especialidad ortodoncia + prótesis + endodoncia + periodoncia + maxilofacial; WhatsApp"}',
            ],
            [
                'name' => 'Dr. José Héctor Miranda Aguilera',
                'clinic_name' => 'Clínica Dental Smile & Life',
                'specialty' => 'Ortodoncia',
                'city' => 'Aguascalientes',
                'address' => 'Prolongación Adoratrices, Villa de Nuestra Señora de la Asunción Sector Encino, 20126 Aguascalientes, Ags.',
                'phone' => '4499968970',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Villa de Nuestra Señora de la Asunción","website":"https:\/\/dentistasenaguascalientes.com\/","source_channel":"website","notes":"Cédula 1727985; 31 años experiencia; Invisalign Doctor; laboratorio Smile 3D propio; implantes"}',
            ],
            [
                'name' => 'Dr. Sergio Godínez Antillón',
                'clinic_name' => 'Dr. Sergio Godínez Antillón',
                'specialty' => 'Ortodoncia',
                'city' => 'Aguascalientes',
                'address' => 'Poder Legislativo Norte 116-B, La Purísima, 20259 Aguascalientes, Ags.',
                'phone' => '4499187733',
                'has_whatsapp' => true,
                'email' => 'ortoags@hotmail.com',
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"La Purísima","website":"https:\/\/www.drsergiogodinezantillon.com.mx\/","source_channel":"website","notes":"Cédula 2044689 UAA; especialidad 7817352; 16+ años experiencia; titular único"}',
            ],
            [
                'name' => 'Dr. Víctor González Bedolla',
                'clinic_name' => 'Odontopediatría y Ortodoncia de Aguascalientes',
                'specialty' => 'Odontopediatría',
                'city' => 'Aguascalientes',
                'address' => 'Av. Universidad esq. Av. Aguascalientes 1001 Int. 503, Bosques del Prado Norte, 20127 Aguascalientes, Ags.',
                'phone' => '4499960979',
                'has_whatsapp' => true,
                'email' => 'qparga@hotmail.com',
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Bosques del Prado Norte","instagram":"@drvictor.odontoinfantil","website":"https:\/\/www.dentistaparaninosyortodoncia.com\/","source_channel":"website","notes":"30 años experiencia; Dr. González Bedolla + Dra. Belinda Quezada Parga; pediatría + ortodoncia"}',
            ],
            [
                'name' => 'Dr. Hugo Mascorro',
                'clinic_name' => 'AMG Dental',
                'specialty' => 'Odontología General',
                'city' => 'Aguascalientes',
                'address' => 'Juan de Montoro 114 Int. 205, Zona Centro, 20117 Aguascalientes, Ags.',
                'phone' => '4492392147',
                'has_whatsapp' => true,
                'email' => 'amgdental28@gmail.com',
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Zona Centro","website":"https:\/\/dentalamg.com\/","source_channel":"website","notes":"Multi-especialidad; preventiva + restauradora + ortodoncia + periodoncia + implantes + cirugía"}',
            ],
            [
                'name' => 'Dr. Asdrúbal Rodríguez Rojas',
                'clinic_name' => 'Dr. Asdrúbal Rodríguez Rojas',
                'specialty' => 'Cirugía Maxilofacial',
                'city' => 'Aguascalientes',
                'address' => 'Río de Janeiro 122, Santa Elena, 20230 Aguascalientes, Ags.',
                'phone' => '4499168669',
                'has_whatsapp' => true,
                'email' => 'drmaxilo@hotmail.com',
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Santa Elena","website":"https:\/\/www.drasdrubalrodriguezrojas.com\/","source_channel":"website","notes":"Cédula 4259039; especialidad 6271860 UdeG; 15+ años privado; muelas juicio + implantes + maxilofacial"}',
            ],
            [
                'name' => 'Dra. Ma. de Lourdes Tapia Salazar',
                'clinic_name' => 'Parliamo Di Denti',
                'specialty' => 'Odontopediatría',
                'city' => 'Aguascalientes',
                'address' => 'Mahatma Gandhi 345 A, Agricultura, 20234 Aguascalientes, Ags.',
                'phone' => '4499714146',
                'has_whatsapp' => true,
                'email' => 'tapia.salazar@hotmail.com',
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Agricultura","website":"https:\/\/www.parliamodidenti.com\/","source_channel":"website","notes":"Cédula 3845653 Maestría Estomatología Pediátrica; cédula 2366717; especialista niños + bebés"}',
            ],
            [
                'name' => 'Dra. Gabriela Alejandra Serna Ojeda',
                'clinic_name' => 'Dra. Gabriela Serna Ojeda',
                'specialty' => 'Periodoncia',
                'city' => 'Aguascalientes',
                'address' => 'Sierra Nevada 219, Bosques del Prado Norte, Aguascalientes, Ags.',
                'phone' => '4499293344',
                'has_whatsapp' => true,
                'email' => 'draserna.perio@gmail.com',
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Bosques del Prado Norte","website":"https:\/\/dragabrielaserna.com\/","source_channel":"website","notes":"Periodoncia + implantología + diabetes; UNAM especialidad; De La Salle Bajío licenciatura; titular única"}',
            ],
            [
                'name' => 'Dr. Ricardo Velasco Avelar',
                'clinic_name' => 'Dr. Ricardo Velasco Periodoncia',
                'specialty' => 'Periodoncia',
                'city' => 'Aguascalientes',
                'address' => '26 de Marzo 302, Residencial del Valle 1ra Sección, Aguascalientes, Ags.',
                'phone' => '4499163056',
                'has_whatsapp' => true,
                'email' => 'dr.velasco.perio@gmail.com',
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Residencial del Valle","instagram":"@dr.velasco.perio","website":"https:\/\/www.drvelascoperio.com\/","source_channel":"website","notes":"Periodoncia + implantología; 2 sedes (Aguascalientes + Tepatitlán Jalisco); consultorio principal AGS"}',
            ],
            [
                'name' => 'Clinikids Aguascalientes',
                'clinic_name' => 'Clinikids Aguascalientes',
                'specialty' => 'Odontopediatría',
                'city' => 'Aguascalientes',
                'address' => 'Silos 507, Trojes de Oriente, Aguascalientes, Ags.',
                'phone' => '4499658620',
                'has_whatsapp' => true,
                'email' => 'clinikidsags@hotmail.com',
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Trojes de Oriente","instagram":"@clinikids.odontopediatria","website":"https:\/\/clinikids.mx\/","source_channel":"website","notes":"Odontopediatría inclusiva; perros de apoyo emocional; pacientes neurodivergentes; sin anestesia"}',
            ],
            [
                'name' => 'DCC Dental Care Center',
                'clinic_name' => 'DCC Dental Care Center',
                'specialty' => 'Odontología General',
                'city' => 'Aguascalientes',
                'address' => 'Av. Convención de 1914 Sur 403, Jardines de la Asunción, Aguascalientes, Ags.',
                'phone' => '4499139099',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Jardines de la Asunción","source_channel":"google-search","notes":"Reemplazo: Dental Care Center zona Jardines de la Asunción; odontología integral"}',
            ],
            [
                'name' => 'Dental One Aguascalientes',
                'clinic_name' => 'Dental One Aguascalientes',
                'specialty' => 'Odontología General',
                'city' => 'Aguascalientes',
                'address' => 'Av. Aguascalientes Nte 605 Int. 102, Bosques del Prado Sur, 20130 Aguascalientes, Ags.',
                'phone' => '4499930889',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Bosques del Prado Sur","source_channel":"google-search","notes":"Reemplazo: consultorio dirigido por equipo femenino; atención personalizada"}',
            ],
            [
                'name' => 'Dr. Manuel de Jesús González De Santiago',
                'clinic_name' => 'Dr. Manuel González De Santiago Maxilofacial',
                'specialty' => 'Cirugía Maxilofacial',
                'city' => 'Aguascalientes',
                'address' => 'Ezequiel A. Chávez 135 Int. 8, La Purísima, 20000 Aguascalientes, Ags.',
                'phone' => '4499186281',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"La Purísima","source_channel":"google-search","notes":"Exclusivo cirugía maxilofacial; muelas juicio + fracturas + ortognática + quistes; solo privado"}',
            ],
            [
                'name' => 'Salud Dental Aguascalientes',
                'clinic_name' => 'Salud Dental Aguascalientes',
                'specialty' => 'Odontología General',
                'city' => 'Aguascalientes',
                'address' => 'Sierra de Los Picachos 114, Bosques del Prado Sur, 20130 Aguascalientes, Ags.',
                'phone' => '4491920042',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Bosques del Prado Sur","source_channel":"google-search","notes":"Reemplazo: consultorio Bosques del Prado Sur; odontología integral"}',
            ],
            [
                'name' => 'Dra. Anita Nava Nava',
                'clinic_name' => 'Dra. Anita Nava Nava',
                'specialty' => 'Odontología General',
                'city' => 'Aguascalientes',
                'address' => 'Av. Gral. Mariano Escobedo 526, Jardines del Sol, 20266 Aguascalientes, Ags.',
                'phone' => '4499132000',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Jardines del Sol","source_channel":"google-search","notes":"Universidad Andres Bello Chile; odontología general; titular única consultorio"}',
            ],
            [
                'name' => 'Dr. Roberto Lagunas Zertuche',
                'clinic_name' => 'Dr. Roberto Lagunas Zertuche',
                'specialty' => 'Endodoncia',
                'city' => 'Aguascalientes',
                'address' => 'Dr. G. Ramírez Valdez 126 Int. 6, El Dorado, 20235 Aguascalientes, Ags.',
                'phone' => '4499173152',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"El Dorado","source_channel":"google-search","notes":"Endodoncista UMSNH; consultorio El Dorado L-V 9-20 Sáb 10-14; también Star Médica Av. Universidad"}',
            ],
            [
                'name' => 'Consultorio Dental Sierra Palomas',
                'clinic_name' => 'Consultorio Dental Sierra Palomas',
                'specialty' => 'Odontología General',
                'city' => 'Aguascalientes',
                'address' => 'Sierra de las Palomas, Bosques del Prado Sur, Aguascalientes, Ags.',
                'phone' => '4499960366',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Bosques del Prado Sur","source_channel":"google-search","notes":"Reemplazo: consultorio independiente zona Bosques del Prado Sur"}',
            ],
            [
                'name' => 'MÖlar Centro de Especialidades Odontológicas',
                'clinic_name' => 'MÖlar Centro de Especialidades Odontológicas',
                'specialty' => 'Odontología General',
                'city' => 'Aguascalientes',
                'address' => 'Ing. Agustín Yáñez 141, Villas de la Universidad, 20010 Aguascalientes, Ags.',
                'phone' => '4499183230',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Villas de la Universidad","source_channel":"google-search","notes":"Reemplazo: centro de especialidades odontológicas multi-disciplina"}',
            ],
            [
                'name' => 'Dental Center Ags',
                'clinic_name' => 'Dental Center Ags',
                'specialty' => 'Odontología General',
                'city' => 'Aguascalientes',
                'address' => 'Aguascalientes, Ags.',
                'phone' => '4492884525',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Zona Centro","source_channel":"google-search","notes":"Reemplazo: consultorio independiente AGS; odontología integral"}',
            ],
            [
                'name' => 'Dentistas Aguascalientes Dental Corporativa',
                'clinic_name' => 'Dentistas Aguascalientes Dental Corporativa',
                'specialty' => 'Ortodoncia',
                'city' => 'Aguascalientes',
                'address' => 'Aguascalientes, Ags.',
                'phone' => '4499151559',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Zona Centro","source_channel":"google-search","notes":"Reemplazo: clínica de ortodoncia y dentistas; Invisalign + brackets"}',
            ],
            [
                'name' => 'Odontología Familiar Especializada',
                'clinic_name' => 'Odontología Familiar Especializada',
                'specialty' => 'Odontología General',
                'city' => 'Aguascalientes',
                'address' => 'Av. Las Américas 601-4, La Fuente, Aguascalientes, Ags.',
                'phone' => '4495211706',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"La Fuente","website":"https:\/\/www.ofamiliar.com\/","source_channel":"website","notes":"Reemplazo: odontología familiar integral; WhatsApp disponible"}',
            ],
            [
                'name' => 'Dentarel',
                'clinic_name' => 'Dentarel',
                'specialty' => 'Odontología General',
                'city' => 'Jesús María',
                'address' => 'Emiliano Zapata 420b, Zona Centro, 20920 Jesús María, Ags.',
                'phone' => '4491257009',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Zona Centro","rating":"5.0","source_channel":"google-search","notes":"Rating 5.0; precios accesibles; consultorio independiente Jesús María centro"}',
            ],
            [
                'name' => 'Dr. Luis Daniel García Rosales',
                'clinic_name' => 'Dr. Luis Daniel García Rosales',
                'specialty' => 'Odontología General',
                'city' => 'Aguascalientes',
                'address' => 'Av. Ojocaliente 1029, Ojocaliente I, Aguascalientes, Ags.',
                'phone' => '4495806092',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Ojocaliente I","source_channel":"google-search","notes":"Reemplazo: dentista titular Ojocaliente; odontología general"}',
            ],
            [
                'name' => 'Dra. Lorena Romo Díaz de León',
                'clinic_name' => 'Ortodoncia Romo Díaz de León',
                'specialty' => 'Ortodoncia',
                'city' => 'Aguascalientes',
                'address' => 'Av. Universidad 103 Int. 332, Villas de la Universidad, 20029 Aguascalientes, Ags.',
                'phone' => '4499930888',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Villas de la Universidad","source_channel":"google-search","notes":"Reemplazo: ortodoncista Villas de la Universidad; titular única"}',
            ],
            [
                'name' => 'Clínica Dental Av. Universidad 103',
                'clinic_name' => 'Clínica Dental Av. Universidad 103',
                'specialty' => 'Odontología General',
                'city' => 'Aguascalientes',
                'address' => 'Av. Universidad 103, Villas de la Universidad, Aguascalientes, Ags.',
                'phone' => '4499109900',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Villas de la Universidad","source_channel":"google-search","notes":"Reemplazo: consultorio dental Villas de la Universidad; odontología integral"}',
            ],
            [
                'name' => 'Consultorio Dental Universidad 101',
                'clinic_name' => 'Consultorio Dental Universidad 101',
                'specialty' => 'Odontología General',
                'city' => 'Aguascalientes',
                'address' => 'Av. Universidad 101, Villas de la Universidad, Aguascalientes, Ags.',
                'phone' => '4492006090',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Villas de la Universidad","source_channel":"google-search","notes":"Reemplazo: consultorio dental Torre Universidad 101; odontología integral"}',
            ],
            [
                'name' => 'Dentista Jesús Gómez Portugal',
                'clinic_name' => 'Dentista Jesús Gómez Portugal',
                'specialty' => 'Odontología General',
                'city' => 'Jesús María',
                'address' => 'Cedro 110, Jesús Gómez Portugal (Margaritas), Centro, 20909 Jesús Gómez Portugal, Ags.',
                'phone' => '4499947058',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Jesús Gómez Portugal","source_channel":"google-search","notes":"Reemplazo: consultorio dental Jesús Gómez Portugal; atención integral"}',
            ],
            [
                'name' => 'Consultorio Dental Oriente',
                'clinic_name' => 'Consultorio Dental Oriente',
                'specialty' => 'Odontología General',
                'city' => 'Aguascalientes',
                'address' => 'Blvd. Guadalupano 205-A, CNOP Oriente, 20177 Aguascalientes, Ags.',
                'phone' => '4492804310',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"CNOP Oriente","rating":"4.9","reviews_count":"79","source_channel":"google-search","notes":"Reemplazo: rating 4.9 con 79 reseñas; odontología integral zona oriente"}',
            ],
            [
                'name' => 'Consultorio Dental Pabellón Plutarco Elías',
                'clinic_name' => 'Consultorio Dental Pabellón Plutarco Elías',
                'specialty' => 'Odontología General',
                'city' => 'Pabellón de Arteaga',
                'address' => 'Av. Plutarco Elías Calles, 5 de Mayo, 20676 Pabellón de Arteaga, Ags.',
                'phone' => '4651110207',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"5 de Mayo","source_channel":"google-search","notes":"Reemplazo: consultorio independiente Pabellón; odontología general"}',
            ],
            [
                'name' => 'Hospital Cardiológica Aguascalientes Ortodoncia',
                'clinic_name' => 'Hospital Cardiológica Aguascalientes Ortodoncia',
                'specialty' => 'Ortodoncia',
                'city' => 'Aguascalientes',
                'address' => 'Aguascalientes, Ags.',
                'phone' => '4499154000',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Zona Centro","website":"https:\/\/hospitalcardiologica.com.mx\/","source_channel":"website","notes":"Reemplazo: servicio ortodoncia del Hospital Cardiológica; especialistas certificados"}',
            ],
            [
                'name' => 'Hospital de Dientes Centro',
                'clinic_name' => 'Hospital de Dientes Centro',
                'specialty' => 'Implantología',
                'city' => 'Aguascalientes',
                'address' => 'Gral. Miguel Barragán 301 esq. Vázquez del Mercado, Zona Centro, Aguascalientes, Ags.',
                'phone' => '4493705066',
                'has_whatsapp' => true,
                'email' => 'hospitaldedientes@gmail.com',
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Zona Centro","website":"https:\/\/www.hospitaldedientes.com\/","source_channel":"website","notes":"Reemplazo: expertos implantes dentales + estética; sede Centro"}',
            ],
            [
                'name' => 'Centro Dental Lomas',
                'clinic_name' => 'Centro Dental Lomas',
                'specialty' => 'Implantología',
                'city' => 'San Luis Potosí',
                'address' => 'Av. Cordillera de los Himalaya 106, Lomas 3ra Sección, 78216 San Luis Potosí, S.L.P.',
                'phone' => '4448136473',
                'has_whatsapp' => true,
                'email' => 'atencion@centrodentallomas.com',
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Lomas 3ra Sección","instagram":"@centrodentallomas","website":"https:\/\/www.centrodentallomas.com\/","source_channel":"website","notes":"Implantes + ortodoncia invisible + carillas + blanqueamiento + botox; especialidades integradas"}',
            ],
            [
                'name' => 'Dra. Caribel Andrade Martínez',
                'clinic_name' => 'Dra. Caribel Andrade Ortodoncia',
                'specialty' => 'Ortodoncia',
                'city' => 'San Luis Potosí',
                'address' => 'Montes Blancos 180 Int. 13, Lomas 2da Sección, 78210 San Luis Potosí, S.L.P.',
                'phone' => '4448283251',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Lomas 2da Sección","instagram":"@caribelandrade_ortodoncia","website":"https:\/\/dentistasanluispotosi.com\/","source_channel":"website","notes":"Especialista ortodoncia + ortopedia maxilar; maestría Invisalign; 1er lugar generación UCC"}',
            ],
            [
                'name' => 'Dentocare México',
                'clinic_name' => 'Dentocare México',
                'specialty' => 'Odontología Estética',
                'city' => 'San Luis Potosí',
                'address' => 'Cañada del Lobo 229, Lomas del Tecnológico 2da Sección, San Luis Potosí, S.L.P.',
                'phone' => '4448415400',
                'has_whatsapp' => true,
                'email' => 'dentocaremexico1@gmail.com',
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Lomas del Tecnológico","instagram":"@dentocaremex","website":"https:\/\/dentocaremexico.com\/","source_channel":"website","notes":"Ortodoncia + digital + blanqueamiento + odontopediatría + endodoncia + implantes + fisioterapia"}',
            ],
            [
                'name' => 'Dr. Christian Zahit Idiáquez Ríos',
                'clinic_name' => 'The Implant Center SLP',
                'specialty' => 'Implantología',
                'city' => 'San Luis Potosí',
                'address' => 'Montes Aconcagua 301 Int. 12, Lomas 2da Sección, 78210 San Luis Potosí, S.L.P.',
                'phone' => '4447729575',
                'has_whatsapp' => true,
                'email' => 'implantcenterslp@gmail.com',
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Lomas 2da Sección","website":"http:\/\/www.theimplantcenterslp.com\/","source_channel":"website","notes":"Cédula 09571312; Dr. Idiáquez + Dr. Ismael Espinosa García; 11+ años implantología"}',
            ],
            [
                'name' => 'Dental Plus SLP',
                'clinic_name' => 'Dental Plus SLP',
                'specialty' => 'Implantología',
                'city' => 'San Luis Potosí',
                'address' => 'Av. Constitución 2280 Int. 30, Santa Fe Sur, 78350 San Luis Potosí, S.L.P.',
                'phone' => '4448159909',
                'has_whatsapp' => true,
                'email' => 'dentalplusslp@gmail.com',
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Santa Fe Sur","instagram":"@dentalplusslp","website":"https:\/\/www.dentalplusslp.com\/","source_channel":"website","notes":"Especialidades odontológicas; implantes + ortodoncia + cirugía + odontopediatría + carillas"}',
            ],
            [
                'name' => 'Ortodoncia & Odontología Integral',
                'clinic_name' => 'Ortodoncia & Odontología Integral',
                'specialty' => 'Ortodoncia',
                'city' => 'San Luis Potosí',
                'address' => 'Av. Cuauhtémoc 620-D, Tequisquiapan, San Luis Potosí, S.L.P.',
                'phone' => '4448118462',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Tequisquiapan","website":"https:\/\/ortodonciayodontologia.com.mx\/","source_channel":"website","notes":"COFEPRIS 213301202A0857; 10+ años; ortodoncia invisible + metálica + estética"}',
            ],
            [
                'name' => 'Dr. José Manuel Rodríguez Álvarez',
                'clinic_name' => 'Forever Dentist',
                'specialty' => 'Odontología General',
                'city' => 'San Luis Potosí',
                'address' => 'Av. Himno Nacional 3820, Planta Baja del Real, 78280 San Luis Potosí, S.L.P.',
                'phone' => '4446571062',
                'has_whatsapp' => true,
                'email' => 'manuel3768@hotmail.com',
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Himno Nacional","website":"https:\/\/www.foreverdentist.net\/","source_channel":"website","notes":"Cédula 1545193; Cirujano Dental Militar; 30+ años experiencia; estética + cirugía + ortodoncia + láser"}',
            ],
            [
                'name' => 'Endo Dental+',
                'clinic_name' => 'Endo Dental+',
                'specialty' => 'Endodoncia',
                'city' => 'San Luis Potosí',
                'address' => 'Av. Industrias 1820-A, Jardines del Sur, 78399 San Luis Potosí, S.L.P.',
                'phone' => '4446001513',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Jardines del Sur","instagram":"@endodentalplus","website":"https:\/\/endodentalplus.com\/","source_channel":"website","notes":"Endodoncia + urgencias; consultorio con doctoras titulares; servicios integrales"}',
            ],
            [
                'name' => 'Dra. Erika Marbel Gómez Tagle Morales',
                'clinic_name' => 'Dra. Erika Gómez Tagle Morales',
                'specialty' => 'Odontopediatría',
                'city' => 'San Luis Potosí',
                'address' => 'Recursos Hidráulicos 525, Las Águilas, 78269 San Luis Potosí, S.L.P.',
                'phone' => '4448115183',
                'has_whatsapp' => false,
                'email' => 'erymarb@hotmail.com',
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Las Águilas","website":"https:\/\/www.draerikamgomeztaglemorales.com\/","source_channel":"website","notes":"Odontopediatría + ortopedia maxilar + ortodoncia; atención desde 1 año; titular única"}',
            ],
            [
                'name' => 'Dra. Mercedes Ascencio Ficachi',
                'clinic_name' => 'Dra. Ficachi Odontopediatría',
                'specialty' => 'Odontopediatría',
                'city' => 'San Luis Potosí',
                'address' => 'Av. Cuauhtémoc 1250 Int. 4, Jardín Vista Hermosa, 78270 San Luis Potosí, S.L.P.',
                'phone' => '4441062709',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Vista Hermosa","instagram":"@dra.ficachi_odontopediatra","website":"https:\/\/odontopediatraficach.wixsite.com\/ficachident","rating":"5.0","source_channel":"website","notes":"Odontopediatría + adultos; 2 sedes (Vista Hermosa + Tequisquiapan Vallarta 105); rating 5.0"}',
            ],
            [
                'name' => 'Dentalcare SLP',
                'clinic_name' => 'Dentalcare SLP',
                'specialty' => 'Odontología General',
                'city' => 'San Luis Potosí',
                'address' => 'Av. Morales Saucito 2300, 78130 San Luis Potosí, S.L.P.',
                'phone' => '4448481772',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Morales Saucito","instagram":"@dentalcare.slp","website":"https:\/\/dentalcare-slp.ueniweb.com\/","source_channel":"website","notes":"Higiene dental + preventiva + diseño sonrisa; tecnología moderna"}',
            ],
            [
                'name' => 'Centro de Especialidades Odontológicas CEO',
                'clinic_name' => 'Centro de Especialidades Odontológicas CEO',
                'specialty' => 'Odontología General',
                'city' => 'San Luis Potosí',
                'address' => 'Gral. Rocha 145, Tequisquiapan, 78250 San Luis Potosí, S.L.P.',
                'phone' => '4448134186',
                'has_whatsapp' => true,
                'email' => 'ceoslp@hotmail.com',
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Tequisquiapan","source_channel":"google-search","notes":"Reemplazo: COFEPRIS 2524015036X00459; especialidades odontológicas Tequis"}',
            ],
            [
                'name' => 'A-Dental',
                'clinic_name' => 'A-Dental',
                'specialty' => 'Odontología General',
                'city' => 'San Luis Potosí',
                'address' => 'Calle San Ángel 421 Edif. A Int. 104, San Ángel 2da Sección, San Luis Potosí, S.L.P.',
                'phone' => '4448232697',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"San Ángel","source_channel":"google-search","notes":"Reemplazo: consultorio dental San Ángel; odontología integral"}',
            ],
            [
                'name' => 'ABCDental',
                'clinic_name' => 'ABCDental',
                'specialty' => 'Odontología General',
                'city' => 'San Luis Potosí',
                'address' => 'Plaza Paseo Guadalcazar, Huasteca 305 Local 18, Lomas 1ra Sección, 78210 San Luis Potosí, S.L.P.',
                'phone' => '4449623960',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Lomas 1ra Sección","source_channel":"google-search","notes":"Reemplazo: consultorio Plaza Paseo Guadalcazar Lomas 1ra; odontología integral"}',
            ],
            [
                'name' => 'Dr. Christian Navarro Herrera',
                'clinic_name' => 'COI Centro Odontología Integral',
                'specialty' => 'Implantología',
                'city' => 'San Luis Potosí',
                'address' => 'Palmira 600B Int. 401, Privadas del Pedregal, 78295 San Luis Potosí, S.L.P.',
                'phone' => '4442659289',
                'has_whatsapp' => true,
                'email' => 'dr.navarro.herrera@gmail.com',
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Privadas del Pedregal","website":"http:\/\/www.dentalcoi.com\/","source_channel":"website","notes":"Hospital Lomas Internacional desde 2009; 2 sedes (Pedregal + Valle Dorado); implantes + rehabilitación"}',
            ],
            [
                'name' => 'Clínica Doctores Tequisquiapan',
                'clinic_name' => 'Clínica Doctores Tequisquiapan',
                'specialty' => 'Odontología General',
                'city' => 'San Luis Potosí',
                'address' => 'Agustín Vera 275, Tequisquiapan, San Luis Potosí, S.L.P.',
                'phone' => '4448333496',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Tequisquiapan","source_channel":"google-search","notes":"Reemplazo: consultorio dental Tequisquiapan; Clínica Doctores"}',
            ],
            [
                'name' => 'Consultorio Dental Smile Care Cactus',
                'clinic_name' => 'Consultorio Dental Smile Care Cactus',
                'specialty' => 'Odontología General',
                'city' => 'Soledad de Graciano Sánchez',
                'address' => 'Av. de Los Cactus 1815, Soledad de Graciano Sánchez, S.L.P.',
                'phone' => '4444239459',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Los Cactus","source_channel":"google-search","notes":"Reemplazo: consultorio Smile Care sede Los Cactus; odontología integral"}',
            ],
            [
                'name' => 'Cade Dental Soledad',
                'clinic_name' => 'Cade Dental Soledad',
                'specialty' => 'Odontología General',
                'city' => 'Soledad de Graciano Sánchez',
                'address' => 'Soledad de Graciano Sánchez, S.L.P.',
                'phone' => '4442064216',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Centro","source_channel":"google-search","notes":"Reemplazo: Cade clínica dental Soledad; odontología integral"}',
            ],
            [
                'name' => 'Centro de Odontología y Médico Especializado',
                'clinic_name' => 'Centro de Odontología y Médico Especializado',
                'specialty' => 'Odontología General',
                'city' => 'Soledad de Graciano Sánchez',
                'address' => 'Soledad de Graciano Sánchez, S.L.P.',
                'phone' => '4448545366',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Centro","source_channel":"google-search","notes":"Reemplazo: centro odontológico multi-especialidad Soledad"}',
            ],
            [
                'name' => 'Clínica Dental Trece de Mayo',
                'clinic_name' => 'Clínica Dental Trece de Mayo',
                'specialty' => 'Odontología General',
                'city' => 'Soledad de Graciano Sánchez',
                'address' => 'Soledad de Graciano Sánchez, S.L.P.',
                'phone' => '4448315452',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Centro","source_channel":"google-search","notes":"Reemplazo: clínica dental Trece de Mayo; múltiples sedes Soledad"}',
            ],
            [
                'name' => 'Dra. Ana Maggiori',
                'clinic_name' => 'Dra. Ana Maggiori Endodoncia',
                'specialty' => 'Endodoncia',
                'city' => 'San Luis Potosí',
                'address' => 'Cordillera Arakan 606, Plaza San Carlos Local 17, Lomas 4a Sección, San Luis Potosí, S.L.P.',
                'phone' => '4448333828',
                'has_whatsapp' => true,
                'email' => 'anamaggiori43@hotmail.com',
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Lomas 4a Sección","source_channel":"google-search","notes":"Reemplazo: endodoncista Lomas 4a; consultorio privado"}',
            ],
            [
                'name' => 'Consultorio Dental San Ángel',
                'clinic_name' => 'Consultorio Dental San Ángel',
                'specialty' => 'Odontología General',
                'city' => 'Soledad de Graciano Sánchez',
                'address' => 'Sierra de Álvarez 193, La Sierra, Soledad de Graciano Sánchez, S.L.P.',
                'phone' => '4448217302',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"La Sierra","source_channel":"google-search","notes":"Consultorio La Sierra; atención personalizada Soledad"}',
            ],
            [
                'name' => 'Clínica Dental Las Flores',
                'clinic_name' => 'Clínica Dental Las Flores',
                'specialty' => 'Odontología Estética',
                'city' => 'Aguascalientes',
                'address' => 'Calle Orquídeas 308, Las Flores, Aguascalientes, Ags.',
                'phone' => '4499158346',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Las Flores","source_channel":"google-search","notes":"Reemplazo: clínica dental zona Las Flores; odontología estética"}',
            ],
            [
                'name' => 'Dra. Ana Patricia Flores Acosta',
                'clinic_name' => 'Médica Scop Ortodoncia Dra. Flores',
                'specialty' => 'Ortodoncia',
                'city' => 'San Luis Potosí',
                'address' => 'Av. Scop 826, Jardín Fundadores, 78270 San Luis Potosí, S.L.P.',
                'phone' => '4441886493',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Fundadores","source_channel":"google-search","notes":"Reemplazo: Médica Scop ortodoncia y ortopedia maxilar; Dra. Flores Acosta"}',
            ],
            [
                'name' => 'Odontología Especializada del Potosí',
                'clinic_name' => 'Odontología Especializada del Potosí',
                'specialty' => 'Odontología General',
                'city' => 'San Luis Potosí',
                'address' => 'Cordillera Himalaya 455 1er Piso Consultorio 3, Colinas del Parque, 78294 San Luis Potosí, S.L.P.',
                'phone' => '4445906462',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Colinas del Parque","source_channel":"google-search","notes":"Torre Médica Himalaya; a 1 cuadra de Av. Chapultepec; especialidades odontológicas"}',
            ],
            [
                'name' => 'Dra. Larissa Olguín Robles',
                'clinic_name' => 'Dra. Larissa Olguín Robles Odontopediatría',
                'specialty' => 'Odontopediatría',
                'city' => 'San Luis Potosí',
                'address' => 'San Luis Potosí, S.L.P.',
                'phone' => '4441056598',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Zona Centro","source_channel":"google-search","notes":"Reemplazo: odontopediatra titular; consultorio privado SLP"}',
            ],
            [
                'name' => 'Dra. Perla Guadalupe Pérez García',
                'clinic_name' => 'Dra. Perla Pérez García Odontopediatría',
                'specialty' => 'Odontopediatría',
                'city' => 'San Luis Potosí',
                'address' => 'Artículo 123 140, Cuauhtémoc, 78260 San Luis Potosí, S.L.P.',
                'phone' => '4443153403',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-ags-dedup-20260423","colonia":"Cuauhtémoc","source_channel":"google-search","notes":"Reemplazo: odontopediatría + ortopedia maxilar; titular única"}',
            ],
        ];

        $this->command->info('Insertando ' . count($prospects) . ' dentistas del pilot (research-dentistas-ags-dedup-20260423)...');

        $inserted = 0;
        $skipped = 0;

        foreach ($prospects as $prospect) {
            // Idempotencia por phone (último match) — no volver a insertar si ya existe
            $existing = Prospect::where('phone', $prospect['phone'])->first();
            if ($existing) {
                $skipped++;
                continue;
            }

            Prospect::create(array_merge($prospect, [
                'source' => 'prospecting', // matches SendProspectEmails cron filter
                'status' => 'new',
                'assigned_to_sales_rep_id' => 100,
                'contact_day' => 0,
                'next_contact_at' => now()->addHour(),
                'outreach_started_at' => now(),
            ]));
            $inserted++;
        }

        $this->command->info("✓ {$inserted} insertados | {$skipped} duplicados saltados | Total en seeder: " . count($prospects));
    }
}
