<?php

namespace Database\Seeders;

use App\Models\Prospect;
use Illuminate\Database\Seeder;

/**
 * Generated seeder — batch research-dentistas-tol-dedup-20260423.
 *
 * 57 dentistas descubiertos vía WebSearch + WebFetch, deduplicados contra prod.
 * Todos con teléfono MX de 10 dígitos. Asignados a Omar (user_id=100) con
 * source='prospecting' para que el cron send-prospect-emails los tome automático.
 * El batch identifier vive en notes.batch = 'research-dentistas-tol-dedup-20260423' para analytics.
 *
 * Ejecutar: php artisan db:seed --class=ProspectDentistasTOLPilotSeeder --force
 */
class ProspectDentistasTOLPilotSeeder extends Seeder
{
    public function run(): void
    {
        $prospects = [
            [
                'name' => 'City Dental Metepec',
                'clinic_name' => 'City Dental Metepec',
                'specialty' => 'Odontología General',
                'city' => 'Metepec',
                'address' => 'Ezequiel Montes 27, Pilares, 52179 San Jerónimo Chicahualco, Méx.',
                'phone' => '7221800627',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"Pilares","website":"https:\/\/citydentalmx.com\/","source_channel":"website","notes":"2 sucursales Metepec (Pilares + 5 de Mayo); multi-especialidad con endodoncia y cirugía maxilofacial"}',
            ],
            [
                'name' => 'Dra. Silvia Nobuko Nishikawa Perea',
                'clinic_name' => 'Nishikawa Clínica Dental',
                'specialty' => 'Implantología',
                'city' => 'Metepec',
                'address' => 'Calle Leona Vicario 204, Coaxustenco, 52140 Metepec, Méx.',
                'phone' => '7222702614',
                'has_whatsapp' => true,
                'email' => 'dranobuko@hotmail.com',
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"Coaxustenco","website":"https:\/\/www.clinicadentalnishikawa.com\/","source_channel":"website","notes":"2 sedes (Metepec + Valle Don Camilo Toluca); cédula 102892 UNAM; titular + Dr. Pérez Morales ortodoncia"}',
            ],
            [
                'name' => 'Dr. Luis Carlos Pérez Morales',
                'clinic_name' => 'Nishikawa Clínica Dental Toluca',
                'specialty' => 'Ortodoncia',
                'city' => 'Toluca',
                'address' => 'Prol. 5 de Mayo #808, Valle Don Camilo, 50140 Toluca de Lerdo, Méx.',
                'phone' => '7229302329',
                'has_whatsapp' => true,
                'email' => 'citas@clinicadentalnishikawa.com',
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"Valle Don Camilo","website":"https:\/\/www.clinicadentalnishikawa.com\/","source_channel":"website","notes":"Sucursal Toluca del grupo Nishikawa; cédula 092004 UNAM; ortodoncia + odontopediatría"}',
            ],
            [
                'name' => 'Dra. Yuvidia',
                'clinic_name' => 'Ube Dental',
                'specialty' => 'Odontología Estética',
                'city' => 'Metepec',
                'address' => 'Blvd. Toluca Metepec #505, La Purísima, Metepec, Méx.',
                'phone' => '7222387307',
                'has_whatsapp' => true,
                'email' => 'contacto@ubedental.com',
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"La Purísima","instagram":"@ubedental.mx","website":"https:\/\/www.ubedental.com\/","source_channel":"website","notes":"Clínica de especialidades; carillas + implantes + coronas; Dra. Yuvidia jefe clínico"}',
            ],
            [
                'name' => 'DoDental Tecnológico Metepec',
                'clinic_name' => 'DoDental Tecnológico Metepec',
                'specialty' => 'Odontología General',
                'city' => 'Metepec',
                'address' => 'Av. Tecnológico 733, Agrícola Bellavista, 52172 Metepec, Méx.',
                'phone' => '7226497576',
                'has_whatsapp' => true,
                'email' => 'do.dental.tecnologico@gmail.com',
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"Agrícola Bellavista","instagram":"@dodentaltecnologico","website":"https:\/\/dodental.mx\/","source_channel":"website","notes":"Multi-especialidad; ortodoncia + implantes + carillas; 1 sede Agrícola Bellavista"}',
            ],
            [
                'name' => 'Dr. Jesús González Arias',
                'clinic_name' => '4U Dental Studio',
                'specialty' => 'Implantología',
                'city' => 'Toluca',
                'address' => 'Hospital Médica Mía, Torre Especialidades Consultorio 319, Toluca',
                'phone' => '7226222462',
                'has_whatsapp' => true,
                'email' => 'contacto@4udentalstudio.com',
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"Las Américas","instagram":"@4udentalstudio","website":"https:\/\/4udentalstudio.com\/","source_channel":"website","notes":"Multi-especialidad; Dr. González Arias + Dra. Diana García; tecnología avanzada"}',
            ],
            [
                'name' => 'Dentals Toluca',
                'clinic_name' => 'Dentals Toluca',
                'specialty' => 'Odontología General',
                'city' => 'Toluca',
                'address' => 'Quintana Roo Sur 540, Ocho Cedros, 50170 Toluca, Méx.',
                'phone' => '7227903877',
                'has_whatsapp' => false,
                'email' => 'info@dentistasentoluca.com',
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"Ocho Cedros","website":"https:\/\/www.dentistasentoluca.com\/","source_channel":"website","notes":"27+ años experiencia; 15 especialistas; independiente Toluca-Metepec"}',
            ],
            [
                'name' => 'Dra. Angela Núñez',
                'clinic_name' => 'Modent',
                'specialty' => 'Endodoncia',
                'city' => 'Toluca',
                'address' => 'Av. México esq. Av. Nicaragua Piso 4 Consultorio 5, 50130 Toluca de Lerdo, Méx.',
                'phone' => '7224987791',
                'has_whatsapp' => true,
                'email' => 'hola@modent.mx',
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"Centro","website":"https:\/\/modent.mx\/","source_channel":"website","notes":"Especialista endodoncia; multi-especialidad; titular Dra. Núñez"}',
            ],
            [
                'name' => 'Dr. Jaime Mejía Garduño',
                'clinic_name' => 'Clínica de Endodoncia Toluca',
                'specialty' => 'Endodoncia',
                'city' => 'Toluca',
                'address' => 'Nezahualcóyotl 219, San Sebastián, 50090 Toluca, Méx.',
                'phone' => '7221674708',
                'has_whatsapp' => true,
                'email' => 'contacto@clinicadeendodoncia.com',
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"San Sebastián","website":"https:\/\/www.clinicadeendodoncia.com\/","source_channel":"website","notes":"Maestría endodoncia; microscopía + cirugía periapical; titular único"}',
            ],
            [
                'name' => 'Dra. Marxy Reynoso',
                'clinic_name' => 'Dental Tot',
                'specialty' => 'Odontopediatría',
                'city' => 'Metepec',
                'address' => 'C. Ceboruco 2317, Solidaridad Electricistas, 52168 San Jorge Pueblo Nuevo, Méx.',
                'phone' => '7225587578',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"Solidaridad Electricistas","instagram":"@dental.tot","website":"https:\/\/www.dental-tot.com\/","source_channel":"website","notes":"Odontopediatría preventiva; pacientes infantiles + con necesidades especiales"}',
            ],
            [
                'name' => 'Dr. Armando Xavier Meneses V.',
                'clinic_name' => 'Panoramika Toluca',
                'specialty' => 'Ortodoncia',
                'city' => 'Toluca',
                'address' => 'Otumba 633, Sor Juana Inés de la Cruz, Toluca, Méx.',
                'phone' => '7222134283',
                'has_whatsapp' => true,
                'email' => 'clinicatoluca@panoramika.mx',
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"Sor Juana Inés de la Cruz","instagram":"@panoramika.mx","website":"https:\/\/panoramika.mx\/","source_channel":"website","notes":"2 sedes (Toluca + Metepec); ortodoncia invisible + implantes + carillas"}',
            ],
            [
                'name' => 'Dr. Armando Xavier Meneses V.',
                'clinic_name' => 'Panoramika Metepec',
                'specialty' => 'Ortodoncia',
                'city' => 'Metepec',
                'address' => 'Vialidad Metepec 284 Edificio Plaza San Juan Piso 3, Las Américas, 52140 Metepec, Méx.',
                'phone' => '7222804553',
                'has_whatsapp' => true,
                'email' => 'clinicametepec@panoramika.mx',
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"Las Américas","instagram":"@panoramika.mx","website":"https:\/\/panoramika.mx\/","source_channel":"website","notes":"Sucursal Metepec; multi-especialidad con ortodoncia invisible"}',
            ],
            [
                'name' => 'Dra. Ariana Aranda Hernández',
                'clinic_name' => 'Antary Médico Dental',
                'specialty' => 'Odontología Estética',
                'city' => 'Toluca',
                'address' => 'General Agustín Olachea A. 1302, Ocho Cedros, 50170 Toluca, Méx.',
                'phone' => '7226380609',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"Ocho Cedros","instagram":"@clinicaantary","website":"https:\/\/www.antarymedicodental.com\/","source_channel":"website","notes":"Diplomado diseño sonrisa; prótesis + implantología; 12+ años experiencia"}',
            ],
            [
                'name' => 'Dra. Valeria V. Díaz García',
                'clinic_name' => 'CliniDent Toluca',
                'specialty' => 'Ortodoncia',
                'city' => 'Toluca',
                'address' => 'Plaza Puerto Madero, Toluca, Méx.',
                'phone' => '7222728261',
                'has_whatsapp' => true,
                'email' => 'clinidenttoluca@outlook.com',
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"Centro","instagram":"@clinidenttoluca","website":"https:\/\/clinidenttoluca.com.mx\/","source_channel":"website","notes":"6 titulares (Díaz García + Ruiz Martínez + García Vega + Arroyo + Quan + Guadarrama)"}',
            ],
            [
                'name' => 'Dental Clinic Zinacantepec',
                'clinic_name' => 'Dental Clinic Zinacantepec',
                'specialty' => 'Ortodoncia',
                'city' => 'Zinacantepec',
                'address' => 'Av. 16 de Septiembre 207, Vista Nevado I, 51350 San Miguel Zinacantepec, Méx.',
                'phone' => '7222206696',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"Vista Nevado","website":"https:\/\/www.dentalcliniczinacantepec.com\/","source_channel":"google-search","notes":"Clínica dental y ortodoncia; abierto L-D; materiales alta calidad"}',
            ],
            [
                'name' => 'Dr. René Iñigo Ruiz',
                'clinic_name' => 'Consultorio Dental Dr. René Iñigo Ruiz',
                'specialty' => 'Odontología General',
                'city' => 'Zinacantepec',
                'address' => 'Av. 16 de Septiembre 202, Vista Nevado I, 51350 San Miguel Zinacantepec, Méx.',
                'phone' => '7221905955',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"Vista Nevado","source_channel":"google-search","notes":"Titular único; odontología integral; cerca Dental Clinic Zinacantepec"}',
            ],
            [
                'name' => 'Dr. Carlos Romero Camacho',
                'clinic_name' => 'Romero Grupo Dental',
                'specialty' => 'Odontología Estética',
                'city' => 'Metepec',
                'address' => 'Paseo San Isidro #51 L02 Portal San Isidro, Santa Cruz, 52140 Metepec, Méx.',
                'phone' => '7223253401',
                'has_whatsapp' => true,
                'email' => 'hola@grupodentalromero.com.mx',
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"Santa Cruz","website":"https:\/\/www.romerogrupodental.com.mx\/","source_channel":"website","notes":"Familia Romero; multi-especialidad; cirujano maxilofacial + odontopediatría + ortodoncia"}',
            ],
            [
                'name' => 'Dr. Oscar Miguel Tello Villegas',
                'clinic_name' => 'White Dental Metepec',
                'specialty' => 'Implantología',
                'city' => 'Metepec',
                'address' => 'Calle Josefa Ortiz de Domínguez 538 Cons. 210 Médica Árbol de la Vida, Metepec, Méx.',
                'phone' => '7223476500',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"San Mateo","website":"https:\/\/whitedentalmetepec.com\/","source_channel":"website","notes":"50+ años experiencia; implantes + ortodoncia + prótesis; consulta gratis adultos mayores"}',
            ],
            [
                'name' => 'Orthodontic Clinic Center Metepec',
                'clinic_name' => 'Orthodontic Clinic Center Metepec',
                'specialty' => 'Ortodoncia',
                'city' => 'Metepec',
                'address' => 'Leona Vicario 501 Pte. Plaza Rubí Int. 29, Coaxustenco, 52140 Metepec, Méx.',
                'phone' => '7222278495',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"Coaxustenco","website":"https:\/\/occmetepec.mx\/","source_channel":"website","notes":"2 sedes (Plaza Rubí + Plaza San Carlos Benito Juárez 226); enfoque ortodoncia y odontología"}',
            ],
            [
                'name' => 'Ceeport Dental & Spa',
                'clinic_name' => 'Ceeport Dental & Spa',
                'specialty' => 'Odontología Estética',
                'city' => 'Metepec',
                'address' => 'Calle Leona Vicario 936, La Purísima, Metepec, Méx.',
                'phone' => '7226816394',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"La Purísima","instagram":"@ceeportdental","website":"https:\/\/www.ceeportdental.com\/","rating":"4.9","reviews_count":"23","source_channel":"website","notes":"Diseño sonrisa + alineadores invisibles; prótesis + implantes + endodoncia"}',
            ],
            [
                'name' => 'Clínica Dental Vaper',
                'clinic_name' => 'Clínica Dental Vaper',
                'specialty' => 'Periodoncia',
                'city' => 'Metepec',
                'address' => 'Colonia Rafael Herrera 14, Jesús Jiménez Gallardo, 52167 San Jorge Pueblo Nuevo, Méx.',
                'phone' => '7222172450',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"Jesús Jiménez Gallardo","website":"https:\/\/clinicadentalvaper.com\/","source_channel":"website","notes":"40+ años experiencia; ortodoncia + ortopedia + implantología + periodoncia"}',
            ],
            [
                'name' => 'Dental Care Metepec',
                'clinic_name' => 'Dental Care Metepec',
                'specialty' => 'Odontología General',
                'city' => 'Metepec',
                'address' => 'Calle Guadalupe Victoria 1330F, Los Cedros, 52169 San Francisco Coaxusco, Méx.',
                'phone' => '7221076469',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"Los Cedros","source_channel":"google-search","notes":"30+ años experiencia; multi-especialidad con ortodoncia + implantes"}',
            ],
            [
                'name' => 'Aramko Dental Care',
                'clinic_name' => 'Aramko Dental Care',
                'specialty' => 'Ortodoncia',
                'city' => 'Metepec',
                'address' => 'Calle Guadalupe Victoria 701 Local 24 Plaza Peninsula, La Purísima, 52169 San Francisco Coaxusco, Méx.',
                'phone' => '7226176662',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"La Purísima","website":"https:\/\/aramkodentalcare.com\/","source_channel":"google-search","notes":"20+ años experiencia; ortodoncia sin brackets + estética dental"}',
            ],
            [
                'name' => 'NovoKids Odontopediatría',
                'clinic_name' => 'NovoKids Odontopediatría',
                'specialty' => 'Odontopediatría',
                'city' => 'Metepec',
                'address' => 'Boulevard Toluca Metepec #601 Norte Local 1, La Purísima Las Américas, 52169 Metepec, Méx.',
                'phone' => '7229170175',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"La Purísima","website":"https:\/\/novokids.mx\/","rating":"4.8","source_channel":"website","notes":"Odontopediatría Metepec; sedación consciente infantil; atiende pacientes con discapacidad"}',
            ],
            [
                'name' => 'Dra. Claudia E. Bobadilla Trigos',
                'clinic_name' => 'Dra. Claudia E. Bobadilla Trigos',
                'specialty' => 'Ortodoncia',
                'city' => 'Toluca',
                'address' => 'Hidalgo Pte. 1110, San Bernardino, Toluca, Méx.',
                'phone' => '7222134037',
                'has_whatsapp' => true,
                'email' => 'claubotri@yahoo.com.mx',
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"San Bernardino","website":"https:\/\/www.doctoraclaudiabobadillatrigos.com\/","source_channel":"website","notes":"Cédula Prof. 2044097; ortopedia maxilar + ATM + odontología estética; titular única"}',
            ],
            [
                'name' => 'GOE Grupo Odontológico Plaza del Parque',
                'clinic_name' => 'GOE Grupo Odontológico Plaza del Parque',
                'specialty' => 'Odontología General',
                'city' => 'Metepec',
                'address' => 'Paseo San Isidro 400, Santa Cruz, 52140 Metepec, Méx.',
                'phone' => '7222127262',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"Santa Cruz","website":"https:\/\/www.goe.com.mx\/","source_channel":"website","notes":"3 sedes GOE (Plaza Parque + Las Torres Metepec + Centro Toluca); preventiva + ortodoncia"}',
            ],
            [
                'name' => 'GOE Grupo Odontológico Las Torres',
                'clinic_name' => 'GOE Grupo Odontológico Las Torres',
                'specialty' => 'Odontología General',
                'city' => 'Metepec',
                'address' => 'Av. Solidaridad Las Torres, La Asunción, 52172 Metepec, Méx.',
                'phone' => '7222715660',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"La Asunción","website":"https:\/\/www.goe.com.mx\/","source_channel":"website","notes":"Sucursal GOE Las Torres; estética + implantología + rehabilitación oral"}',
            ],
            [
                'name' => 'GOE Grupo Odontológico Toluca',
                'clinic_name' => 'GOE Grupo Odontológico Toluca',
                'specialty' => 'Odontología General',
                'city' => 'Toluca',
                'address' => 'Calle Valentín Gómez Farías Pte. 505 P.B., Centro, 50000 Toluca de Lerdo, Méx.',
                'phone' => '7222131946',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"Centro","website":"https:\/\/www.goe.com.mx\/","source_channel":"website","notes":"Sucursal Toluca GOE; odontopediatría + estética + endodoncia"}',
            ],
            [
                'name' => 'Dra. María Alejandra Arismendi Martínez',
                'clinic_name' => 'OdontoEsthetic',
                'specialty' => 'Implantología',
                'city' => 'Metepec',
                'address' => 'Calle Melchor Ocampo 417, San Mateo, 52140 Metepec, Méx.',
                'phone' => '5520788092',
                'has_whatsapp' => true,
                'email' => 'contacto@odontoesthetic.com',
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"San Mateo","instagram":"@odontoestheticmx","website":"https:\/\/odontoestheticmx.com\/","source_channel":"website","notes":"15+ años experiencia; prótesis oral + implantología + diseño sonrisa; Dra. Arismendi + Dr. José"}',
            ],
            [
                'name' => 'Dra. Rosa Otilia Franco Mejía',
                'clinic_name' => 'Consultorio Dental Dra. Otilia Franco',
                'specialty' => 'Odontología General',
                'city' => 'Metepec',
                'address' => 'Plaza Villas Kent, Calle Adolfo López Mateos 1100 Int. 6, La Asunción, 52172 San Salvador Tizatlalli, Méx.',
                'phone' => '7225104598',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"La Asunción","source_channel":"google-search","notes":"Titular única; odontología general L-S; 52172 San Salvador Tizatlalli"}',
            ],
            [
                'name' => 'Dental Dream Teeth',
                'clinic_name' => 'Dental Dream Teeth',
                'specialty' => 'Implantología',
                'city' => 'Metepec',
                'address' => 'Cto Metropolitano Exterior 1005, Lázaro Cárdenas, 50149 San Salvador Tizatlalli, Méx.',
                'phone' => '7222815388',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"San Salvador Tizatlalli","rating":"5.0","reviews_count":"19","source_channel":"google-search","notes":"Especialistas manejo pacientes con dientes faltantes; innovación + salud bucal largo plazo"}',
            ],
            [
                'name' => 'Dra. Dora Lucía Ponce Salas',
                'clinic_name' => 'SM Dental',
                'specialty' => 'Odontología General',
                'city' => 'Metepec',
                'address' => 'Centro Metepec, Méx.',
                'phone' => '7221008487',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"Centro","source_channel":"google-search","notes":"Titular única Dra. Ponce; consultorio acogedor; estacionamiento gratis"}',
            ],
            [
                'name' => 'Dra. Gabriela Rivera Castillón',
                'clinic_name' => 'Odontología Vital',
                'specialty' => 'Endodoncia',
                'city' => 'Metepec',
                'address' => 'Presidentes Municipales 236 segundo piso, Jesús Jiménez Gallardo, 52168 San Jorge Pueblo Nuevo, Méx.',
                'phone' => '7224437830',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"Jesús Jiménez Gallardo","source_channel":"google-search","notes":"Preventiva + especialistas odontopediatría + endodoncista + maxilofacial + ortodoncia"}',
            ],
            [
                'name' => 'Düo Dental',
                'clinic_name' => 'Düo Dental',
                'specialty' => 'Odontología General',
                'city' => 'Metepec',
                'address' => 'Calle Prof. Cándido Jaramillo 27, Jesús Jiménez Gallardo, 52167 San Jorge Pueblo Nuevo, Méx.',
                'phone' => '7223661131',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"Jesús Jiménez Gallardo","source_channel":"google-search","notes":"Odontología integral; opciones accesibles para todos sus pacientes"}',
            ],
            [
                'name' => 'Dr. Cuauhtémoc Bello Hernández',
                'clinic_name' => 'BeLa Smile Studio',
                'specialty' => 'Cirugía Maxilofacial',
                'city' => 'Metepec',
                'address' => 'Paseo de la Asunción 317, Bella Vista, Metepec, Méx.',
                'phone' => '5579441138',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"Bella Vista","instagram":"@belasmilestudio","source_channel":"google-search","notes":"Cirugía maxilofacial titular Dr. Bello; limpieza + ortodoncia + implantes dentales"}',
            ],
            [
                'name' => 'Dr. Alfonso Castillo Gutiérrez',
                'clinic_name' => 'Consultorio Dr. Alfonso Castillo Gutiérrez',
                'specialty' => 'Ortodoncia',
                'city' => 'Lerma',
                'address' => 'Hidalgo 50, San Pedro Tultepec, 52030 Lerma, Méx.',
                'phone' => '7282825787',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"San Pedro Tultepec","source_channel":"google-search","notes":"Ortopedia + ortodoncia; titular único; Pueblo San Pedro Tultepec Lerma"}',
            ],
            [
                'name' => 'Dante Care Clínica',
                'clinic_name' => 'Dante Care Clínica',
                'specialty' => 'Odontología General',
                'city' => 'Lerma',
                'address' => '5 de Mayo 4, La Estación, Lerma de Villada, 52000 Lerma, Méx.',
                'phone' => '7282841432',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"La Estación","source_channel":"google-search","notes":"Clínica dental Lerma centro; odontología general"}',
            ],
            [
                'name' => 'Dr. Mario Alberto Marín Baeza',
                'clinic_name' => 'Consultorio Dental Mario Alberto Marín',
                'specialty' => 'Endodoncia',
                'city' => 'Lerma',
                'address' => 'Lerma de Villada, Estado de México',
                'phone' => '7223885810',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"Centro","source_channel":"google-search","notes":"Endodoncista titular; consultorio con ortodoncia en Lerma de Villada"}',
            ],
            [
                'name' => 'Teeth and Tooth Toluca',
                'clinic_name' => 'Teeth and Tooth Toluca',
                'specialty' => 'Odontología Estética',
                'city' => 'Toluca',
                'address' => 'Rafael M. Hidalgo 901 Int. 201, Américas Cárdenas, 50130 Toluca de Lerdo, Méx.',
                'phone' => '7222809039',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"Américas","website":"https:\/\/teethandtooth.mx\/","rating":"4.3","reviews_count":"60","source_channel":"website","notes":"Especialistas en sonrisas; diseño sonrisa + ortodoncia; 4 sedes (Toluca + Polanco + Insurgentes + Sur)"}',
            ],
            [
                'name' => 'Dental Family Metepec',
                'clinic_name' => 'Dental Family Metepec',
                'specialty' => 'Implantología',
                'city' => 'Metepec',
                'address' => 'Ceboruco 297 esq. Iztaccíhuatl, Xinantécatl, Metepec, Méx.',
                'phone' => '7222198647',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"Xinantécatl","website":"https:\/\/www.dentalfamilyweb.com\/","source_channel":"website","notes":"Implantes + prótesis + carillas + diseño sonrisa; centro radiológico digital"}',
            ],
            [
                'name' => 'Dra. Paola Raquel Mondragón Esquivel',
                'clinic_name' => 'Consultorio Dental Dra. Paola Mondragón',
                'specialty' => 'Odontología General',
                'city' => 'Zinacantepec',
                'address' => 'Paseo Presidente Adolfo López Mateos 259, Linda Vista, 51356 San Miguel Zinacantepec, Méx.',
                'phone' => '7222184508',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"Linda Vista","source_channel":"google-search","notes":"Titular única Dra. Mondragón Esquivel; odontología general Linda Vista"}',
            ],
            [
                'name' => 'Dr. Diego Mejía',
                'clinic_name' => 'ZINA-DENT Clínica Dental',
                'specialty' => 'Odontología General',
                'city' => 'Zinacantepec',
                'address' => 'Avenida 16 de Septiembre 206, Calvario, 51350 Zinacantepec, Méx.',
                'phone' => '7225085840',
                'has_whatsapp' => true,
                'email' => 'cddiegomejiap@gmail.com',
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"Calvario","source_channel":"google-search","notes":"2 sedes Zinacantepec (Calvario + ZINA-DENT 2); Dr. Mejía + Dra. Chantal M. + Dra. Ilse Sotelo"}',
            ],
            [
                'name' => 'Dra. Andrea',
                'clinic_name' => 'Denta Lú Clínica Dental',
                'specialty' => 'Odontología Estética',
                'city' => 'Toluca',
                'address' => 'Av. Heroico Colegio Militar 106, Los Ángeles, 50020 Toluca de Lerdo, Méx.',
                'phone' => '7226354137',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"Los Ángeles","website":"https:\/\/dentalu.com.mx\/","source_channel":"website","notes":"Estética bucal y facial; Dra. Andrea; consultorio independiente"}',
            ],
            [
                'name' => 'Centro Odontológico Láser',
                'clinic_name' => 'Centro Odontológico Láser',
                'specialty' => 'Odontología Estética',
                'city' => 'Toluca',
                'address' => 'Manuel María Contreras 228-2, Vértice, 50150 Toluca de Lerdo, Méx.',
                'phone' => '7222174713',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"Vértice","source_channel":"google-search","notes":"Tratamientos sin anestesia; láser + periodoncia + maxilofacial + ortodoncia + odontopediatría"}',
            ],
            [
                'name' => 'Consultorio Dental López Mateos',
                'clinic_name' => 'Consultorio Dental López Mateos',
                'specialty' => 'Odontología General',
                'city' => 'Toluca',
                'address' => 'Lic. Adolfo López Mateos 248, Toluca, 50020 Toluca, Estado de México',
                'phone' => '7223771845',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"Centro","source_channel":"google-search","notes":"Consultorio corredor López Mateos; odontología general Toluca centro"}',
            ],
            [
                'name' => 'Dra. Sandi Bell Vázquez',
                'clinic_name' => 'Microendodontics Center',
                'specialty' => 'Endodoncia',
                'city' => 'Metepec',
                'address' => 'Médica Árbol de la Vida Mz 032 Consultorio 509, Coaxustenco, 52140 Metepec, Méx.',
                'phone' => '7225038448',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"Coaxustenco","website":"https:\/\/www.microendodonticscenter.net\/","source_channel":"website","notes":"Centro especializado endodoncia; microendodoncia; titular Dra. Sandi Bell"}',
            ],
            [
                'name' => 'Clínica Odontológica Morelos',
                'clinic_name' => 'Clínica Odontológica Morelos',
                'specialty' => 'Odontología General',
                'city' => 'Toluca',
                'address' => 'Felipe Villanueva 609, Morelos Primera Sección, 50120 Toluca de Lerdo, Méx.',
                'phone' => '7222261900',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"Morelos Primera Sección","source_channel":"google-search","notes":"Clínica odontológica Morelos Primera Sección; multi-especialidad"}',
            ],
            [
                'name' => 'Dent-x Ortodoncia y Odontología Integral',
                'clinic_name' => 'Dent-x Ortodoncia y Odontología Integral',
                'specialty' => 'Ortodoncia',
                'city' => 'Metepec',
                'address' => 'Villas Alteza, Metepec, Méx.',
                'phone' => '7226492417',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"Villas Alteza","source_channel":"google-search","notes":"Ortodoncia + odontología integral Toluca-Metepec; consultorio Villas Alteza"}',
            ],
            [
                'name' => 'Consultorio Dental Familiar Zinacantepec',
                'clinic_name' => 'Consultorio Dental Familiar Zinacantepec',
                'specialty' => 'Odontología General',
                'city' => 'Zinacantepec',
                'address' => '16 de Septiembre 339-A, San Miguel, 51354 San Miguel Zinacantepec, Méx.',
                'phone' => '7222180776',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"San Miguel","source_channel":"google-search","notes":"Odontología familiar Zinacantepec San Miguel; consultorio general"}',
            ],
            [
                'name' => 'Consultorio Dental Guadalupe Victoria',
                'clinic_name' => 'Consultorio Dental Guadalupe Victoria',
                'specialty' => 'Odontología General',
                'city' => 'Toluca',
                'address' => 'Guadalupe Victoria 916, Centro, Toluca, Méx.',
                'phone' => '7222195531',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"Centro","source_channel":"google-search","notes":"Clínica dental Centro; odontología general"}',
            ],
            [
                'name' => 'Consultorio Dental Pino Suárez',
                'clinic_name' => 'Consultorio Dental Pino Suárez',
                'specialty' => 'Odontología General',
                'city' => 'Toluca',
                'address' => 'José María Pino Suárez 206, Centro, Toluca, Méx.',
                'phone' => '7222148989',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"Centro","source_channel":"google-search","notes":"Clínica dental Centro Pino Suárez; cerca Cosmovitral"}',
            ],
            [
                'name' => 'Odontología Integral A M',
                'clinic_name' => 'Odontología Integral A M',
                'specialty' => 'Odontología General',
                'city' => 'Metepec',
                'address' => 'Santos Degollado 3, San Miguel Totocuitlapilco, 52143 Metepec, Méx.',
                'phone' => '7222885115',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"San Miguel Totocuitlapilco","source_channel":"google-search","notes":"Odontología integral familiar; zona San Miguel Totocuitlapilco Metepec"}',
            ],
            [
                'name' => 'Clínica Dental El Hípico',
                'clinic_name' => 'Clínica Dental El Hípico',
                'specialty' => 'Odontología General',
                'city' => 'Metepec',
                'address' => 'Salvador Sánchez Colín 118, El Hípico, 52156 Metepec, Méx.',
                'phone' => '7223502897',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"El Hípico","rating":"5.0","source_channel":"google-search","notes":"Clínica zona El Hípico; precios accesibles; rating 5.0; ambiente acogedor"}',
            ],
            [
                'name' => 'Consultorio Dental Casa Blanca',
                'clinic_name' => 'Consultorio Dental Casa Blanca',
                'specialty' => 'Odontología General',
                'city' => 'Metepec',
                'address' => 'Paseo de los Sauces, Casa Blanca, Metepec, Méx.',
                'phone' => '7224908998',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"Casa Blanca","source_channel":"google-search","notes":"Consultorio Casa Blanca; odontología general"}',
            ],
            [
                'name' => 'Depósito Dental Hípico Metepec',
                'clinic_name' => 'Depósito Dental Hípico Metepec',
                'specialty' => 'Odontología General',
                'city' => 'Metepec',
                'address' => 'Gustavo Baz 311, El Hípico, 52156 Metepec, Méx.',
                'phone' => '7222123374',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"El Hípico","source_channel":"google-search","notes":"Consultorio + depósito dental zona Hípico; odontología general"}',
            ],
            [
                'name' => 'Consultorio Dental Lerma San Mateo',
                'clinic_name' => 'Consultorio Dental Lerma San Mateo',
                'specialty' => 'Odontología General',
                'city' => 'Lerma',
                'address' => 'Calle Reforma 120, San Mateo Atarasquillo, Lerma, Méx.',
                'phone' => '7282813404',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"San Mateo Atarasquillo","source_channel":"google-search","notes":"Consultorio Lerma zona San Mateo Atarasquillo"}',
            ],
            [
                'name' => 'Vitadent Toluca',
                'clinic_name' => 'Vitadent Toluca',
                'specialty' => 'Odontología General',
                'city' => 'Toluca',
                'address' => 'Ramón Corona Oriente 300, Toluca de Lerdo, 50130 Toluca, Méx.',
                'phone' => '7229802685',
                'has_whatsapp' => true,
                'email' => 'vitadentmex@google.com',
                'notes' => '{"batch":"research-dentistas-tol-dedup-20260423","colonia":"Centro","website":"https:\/\/www.vitadentmex.com\/","source_channel":"website","notes":"Todas las especialidades; técnicas innovadoras; 1200+ tratamientos; ortodoncia + endodoncia"}',
            ],
        ];

        $this->command->info('Insertando ' . count($prospects) . ' dentistas del pilot (research-dentistas-tol-dedup-20260423)...');

        $inserted = 0;
        $skipped = 0;

        foreach ($prospects as $prospect) {
            // Idempotencia por phone (último match) — no volver a insertar si ya existe
            $existing = Prospect::where('phone', $prospect['phone'])->first();
            if ($existing) {
                $skipped++;
                continue;
            }

            Prospect::create(array_merge($prospect, [
                'source' => 'prospecting', // matches SendProspectEmails cron filter
                'status' => 'new',
                'assigned_to_sales_rep_id' => 100,
                'contact_day' => 0,
                'next_contact_at' => now()->addHour(),
                'outreach_started_at' => now(),
            ]));
            $inserted++;
        }

        $this->command->info("✓ {$inserted} insertados | {$skipped} duplicados saltados | Total en seeder: " . count($prospects));
    }
}
