<?php

namespace Database\Seeders;

use App\Models\Prospect;
use Illuminate\Database\Seeder;

/**
 * Generated seeder — batch research-dentistas-morelia-dedup-20260428.
 *
 * 37 dentistas descubiertos vía WebSearch + WebFetch, deduplicados contra prod.
 * Todos con teléfono MX de 10 dígitos. Asignados a Omar (user_id=100) con
 * source='prospecting' para que el cron send-prospect-emails los tome automático.
 * El batch identifier vive en notes.batch = 'research-dentistas-morelia-dedup-20260428' para analytics.
 *
 * Ejecutar: php artisan db:seed --class=ProspectDentistasMoreliaPilotSeeder --force
 */
class ProspectDentistasMoreliaPilotSeeder extends Seeder
{
    public function run(): void
    {
        $prospects = [
            [
                'name' => 'Dr. Manuel Carrillo',
                'clinic_name' => 'CimaVIP Clínica Dental',
                'specialty' => 'Implantología',
                'city' => 'Morelia',
                'address' => 'Lago Yuriria, Ventura Puente, Morelia, Mich.',
                'phone' => '4433246863',
                'has_whatsapp' => true,
                'email' => 'contacto@cimavip.com',
                'notes' => '{"batch":"research-dentistas-morelia-dedup-20260428","colonia":"Ventura Puente","instagram":"@cimavipoficial","website":"https:\/\/www.cimavip.com\/","source_channel":"website","notes":"Multi-especialidad VIP rehabilitación + implantes + ortodoncia invisible + endodoncia; 12+ doctores titulares; 3 sedes Ventura Puente\/Las Américas\/Mega Costco; ICP boutique premium Morelia"}',
            ],
            [
                'name' => 'B-Orthodontics Altozano',
                'clinic_name' => 'B-Orthodontics Altozano',
                'specialty' => 'Ortodoncia',
                'city' => 'Morelia',
                'address' => 'Hospital Ángeles Morelia Consultorio 401 y 402B, Altozano, Morelia, Mich.',
                'phone' => '4436881078',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-morelia-dedup-20260428","colonia":"Altozano","website":"https:\/\/www.b-orthodontics.com.mx\/","source_channel":"website","notes":"Boutique premium Altozano dentro Hospital Ángeles; diseño vanguardista; segunda sede Las Américas (Chapultepec Oriente); tickets premium zona alta nueva Morelia"}',
            ],
            [
                'name' => 'B-Orthodontics Las Américas',
                'clinic_name' => 'B-Orthodontics Las Américas',
                'specialty' => 'Ortodoncia',
                'city' => 'Morelia',
                'address' => 'Artilleros del 47 1483-204, Chapultepec Oriente, Morelia, Mich.',
                'phone' => '4433150832',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-morelia-dedup-20260428","colonia":"Chapultepec Oriente","website":"https:\/\/www.b-orthodontics.com.mx\/","source_channel":"website","notes":"Sede Las Américas; ortodoncia exclusiva; multi-sede pero local independiente"}',
            ],
            [
                'name' => 'Dr. Amaury Ballesteros, Dra. Mónica González',
                'clinic_name' => 'Clínica Dental Dr. Amaury Ballesteros',
                'specialty' => 'Ortodoncia',
                'city' => 'Morelia',
                'address' => 'Sor Juana Inés de la Cruz 109, Centro, Morelia, Mich.',
                'phone' => '4433125319',
                'has_whatsapp' => true,
                'email' => 'contacto@dentalorto.com',
                'notes' => '{"batch":"research-dentistas-morelia-dedup-20260428","colonia":"Centro","website":"https:\/\/dentalorto.com\/","source_channel":"website","notes":"Pareja titular ortodoncia + rehabilitación bucal; Centro Histórico UNESCO; consolidados; ICP independiente premium"}',
            ],
            [
                'name' => 'Dr. Efrén Alejandre Bedolla',
                'clinic_name' => 'Clínica Odontológica Sonrisas',
                'specialty' => 'Ortodoncia',
                'city' => 'Morelia',
                'address' => 'Ireti Ticateme 501, Félix Ireta, 58070 Morelia, Mich.',
                'phone' => '4433158751',
                'has_whatsapp' => true,
                'email' => 'com.clinica.odontologica2000@gmail.com',
                'notes' => '{"batch":"research-dentistas-morelia-dedup-20260428","colonia":"Félix Ireta","website":"https:\/\/www.sonrisascom.mx\/","source_channel":"website","notes":"34 años experiencia; multidisciplinaria; titular único de prestigio; multi-especialidad orto + endo + perio + odontopediatría + maxilofacial"}',
            ],
            [
                'name' => 'Dr. Valdovinos',
                'clinic_name' => 'COREVA Dental',
                'specialty' => 'Ortodoncia',
                'city' => 'Morelia',
                'address' => 'Rafael Sánchez Tapia 954, Nueva Chapultepec, 58260 Morelia, Mich.',
                'phone' => '4433316950',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-morelia-dedup-20260428","colonia":"Nueva Chapultepec","instagram":"@drvaldovinosm","website":"https:\/\/dentalmorelia.com\/","source_channel":"website","notes":"Multi-especialidad Invisalign + estética + cirugía + endodoncia + implantes + odontopediatría; titular activo en redes"}',
            ],
            [
                'name' => 'CÉNIT Odontología Avanzada',
                'clinic_name' => 'CÉNIT Odontología Avanzada',
                'specialty' => 'Implantología',
                'city' => 'Morelia',
                'address' => 'Ana María Gallaga 911-105, Cuauhtémoc, 58020 Morelia, Mich.',
                'phone' => '4431138055',
                'has_whatsapp' => true,
                'email' => 'info@cenitodontologia.com.mx',
                'notes' => '{"batch":"research-dentistas-morelia-dedup-20260428","colonia":"Cuauhtémoc","instagram":"@cenit.oa","website":"https:\/\/cenitodontologia.com.mx\/","source_channel":"website","notes":"Multi-especialidad implantes + diseño sonrisa; Cuauhtémoc zona céntrica; ICP boutique"}',
            ],
            [
                'name' => 'Dr. Papik Eduardo Durán Millán',
                'clinic_name' => 'PAPIK Centro de Periodoncia e Implantología',
                'specialty' => 'Periodoncia',
                'city' => 'Morelia',
                'address' => 'H. Colegio Militar 354-1, Chapultepec Sur, 58260 Morelia, Mich.',
                'phone' => '4433146023',
                'has_whatsapp' => true,
                'email' => 'contacto@papik.com.mx',
                'notes' => '{"batch":"research-dentistas-morelia-dedup-20260428","colonia":"Chapultepec Sur","website":"https:\/\/papik.com.mx\/","source_channel":"website","notes":"Titular único periodoncia + implantes; consultorio independiente; zona Chapultepec Sur premium"}',
            ],
            [
                'name' => 'Dr. David Chacón, Dra. Martha A. Gaona',
                'clinic_name' => 'Dental Group Morelia',
                'specialty' => 'Endodoncia',
                'city' => 'Morelia',
                'address' => 'Aristeo Mercado 607, Nueva Chapultepec, 58280 Morelia, Mich.',
                'phone' => '4433152343',
                'has_whatsapp' => true,
                'email' => 'info@dentalgroup.com.mx',
                'notes' => '{"batch":"research-dentistas-morelia-dedup-20260428","colonia":"Nueva Chapultepec","instagram":"@dentalgroupmexico","website":"https:\/\/dentalgroup.com.mx\/","source_channel":"website","notes":"25+ años; multi-especialidad endodoncia + periodoncia + implantes + diseño sonrisa + estética + maxilofacial + ortodoncia + odontopediatría; 5 titulares"}',
            ],
            [
                'name' => 'Dra. Berenice Aguirre Solorio',
                'clinic_name' => 'Maxilo Aguirre',
                'specialty' => 'Cirugía Maxilofacial',
                'city' => 'Morelia',
                'address' => 'Alfareros de Capula 11, 58230 Morelia, Mich.',
                'phone' => '4436390237',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-morelia-dedup-20260428","colonia":"Vasco de Quiroga","instagram":"@draaguirremaxilofacial","website":"https:\/\/www.maxiloaguirre.com\/","source_channel":"website","notes":"Cédula 6066784; Consejo Mexicano CMF; oncología bucal; cirugía estética facial; titular único"}',
            ],
            [
                'name' => 'Centro de Diagnóstico en Ortodoncia',
                'clinic_name' => 'Centro de Diagnóstico en Ortodoncia',
                'specialty' => 'Ortodoncia',
                'city' => 'Morelia',
                'address' => 'Morelia, Mich.',
                'phone' => '4433150582',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-morelia-dedup-20260428","colonia":"Centro","website":"https:\/\/www.cdo3d.com\/","source_channel":"website","notes":"Centro de diagnóstico estudios ortodónticos; especializado en imagen para ortodoncia"}',
            ],
            [
                'name' => 'Dr. Bernardo Moreno Domínguez',
                'clinic_name' => 'Dr. Bernardo Moreno & Co.',
                'specialty' => 'Rehabilitación Oral',
                'city' => 'Morelia',
                'address' => 'H. Colegio Militar 82, Chapultepec Sur, Morelia, Mich.',
                'phone' => '4433122214',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-morelia-dedup-20260428","colonia":"Chapultepec Sur","source_channel":"maps","notes":"Titular único; ATM y oclusión + rehabilitación oral + periodoncia; consultorio independiente"}',
            ],
            [
                'name' => 'Dr. Roberto Omaña Naranjo',
                'clinic_name' => 'Dental4Kids',
                'specialty' => 'Odontopediatría',
                'city' => 'Morelia',
                'address' => 'Morelia, Mich.',
                'phone' => '4432073741',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-morelia-dedup-20260428","colonia":"Centro","website":"https:\/\/www.dental4kids.com.mx\/","source_channel":"website","notes":"Titular único odontopediatría exclusiva; ICP nicho infantil"}',
            ],
            [
                'name' => 'Dra. Crystell Rangel',
                'clinic_name' => 'Dentista Para Niños Crystell Rangel',
                'specialty' => 'Odontopediatría',
                'city' => 'Morelia',
                'address' => 'Lic. Pudenciano Dorantes 80, Nueva Chapultepec, 58280 Morelia, Mich.',
                'phone' => '4431237238',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-morelia-dedup-20260428","colonia":"Nueva Chapultepec","rating":"5.0","source_channel":"maps","notes":"Titular única odontopediatría; reputación 5 estrellas; ambiente amigable infantil"}',
            ],
            [
                'name' => 'Dra. Samy',
                'clinic_name' => 'Blue Dental Morelia',
                'specialty' => 'Odontopediatría',
                'city' => 'Morelia',
                'address' => 'Lic. Antonio del Moral 240 Consultorio 1 y 2, Nueva Chapultepec, 58280 Morelia, Mich.',
                'phone' => '4433935191',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-morelia-dedup-20260428","colonia":"Nueva Chapultepec","instagram":"@bluedentalmorelia","website":"https:\/\/bluedentalmorelia.com\/","source_channel":"website","notes":"Multi-especialidad odontopediatría + ortodoncia + periodoncia + endodoncia; segunda sede Chap Norte; ICP boutique"}',
            ],
            [
                'name' => 'Pediátrica Dental Morelia',
                'clinic_name' => 'Pediátrica Dental Morelia',
                'specialty' => 'Odontopediatría',
                'city' => 'Morelia',
                'address' => 'Av. Camelinas 1866 int. 302, Camelinas, Morelia, Mich.',
                'phone' => '4431416898',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-morelia-dedup-20260428","colonia":"Camelinas","source_channel":"maps","notes":"Boutique odontopediatría Camelinas zona premium; ICP nicho infantil tickets premium"}',
            ],
            [
                'name' => 'IMPDENTAL Morelia',
                'clinic_name' => 'IMPDENTAL Morelia',
                'specialty' => 'Implantología',
                'city' => 'Morelia',
                'address' => 'Dr. Ignacio Chávez 35, Bosque Camelinas, Morelia, Mich.',
                'phone' => '4433690121',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-morelia-dedup-20260428","colonia":"Bosque Camelinas","source_channel":"facebook","notes":"Titular implantología; Bosque Camelinas zona premium; FB Impdental Morelia"}',
            ],
            [
                'name' => 'Dental Camelinas Plaza',
                'clinic_name' => 'Dental Camelinas Plaza',
                'specialty' => 'Implantología',
                'city' => 'Morelia',
                'address' => 'Perif. Paseo de la República 2128, Bosque Camelinas, Morelia, Mich.',
                'phone' => '4435313940',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-morelia-dedup-20260428","colonia":"Bosque Camelinas","source_channel":"maps","notes":"Multi-especialidad prótesis + implantes + cirugía oral; Periférico Bosque Camelinas zona premium"}',
            ],
            [
                'name' => 'Odontocentral Clínica Dental',
                'clinic_name' => 'Odontocentral Clínica Dental',
                'specialty' => 'Odontología General',
                'city' => 'Morelia',
                'address' => 'Arnulfo Ávila 811, Morelos, 58030 Morelia, Mich.',
                'phone' => '4432867756',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-morelia-dedup-20260428","colonia":"Morelos","source_channel":"buscodentista","notes":"Consultorio independiente colonia Morelos; ICP local"}',
            ],
            [
                'name' => 'Clínica Dental Condesa LC',
                'clinic_name' => 'Clínica Dental Condesa LC',
                'specialty' => 'Odontología General',
                'city' => 'Morelia',
                'address' => 'Antonio Alzate, Centro, Morelia, Mich.',
                'phone' => '4431881438',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-morelia-dedup-20260428","colonia":"Centro","website":"https:\/\/clinicadentalcondesa.com.mx\/","source_channel":"website","notes":"3 sedes pequeñas Centro\/Chapultepec\/Santa María; multi-especialidad orto + endo + maxilofacial + rehabilitación; tamaño boutique chico"}',
            ],
            [
                'name' => 'Grupo Dental Ángeles',
                'clinic_name' => 'Grupo Dental Ángeles',
                'specialty' => 'Odontología General',
                'city' => 'Morelia',
                'address' => 'Av. Montaña Monarca Norte 331, Desarrollo Montaña Monarca, 58350 Morelia, Mich.',
                'phone' => '4431477150',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-morelia-dedup-20260428","colonia":"Desarrollo Montaña Monarca","instagram":"@gda_morelia","source_channel":"instagram","notes":"Hospital Ángeles Morelia Altozano zona premium; activos en IG"}',
            ],
            [
                'name' => 'Dr. Isaac Antonio López Arceo',
                'clinic_name' => 'Consultorio Dental de Ortodoncia',
                'specialty' => 'Ortodoncia',
                'city' => 'Uruapan',
                'address' => 'Hilanderos 94, La Magdalena, 60080 Uruapan, Mich.',
                'phone' => '4525242605',
                'has_whatsapp' => true,
                'email' => 'drisaaclopezarceo@gmail.com',
                'notes' => '{"batch":"research-dentistas-morelia-dedup-20260428","colonia":"La Magdalena","website":"https:\/\/www.ortodonciauruapan.com\/","source_channel":"website","notes":"Titular único; UNAM + AOMEI + UPenn + Consejo Mexicano Ortodoncia; Magdalena zona consultorios consolidada"}',
            ],
            [
                'name' => 'Dra. Patricia Sánchez Soriano',
                'clinic_name' => 'Rehabilitación Bucal Sánchez',
                'specialty' => 'Rehabilitación Oral',
                'city' => 'Uruapan',
                'address' => 'Hilanderos 377/3, La Magdalena, 60080 Uruapan, Mich.',
                'phone' => '4525247032',
                'has_whatsapp' => true,
                'email' => 'patysanchezsoriano@hotmail.com',
                'notes' => '{"batch":"research-dentistas-morelia-dedup-20260428","colonia":"La Magdalena","website":"https:\/\/www.rehabilitacionbucalsanchez.com\/","source_channel":"website","notes":"22 años experiencia; titular única rehabilitación + diplomada implantología; aguacate-belt clase media-alta"}',
            ],
            [
                'name' => 'Dra. Carmen Edith Rodríguez Camacho',
                'clinic_name' => 'Odontología Estética Rodríguez',
                'specialty' => 'Ortodoncia',
                'city' => 'Uruapan',
                'address' => 'Juan N. López 2/A, La Magdalena, 60080 Uruapan, Mich.',
                'phone' => '4525246904',
                'has_whatsapp' => true,
                'email' => 'consultorio.mey.cr@gmail.com',
                'notes' => '{"batch":"research-dentistas-morelia-dedup-20260428","colonia":"La Magdalena","website":"https:\/\/www.odontologiaesteticaupn.com\/","source_channel":"website","notes":"20+ años; titular única multi-especialidad orto + perio + endo + rehabilitación; ICP boutique"}',
            ],
            [
                'name' => 'Dra. Rosa Alejandra Magaña Moreno',
                'clinic_name' => 'Praxis Dental Uruapan',
                'specialty' => 'Odontopediatría',
                'city' => 'Uruapan',
                'address' => 'Honduras 17 B, Los Ángeles, 60160 Uruapan, Mich.',
                'phone' => '4521318071',
                'has_whatsapp' => true,
                'email' => 'nikitamm_1@hotmail.com',
                'notes' => '{"batch":"research-dentistas-morelia-dedup-20260428","colonia":"Los Ángeles","website":"https:\/\/www.praxisdentaluruapan.com\/","source_channel":"website","notes":"16 años experiencia; titular única odontopediatría exclusiva; bebés + niños + capacidades distintas + adolescentes"}',
            ],
            [
                'name' => 'Dr. Alejandro Mendoza Lemus',
                'clinic_name' => 'Almedent Dr. Mendoza',
                'specialty' => 'Odontología General',
                'city' => 'Uruapan',
                'address' => 'Francisco Villa 32 5 Planta Alta, Morelos, 60050 Uruapan, Mich.',
                'phone' => '4525270903',
                'has_whatsapp' => true,
                'email' => 'almele.7@hotmail.com',
                'notes' => '{"batch":"research-dentistas-morelia-dedup-20260428","colonia":"Morelos","website":"https:\/\/www.almedent.com\/","source_channel":"website","notes":"Titular único multi-especialidad orto + endo + rehabilitación; niños jóvenes adultos"}',
            ],
            [
                'name' => 'Dr. David Almaraz',
                'clinic_name' => 'Dental Flex Uruapan',
                'specialty' => 'Odontología General',
                'city' => 'Uruapan',
                'address' => 'Paseo Lázaro Cárdenas 1114 Edificio Latino Int. 203, Centro, Uruapan, Mich.',
                'phone' => '4521115901',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-morelia-dedup-20260428","colonia":"Centro","instagram":"@dentalflex.com.mx","website":"https:\/\/uruapan.dentalflex.com.mx\/","source_channel":"website","notes":"Multi-especialidad orto + endo + carillas + zirconio + estética + protesis; tickets accesibles"}',
            ],
            [
                'name' => 'Dra. Liliana Rodríguez, Dra. Karla Olea, Dr. Edgar Medina',
                'clinic_name' => 'rDental Uruapan',
                'specialty' => 'Implantología',
                'city' => 'Uruapan',
                'address' => 'Américas 106-B Altos, Morelos, 60050 Uruapan, Mich.',
                'phone' => '4521563169',
                'has_whatsapp' => true,
                'email' => 'rdentalconsultorio@gmail.com',
                'notes' => '{"batch":"research-dentistas-morelia-dedup-20260428","colonia":"Morelos","instagram":"@rdentalmx","website":"https:\/\/www.rdentalmx.com\/","source_channel":"website","notes":"7 titulares multi-especialidad endo + prótesis + perio + orto + rehabilitación + implantes + maxilofacial; ICP boutique premium aguacate-belt"}',
            ],
            [
                'name' => 'Dra. Nancy Anahí Vega Gudiño',
                'clinic_name' => 'Dra. Nancy Vega Dentista de Niños',
                'specialty' => 'Odontopediatría',
                'city' => 'Uruapan',
                'address' => 'Paraguay 387, Los Ángeles, 60160 Uruapan, Mich.',
                'phone' => '4525238897',
                'has_whatsapp' => true,
                'email' => 'nancy21.10@hotmail.com',
                'notes' => '{"batch":"research-dentistas-morelia-dedup-20260428","colonia":"Los Ángeles","website":"https:\/\/www.dranancydentistadeninos.com\/","source_channel":"website","notes":"8 años experiencia; titular única odontopediatría exclusiva; bebés niños adolescentes"}',
            ],
            [
                'name' => 'Dr. Jesús Manuel Doddoli Fragoso',
                'clinic_name' => 'Ortodoncia Doddoli',
                'specialty' => 'Ortodoncia',
                'city' => 'Uruapan',
                'address' => 'Hilanderos 110/202, La Magdalena, 60080 Uruapan, Mich.',
                'phone' => '4525247350',
                'has_whatsapp' => true,
                'email' => 'manueldoddoli@gmail.com',
                'notes' => '{"batch":"research-dentistas-morelia-dedup-20260428","colonia":"La Magdalena","website":"https:\/\/www.ortodonciadoddoli.com\/","source_channel":"website","notes":"20 años experiencia; Maestría Ortodoncia Universidad Intercontinental; titular único"}',
            ],
            [
                'name' => 'Centro Odontológico DentADE',
                'clinic_name' => 'Centro Odontológico DentADE',
                'specialty' => 'Odontología General',
                'city' => 'Uruapan',
                'address' => 'Hilanderos 26 Planta Alta, Morelos, 60050 Uruapan, Mich.',
                'phone' => '4525455995',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-morelia-dedup-20260428","colonia":"Morelos","source_channel":"maps","notes":"Multi-especialidad consultorio independiente; zona Magdalena\/Morelos consolidada"}',
            ],
            [
                'name' => 'Dental Clínic Odontología Integral',
                'clinic_name' => 'Dental Clínic Odontología Integral',
                'specialty' => 'Odontología General',
                'city' => 'Uruapan',
                'address' => 'Niños Héroes 64 Esquina Guadalupe Victoria, Centro, Uruapan, Mich.',
                'phone' => '4521350340',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-morelia-dedup-20260428","colonia":"Centro","website":"https:\/\/dental-clinic-odontologia-integral.ueniweb.com\/","source_channel":"website","notes":"Multi-especialidad incluye ortodoncia; tecnología moderna; Centro Uruapan"}',
            ],
            [
                'name' => 'Dra. Marcela Zamora',
                'clinic_name' => 'Dra. Marcela Zamora Clínica Dental',
                'specialty' => 'Endodoncia',
                'city' => 'Zamora',
                'address' => 'Calle Colón 109, Centro, Zamora, Mich.',
                'phone' => '3511369449',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-morelia-dedup-20260428","colonia":"Centro","source_channel":"facebook","notes":"Dental Care Zamora Clínica Especialidades; FB Dentalcarezam; consultorio Centro"}',
            ],
            [
                'name' => 'Dr. Luis Fernando Morales Martínez',
                'clinic_name' => 'Dr. Luis Fernando Morales Martínez',
                'specialty' => 'Implantología',
                'city' => 'Zamora',
                'address' => 'Pino Suárez Sur 468, Centro, 59600 Zamora, Mich.',
                'phone' => '3515122333',
                'has_whatsapp' => true,
                'email' => 'luisfernandomorales@me.com',
                'notes' => '{"batch":"research-dentistas-morelia-dedup-20260428","colonia":"Centro","website":"https:\/\/www.drluisfernandomorales.com\/","source_channel":"website","notes":"23+ años; UAG 2002 + Maestría Prótesis 2021; cédula 3630126; titular único implantes + prótesis + estética"}',
            ],
            [
                'name' => 'Consultorio Dental Valdés',
                'clinic_name' => 'Consultorio Dental Valdés',
                'specialty' => 'Odontología General',
                'city' => 'Zamora',
                'address' => 'Allende 193, Centro, Zamora, Mich.',
                'phone' => '3511619612',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-morelia-dedup-20260428","colonia":"Centro","website":"https:\/\/xn--valdsdental-ebb.com\/","source_channel":"website","notes":"Multi-especialidad endodoncia + coronas + implantes; consultorio independiente Centro"}',
            ],
            [
                'name' => 'Dr. Marcos Gómez Sosa',
                'clinic_name' => 'Dr. Marcos Gómez Sosa Ortodoncia',
                'specialty' => 'Ortodoncia',
                'city' => 'Pátzcuaro',
                'address' => 'Tángara 15, Centro, 61600 Pátzcuaro, Mich.',
                'phone' => '4341125735',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-morelia-dedup-20260428","colonia":"Centro","source_channel":"doctoralia","notes":"Boutique premium Centro Histórico Pueblo Mágico; 14 años experiencia + 8 años orto exclusiva; titular único turismo nacional"}',
            ],
            [
                'name' => 'Dr. Guillermo Roque Palacios',
                'clinic_name' => 'Odontología Restauradora Palacios',
                'specialty' => 'Odontología General',
                'city' => 'Pátzcuaro',
                'address' => 'Lloreda 5 Plaza Lupita, Centro, 61600 Pátzcuaro, Mich.',
                'phone' => '4341050854',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-morelia-dedup-20260428","colonia":"Centro","rating":"5.0","source_channel":"facebook","notes":"5.0 rating; titular único; Centro Histórico Pueblo Mágico; consultorio independiente"}',
            ],
        ];

        $this->command->info('Insertando ' . count($prospects) . ' dentistas del pilot (research-dentistas-morelia-dedup-20260428)...');

        $inserted = 0;
        $skipped = 0;

        foreach ($prospects as $prospect) {
            // Idempotencia por phone (último match) — no volver a insertar si ya existe
            $existing = Prospect::where('phone', $prospect['phone'])->first();
            if ($existing) {
                $skipped++;
                continue;
            }

            Prospect::create(array_merge($prospect, [
                'source' => 'prospecting', // matches SendProspectEmails cron filter
                'status' => 'new',
                'assigned_to_sales_rep_id' => 100,
                'contact_day' => 0,
                'next_contact_at' => now()->addHour(),
                'outreach_started_at' => now(),
            ]));
            $inserted++;
        }

        $this->command->info("✓ {$inserted} insertados | {$skipped} duplicados saltados | Total en seeder: " . count($prospects));
    }
}
