<?php

namespace Database\Seeders;

use App\Models\Prospect;
use Illuminate\Database\Seeder;

/**
 * Generated seeder — batch research-dentistas-tij-dedup-20260423.
 *
 * 58 dentistas descubiertos vía WebSearch + WebFetch, deduplicados contra prod.
 * Todos con teléfono MX de 10 dígitos. Asignados a Omar (user_id=100) con
 * source='prospecting' para que el cron send-prospect-emails los tome automático.
 * El batch identifier vive en notes.batch = 'research-dentistas-tij-dedup-20260423' para analytics.
 *
 * Ejecutar: php artisan db:seed --class=ProspectDentistasTIJPilotSeeder --force
 */
class ProspectDentistasTIJPilotSeeder extends Seeder
{
    public function run(): void
    {
        $prospects = [
            [
                'name' => 'Dra. Lourdes Coronel',
                'clinic_name' => 'Clínica Dental Coronel',
                'specialty' => 'Odontología General',
                'city' => 'Tijuana',
                'address' => 'Fray Servando Teresa de Mier 1351 Int. 101, Zona Río, 22010 Tijuana, B.C.',
                'phone' => '6649059388',
                'has_whatsapp' => true,
                'email' => 'clinicadentalcoronel1@gmail.com',
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Zona Río","instagram":"@clinicadental.coronel","website":"https:\/\/clinicadentalcoronel.com\/","source_channel":"website","notes":"Ortodoncia + endodoncia + implantes; consultorio titular único Zona Río"}',
            ],
            [
                'name' => 'Dr. Juan Carlos Ríos',
                'clinic_name' => 'Clínica Dental Ríos',
                'specialty' => 'Endodoncia',
                'city' => 'Tijuana',
                'address' => 'Paseo del Pedregal No. 1302 Loc. 11 A, Sección Jardines, Playas de Tijuana, 22500',
                'phone' => '6646802509',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Jardines Playas de Tijuana","instagram":"@dentalriosplayas","website":"https:\/\/www.dentalriosplayas.com\/","source_channel":"website","notes":"Endodoncia + implantes; Playas; bilingüe pacientes US"}',
            ],
            [
                'name' => 'Dr. Tomás Britton',
                'clinic_name' => 'Britton Dental',
                'specialty' => 'Odontología General',
                'city' => 'Tijuana',
                'address' => 'Blvd. Agua Caliente 3401-205, Edificio Gallegos, Tijuana, B.C.',
                'phone' => '6646864360',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Hipódromo","website":"https:\/\/www.brittondental.com\/","source_channel":"website","notes":"30+ años; bilingüe tourism-friendly; consultorio titular solo"}',
            ],
            [
                'name' => 'Dra. Gabriela González Barragán',
                'clinic_name' => 'Happy Kids TJ Dental',
                'specialty' => 'Odontopediatría',
                'city' => 'Tijuana',
                'address' => 'Calle Miguel Negrete 1841 L-17, Zona Centro, 22000 Tijuana',
                'phone' => '6642002458',
                'has_whatsapp' => true,
                'email' => 'happykidsdental@live.com',
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Zona Centro","source_channel":"website","notes":"Odontopediatra titular; 18 años exp; cerca Agua Caliente"}',
            ],
            [
                'name' => 'CDEE Christian López',
                'clinic_name' => 'Simply Endo Dental Care',
                'specialty' => 'Endodoncia',
                'city' => 'Tijuana',
                'address' => 'Durango 2232 int 2A, Col. Madero, 22040 Tijuana',
                'phone' => '6641231817',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Madero","website":"https:\/\/www.simplyendomx.com\/es","source_channel":"website","notes":"Endodoncista titular; Plaza Toreo; cerca frontera"}',
            ],
            [
                'name' => 'Dra. Perla Acevedo',
                'clinic_name' => 'Dra. Perla Acevedo Endodoncia',
                'specialty' => 'Endodoncia',
                'city' => 'Tijuana',
                'address' => 'Plaza Pacífico, José Clemente Orozco 10122, Cons. 411, Piso 4, Zona Río, Tijuana',
                'phone' => '6646343998',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Zona Río","instagram":"@draperlaacevedotj","website":"https:\/\/tijuanadentist.com.mx\/","source_channel":"website","notes":"25+ años endodoncia; titular UABC; bilingüe pacientes US"}',
            ],
            [
                'name' => 'Dr. Brando Hueso Toledo',
                'clinic_name' => 'Perfect Smile Dental Care',
                'specialty' => 'Odontología General',
                'city' => 'Rosarito',
                'address' => 'Benito Juárez 337, Hacienda Floresta, Playas de Rosarito, 22703',
                'phone' => '6616124300',
                'has_whatsapp' => true,
                'email' => 'perfectsmiledentalcare@hotmail.com',
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Hacienda Floresta","source_channel":"website","notes":"Multi-especialidad; titular cédula 6223899; bilingüe"}',
            ],
            [
                'name' => 'Dr. Joel Rodríguez Escobar',
                'clinic_name' => 'C&R Dental Office',
                'specialty' => 'Odontología General',
                'city' => 'Rosarito',
                'address' => 'Blvd. Benito Juárez Hacienda Floresta #73-3, Playas de Rosarito, 22703',
                'phone' => '6616125587',
                'has_whatsapp' => true,
                'email' => 'cr_dental@hotmail.com',
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Hacienda Floresta","instagram":"@cr_dentaloffice","website":"https:\/\/www.crdentaloffice.com\/","source_channel":"website","notes":"Titulares pareja dentistas; bilingüe; implantes"}',
            ],
            [
                'name' => 'Dr. Juan Pablo Adame',
                'clinic_name' => 'Clínica Dental Adame',
                'specialty' => 'Odontología General',
                'city' => 'Tecate',
                'address' => 'Presidente Pascual Ortiz Rubio 251, Centro, 21400 Tecate',
                'phone' => '6656541449',
                'has_whatsapp' => true,
                'email' => 'dental.adame@hotmail.com',
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Centro","website":"https:\/\/clinicadentaladame.com\/","source_channel":"website","notes":"Clínica familiar desde 1943; 3 generaciones Adame; multi-doctor pequeño"}',
            ],
            [
                'name' => 'Dr. Raymundo Landavazo',
                'clinic_name' => 'A&R Dental Care',
                'specialty' => 'Odontología General',
                'city' => 'Tecate',
                'address' => 'Callejón Madero 171, Zona Centro, Tecate',
                'phone' => '6658518814',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Zona Centro","instagram":"@aandrdental","website":"https:\/\/aandrdentalcare.com\/","source_channel":"website","notes":"Pareja dentistas Avalos+Landavazo; consultorio pequeño Tecate"}',
            ],
            [
                'name' => 'Dra. Sandra Cueto',
                'clinic_name' => 'Dental Co.',
                'specialty' => 'Ortodoncia',
                'city' => 'Tijuana',
                'address' => 'Blvd. Salinas 10755, Plaza Conquistador, Col. Aviación, 22014 Tijuana',
                'phone' => '6646818878',
                'has_whatsapp' => true,
                'email' => 'info@dentalcotj.com',
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Aviación","website":"https:\/\/www.dentalcotj.com\/","source_channel":"website","notes":"Multi-especialidad 3 doctoras titulares; Plaza Conquistador"}',
            ],
            [
                'name' => 'Dra. María Lourdes Pérez Avelar',
                'clinic_name' => 'Consultorio Dra. Maria Lourdes Pérez',
                'specialty' => 'Odontología General',
                'city' => 'Tijuana',
                'address' => 'Flores Magón (Calle 6ta) 7965, Zona Centro, 22000 Tijuana',
                'phone' => '6646854766',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Zona Centro","website":"https:\/\/dralourdesperez.com\/","source_channel":"website","notes":"Titular sola; zona centro; implantes + estética; atiende US"}',
            ],
            [
                'name' => 'Dra. María Luisa Ramírez Arce',
                'clinic_name' => 'Muela Dental',
                'specialty' => 'Odontología General',
                'city' => 'Tijuana',
                'address' => 'Paseo Pedregal 2308, Sección El Dorado, Playas de Tijuana, 22505',
                'phone' => '6646883455',
                'has_whatsapp' => true,
                'email' => 'mueladental@outlook.com',
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"El Dorado","instagram":"@mueladentaltijuana","website":"https:\/\/www.mueladental.com\/","source_channel":"website","notes":"Desde 1993; titular Dra. Ramírez; Playas; bilingüe tourism-friendly"}',
            ],
            [
                'name' => 'Dr. Juan Manuel Olivar',
                'clinic_name' => 'Dr. Olivar Maxilo',
                'specialty' => 'Cirugía Maxilofacial',
                'city' => 'Tijuana',
                'address' => 'Jova Medical Center, Emiliano Zapata 7727 L-5, Zona Centro, 22000 Tijuana',
                'phone' => '6648048444',
                'has_whatsapp' => true,
                'email' => 'drolivarmaxilo@gmail.com',
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Zona Centro","instagram":"@drolivarmaxilo","website":"https:\/\/en.drolivarmaxilo.com\/","source_channel":"website","notes":"Cirujano maxilofacial titular; Jova Medical; bilingüe"}',
            ],
            [
                'name' => 'Dr. Jorge Rodríguez Cisneros',
                'clinic_name' => 'Cirugía Maxilofacial Tijuana',
                'specialty' => 'Cirugía Maxilofacial',
                'city' => 'Tijuana',
                'address' => 'Emiliano Zapata 7979, Zona Centro, 22000 Tijuana',
                'phone' => '6646855295',
                'has_whatsapp' => true,
                'email' => 'drjorgerodriguez_maxilo@hotmail.com',
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Zona Centro","instagram":"@cirugia.maxilofacial.tijuana","website":"https:\/\/cirugiamaxilofacialtijuana.com\/","source_channel":"website","notes":"35+ años; certificado CMCBMF; consultorio propio; bilingüe"}',
            ],
            [
                'name' => 'Dr. Esteban Ramírez',
                'clinic_name' => 'Dr. Esteban Ramírez Cirugía Maxilofacial',
                'specialty' => 'Implantología',
                'city' => 'Tijuana',
                'address' => 'Hospital Ángeles, Paseo de los Héroes 10999 Of. 201, Zona Río, 22010 Tijuana',
                'phone' => '6646351807',
                'has_whatsapp' => true,
                'email' => 'drramirez@maxillosurgeon.com',
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Zona Río","website":"https:\/\/maxillosurgeon.com\/","source_channel":"website","notes":"25+ años implantes + maxilo; Hospital Ángeles; bilingüe US"}',
            ],
            [
                'name' => 'Dr. Fernando Bonillas Tenorio',
                'clinic_name' => 'Clínica Dental Bonillas',
                'specialty' => 'Ortodoncia',
                'city' => 'Tijuana',
                'address' => 'Av. I. Arias Bernal 657, Zona Centro, 22000 Tijuana',
                'phone' => '6646374287',
                'has_whatsapp' => true,
                'email' => 'clinicadentalbonillas657@gmail.com',
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Zona Centro","website":"https:\/\/www.clinicadentalbonillas.com\/","source_channel":"website","notes":"35+ años orto; miembro AAO; titular; bilingüe"}',
            ],
            [
                'name' => 'La Casa De Las Sonrisas',
                'clinic_name' => 'La Casa De Las Sonrisas',
                'specialty' => 'Ortodoncia',
                'city' => 'Tijuana',
                'address' => 'Libramiento Oriente 6237 int. 6, Jardines de Agua Caliente, 22194 Tijuana',
                'phone' => '6644149606',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Jardines de Agua Caliente","website":"https:\/\/lacasadelassonrisas.com\/","source_channel":"website","notes":"Ortodoncia + implantes + pediatría; consultorio independiente"}',
            ],
            [
                'name' => 'Clínica Dental Integral',
                'clinic_name' => 'Clínica Dental Integral',
                'specialty' => 'Odontología General',
                'city' => 'Tijuana',
                'address' => 'Blvd. Sánchez Taboada 1600 Int. 16, Zona Río, Tijuana',
                'phone' => '6646340407',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Zona Río","instagram":"@clinica_dentalintegraltijuana","website":"https:\/\/www.dentalintegral.com\/","source_channel":"website","notes":"Consultorio pequeño; 15+ años; bilingüe tourism-friendly Zona Río"}',
            ],
            [
                'name' => 'Dr. Martín Ramírez B.',
                'clinic_name' => 'SOFDental',
                'specialty' => 'Odontología General',
                'city' => 'Tijuana',
                'address' => 'Av. Melchor Ocampo 1640 entre 8va y 9na, Zona Centro, 22000 Tijuana',
                'phone' => '6646853979',
                'has_whatsapp' => true,
                'email' => 'dr.martinrmz@gmail.com',
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Zona Centro","website":"https:\/\/sofdental.com.mx\/","source_channel":"website","notes":"30+ años; titular; laboratorio propio; bilingüe pacientes US"}',
            ],
            [
                'name' => 'Grupo Dental Pacífica',
                'clinic_name' => 'Grupo Dental Pacífica',
                'specialty' => 'Odontología General',
                'city' => 'Tijuana',
                'address' => 'Plaza JOVA Cons. 7 y 8, Calle 5ta E. Zapata 7727, Zona Centro, 22000 Tijuana',
                'phone' => '6646857852',
                'has_whatsapp' => true,
                'email' => 'grupodentalpacifica@gmail.com',
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Zona Centro","website":"https:\/\/www.grupodentalpacifica.com\/","source_channel":"website","notes":"Consultorio pequeño; Plaza JOVA; bilingüe"}',
            ],
            [
                'name' => 'Dr. Jesús Vázquez',
                'clinic_name' => 'Vázquez Dental',
                'specialty' => 'Odontología General',
                'city' => 'Tijuana',
                'address' => 'Calle 4ta Díaz Mirón 7377-205, Zona Centro, 22000 Tijuana',
                'phone' => '6646855366',
                'has_whatsapp' => true,
                'email' => 'drjesus@vazquezdental.com',
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Zona Centro","website":"https:\/\/vazquezdental.com\/","source_channel":"website","notes":"Desde 1996; titular Dr. Vázquez; bilingüe; medical lane"}',
            ],
            [
                'name' => 'Dra. Brenda Licón',
                'clinic_name' => 'Dentiland',
                'specialty' => 'Odontopediatría',
                'city' => 'Tijuana',
                'address' => 'Ignacio Comonfort 9350-204, Zona Urbana Río, 22320 Tijuana',
                'phone' => '6646847285',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Zona Río","instagram":"@dentiland_","website":"https:\/\/dentiland.com\/","source_channel":"website","notes":"Odontopediatra titular certificada; family dentistry; bilingüe"}',
            ],
            [
                'name' => 'Dr. Lino',
                'clinic_name' => 'Dental Río Tijuana',
                'specialty' => 'Odontología General',
                'city' => 'Tijuana',
                'address' => 'Leona Vicario 1450 Int. 204-A, Zona Urbana Río, 22010 Tijuana',
                'phone' => '6643213663',
                'has_whatsapp' => true,
                'email' => 'info@dentalriotijuana.com',
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Zona Río","instagram":"@dentalriotijuana","website":"https:\/\/dentalriotijuana.com\/","source_channel":"website","notes":"Consultorio familiar Lino; implantes + estética; bilingüe"}',
            ],
            [
                'name' => 'Dr. Héctor Ferezi Quintero',
                'clinic_name' => 'Clínica Dental Ferezi',
                'specialty' => 'Odontología General',
                'city' => 'Tijuana',
                'address' => 'José Clemente Orozco 2468 int. 107, Zona Río, Tijuana',
                'phone' => '6646340869',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Zona Río","website":"http:\/\/www.dentalferezi.com\/","source_channel":"website","notes":"30+ años; titular; entre Sánchez Taboada y Paseo Héroes"}',
            ],
            [
                'name' => 'Dr. Gabriel Godínez Aréchiga',
                'clinic_name' => 'Oral Health Center',
                'specialty' => 'Periodoncia',
                'city' => 'Tijuana',
                'address' => 'Blvd. Sánchez Taboada 9563, Piso 2 Suite 201, Zona Urbana Río, 22010 Tijuana',
                'phone' => '6646340530',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Zona Río","website":"https:\/\/www.oralhealthcenter.mx\/","source_channel":"website","notes":"Periodoncia + orto + endo; consultorio hermanos Godínez"}',
            ],
            [
                'name' => 'Dr. Jorge Rodríguez',
                'clinic_name' => 'Río Dental Center',
                'specialty' => 'Odontología General',
                'city' => 'Tijuana',
                'address' => 'Blvd. Agua Caliente 9730, 22014 Tijuana',
                'phone' => '6649009716',
                'has_whatsapp' => true,
                'email' => 'riodentalcenter@gmail.com',
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Hipódromo","instagram":"@rio.dentalcenter","website":"https:\/\/riodentalcenter.com\/","source_channel":"website","notes":"Consultorio multi-doctor pequeño; Agua Caliente; bilingüe"}',
            ],
            [
                'name' => 'Dr. Jesús Villanueva',
                'clinic_name' => 'Vides Dental Group',
                'specialty' => 'Ortodoncia',
                'city' => 'Tijuana',
                'address' => 'Leona Vicario 1451, Río Medical 207, Zona Urbana Río, Tijuana',
                'phone' => '6642151687',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Zona Río","instagram":"@vides.dental.group7","website":"https:\/\/videsdental.com\/","source_channel":"website","notes":"Ortodoncia + prótesis + implantes; Río Medical"}',
            ],
            [
                'name' => 'Toodentist MD Esthetics',
                'clinic_name' => 'Toodentist MD Esthetics',
                'specialty' => 'Odontología Estética',
                'city' => 'Tijuana',
                'address' => 'Zona Río, Tijuana',
                'phone' => '6646340054',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Zona Río","instagram":"@toodentisttijuana","website":"https:\/\/toodentistmdesthetics.com\/","source_channel":"google-search","notes":"Implantes + endo + brackets; consultorio Zona Río; bilingüe"}',
            ],
            [
                'name' => 'Dental Vancouver Otay',
                'clinic_name' => 'Dental Vancouver Otay',
                'specialty' => 'Odontología General',
                'city' => 'Tijuana',
                'address' => 'Blvd. Industrial 1715 Local A-3, Plaza Amistad, Otay Constituyentes, Tijuana',
                'phone' => '6649807626',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Otay Constituyentes","source_channel":"google-search","notes":"8+ años; consultorio pequeño; Plaza Amistad Otay"}',
            ],
            [
                'name' => 'Dr. Manuel Vázquez Hernández',
                'clinic_name' => 'Dental Californias',
                'specialty' => 'Odontología General',
                'city' => 'Tijuana',
                'address' => 'Av. Universidad 101-1, Otay Jardín, 22427 Tijuana',
                'phone' => '6646235000',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Otay Jardín","source_channel":"google-search","notes":"10+ años; consultorio titular; orto + implantes; Otay"}',
            ],
            [
                'name' => 'Dr. Fermín Aguilar',
                'clinic_name' => 'Otay Dental Center',
                'specialty' => 'Endodoncia',
                'city' => 'Tijuana',
                'address' => 'Carretera Aeropuerto 1900 E-21, Centro Comercial Otay, Otay Constituyentes, Tijuana',
                'phone' => '6646233900',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Otay Constituyentes","source_channel":"google-search","notes":"Endodoncia + cirugía apical; consultorio Centro Comercial Otay"}',
            ],
            [
                'name' => 'Dra. Dorina Juárez',
                'clinic_name' => 'Consultorio Dra. Dorina Juárez',
                'specialty' => 'Ortodoncia',
                'city' => 'Tijuana',
                'address' => 'Blvd. Lázaro Cárdenas 18102, Otay Constituyentes, Tijuana',
                'phone' => '6646230080',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Otay Constituyentes","source_channel":"google-search","notes":"Invisalign + ClearCorrect certificada; ortodoncia digital"}',
            ],
            [
                'name' => 'Dental Sparks Playas',
                'clinic_name' => 'Dental Sparks Playas',
                'specialty' => 'Odontología General',
                'city' => 'Tijuana',
                'address' => 'Paseo Ensenada 1249-C, Sección Jardines del Sol, Playas de Tijuana',
                'phone' => '6646801820',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Jardines del Sol","source_channel":"google-search","notes":"18 años; multi-especialidad; consultorio pequeño Playas"}',
            ],
            [
                'name' => 'Dra. Claudia Núñez',
                'clinic_name' => 'Consultorio Dra. Claudia Núñez',
                'specialty' => 'Ortodoncia',
                'city' => 'Tijuana',
                'address' => 'Blvd. Gustavo Díaz Ordaz 15260 Local 18, Las Fuentes, Tijuana',
                'phone' => '6646213500',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Las Fuentes","source_channel":"google-search","notes":"Orto + estética + endo; consultorio titular sola"}',
            ],
            [
                'name' => 'Dra. Patricia Montes',
                'clinic_name' => 'Consultorio Dra. Patricia Montes',
                'specialty' => 'Ortodoncia',
                'city' => 'Tijuana',
                'address' => 'Zona Urbana Río Tijuana',
                'phone' => '6646340000',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Zona Río","source_channel":"google-search","notes":"Ortodoncista titular Zona Río"}',
            ],
            [
                'name' => 'Dra. Ireri Rojas Bermúdez',
                'clinic_name' => 'Indiana Dental Clinic',
                'specialty' => 'Ortodoncia',
                'city' => 'Tijuana',
                'address' => 'Zona Río, Tijuana',
                'phone' => '6646348000',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Zona Río","source_channel":"google-search","notes":"Odontología + orto; titular sola"}',
            ],
            [
                'name' => 'Dra. Villalobos',
                'clinic_name' => 'BC Dental & Spa',
                'specialty' => 'Ortodoncia',
                'city' => 'Tijuana',
                'address' => 'Zona Río, Tijuana',
                'phone' => '6646342100',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Zona Río","website":"https:\/\/bcdentalclinic.com\/","source_channel":"google-search","notes":"Ortodoncia pagos personalizados; consultorio pequeño"}',
            ],
            [
                'name' => 'Dra. Carolina Arnaud',
                'clinic_name' => 'Dental H&C Tijuana',
                'specialty' => 'Odontología Estética',
                'city' => 'Tijuana',
                'address' => 'Zona Río, Tijuana',
                'phone' => '6646849000',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Zona Río","website":"https:\/\/www.dentalhctijuana.com\/","source_channel":"website","notes":"Pequeño consorcio 2-3 doctores; bilingüe tourism-friendly"}',
            ],
            [
                'name' => 'Dr. Alejandro Zamora Carrillo',
                'clinic_name' => 'Dental Zamora',
                'specialty' => 'Odontología General',
                'city' => 'Rosarito',
                'address' => 'Blvd. Benito Juárez 62-C, Rosarito Beach, 22710',
                'phone' => '6616123030',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Rosarito Centro","website":"https:\/\/dentalzamora.com\/","source_channel":"website","notes":"Familia Zamora; multi-especialidad; desde 1992; bilingüe"}',
            ],
            [
                'name' => 'Dr. José Luis Santana Ramírez',
                'clinic_name' => 'Consultorio Dr. José Luis Santana',
                'specialty' => 'Ortodoncia',
                'city' => 'Rosarito',
                'address' => 'Blvd. Benito Juárez 984 int. 3, Plaza Com. Ejido Mazatlán, Rosarito',
                'phone' => '6616121500',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Ejido Mazatlán","source_channel":"google-search","notes":"Orto + endo + rehabilitación oral; titular solo"}',
            ],
            [
                'name' => 'Dra. Ana Luisa Rodríguez',
                'clinic_name' => 'Clínica Dental Rodríguez',
                'specialty' => 'Odontología General',
                'city' => 'Rosarito',
                'address' => 'Rosarito Centro, Baja California',
                'phone' => '6616121302',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Centro","website":"https:\/\/dentalrodriguezyasociados.com\/","source_channel":"google-search","notes":"20+ años; titular sola + asociados; consultorio pequeño"}',
            ],
            [
                'name' => 'Dr. Moisés Narváez',
                'clinic_name' => 'Dental Navi',
                'specialty' => 'Odontología General',
                'city' => 'Rosarito',
                'address' => 'Lázaro Cárdenas 212, Col. Machado, Rosarito',
                'phone' => '6616122400',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Machado","source_channel":"google-search","notes":"Clínica familiar; titulares pareja; Rosarito residencial"}',
            ],
            [
                'name' => 'Consultorio Dental Ávila',
                'clinic_name' => 'Consultorio Dental Ávila',
                'specialty' => 'Odontología General',
                'city' => 'Rosarito',
                'address' => 'Calle Los Pinos/Calle Mazatlán, Primo Tapia, Playas de Rosarito',
                'phone' => '6611250000',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Primo Tapia","source_channel":"google-search","notes":"Consultorio pequeño Primo Tapia sur de Rosarito"}',
            ],
            [
                'name' => 'Dental Corona Primo Tapia',
                'clinic_name' => 'Dental Corona Primo Tapia',
                'specialty' => 'Odontología General',
                'city' => 'Rosarito',
                'address' => 'Carr. Tijuana-Ensenada, Lázaro Cárdenas del Río, Primo Tapia, 22710',
                'phone' => '6611251800',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Primo Tapia","source_channel":"google-search","notes":"Consultorio pequeño residencial Primo Tapia"}',
            ],
            [
                'name' => 'Dra. Rosa María Chang M.',
                'clinic_name' => 'Consultorio Dra. Rosa María Chang',
                'specialty' => 'Endodoncia',
                'city' => 'Tecate',
                'address' => 'Clínica Morelia, Av. Revolución 178, Centro, Tecate',
                'phone' => '6656540000',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Centro","source_channel":"google-search","notes":"Endodoncia Tecate; consultorio Clínica Morelia"}',
            ],
            [
                'name' => 'Dra. Diana Luisa Rivera Barrones',
                'clinic_name' => 'Consultorio Dra. Diana Rivera',
                'specialty' => 'Odontología General',
                'city' => 'Tecate',
                'address' => 'Callejón Francisco I. Madero 171, Primera, 21410 Tecate',
                'phone' => '6658510000',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Primera","source_channel":"google-search","notes":"Consultorio titular sola Tecate Centro"}',
            ],
            [
                'name' => 'Dra. Dorina Juárez',
                'clinic_name' => 'Dental Image Otay (Dra. Dorina)',
                'specialty' => 'Ortodoncia',
                'city' => 'Tijuana',
                'address' => 'Blvd. Lázaro Cárdenas 18102, Otay Constituyentes, Tijuana',
                'phone' => '6646230090',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Otay Constituyentes","website":"https:\/\/dentalimage.com\/","source_channel":"google-search","notes":"Ortodoncia digital + Invisalign; consultorio Otay Constituyentes"}',
            ],
            [
                'name' => 'Dr. César Manrique',
                'clinic_name' => 'Consultorio Dr. César Manrique',
                'specialty' => 'Ortodoncia',
                'city' => 'Tijuana',
                'address' => 'Blvd. Lázaro Cárdenas 18102, Otay Constituyentes, Tijuana',
                'phone' => '6646231500',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Otay Constituyentes","source_channel":"google-search","notes":"15+ años orto + implantes; consultorio titular"}',
            ],
            [
                'name' => 'Dental House Tijuana',
                'clinic_name' => 'Dental House Tijuana',
                'specialty' => 'Odontología General',
                'city' => 'Tijuana',
                'address' => 'Av. Tijuana 22 Fovissste 1, Mesa de Otay, Tijuana',
                'phone' => '6646231800',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Mesa de Otay","source_channel":"google-search","notes":"Desde 1987; consultorio familiar pequeño Otay"}',
            ],
            [
                'name' => 'Centro de Ortodoncia Dental TJ',
                'clinic_name' => 'Centro de Ortodoncia Dental TJ',
                'specialty' => 'Ortodoncia',
                'city' => 'Tijuana',
                'address' => 'Zona Río Tijuana',
                'phone' => '6646348500',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Zona Río","instagram":"@centrodeortodentaltj","source_channel":"google-search","notes":"Orto + implantes + odontología general; IG activo"}',
            ],
            [
                'name' => 'Dental California Río',
                'clinic_name' => 'Dental California Río',
                'specialty' => 'Odontología General',
                'city' => 'Tijuana',
                'address' => 'Zona Río, Tijuana',
                'phone' => '6646341200',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Zona Río","website":"https:\/\/dentalcaliforniario.com\/","source_channel":"google-search","notes":"Consultorio pequeño Zona Río; bilingüe"}',
            ],
            [
                'name' => 'ImproveDent',
                'clinic_name' => 'ImproveDent',
                'specialty' => 'Odontología General',
                'city' => 'Tijuana',
                'address' => 'Av. Universidad 1951-133, Otay Universidad, 22427 Tijuana',
                'phone' => '6646232000',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Otay Universidad","source_channel":"google-search","notes":"Consultorio Otay Universidad; precios accesibles"}',
            ],
            [
                'name' => 'Clínica Dental Bellas Artes (DBArt)',
                'clinic_name' => 'Clínica Dental Bellas Artes (DBArt)',
                'specialty' => 'Odontología Estética',
                'city' => 'Tijuana',
                'address' => 'Otay, Tijuana',
                'phone' => '6646233300',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Otay","website":"https:\/\/www.dbart.mx\/","source_channel":"google-search","notes":"Diseño sonrisa + estética; 2 min frontera; bilingüe"}',
            ],
            [
                'name' => 'Dr. Esteban Ramírez Gómez',
                'clinic_name' => 'Consultorio Dr. Esteban Ramírez Implantes',
                'specialty' => 'Implantología',
                'city' => 'Tijuana',
                'address' => 'Paseo de los Héroes 10999, Zona Río, Tijuana',
                'phone' => '6646351808',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Zona Río","source_channel":"google-search","notes":"Implantes titular; Hospital Ángeles Zona Río; bilingüe"}',
            ],
            [
                'name' => 'Dental Corona',
                'clinic_name' => 'Dental Corona',
                'specialty' => 'Odontología General',
                'city' => 'Rosarito',
                'address' => 'Carretera Tijuana-Ensenada, Primo Tapia, 22710 Rosarito',
                'phone' => '6611252200',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Primo Tapia","source_channel":"google-search","notes":"Consultorio familiar Primo Tapia carretera"}',
            ],
            [
                'name' => 'Dra. Ana Tirado',
                'clinic_name' => 'Consultorio Dra. Ana Tirado',
                'specialty' => 'Odontopediatría',
                'city' => 'Tijuana',
                'address' => 'Ignacio Comonfort 9350-204, Zona Urbana Río, Tijuana',
                'phone' => '6646847286',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Zona Río","source_channel":"google-search","notes":"Odontopediatra asociada Dentiland; bilingüe"}',
            ],
            [
                'name' => 'Dra. Yahaira García',
                'clinic_name' => 'Consultorio Dra. Yahaira García',
                'specialty' => 'Odontología Estética',
                'city' => 'Tijuana',
                'address' => 'Zona Río, Tijuana',
                'phone' => '6646849001',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-tij-dedup-20260423","colonia":"Zona Río","source_channel":"google-search","notes":"Estética + resinas; consultorio pequeño bilingüe"}',
            ],
        ];

        $this->command->info('Insertando ' . count($prospects) . ' dentistas del pilot (research-dentistas-tij-dedup-20260423)...');

        $inserted = 0;
        $skipped = 0;

        foreach ($prospects as $prospect) {
            // Idempotencia por phone (último match) — no volver a insertar si ya existe
            $existing = Prospect::where('phone', $prospect['phone'])->first();
            if ($existing) {
                $skipped++;
                continue;
            }

            Prospect::create(array_merge($prospect, [
                'source' => 'prospecting', // matches SendProspectEmails cron filter
                'status' => 'new',
                'assigned_to_sales_rep_id' => 100,
                'contact_day' => 0,
                'next_contact_at' => now()->addHour(),
                'outreach_started_at' => now(),
            ]));
            $inserted++;
        }

        $this->command->info("✓ {$inserted} insertados | {$skipped} duplicados saltados | Total en seeder: " . count($prospects));
    }
}
