<?php

namespace Database\Seeders;

use App\Models\Prospect;
use Illuminate\Database\Seeder;

/**
 * Generated seeder — batch research-dentistas-cuernavaca-dedup-20260427.
 *
 * 60 dentistas descubiertos vía WebSearch + WebFetch, deduplicados contra prod.
 * Todos con teléfono MX de 10 dígitos. Asignados a Omar (user_id=100) con
 * source='prospecting' para que el cron send-prospect-emails los tome automático.
 * El batch identifier vive en notes.batch = 'research-dentistas-cuernavaca-dedup-20260427' para analytics.
 *
 * Ejecutar: php artisan db:seed --class=ProspectDentistasCuernavacaPilotSeeder --force
 */
class ProspectDentistasCuernavacaPilotSeeder extends Seeder
{
    public function run(): void
    {
        $prospects = [
            [
                'name' => 'Dr. Oscar S.',
                'clinic_name' => 'La Clínica Dental Cuernavaca',
                'specialty' => 'Implantología',
                'city' => 'Cuernavaca',
                'address' => 'Av. Río Mayo 1001, Vista Hermosa, 62290 Cuernavaca, Mor.',
                'phone' => '7774540185',
                'has_whatsapp' => true,
                'email' => 'info@laclinicadental.com.mx',
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Vista Hermosa","instagram":"@laclinicadental_mexico","website":"https:\/\/laclinicadental.com.mx\/","source_channel":"website","notes":"Boutique premium Vista Hermosa zona alta; multi-especialidad implantes + ortodoncia + estética; tecnología digital DSD; tickets premium spillover CDMX"}',
            ],
            [
                'name' => 'Dra. Beatriz Palacios Zúñiga',
                'clinic_name' => 'Denta Clinique',
                'specialty' => 'Odontología General',
                'city' => 'Cuernavaca',
                'address' => 'Av. Teopanzolco 408 Torre C 203, Reforma, 62260 Cuernavaca, Mor.',
                'phone' => '7773160771',
                'has_whatsapp' => true,
                'email' => 'dra_palacios@hotmail.com',
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Reforma","website":"https:\/\/www.dentaclinique.com.mx\/","source_channel":"website","notes":"Titular única 26 años experiencia; Recertificación AMD; multi-especialidad; consultorio premium Reforma"}',
            ],
            [
                'name' => 'Ortho Frank Dental',
                'clinic_name' => 'Ortho Frank Dental',
                'specialty' => 'Ortodoncia',
                'city' => 'Cuernavaca',
                'address' => 'Av. Tabachín 97, Bellavista, 62130 Cuernavaca, Mor.',
                'phone' => '7771021102',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Bellavista","instagram":"@orthofrankdental","website":"https:\/\/www.orthofrankdental.com\/","source_channel":"website","notes":"Centro Avanzado en Ortodoncia y Odontología A.C.; multi-especialidad ortodoncia + maxilofacial + implantes; zona Tabachines premium"}',
            ],
            [
                'name' => 'Dental System',
                'clinic_name' => 'Dental System',
                'specialty' => 'Odontología General',
                'city' => 'Cuernavaca',
                'address' => 'Pericón 116 Plaza Andrómeda local 22 y 23, Lomas de la Selva, 62270 Cuernavaca, Mor.',
                'phone' => '7771348910',
                'has_whatsapp' => true,
                'email' => 'dentalsystemcuernavaca@gmail.com',
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Lomas de la Selva","website":"https:\/\/www.dentalsystemencuernavaca.com\/","source_channel":"website","notes":"Multi-especialidad rehabilitación bucal; Plaza Andrómeda Lomas de la Selva zona premium"}',
            ],
            [
                'name' => 'Dra. Itiel Mondragón Meléndez',
                'clinic_name' => 'Clínica Dental Cuernavaca WeSmile',
                'specialty' => 'Ortodoncia',
                'city' => 'Cuernavaca',
                'address' => 'Av. Alta Tensión 18 Local 208, Cantarranas, 62448 Cuernavaca, Mor.',
                'phone' => '7772446560',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Cantarranas","website":"https:\/\/www.clinicadentalcuernavaca.com\/","source_channel":"website","notes":"4 titulares: Mondragón orto + Castañeda cirugía + Arellano endodoncia (pareja); rehabilitación integral"}',
            ],
            [
                'name' => 'Healteeth Dental Center',
                'clinic_name' => 'Healteeth Dental Center',
                'specialty' => 'Odontología General',
                'city' => 'Cuernavaca',
                'address' => 'Av. Morelos 178 Local D-3 Plaza Esmeralda, Centro, Cuernavaca, Mor.',
                'phone' => '7773103654',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Centro","instagram":"@dentalcentercuerna","website":"https:\/\/www.dentalcentercuernavaca.com\/","source_channel":"website","notes":"Sin sucursales; multi-especialidad ortodoncia + implantes + maxilofacial + odontopediatría"}',
            ],
            [
                'name' => 'Dr. Iván Bello',
                'clinic_name' => 'Estética Dental Center',
                'specialty' => 'Odontología Estética',
                'city' => 'Cuernavaca',
                'address' => 'Av. Morelos Sur, Privada del Carmen 9, Torre Médica Cuernavaca Piso 6, Cuernavaca, Mor.',
                'phone' => '7772900100',
                'has_whatsapp' => true,
                'email' => 'estetica.dental.center3@gmail.com',
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Privada del Carmen","instagram":"@estetica_dental_center_","website":"https:\/\/www.esteticadentalcenter.com\/","source_channel":"website","notes":"Diseño sonrisa + brackets + ácido hialurónico + Botox; Torre Médica zona médica premium"}',
            ],
            [
                'name' => 'Dr. Levin Barajas',
                'clinic_name' => 'Clínica Dental Spekter',
                'specialty' => 'Implantología',
                'city' => 'Cuernavaca',
                'address' => 'Av. Cuauhtémoc 121, Chapultepec, 62450 Cuernavaca, Mor.',
                'phone' => '7771294491',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Chapultepec","instagram":"@clinicadentalspekter","website":"https:\/\/dentalspekter.com\/","source_channel":"website","notes":"Cédula 13569155; All-On-4 + DSD; 15+ años implantología; ortodoncia estética + alineadores; Chapultepec premium"}',
            ],
            [
                'name' => 'Smile Cuernavaca',
                'clinic_name' => 'Smile Cuernavaca',
                'specialty' => 'Ortodoncia',
                'city' => 'Cuernavaca',
                'address' => 'Chilpancingo 105 Int 20 ALTHEA, Vista Hermosa, Cuernavaca, Mor.',
                'phone' => '7779862002',
                'has_whatsapp' => true,
                'email' => 'contacto@smilecuernavaca.com',
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Vista Hermosa","instagram":"@smilecuernavaca","website":"https:\/\/www.smilecuernavaca.com\/","source_channel":"website","notes":"Boutique Vista Hermosa zona alta; Invisalign + Aliwell; parte de Dental Smile Group Acapulco\/Cuernavaca; ICP boutique premium spillover CDMX"}',
            ],
            [
                'name' => 'Dra. Mayra Moreno Rojas',
                'clinic_name' => 'Ortodoncia Cuernavaca',
                'specialty' => 'Ortodoncia',
                'city' => 'Cuernavaca',
                'address' => 'Cuernavaca, Mor.',
                'phone' => '7771875119',
                'has_whatsapp' => true,
                'email' => 'dra_may_mor@hotmail.com',
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Centro","instagram":"@ortodoncia_mayra_moreno","website":"https:\/\/www.ortodonciacuernavaca.com\/","source_channel":"website","notes":"12+ años; 500+ casos; brackets + alineadores invisibles; opera Cuernavaca + CDMX titular única"}',
            ],
            [
                'name' => 'Dental Health Solutions',
                'clinic_name' => 'Dental Health Solutions',
                'specialty' => 'Endodoncia',
                'city' => 'Cuernavaca',
                'address' => 'Av. Diana 4A, Delicias, 62330 Cuernavaca, Mor.',
                'phone' => '7773220885',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Delicias","website":"https:\/\/dentalhealthsolutions.com.mx\/","source_channel":"website","notes":"Multi-especialidad endodoncia + estética + implantes + cirugía; zona Delicias media-premium"}',
            ],
            [
                'name' => 'Centro Médico Clínico',
                'clinic_name' => 'Centro Médico Clínico',
                'specialty' => 'Ortodoncia',
                'city' => 'Cuernavaca',
                'address' => 'Av. de los Maestros 203, El Vergel, 62400 Cuernavaca, Mor.',
                'phone' => '7773122214',
                'has_whatsapp' => true,
                'email' => 'contacto@centromedicoclinico.com',
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"El Vergel","website":"https:\/\/centromedicoclinico.com\/","source_channel":"website","notes":"Multi-especialidad ortodoncia + endodoncia + odontopediatría + implantes; zona El Vergel"}',
            ],
            [
                'name' => 'Clínica Dental Ponce',
                'clinic_name' => 'Clínica Dental Ponce',
                'specialty' => 'Odontología General',
                'city' => 'Cuernavaca',
                'address' => 'Av. Diana 148, Delicias, 62330 Cuernavaca, Mor.',
                'phone' => '7772452922',
                'has_whatsapp' => true,
                'email' => 'clinicadentalponce@gmail.com',
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Delicias","website":"https:\/\/dentalponce.com.mx\/","source_channel":"website","notes":"Sitio web activo zona Delicias; consultorio independiente"}',
            ],
            [
                'name' => 'Junco Odontología',
                'clinic_name' => 'Junco Odontología',
                'specialty' => 'Odontología Estética',
                'city' => 'Cuernavaca',
                'address' => 'Río Conchos 410, Vista Hermosa, 62290 Cuernavaca, Mor.',
                'phone' => '7773157020',
                'has_whatsapp' => true,
                'email' => 'info@dentaljunco.com',
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Vista Hermosa","instagram":"@junco_odontologia","website":"https:\/\/www.dentaljunco.com\/","source_channel":"website","notes":"20+ años; estética + diseño sonrisa + ortodoncia invisible + implantes; Vista Hermosa zona alta; ICP boutique premium spillover CDMX"}',
            ],
            [
                'name' => 'Dr. Eduardo González De La Torre',
                'clinic_name' => 'Fusión Clínica Dental',
                'specialty' => 'Implantología',
                'city' => 'Cuernavaca',
                'address' => 'Jalisco 20, 62050 Cuernavaca, Mor.',
                'phone' => '5533320692',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Centro","instagram":"@eduardogonzalezdelatorre","website":"https:\/\/www.fusionclinicadental.com\/","source_channel":"website","notes":"Posgrado NYU Implantología 2017-2019; titular único; rehabilitación bucal; tickets premium especialidad"}',
            ],
            [
                'name' => 'Dr. Kevin Andrew Gómez Hernández',
                'clinic_name' => 'Smile & Face',
                'specialty' => 'Cirugía Maxilofacial',
                'city' => 'Cuernavaca',
                'address' => 'Calle Pericón 105, Lomas de la Selva, 62270 Cuernavaca, Mor.',
                'phone' => '7701444416',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Lomas de la Selva","instagram":"@andrew_gmz","website":"https:\/\/www.andrewgomezmaxilofacial.com\/","source_channel":"website","notes":"Profesor UNAM Posgrado; Maestría cirugía ortognática Madrid; CMF + implantología; bilingüe; tickets premium especialidad"}',
            ],
            [
                'name' => 'Dra. María Margarita Sonn García López',
                'clinic_name' => 'Centro de Radiología Maxilofacial y Diagnóstico Dental',
                'specialty' => 'Radiología Dental',
                'city' => 'Cuernavaca',
                'address' => 'Calle Francisco Zarco 10, Centro, 62000 Cuernavaca, Mor.',
                'phone' => '7773100248',
                'has_whatsapp' => true,
                'email' => 'radiologiamaxilofacial@hotmail.com',
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Centro","website":"https:\/\/www.centroderadiologiamaxilofacial.com.mx\/","source_channel":"website","notes":"30+ años imagenología; cédula UNAM 1613971; especialidad radiología\/diagnóstico"}',
            ],
            [
                'name' => 'Dra. Ma Isabel Sánchez',
                'clinic_name' => 'Atelier Dental Cuernavaca',
                'specialty' => 'Ortodoncia',
                'city' => 'Cuernavaca',
                'address' => 'Av. Vicente Guerrero 110 Of. 1, Plaza Casa Blanca, Lomas de la Selva, 62270 Cuernavaca, Mor.',
                'phone' => '7771051506',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Lomas de la Selva","instagram":"@atelierdentalmexico","website":"https:\/\/atelierdental.mx\/","source_channel":"website","notes":"Maestría Ortodoncia + Ortopedia Maxilofacial; ortodoncia invisible 3D propia; multi-especialidad; sucursal CDMX (Coapa)"}',
            ],
            [
                'name' => 'Clínica Dentarte',
                'clinic_name' => 'Clínica Dentarte',
                'specialty' => 'Implantología',
                'city' => 'Cuernavaca',
                'address' => 'Gustavo Gómez Azcárate 204 Local 1B, Lomas de la Selva, 62270 Cuernavaca, Mor.',
                'phone' => '5529179095',
                'has_whatsapp' => true,
                'email' => 'dentarte204@gmail.com',
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Lomas de la Selva","instagram":"@clinicadentarte","website":"https:\/\/www.clinicadentarte.com\/","source_channel":"website","notes":"Plaza Médica Lomas; rehabilitación funcional + estética + All-on-Four; cirugía periodontal plástica"}',
            ],
            [
                'name' => 'Dra. Martha Carolina Rodríguez García',
                'clinic_name' => 'Ortodoncia Multidisciplinaria',
                'specialty' => 'Ortodoncia',
                'city' => 'Cuernavaca',
                'address' => 'Privada Juárez 8, Centro, 62000 Cuernavaca, Mor.',
                'phone' => '7773186093',
                'has_whatsapp' => true,
                'email' => 'contacto@ortodonciamultidisciplinaria.com.mx',
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Centro","website":"https:\/\/ortodonciamultidisciplinaria.com.mx\/","source_channel":"website","notes":"25 años experiencia; ortodoncia + anomalías craneofaciales + labio-paladar hendido + ATM; titular única"}',
            ],
            [
                'name' => 'Ortec Dental Smile Boutique',
                'clinic_name' => 'Ortec Dental Smile Boutique',
                'specialty' => 'Odontología General',
                'city' => 'Cuernavaca',
                'address' => 'Plaza Jade, Blvd. Lic. Benito Juárez 63, 62050 Cuernavaca, Mor.',
                'phone' => '7778003058',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Centro","instagram":"@ortecsmiles","source_channel":"maps","notes":"Smile Boutique branding; ICP boutique premium; sitio web N\/A pero IG activo"}',
            ],
            [
                'name' => 'Dra. Dulce',
                'clinic_name' => 'SonrisaD10',
                'specialty' => 'Odontología General',
                'city' => 'Cuernavaca',
                'address' => 'Av. Diana 783 Local 12, Delicias, 62330 Cuernavaca, Mor.',
                'phone' => '7772099036',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Delicias","website":"https:\/\/www.sonrisad10.com.mx\/","source_channel":"maps","notes":"Multi-doctora Dra. Dulce + Dra. Flor; ortodoncia + limpiezas; zona Delicias"}',
            ],
            [
                'name' => '2M&E Dental',
                'clinic_name' => '2M&E Dental',
                'specialty' => 'Odontología General',
                'city' => 'Cuernavaca',
                'address' => 'Av. de los 100m 50 TII-503, Villas Deportivas, 62374 Cuernavaca, Mor.',
                'phone' => '7772253956',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Villas Deportivas","source_channel":"maps","notes":"Consultorio independiente Villas Deportivas; tratamiento sensibilidad dental"}',
            ],
            [
                'name' => 'ODONTIX Dental',
                'clinic_name' => 'ODONTIX Dental',
                'specialty' => 'Implantología',
                'city' => 'Cuernavaca',
                'address' => 'Gustavo Gómez Azcárate 204 Int 103, Lomas de la Selva, 62270 Cuernavaca, Mor.',
                'phone' => '7772209584',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Lomas de la Selva","source_channel":"maps","notes":"Plaza Médica Lomas; implantes + ortodoncia brackets\/alineadores + prótesis; FB Odontix Cuernavaca"}',
            ],
            [
                'name' => 'Dental Art Cuernavaca',
                'clinic_name' => 'Dental Art Cuernavaca',
                'specialty' => 'Odontología General',
                'city' => 'Cuernavaca',
                'address' => 'Corporativo Cuernavaca, Blvd. del Lago 100 Torre 3 Piso 9, 62440 Cuernavaca, Mor.',
                'phone' => '7771902990',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Tres de Mayo","instagram":"@dentalartcuerna","source_channel":"maps","notes":"5,674 seguidores IG; Corporativo Cuernavaca Torre 3; integral; ICP medio-premium"}',
            ],
            [
                'name' => 'Dra. Alejandra Osorio Chévez',
                'clinic_name' => 'Ortodoncia y Spa Dental',
                'specialty' => 'Ortodoncia',
                'city' => 'Cuernavaca',
                'address' => 'Av. de los 50 metros 100 Torre 2-502, Villas Deportivas, Cuernavaca, Mor.',
                'phone' => '7771715462',
                'has_whatsapp' => true,
                'email' => 'ortodonciacuerna@gmail.com',
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Villas Deportivas","instagram":"@ortodoncia.cuerna","website":"http:\/\/ortodonciacuerna.com\/","source_channel":"website","notes":"Titular Dra. Osorio Chévez; ortodoncia + odontopediatría + prótesis + endodoncia + periodoncia + maxilofacial; 96% recomendado 51 opiniones"}',
            ],
            [
                'name' => 'Dra. Anita Armada',
                'clinic_name' => 'Dra. Anita Armada Dentista Cuernavaca',
                'specialty' => 'Ortodoncia',
                'city' => 'Cuernavaca',
                'address' => 'Torre Médica, Av. Cuauhtémoc 155 int 105, Chapultepec, 62450 Cuernavaca, Mor.',
                'phone' => '7773220201',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Chapultepec","instagram":"@dentista_cuernavaca","source_channel":"maps","notes":"Titular única Dra. Anita Armada; ortodoncia; consultas Cuernavaca + Temixco; IG + TikTok activos"}',
            ],
            [
                'name' => 'Dra. Maricela Herrera Pineda',
                'clinic_name' => 'Centro de Estética y Cirugía Maxilofacial Cuernavaca',
                'specialty' => 'Cirugía Maxilofacial',
                'city' => 'Cuernavaca',
                'address' => 'Gustavo Gómez Azcárate 200 Primer Piso Consultorio 6, Lomas de la Selva, 62270 Cuernavaca, Mor.',
                'phone' => '7773176703',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Lomas de la Selva","source_channel":"maps","notes":"Plaza Médica Lomas; CMF especialidad; tickets premium"}',
            ],
            [
                'name' => 'Consultorio Dental Pro Civac',
                'clinic_name' => 'Consultorio Dental Pro Civac',
                'specialty' => 'Odontología General',
                'city' => 'Jiutepec',
                'address' => 'Av 48 Nte 101, Civac Narciso Mendoza, 62578 Jiutepec, Mor.',
                'phone' => '7772126527',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Civac","rating":"5","source_channel":"maps","notes":"Civac parque industrial Nissan; familia trabajadora; rating 5.0; consultorio independiente"}',
            ],
            [
                'name' => 'Eova Dental Care',
                'clinic_name' => 'Eova Dental Care',
                'specialty' => 'Odontología General',
                'city' => 'Jiutepec',
                'address' => 'Calle Xochicalco Mz G #8, Las Torres de Civac, 62570 Jiutepec, Mor.',
                'phone' => '7776534815',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Las Torres de Civac","rating":"5","source_channel":"maps","notes":"Civac; precios accesibles; rating 5.0; consultorio chico independiente"}',
            ],
            [
                'name' => 'Clínica Dental Polanco',
                'clinic_name' => 'Clínica Dental Polanco',
                'specialty' => 'Odontología General',
                'city' => 'Jiutepec',
                'address' => 'Av 40 Nte 11, 62550 Jiutepec, Mor.',
                'phone' => '7773695274',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Centro","rating":"5","source_channel":"maps","notes":"Centro Jiutepec; rating 5.0; consultorio independiente"}',
            ],
            [
                'name' => 'Clínica Dental Villas',
                'clinic_name' => 'Clínica Dental Villas',
                'specialty' => 'Ortodoncia',
                'city' => 'Jiutepec',
                'address' => 'C. Chopo 8, 62550 Jiutepec, Mor.',
                'phone' => '7775443000',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Centro","rating":"5","source_channel":"maps","notes":"Multi-especialidad ortodoncia + implantología + estética dental; rating 5.0"}',
            ],
            [
                'name' => 'Dra. Karla Flores',
                'clinic_name' => 'Clinica Integral Metzli',
                'specialty' => 'Odontología General',
                'city' => 'Jiutepec',
                'address' => 'Xochitl 31, 62570 Jiutepec, Mor.',
                'phone' => '7775237623',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Tejalpa","rating":"5","source_channel":"maps","notes":"Titular única Dra. Karla Flores; rating 5.0; Tejalpa zona Civac"}',
            ],
            [
                'name' => 'Hapyli Dental',
                'clinic_name' => 'Hapyli Dental',
                'specialty' => 'Odontología General',
                'city' => 'Jiutepec',
                'address' => '62570 Tejalpa, Jiutepec, Mor.',
                'phone' => '7776535616',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Tejalpa","source_channel":"maps","notes":"Tejalpa cerca Civac; cirugías + limpiezas + ortodoncia; consultorio independiente; FB activo"}',
            ],
            [
                'name' => 'Clínica Dental Dimas Dent',
                'clinic_name' => 'Clínica Dental Dimas Dent',
                'specialty' => 'Odontología General',
                'city' => 'Jiutepec',
                'address' => 'C. Gral Emiliano Zapata 62, 62550 Jiutepec, Mor.',
                'phone' => '7775593432',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Centro","source_channel":"maps","notes":"Centro Jiutepec; consultorio independiente"}',
            ],
            [
                'name' => 'Acadent Dentista',
                'clinic_name' => 'Acadent Dentista',
                'specialty' => 'Odontología General',
                'city' => 'Jiutepec',
                'address' => 'C. 5 de Mayo 19, 62550 Jiutepec, Mor.',
                'phone' => '7771577922',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Centro","source_channel":"maps","notes":"Centro Jiutepec; equipo multi-doctor; consultorio independiente"}',
            ],
            [
                'name' => 'DENTISSIMO',
                'clinic_name' => 'DENTISSIMO',
                'specialty' => 'Odontología General',
                'city' => 'Jiutepec',
                'address' => 'Lic. Benito Juárez García y Francisco Zarco, 62550 Jiutepec, Mor.',
                'phone' => '7773197982',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Centro","source_channel":"maps","notes":"15+ años; ortodoncia + endodoncia + implantología + rehabilitación; FB activo Dentissimo Jiutepec"}',
            ],
            [
                'name' => 'Dr. Miguel García',
                'clinic_name' => 'Clinica Dental Endored',
                'specialty' => 'Endodoncia',
                'city' => 'Jiutepec',
                'address' => 'Gral. Mariano Matamoros 15, 62550 Jiutepec, Mor.',
                'phone' => '7775169354',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Centro","source_channel":"maps","notes":"Titular Dr. Miguel García endodoncista reconocido Morelos; especialidad alta"}',
            ],
            [
                'name' => 'Consultorio Laoos Dental',
                'clinic_name' => 'Consultorio Laoos Dental',
                'specialty' => 'Odontología General',
                'city' => 'Jiutepec',
                'address' => 'C. 5 de Mayo 32 Local 32-A, 62550 Jiutepec, Mor.',
                'phone' => '7773090639',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Centro","source_channel":"maps","notes":"Centro Jiutepec; consultorio independiente chico"}',
            ],
            [
                'name' => 'Dra. Evelia López R.',
                'clinic_name' => 'Odontología Especializada Dr. Evelia López',
                'specialty' => 'Odontología General',
                'city' => 'Jiutepec',
                'address' => 'Gral. Diego Díaz González Mtz. 14, 62564 Jiutepec, Mor.',
                'phone' => '7773211498',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Centro","source_channel":"maps","notes":"Titular única Dra. Evelia López; consultorio independiente"}',
            ],
            [
                'name' => 'Dra. F. Moreno Franco',
                'clinic_name' => 'Consultorio Dental Dra. F. Moreno Franco',
                'specialty' => 'Odontología General',
                'city' => 'Jiutepec',
                'address' => 'C. Miguel Hidalgo 31, 62550 Jiutepec, Mor.',
                'phone' => '7772290801',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Centro","rating":"4","source_channel":"maps","notes":"Titular única; Centro Jiutepec; rating 4.0; consultorio chico independiente"}',
            ],
            [
                'name' => 'Dr. Daniel Ocampo Díaz',
                'clinic_name' => 'Consultorio del Dr. Daniel Ocampo Díaz',
                'specialty' => 'Odontología General',
                'city' => 'Jiutepec',
                'address' => 'Cam. Real de Yautepec 27, Jiutepec, Mor.',
                'phone' => '5519139618',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Centro","rating":"5","source_channel":"maps","notes":"Titular único; rating 5.0; consultorio independiente"}',
            ],
            [
                'name' => 'OnSide Dental',
                'clinic_name' => 'OnSide Dental',
                'specialty' => 'Implantología',
                'city' => 'Temixco',
                'address' => 'Av. Emiliano Zapata 152 Plaza Escorial, Centro, 62580 Temixco, Mor.',
                'phone' => '7772028250',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Centro","rating":"5","reviews_count":"50","source_channel":"maps","notes":"Multi-especialidad implantes + endodoncia + maxilofacial + ortodoncia + prostodoncia; rating 5.0\/50 reviews; LGBTQ+ friendly; FB Clinica Onside Dental"}',
            ],
            [
                'name' => 'Dr. Lemus',
                'clinic_name' => 'Perfect Smile Dental Temixco',
                'specialty' => 'Odontología General',
                'city' => 'Temixco',
                'address' => 'Plutarco Elías Calles 56, 62580 Temixco, Mor.',
                'phone' => '7771416987',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Centro","website":"https:\/\/perfec-smile-dental.ueniweb.com\/","source_channel":"website","notes":"Titular Dr. Lemus; Centro Temixco; última tecnología; consultorio independiente"}',
            ],
            [
                'name' => 'Clínica Dental Ocampo',
                'clinic_name' => 'Clínica Dental Ocampo',
                'specialty' => 'Odontología General',
                'city' => 'Temixco',
                'address' => 'Álvaro Obregón 164, Centro, 62580 Temixco, Mor.',
                'phone' => '7771036088',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Centro","source_channel":"maps","notes":"Centro Temixco; consultorio independiente"}',
            ],
            [
                'name' => 'Acatlipa Dental',
                'clinic_name' => 'Acatlipa Dental',
                'specialty' => 'Odontología General',
                'city' => 'Temixco',
                'address' => 'Lázaro Cárdenas 8, Acatlipa, Temixco, Mor.',
                'phone' => '7773858647',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Acatlipa","rating":"4.6","source_channel":"maps","notes":"Acatlipa zona industrial Temixco; rating 4.6; consultorio independiente"}',
            ],
            [
                'name' => 'A Dental Temixco',
                'clinic_name' => 'A Dental Temixco',
                'specialty' => 'Odontología General',
                'city' => 'Temixco',
                'address' => 'Francisco I. Madero 54, Centro, 62580 Temixco, Mor.',
                'phone' => '7772593294',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Centro","source_channel":"maps","notes":"Centro Temixco; consultorio chico independiente"}',
            ],
            [
                'name' => 'Consultorio Dental Entis',
                'clinic_name' => 'Consultorio Dental Entis',
                'specialty' => 'Odontología General',
                'city' => 'Temixco',
                'address' => 'Hermenegildo Galeana 22, 62587 Temixco, Mor.',
                'phone' => '7773250317',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Acatlipa","source_channel":"maps","notes":"Acatlipa Temixco; consultorio independiente"}',
            ],
            [
                'name' => 'CIAdent Temixco',
                'clinic_name' => 'CIAdent Temixco',
                'specialty' => 'Odontología General',
                'city' => 'Temixco',
                'address' => 'Benito Juárez 58, Centro, 62580 Temixco, Mor.',
                'phone' => '7773373654',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Centro","source_channel":"maps","notes":"Centro Temixco; consultorio independiente"}',
            ],
            [
                'name' => 'Dr. Mejía',
                'clinic_name' => 'Consultorio Dental Dr. Mejía Temixco',
                'specialty' => 'Odontología General',
                'city' => 'Temixco',
                'address' => 'Independencia 26, Lázaro Cárdenas del Río, 62580 Temixco, Mor.',
                'phone' => '7771640208',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Lázaro Cárdenas","source_channel":"maps","notes":"Titular Dr. Mejía; 621 visitas; consultorio independiente"}',
            ],
            [
                'name' => 'Dr. José Luis Malacara',
                'clinic_name' => 'Dentista José Luis Malacara',
                'specialty' => 'Odontología General',
                'city' => 'Temixco',
                'address' => 'Calle Reforma 6, Centro, 62580 Temixco, Mor.',
                'phone' => '7773250110',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Centro","source_channel":"maps","notes":"Titular único; Centro Temixco; consultorio independiente"}',
            ],
            [
                'name' => 'Dr. Ramón García',
                'clinic_name' => 'Consultorio Dental Dr. Ramón García',
                'specialty' => 'Odontología General',
                'city' => 'Temixco',
                'address' => 'Calzada de Guadalupe 62, Lomas del Carril, 62583 Temixco, Mor.',
                'phone' => '7773659467',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Lomas del Carril","source_channel":"maps","notes":"Titular único Dr. García; Lomas del Carril Temixco; consultorio independiente"}',
            ],
            [
                'name' => 'Dental Carlet Yautepec',
                'clinic_name' => 'Dental Carlet Yautepec',
                'specialty' => 'Odontología General',
                'city' => 'Yautepec',
                'address' => 'C. Esther Casariego 15, Rancho Nuevo, 62731 Yautepec de Zaragoza, Mor.',
                'phone' => '7351136495',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Rancho Nuevo","source_channel":"maps","notes":"Lada 735 Yautepec; consultorio independiente"}',
            ],
            [
                'name' => 'Dr. Rafael Herrera Vital',
                'clinic_name' => 'Consultorio Dental Dr. Rafael Herrera Vital',
                'specialty' => 'Odontología General',
                'city' => 'Yautepec',
                'address' => 'C. Emiliano Zapata 35, Centro, Yautepec de Zaragoza, Mor.',
                'phone' => '7353940468',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Centro","source_channel":"maps","notes":"Titular único Dr. Herrera Vital; lada 735 Yautepec"}',
            ],
            [
                'name' => 'CONSULTORIO DENTALSTONE Yautepec',
                'clinic_name' => 'CONSULTORIO DENTALSTONE Yautepec',
                'specialty' => 'Odontología General',
                'city' => 'Yautepec',
                'address' => 'Calle Otilio Montaño 46, Los Arcos, Yautepec de Zaragoza, Mor.',
                'phone' => '7351075653',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Los Arcos","source_channel":"maps","notes":"Los Arcos Yautepec; consultorio independiente"}',
            ],
            [
                'name' => 'Dra. Gabriela Carballido Nava',
                'clinic_name' => 'Dra. Gabriela Carballido Nava',
                'specialty' => 'Odontología General',
                'city' => 'Yautepec',
                'address' => 'Bo. de Santiago Calle Curtidores 13, Yautepec de Zaragoza, Mor.',
                'phone' => '7353043604',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Barrio de Santiago","source_channel":"maps","notes":"Titular única Dra. Carballido; lada 735 Yautepec; consultorio independiente"}',
            ],
            [
                'name' => 'Clínica Dental San Pedro Yautepec',
                'clinic_name' => 'Clínica Dental San Pedro Yautepec',
                'specialty' => 'Odontología General',
                'city' => 'Yautepec',
                'address' => 'C. Zaragoza 15, Centro, Yautepec de Zaragoza, Mor.',
                'phone' => '7353941744',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Centro","source_channel":"maps","notes":"Centro Yautepec; consultorio independiente"}',
            ],
            [
                'name' => 'Dr. Israel Bricaire Mancera',
                'clinic_name' => 'Dr. Israel Bricaire Mancera',
                'specialty' => 'Odontología General',
                'city' => 'Yautepec',
                'address' => 'C. de Morelos 11, Centro, Yautepec de Zaragoza, Mor.',
                'phone' => '7353949630',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Centro","source_channel":"maps","notes":"Titular único Dr. Bricaire; lada 735 Yautepec; consultorio independiente"}',
            ],
            [
                'name' => 'CROM Centro Radiológico Oral y Maxilofacial',
                'clinic_name' => 'CROM Centro Radiológico Oral y Maxilofacial',
                'specialty' => 'Radiología Dental',
                'city' => 'Cuernavaca',
                'address' => 'Av. Teopanzolco 408 Local 2 Torre B, Reforma, Cuernavaca, Mor.',
                'phone' => '7772438595',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Reforma","instagram":"@cromcuerna","website":"https:\/\/www.cromcuernavaca.com\/","source_channel":"website","notes":"2 sedes Cuernavaca (Teopanzolco + Las Palmas); radiología oral + maxilofacial; especialidad alta complementaria a clínicas dentales"}',
            ],
            [
                'name' => 'Centro Odontológico Médico Morelos',
                'clinic_name' => 'Centro Odontológico Médico Morelos',
                'specialty' => 'Odontología General',
                'city' => 'Cuernavaca',
                'address' => 'Av. Domingo Diez 921, Lomas de la Selva, 62250 Cuernavaca, Mor.',
                'phone' => '7773135363',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cuernavaca-dedup-20260427","colonia":"Lomas de la Selva","source_channel":"maps","notes":"Domingo Diez zona corredor médico; atención personalizada con cita; consultorio independiente"}',
            ],
        ];

        $this->command->info('Insertando ' . count($prospects) . ' dentistas del pilot (research-dentistas-cuernavaca-dedup-20260427)...');

        $inserted = 0;
        $skipped = 0;

        foreach ($prospects as $prospect) {
            // Idempotencia por phone (último match) — no volver a insertar si ya existe
            $existing = Prospect::where('phone', $prospect['phone'])->first();
            if ($existing) {
                $skipped++;
                continue;
            }

            Prospect::create(array_merge($prospect, [
                'source' => 'prospecting', // matches SendProspectEmails cron filter
                'status' => 'new',
                'assigned_to_sales_rep_id' => 100,
                'contact_day' => 0,
                'next_contact_at' => now()->addHour(),
                'outreach_started_at' => now(),
            ]));
            $inserted++;
        }

        $this->command->info("✓ {$inserted} insertados | {$skipped} duplicados saltados | Total en seeder: " . count($prospects));
    }
}
