<?php

namespace Database\Seeders;

use App\Models\Prospect;
use Illuminate\Database\Seeder;

/**
 * Pilot CDMX dentist batch — generated from dentistas-cdmx-dedup.csv.
 *
 * 42 registros descubiertos vía WebSearch + WebFetch (Google Maps + sitios propios),
 * deduplicados contra los 403 prospectos existentes en prod.
 *
 * Todos tienen teléfono válido (10 dígitos MX). Se asignan a Omar (user_id=100)
 * con source='prospecting' para que el cron send-prospect-emails los tome automático.
 * El batch identifier vive en notes.batch = 'research-cdmx-pilot-20260421' para analytics.
 *
 * Ejecutar con: php artisan db:seed --class=ProspectDentistasCDMXPilotSeeder --force
 */
class ProspectDentistasCDMXPilotSeeder extends Seeder
{
    public function run(): void
    {
        $prospects = [
            [
                'name' => 'Odontología Polanco',
                'clinic_name' => 'Odontología Polanco',
                'specialty' => 'Odontología General',
                'city' => 'Ciudad de México',
                'address' => 'Presidente Masaryk 490 piso 4, Polanco II, Miguel Hidalgo, 11530',
                'phone' => '5529651703',
                'has_whatsapp' => true,
                'email' => 'contacto@odontologiapolanco.com',
                'notes' => '{"batch":"research-cdmx-pilot-20260421","colonia":"Polanco II","instagram":"@odontologiapolanco","website":"https:\/\/odontologiapolanco.com","source_channel":"google-maps","notes":"Consultorio en Masaryk, zona premium; IG activo"}',
            ],
            [
                'name' => 'Dr. Juan Alfredo Morales Viramontes',
                'clinic_name' => 'Consultorio Dental Dr. Alfredo Morales',
                'specialty' => 'Odontología Estética',
                'city' => 'Ciudad de México',
                'address' => 'Av. Ejército Nacional 475, 3er piso, Polanco, Miguel Hidalgo',
                'phone' => '5552553822',
                'has_whatsapp' => true,
                'email' => 'dentistalfredo@yahoo.com',
                'notes' => '{"batch":"research-cdmx-pilot-20260421","colonia":"Polanco","website":"https:\/\/dentistaenpolanco.com","source_channel":"google-search","notes":"Pionero Invisalign MX +30 años experiencia"}',
            ],
            [
                'name' => 'Clínica Dental Condesa',
                'clinic_name' => 'Clínica Dental Condesa',
                'specialty' => 'Odontología Estética',
                'city' => 'Ciudad de México',
                'address' => 'Av. Baja California 245, Condesa, Cuauhtémoc, 06100',
                'phone' => '5555745347',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-cdmx-pilot-20260421","colonia":"Condesa","website":"https:\/\/esteticadentalcdmx.com","source_channel":"google-search","notes":"WhatsApp visible en sitio"}',
            ],
            [
                'name' => 'Arte Dental Condesa',
                'clinic_name' => 'Arte Dental Condesa',
                'specialty' => 'Odontología Estética',
                'city' => 'Ciudad de México',
                'address' => 'Aguascalientes 181, Hipódromo, Cuauhtémoc, 06100',
                'phone' => '5538631323',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-cdmx-pilot-20260421","colonia":"Hipódromo","instagram":"@arte.dental.condesa","website":"http:\/\/artedentalcondesa.com","source_channel":"google-search","notes":"IG @arte.dental.condesa; foco diseño de sonrisa"}',
            ],
            [
                'name' => 'Dr. Alberto Salcedo Sotomayor',
                'clinic_name' => 'Consultorio de Especialidades Dentales Condesa',
                'specialty' => 'Implantología',
                'city' => 'Ciudad de México',
                'address' => 'Fernando Montes de Oca 113, Condesa, Cuauhtémoc, 06140',
                'phone' => '5533316960',
                'has_whatsapp' => false,
                'email' => 'contacto@especialidadesdentales.mx',
                'notes' => '{"batch":"research-cdmx-pilot-20260421","colonia":"Condesa","website":"https:\/\/especialidadesdentales.mx","source_channel":"google-search","notes":"3 especialistas (prótesis, periodoncia, endodoncia) — equipo pequeño"}',
            ],
            [
                'name' => 'Juan Ricardo Hernández Rodríguez',
                'clinic_name' => 'OdontoHealth Condesa',
                'specialty' => 'Implantología',
                'city' => 'Ciudad de México',
                'address' => 'Av. Michoacán 9 Piso 5, Hipódromo Condesa, Cuauhtémoc, 06100',
                'phone' => '5640004321',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-cdmx-pilot-20260421","colonia":"Hipódromo Condesa","website":"https:\/\/odontohealth.com.mx","source_channel":"google-search","notes":"Cédula 7391180; turismo dental"}',
            ],
            [
                'name' => 'ArrFox Clínica Dental',
                'clinic_name' => 'ArrFox Clínica Dental',
                'specialty' => 'Odontología General',
                'city' => 'Ciudad de México',
                'address' => 'Atlixco 18-1, Condesa, Cuauhtémoc, 06140',
                'phone' => '5552564039',
                'has_whatsapp' => false,
                'email' => 'contacto@arrfox.com.mx',
                'notes' => '{"batch":"research-cdmx-pilot-20260421","colonia":"Condesa","website":"https:\/\/www.arrfox.com.mx","source_channel":"google-search","notes":"+20 años operando; L-V 10-20h"}',
            ],
            [
                'name' => 'Dra. Marcela H.',
                'clinic_name' => 'La Clínica Dental Roma',
                'specialty' => 'Odontología General',
                'city' => 'Ciudad de México',
                'address' => 'Cozumel 22, Roma Norte, Cuauhtémoc, 06700',
                'phone' => '5585265090',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-cdmx-pilot-20260421","colonia":"Roma Norte","instagram":"@laclinicadental_mexico","website":"https:\/\/laclinicaroma.com.mx","source_channel":"google-search","notes":"Director Dra. Marcela H.; 6 especialistas"}',
            ],
            [
                'name' => 'Dentalisima',
                'clinic_name' => 'Dentalisima',
                'specialty' => 'Ortodoncia',
                'city' => 'Ciudad de México',
                'address' => 'Córdoba 95, Roma Norte, 06700',
                'phone' => '5522140597',
                'has_whatsapp' => false,
                'email' => 'rodrigo_101@dentalisima.com',
                'notes' => '{"batch":"research-cdmx-pilot-20260421","colonia":"Roma Norte","instagram":"@dentalisima","website":"https:\/\/www.dentalisima.com","source_channel":"google-search","notes":"Ortodoncia y odontopediatría; horario extendido"}',
            ],
            [
                'name' => 'Dra. María Elizabeth González de Paz',
                'clinic_name' => 'Dra. Elizabeth González Endodoncia Integral',
                'specialty' => 'Endodoncia',
                'city' => 'Ciudad de México',
                'address' => 'Zacatecas 40 514, Roma Norte, Cuauhtémoc, 06700',
                'phone' => '5555748395',
                'has_whatsapp' => false,
                'email' => 'maria.egonzalez.depaz@gmail.com',
                'notes' => '{"batch":"research-cdmx-pilot-20260421","colonia":"Roma Norte","website":"https:\/\/www.draelizabethgonzalezendodonciaintegral.com","source_channel":"google-search","notes":"Cédula 0834652; L-V 9-20h"}',
            ],
            [
                'name' => 'Dra. Alejandra Guillén Cedillo',
                'clinic_name' => 'Odontología Integral GC',
                'specialty' => 'Ortodoncia',
                'city' => 'Ciudad de México',
                'address' => 'Casas Grandes 74, Narvarte Oriente, Benito Juárez, 03023',
                'phone' => '5512391476',
                'has_whatsapp' => true,
                'email' => 'contacto@odontologiaintegralgc.com',
                'notes' => '{"batch":"research-cdmx-pilot-20260421","colonia":"Narvarte Oriente","instagram":"@dra.aleguillen__","website":"https:\/\/odontologiaintegralgc.com","source_channel":"google-search","notes":"3 especialistas; equipo pequeño"}',
            ],
            [
                'name' => 'Wendy Contreras Cárdenas',
                'clinic_name' => 'We Dental Health',
                'specialty' => 'Periodoncia',
                'city' => 'Ciudad de México',
                'address' => 'Heriberto Frías 847, Narvarte Poniente, Benito Juárez, 03020',
                'phone' => '5579383662',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-cdmx-pilot-20260421","colonia":"Narvarte Poniente","website":"https:\/\/www.wedental.mx","source_channel":"google-search","notes":"Periodoncista titular, único consultorio"}',
            ],
            [
                'name' => 'Dr. José Soto',
                'clinic_name' => 'Clínica Dental Josso',
                'specialty' => 'Implantología',
                'city' => 'Ciudad de México',
                'address' => 'Benjamín Franklin 20 Int 4 Piso 1, Escandón, Miguel Hidalgo',
                'phone' => '5552763205',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-cdmx-pilot-20260421","colonia":"Escandón","instagram":"@soyjosso_tudentista","website":"https:\/\/clinicadentaljosso.mx","rating":"4.7","reviews_count":"120","source_channel":"google-search","notes":"120 reseñas 4.7 estrellas; estacionamiento"}',
            ],
            [
                'name' => 'Dr. Héctor Manuel García Alatorre',
                'clinic_name' => 'OrtoDental México',
                'specialty' => 'Ortodoncia',
                'city' => 'Ciudad de México',
                'address' => 'Matías Romero 301, Del Valle Centro, Benito Juárez, 03100',
                'phone' => '5571555394',
                'has_whatsapp' => true,
                'email' => 'ortodentalmexico@outlook.com',
                'notes' => '{"batch":"research-cdmx-pilot-20260421","colonia":"Del Valle Centro","instagram":"@ortodental_mexico","website":"https:\/\/ortodental.com.mx","source_channel":"google-search","notes":"Invisalign Emerald Category; AAO y WFO member"}',
            ],
            [
                'name' => 'Dr. Marcelo Balboa Melgarejo',
                'clinic_name' => 'Espacio Arte Dental',
                'specialty' => 'Odontología Estética',
                'city' => 'Ciudad de México',
                'address' => 'Cerrada Félix Cuevas 204 Int 3, Del Valle, Benito Juárez, 03100',
                'phone' => '5579462166',
                'has_whatsapp' => true,
                'email' => 'info@espacioartedental.com',
                'notes' => '{"batch":"research-cdmx-pilot-20260421","colonia":"Del Valle","instagram":"@espacioartedental","website":"https:\/\/www.espacioartedental.com","source_channel":"google-search","notes":"Dr. Balboa IG personal @marcelo_balboa_melgarejo"}',
            ],
            [
                'name' => 'Especialidades Dentales Del Valle',
                'clinic_name' => 'Especialidades Dentales Del Valle',
                'specialty' => 'Odontología General',
                'city' => 'Ciudad de México',
                'address' => 'José María Rico 634, Del Valle, Benito Juárez',
                'phone' => '5555244769',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-cdmx-pilot-20260421","colonia":"Del Valle","website":"https:\/\/especialidadesdentalesdelvalle.com","source_channel":"google-search","notes":"Horario L-V 10-14 y 16-20; sitio con error SSL pero operativo"}',
            ],
            [
                'name' => 'Dr. Pedro Jorge Téllez Rodríguez',
                'clinic_name' => 'Odontali Sucursal Tepeyac',
                'specialty' => 'Implantología',
                'city' => 'Ciudad de México',
                'address' => 'Av. La Fortuna 106, Tepeyac Insurgentes, Gustavo A. Madero, 07020',
                'phone' => '5515794521',
                'has_whatsapp' => true,
                'email' => 'info@odontali.com',
                'notes' => '{"batch":"research-cdmx-pilot-20260421","colonia":"Tepeyac Insurgentes","instagram":"@clinica_odontali","website":"https:\/\/www.odontali.com","source_channel":"google-search","notes":"Fundador cirujano maxilofacial; 2 sucursales total"}',
            ],
            [
                'name' => 'Dr. Allan Rotberg',
                'clinic_name' => 'Odontólogos Unidos Bosques',
                'specialty' => 'Odontopediatría',
                'city' => 'Ciudad de México',
                'address' => 'Bosque de Duraznos 69 desp 301, Bosques de las Lomas, Miguel Hidalgo, 11700',
                'phone' => '5555962129',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-cdmx-pilot-20260421","colonia":"Bosques de las Lomas","instagram":"@allanrotberg.dr","website":"https:\/\/dientitos.com","source_channel":"google-search","notes":"Valet parking; Dr. Rotberg titular"}',
            ],
            [
                'name' => 'Dentinela Clinic',
                'clinic_name' => 'Dentinela Clinic',
                'specialty' => 'Odontología General',
                'city' => 'Ciudad de México',
                'address' => 'Av. Miguel Ángel de Quevedo 1144, Parque San Andrés, Coyoacán, 04040',
                'phone' => '5579429428',
                'has_whatsapp' => true,
                'email' => 'dentinelaclinic@gmail.com',
                'notes' => '{"batch":"research-cdmx-pilot-20260421","colonia":"Parque San Andrés","instagram":"@dentinela","website":"https:\/\/dentinela.mx","source_channel":"google-search","notes":"Dentro de Medhaus consultorio J105"}',
            ],
            [
                'name' => 'Dra. Analy Resendiz',
                'clinic_name' => 'Pediatric Dental Care',
                'specialty' => 'Odontopediatría',
                'city' => 'Ciudad de México',
                'address' => 'Dakota 45 Int 3, Parque San Andrés, Coyoacán, 04040',
                'phone' => '5556893010',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-cdmx-pilot-20260421","colonia":"Parque San Andrés","website":"https:\/\/pediatricdentalcare.com.mx","source_channel":"google-search","notes":"Fundadora odontopediatra; 5 doctores en total"}',
            ],
            [
                'name' => 'Katia Fernanda Contreras Domínguez',
                'clinic_name' => 'Sanamedic Dent',
                'specialty' => 'Odontología Estética',
                'city' => 'Ciudad de México',
                'address' => 'Anillo de Circunvalación 3, Atlántida, Coyoacán, 04370',
                'phone' => '5512314006',
                'has_whatsapp' => true,
                'email' => 'clinicasanamedic@gmail.com',
                'notes' => '{"batch":"research-cdmx-pilot-20260421","colonia":"Atlántida","website":"https:\/\/sanamedicdent.com","source_channel":"google-search","notes":"Cédula UNAM 12970086; carillas inyectables"}',
            ],
            [
                'name' => 'Clínica Integral Odontológica',
                'clinic_name' => 'Clínica Integral Odontológica',
                'specialty' => 'Odontología General',
                'city' => 'Ciudad de México',
                'address' => 'Av. Escuinapa 394, Pedregal de Santo Domingo, Coyoacán, 04369',
                'phone' => '5556197757',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-cdmx-pilot-20260421","colonia":"Pedregal de Santo Domingo","instagram":"@cio.mexico","website":"https:\/\/www.ciomexico.mx","source_channel":"google-search","notes":"Horario L-J 9-21 V 9-19:30 S 8-14"}',
            ],
            [
                'name' => 'Dr. Víctor M. Navarro Sousa',
                'clinic_name' => 'Nav\'s Dental',
                'specialty' => 'Implantología',
                'city' => 'Ciudad de México',
                'address' => 'Lima 880-A Altos 1, Lindavista, Gustavo A. Madero, 07300',
                'phone' => '5555860968',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-cdmx-pilot-20260421","colonia":"Lindavista","instagram":"@navsdental","website":"https:\/\/navsdental.com","source_channel":"google-search","notes":"Dr. titular; perfil IG activo"}',
            ],
            [
                'name' => 'Crotte Dental',
                'clinic_name' => 'Crotte Dental',
                'specialty' => 'Odontología General',
                'city' => 'Ciudad de México',
                'address' => 'Ticomán 258, Lindavista Norte, Gustavo A. Madero, 07300',
                'phone' => '5559142134',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-cdmx-pilot-20260421","colonia":"Lindavista Norte","website":"https:\/\/www.crottedental.com.mx","source_channel":"google-search","notes":"3 líneas telefónicas; sitio no respondió a fetch pero listado en Google"}',
            ],
            [
                'name' => 'Consultorio Dental Lindavista',
                'clinic_name' => 'Consultorio Dental Lindavista',
                'specialty' => 'Odontología General',
                'city' => 'Ciudad de México',
                'address' => 'Calle Lindavista 827 Int 5, Lindavista, Gustavo A. Madero, 07300',
                'phone' => '5555866862',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-cdmx-pilot-20260421","colonia":"Lindavista","source_channel":"google-search","notes":"Consultorio pequeño independiente"}',
            ],
            [
                'name' => 'Dra. Gloria González Estrada',
                'clinic_name' => 'DentiGlow',
                'specialty' => 'Odontopediatría',
                'city' => 'Ciudad de México',
                'address' => 'Avenida de las Granjas 155, Azcapotzalco',
                'phone' => '5540436900',
                'has_whatsapp' => true,
                'email' => 'contacto@dentiglow.com.mx',
                'notes' => '{"batch":"research-cdmx-pilot-20260421","colonia":"Azcapotzalco","website":"https:\/\/dentiglow.com.mx","source_channel":"google-search","notes":"Odontopediatra especialista única"}',
            ],
            [
                'name' => 'Consultorio Dental Diente de León',
                'clinic_name' => 'Consultorio Dental Diente de León',
                'specialty' => 'Odontología General',
                'city' => 'Ciudad de México',
                'address' => 'Trebol, Xalpa, Iztapalapa, 09640',
                'phone' => '5611793821',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-cdmx-pilot-20260421","colonia":"Xalpa","source_channel":"google-maps","notes":"Consultorio barrio; teléfono directo"}',
            ],
            [
                'name' => 'Sonrisas MVDental',
                'clinic_name' => 'Sonrisas MVDental',
                'specialty' => 'Odontopediatría',
                'city' => 'Ciudad de México',
                'address' => 'Av. de las Minas 3, Xalpa, Iztapalapa, 09640',
                'phone' => '5554290197',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-cdmx-pilot-20260421","colonia":"Xalpa","source_channel":"google-maps","notes":"Odontopediatría; verificar antes de llamar"}',
            ],
            [
                'name' => 'Dra. María Fernanda Zarco',
                'clinic_name' => 'Consultorio Dental Pasta y Cepillo',
                'specialty' => 'Odontología General',
                'city' => 'Ciudad de México',
                'address' => 'Gral. Radamés Gaxiola Andrade 243, Escuadrón 201, Iztapalapa, 09060',
                'phone' => '5539837097',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-cdmx-pilot-20260421","colonia":"Escuadrón 201","instagram":"@pastaycepillo","website":"https:\/\/pastaycepillo.com","source_channel":"google-search","notes":"6 doctores — cerca del límite, pero siguen siendo 1 consultorio único"}',
            ],
            [
                'name' => 'Dr. Jorge B. Gallardo Macías',
                'clinic_name' => 'Endodoncia Dr. Jorge Gallardo',
                'specialty' => 'Endodoncia',
                'city' => 'Ciudad de México',
                'address' => 'Pennsylvania 209, Nápoles, Benito Juárez, 03810',
                'phone' => '5555235453',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-cdmx-pilot-20260421","colonia":"Nápoles","website":"https:\/\/endodonciasdf.wixsite.com\/endodoncia","source_channel":"google-search","notes":"Endodoncista solo; 1 consultorio clásico"}',
            ],
            [
                'name' => 'EOLODENT Coyoacán',
                'clinic_name' => 'EOLODENT Coyoacán',
                'specialty' => 'Odontología General',
                'city' => 'Ciudad de México',
                'address' => 'Av. Miguel Ángel de Quevedo 928, Coyoacán, 04040',
                'phone' => '5648934006',
                'has_whatsapp' => true,
                'email' => 'clinicadental@eolodent.com',
                'notes' => '{"batch":"research-cdmx-pilot-20260421","colonia":"Coyoacán","instagram":"@eolodent_clinica","website":"https:\/\/eolodent.com","source_channel":"google-search","notes":"Servicio 24h; sucursal Coyoacán"}',
            ],
            [
                'name' => 'Centro Dental Coyoacán',
                'clinic_name' => 'Centro Dental Coyoacán',
                'specialty' => 'Odontología General',
                'city' => 'Ciudad de México',
                'address' => 'Av. Santa Ana 372 local 12, San Francisco Culhuacán, Coyoacán',
                'phone' => '5554073711',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-cdmx-pilot-20260421","colonia":"San Francisco Culhuacán","website":"https:\/\/www.centrodentalcoyoacan.com.mx","source_channel":"google-search","notes":"Celular directo del consultorio"}',
            ],
            [
                'name' => 'Consultorio Odontológico Canal Miramontes',
                'clinic_name' => 'Consultorio Odontológico Canal Miramontes',
                'specialty' => 'Odontología General',
                'city' => 'Ciudad de México',
                'address' => 'Eje Vial 1 Oriente 2769, Jardines de Coyoacán, Coyoacán, 04890',
                'phone' => '5556849280',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-cdmx-pilot-20260421","colonia":"Jardines de Coyoacán","source_channel":"google-maps","notes":"Sobre Canal de Miramontes"}',
            ],
            [
                'name' => 'Karina Cervantes Lara',
                'clinic_name' => 'Dental Inn San Ángel',
                'specialty' => 'Odontopediatría',
                'city' => 'Ciudad de México',
                'address' => 'Av. Revolución 1346, Guadalupe Inn, Álvaro Obregón, 01020',
                'phone' => '5534410219',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-cdmx-pilot-20260421","colonia":"Guadalupe Inn","website":"https:\/\/dentalinnsanangel.com.mx","source_channel":"google-search","notes":"Odontopediatría + Dental Inn Kids; 3 especialistas principales"}',
            ],
            [
                'name' => 'Consultorio Dental Área Satélite',
                'clinic_name' => 'Consultorio Dental Área Satélite',
                'specialty' => 'Odontología General',
                'city' => 'Ciudad de México',
                'address' => 'Circuito Médicos, Ciudad Satélite, Naucalpan, 53100',
                'phone' => '5515911391',
                'has_whatsapp' => false,
                'email' => 'c.d.ruthrodriguez@hotmail.com',
                'notes' => '{"batch":"research-cdmx-pilot-20260421","colonia":"Ciudad Satélite","maps_url":"https:\/\/www.facebook.com\/DentistaSatelite\/","source_channel":"google-search","notes":"Titular Dra. Ruth Rodríguez; email directo"}',
            ],
            [
                'name' => 'Dra. Berenice Apodaca',
                'clinic_name' => 'Salud Bucal Satélite',
                'specialty' => 'Ortodoncia',
                'city' => 'Ciudad de México',
                'address' => 'Enrique Sada Moguerza Circuito Comercial 13, Ciudad Satélite, Naucalpan, 53100',
                'phone' => '5512309020',
                'has_whatsapp' => true,
                'email' => 'drabereapodaca@saludbucal.com.mx',
                'notes' => '{"batch":"research-cdmx-pilot-20260421","colonia":"Ciudad Satélite","instagram":"@saludbucal.mx","website":"https:\/\/www.saludbucal.com.mx","source_channel":"google-search","notes":"Dra. Berenice Apodaca única titular"}',
            ],
            [
                'name' => 'Grupo Dental Satélite',
                'clinic_name' => 'Grupo Dental Satélite',
                'specialty' => 'Odontología General',
                'city' => 'Ciudad de México',
                'address' => 'Circuito Circunvalación Pte 7a Piso 2 Consultorio 8, Ciudad Satélite, Naucalpan, 53100',
                'phone' => '5553937661',
                'has_whatsapp' => false,
                'email' => 'contacto@dentistasatelite.com',
                'notes' => '{"batch":"research-cdmx-pilot-20260421","colonia":"Ciudad Satélite","website":"https:\/\/dentistasatelite.com","source_channel":"google-search","notes":"4 líneas; urgencias separadas"}',
            ],
            [
                'name' => 'Dra. Marion Ormeño Gómez',
                'clinic_name' => 'Consultorio Dra. Marion Ormeño',
                'specialty' => 'Endodoncia',
                'city' => 'Ciudad de México',
                'address' => 'Av. Jesús del Monte 39, Interlomas, Huixquilucan',
                'phone' => '5536879046',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-cdmx-pilot-20260421","colonia":"Interlomas","website":"https:\/\/marionormeno.com","source_channel":"google-search","notes":"Microendodoncia; también sitio endodoncia-mexico.com"}',
            ],
            [
                'name' => 'Dra. Marion Ormeño Gómez',
                'clinic_name' => 'Remitiendo Microendodoncia',
                'specialty' => 'Endodoncia',
                'city' => 'Ciudad de México',
                'address' => 'Plaza Victoria Av. Jesús del Monte 39 Piso 2 Consultorio 229, Interlomas, Huixquilucan, 52764',
                'phone' => '5536868168',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-cdmx-pilot-20260421","colonia":"Interlomas","instagram":"@remitiendo","website":"https:\/\/endodoncia-mexico.com","source_channel":"google-search","notes":"Consultorio secundario de Dra. Ormeño — mismo titular, distinto consultorio"}',
            ],
            [
                'name' => 'Clínica Dental Centauro Verónica Anzures',
                'clinic_name' => 'Clínica Dental Centauro Verónica Anzures',
                'specialty' => 'Odontología General',
                'city' => 'Ciudad de México',
                'address' => 'Local F-04 193, Verónica Anzures, Miguel Hidalgo',
                'phone' => '5588975555',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-cdmx-pilot-20260421","colonia":"Verónica Anzures","website":"https:\/\/www.clinicadentalcentauro.com.mx","source_channel":"google-search","notes":"L-S 10-20 D 10-18"}',
            ],
            [
                'name' => 'Claudia Welsh',
                'clinic_name' => 'Chiquident',
                'specialty' => 'Odontopediatría',
                'city' => 'Ciudad de México',
                'address' => 'Dirección no confirmada Polanco',
                'phone' => '5521553989',
                'has_whatsapp' => true,
                'email' => 'contacto@chiquident.com.mx',
                'notes' => '{"batch":"research-cdmx-pilot-20260421","colonia":"Polanco","instagram":"@chiquident_mx","website":"https:\/\/chiquident.com.mx","source_channel":"google-search","notes":"Sin dirección exacta en sitio; IG activo"}',
            ],
            [
                'name' => 'Sakar Dental',
                'clinic_name' => 'Sakar Dental',
                'specialty' => 'Implantología',
                'city' => 'Ciudad de México',
                'address' => 'Presa Sanalona 8, Irrigación, Miguel Hidalgo, 11500',
                'phone' => '5555571138',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-cdmx-pilot-20260421","colonia":"Irrigación","website":"https:\/\/www.sakardental.mx","source_channel":"google-search","notes":"Equipo multidisciplinario — verificar tamaño antes de vender"}',
            ],
        ];

        $this->command->info('Insertando ' . count($prospects) . ' dentistas CDMX (pilot)...');

        $inserted = 0;
        $skipped = 0;

        foreach ($prospects as $prospect) {
            // Idempotencia por phone (último match) — no volver a insertar si ya existe
            $existing = Prospect::where('phone', $prospect['phone'])->first();
            if ($existing) {
                $skipped++;
                continue;
            }

            Prospect::create(array_merge($prospect, [
                'source' => 'prospecting', // matches SendProspectEmails cron filter
                'status' => 'new',
                'assigned_to_sales_rep_id' => 100,
                'contact_day' => 0,
                'next_contact_at' => now()->addHour(),
                'outreach_started_at' => now(),
            ]));
            $inserted++;
        }

        $this->command->info("✓ {$inserted} insertados | {$skipped} duplicados saltados | Total en seeder: " . count($prospects));
    }
}
