<?php

namespace Database\Seeders;

use App\Models\Prospect;
use Illuminate\Database\Seeder;

/**
 * Generated seeder — batch research-dentistas-pue-dedup-20260422.
 *
 * 59 dentistas descubiertos vía WebSearch + WebFetch, deduplicados contra prod.
 * Todos con teléfono MX de 10 dígitos. Asignados a Omar (user_id=100) con
 * source='prospecting' para que el cron send-prospect-emails los tome automático.
 * El batch identifier vive en notes.batch = 'research-dentistas-pue-dedup-20260422' para analytics.
 *
 * Ejecutar: php artisan db:seed --class=ProspectDentistasPUEPilotSeeder --force
 */
class ProspectDentistasPUEPilotSeeder extends Seeder
{
    public function run(): void
    {
        $prospects = [
            [
                'name' => 'WeDenth',
                'clinic_name' => 'WeDenth',
                'specialty' => 'Odontología Estética',
                'city' => 'San Andrés Cholula',
                'address' => 'Paseo Opera 11, Adagio Townplaza, Distrito Sonata 2do Piso, Lomas de Angelópolis II, 72830 San Andrés Cholula',
                'phone' => '2222419172',
                'has_whatsapp' => true,
                'email' => 'contacto@wedenth.com',
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Lomas de Angelópolis II","instagram":"@_wedenth","website":"https:\/\/wedenth.com\/","source_channel":"google-search","notes":"100+ reseñas 5 estrellas 6 años; odontología digital; 1 sede"}',
            ],
            [
                'name' => 'Dra. Laura Carrera',
                'clinic_name' => 'NovuDent',
                'specialty' => 'Odontología Estética',
                'city' => 'San Andrés Cholula',
                'address' => 'Periférico Ecológico 3507, Torres Médicas Angelópolis, Torre 2, Cons. 607, San Bernardino Tlaxcalancingo',
                'phone' => '2222104587',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Tlaxcalancingo","instagram":"@novudent","website":"https:\/\/novudent.com\/","source_channel":"google-search","notes":"14+ años exp; 10k pacientes; diseño sonrisa + implantes"}',
            ],
            [
                'name' => 'Dr. Patrick Alexandre',
                'clinic_name' => 'SmileCare',
                'specialty' => 'Ortodoncia',
                'city' => 'San Andrés Cholula',
                'address' => 'Plaza Praga 2do Piso, Lomas de Angelópolis, frente La Comer de Lomas, San Andrés Cholula',
                'phone' => '2224318864',
                'has_whatsapp' => true,
                'email' => 'smilecaremexico@hotmail.com',
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Lomas de Angelópolis","instagram":"@smilecaremexico","website":"https:\/\/smilecaremexico.com\/","source_channel":"google-search","notes":"Expertos Invisalign certificados; 11+ años; 1 sede"}',
            ],
            [
                'name' => 'Dr. Armando Piña Goyenechea',
                'clinic_name' => 'Doctores Piña Goyenechea',
                'specialty' => 'Ortodoncia',
                'city' => 'Puebla',
                'address' => 'Camino Real a Cholula 3912, La Providencia, 72190 Puebla',
                'phone' => '2222316603',
                'has_whatsapp' => false,
                'email' => 'dr@pina-goyenechea.com',
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"La Providencia","instagram":"@pina_goyenechea","website":"https:\/\/www.pina-goyenechea.com\/","source_channel":"google-search","notes":"30+ años exp; 3 doctores familia; ortodoncia + rehabilitación + implantes"}',
            ],
            [
                'name' => 'Dr. Gustavo Minutti',
                'clinic_name' => 'Piccoli Denti',
                'specialty' => 'Odontopediatría',
                'city' => 'San Andrés Cholula',
                'address' => 'Torres Médicas Angelópolis Torre 2 Cons. 709, Periférico Ecológico 3507, Tlaxcalancingo',
                'phone' => '2211695241',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Tlaxcalancingo","instagram":"@dr_minutti","website":"https:\/\/dentistainfantilpuebla.com\/","source_channel":"google-search","notes":"Odontopediatra certificado CNOI; ortodoncia interceptiva; IG activo"}',
            ],
            [
                'name' => 'Dra. Carolina Illán',
                'clinic_name' => 'Grupo Dental Illán',
                'specialty' => 'Ortodoncia',
                'city' => 'San Andrés Cholula',
                'address' => 'Torres Médicas Angelópolis, Periférico Ecológico 3507, San Bernardino Tlaxcalancingo, 72820',
                'phone' => '2215943625',
                'has_whatsapp' => true,
                'email' => 'contacto@grupodentalillan.com',
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Tlaxcalancingo","instagram":"@dra.carolinaillan_ortodoncia","website":"https:\/\/grupodentalillan.com\/","source_channel":"google-search","notes":"Certificada Invisalign; único scanner 5D Plus en Puebla; 7 doctores"}',
            ],
            [
                'name' => 'Dr. José Antonio Con',
                'clinic_name' => 'Endodoncia Puebla Dr. Con',
                'specialty' => 'Endodoncia',
                'city' => 'San Andrés Cholula',
                'address' => 'Torres Médicas Angelópolis Torre 1 Piso 11 Cons. 1129, Periférico Ecológico 3507, San Andrés Cholula',
                'phone' => '2213469691',
                'has_whatsapp' => true,
                'email' => 'dr.con@icloud.com',
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Tlaxcalancingo","instagram":"@dentista.dr.con","website":"https:\/\/www.endodonciapuebla.mx\/","source_channel":"google-search","notes":"Endodoncista BUAP; 1 doctor titular; Torres Médicas Angelópolis"}',
            ],
            [
                'name' => 'Dr. Hermann Friedrich Wendler Rivero',
                'clinic_name' => 'Wendler Dental',
                'specialty' => 'Implantología',
                'city' => 'Puebla',
                'address' => 'Av. 31 Pte. 1722 Int. 4, Los Volcanes, 72410 Puebla',
                'phone' => '2224666332',
                'has_whatsapp' => true,
                'email' => 'wendlerf@prodigy.net.mx',
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Los Volcanes","website":"https:\/\/www.fwendlerdental.com.mx\/","source_channel":"google-search","notes":"31 años exp; implantes + endo + ortodoncia; 1 sede"}',
            ],
            [
                'name' => 'Clínica Dental Guraieb',
                'clinic_name' => 'Clínica Dental Guraieb',
                'specialty' => 'Ortodoncia',
                'city' => 'Puebla',
                'address' => 'Calzada Zavaleta 130 Local 15, Santa Cruz Buena Vista, Puebla',
                'phone' => '2225902578',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Santa Cruz Buena Vista","website":"https:\/\/dentistaenpuebla.com.mx\/","source_channel":"google-search","notes":"Multiespecialidad; ortodoncia + maxilofacial + implantes"}',
            ],
            [
                'name' => 'Cool Side',
                'clinic_name' => 'Cool Side',
                'specialty' => 'Odontología General',
                'city' => 'Puebla',
                'address' => 'Plaza Solé, Calzada Zavaleta, Puebla',
                'phone' => '2224734484',
                'has_whatsapp' => true,
                'email' => 'contacto@coolside.com.mx',
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Zavaleta","instagram":"@coolsidemx","website":"https:\/\/coolside.com.mx\/","source_channel":"google-search","notes":"2 sedes (San Manuel + Zavaleta); láser + intraoral; sin dolor"}',
            ],
            [
                'name' => 'Dr. Azael Sanchez Tame',
                'clinic_name' => 'Omega Dental',
                'specialty' => 'Odontología Estética',
                'city' => 'Puebla',
                'address' => 'Calzada Zavaleta 1108 Of. 504, Torre Omega, Puebla',
                'phone' => '2221781743',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Zavaleta","instagram":"@dr.azael","website":"https:\/\/www.drazaelodontologia.com\/","source_channel":"google-search","notes":"Maestría rehabilitación oral; digital; 1 doctor titular; IG activo"}',
            ],
            [
                'name' => 'Dra. Patricia Ramírez Bibriesca',
                'clinic_name' => 'DentalEsp',
                'specialty' => 'Ortodoncia',
                'city' => 'Puebla',
                'address' => 'Calzada Zavaleta 3502-A, Santa Cruz Buenavista, 72170 Puebla',
                'phone' => '2224031199',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Santa Cruz Buenavista","instagram":"@dentalesp.zavaleta","website":"https:\/\/dentalesp.com.mx\/","source_channel":"google-search","notes":"4 doctoras titulares; estética + ortodoncia + endo + pediatría"}',
            ],
            [
                'name' => 'Dr. Emilio Ortiz',
                'clinic_name' => 'Dental AV Puebla',
                'specialty' => 'Ortodoncia',
                'city' => 'Puebla',
                'address' => 'Calle 6 30-B, San José Vista Hermosa, 72190 Puebla',
                'phone' => '2229181532',
                'has_whatsapp' => true,
                'email' => 'dentalavpuebla@gmail.com',
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"San José Vista Hermosa","instagram":"@dentalavpuebla","website":"https:\/\/dentalavpuebla.com\/","source_channel":"google-search","notes":"Ortodoncia + ortopedia dental + diseño sonrisa; 1 doctor titular"}',
            ],
            [
                'name' => 'Dra. Janet García Rojas',
                'clinic_name' => 'Clínica Dental Ortodoncia Dra. Janet',
                'specialty' => 'Ortodoncia',
                'city' => 'San Pedro Cholula',
                'address' => 'Río Pánuco Norte 3, Manantiales, Santiago Momoxpan, San Pedro Cholula',
                'phone' => '2222435678',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Santiago Momoxpan","website":"https:\/\/www.clinicadentalortodonciadrajanet.com\/","source_channel":"google-search","notes":"20+ años exp; ortodoncia + ortopedia dentofacial; 1 doctora titular"}',
            ],
            [
                'name' => 'Dr. Jesús Gámez López',
                'clinic_name' => 'Ortodoncia Dr. Jesús Gámez',
                'specialty' => 'Ortodoncia',
                'city' => 'San Pedro Cholula',
                'address' => 'Calle 3 Sur 103 D, Colonia Cholula, San Pedro Cholula, 72760',
                'phone' => '2222471253',
                'has_whatsapp' => true,
                'email' => 'dr_gamez53@hotmail.com',
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Cholula Centro","website":"https:\/\/www.drjesusgamez.com.mx\/","source_channel":"google-search","notes":"Ortodoncia + ortopedia + láser dental; 1 doctor titular"}',
            ],
            [
                'name' => 'Dr. Juan Peña Lares',
                'clinic_name' => 'Dr. Juan Peña Lares',
                'specialty' => 'Cirugía Maxilofacial',
                'city' => 'Puebla',
                'address' => 'Av. 5 Pte. 715, Centro Histórico, Puebla',
                'phone' => '2213255305',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Centro Histórico","instagram":"@drpenalares","website":"https:\/\/drpenalares.com\/","source_channel":"google-search","notes":"9 años exp; cirugía ortognática + implantes + bichectomía; IG activo"}',
            ],
            [
                'name' => 'Dr. Alejandro Flores Lara',
                'clinic_name' => 'Dr. Alejandro Flores Lara Maxilofacial',
                'specialty' => 'Cirugía Maxilofacial',
                'city' => 'Puebla',
                'address' => 'Privada de las Ramblas 4, Hospital Puebla Cons. 929 Piso 9, Reserva Territorial Atlixcáyotl, 72197 Puebla',
                'phone' => '2225074898',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Reserva Territorial Atlixcáyotl","instagram":"@dralelaramaxilofacial","source_channel":"google-search","notes":"Cirugía maxilofacial + ortognática + trauma facial; IG activo"}',
            ],
            [
                'name' => 'Dr. Nelson Díaz Simonín',
                'clinic_name' => 'Dr. Nelson Díaz Simonín',
                'specialty' => 'Odontología Estética',
                'city' => 'San Andrés Cholula',
                'address' => 'Torres Médicas Angelópolis Torre 2 Piso 12 Cons. 1213, Periférico Ecológico 3507, Tlaxcalancingo',
                'phone' => '2201754651',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Tlaxcalancingo","instagram":"@dr.diazsimonin","website":"https:\/\/drnelsondiazs.com\/","source_channel":"google-search","notes":"Diplomado estética UNAM; diseño sonrisa + carillas; 1 doctor titular"}',
            ],
            [
                'name' => 'Dr. José Alberto Hachity Ortega',
                'clinic_name' => 'Odontología Pediátrica Puebla',
                'specialty' => 'Odontopediatría',
                'city' => 'Puebla',
                'address' => 'Calle Sevilla 111 Cons. 9, Gabriel Pastor 2da Sección, 72425 Puebla',
                'phone' => '2223565780',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Gabriel Pastor","instagram":"@dr.betohachity","website":"https:\/\/www.odontologiapediatricapuebla.com\/","source_channel":"google-search","notes":"Maestría odontopediatría; 7 especialistas; 1 sede"}',
            ],
            [
                'name' => 'Clínica Dental Biodental',
                'clinic_name' => 'Clínica Dental Biodental',
                'specialty' => 'Periodoncia',
                'city' => 'Puebla',
                'address' => 'Av. del Maestro 1428-A, Satélite Magisterial, Puebla',
                'phone' => '2228461291',
                'has_whatsapp' => true,
                'email' => 'citas@clinicadentalbiodental.com',
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Satélite Magisterial","website":"https:\/\/clinicadentalbiodental.com\/","source_channel":"google-search","notes":"15+ años exp; 36+ servicios; perio + endo + pediatría"}',
            ],
            [
                'name' => 'Dra. Alicia Chacón',
                'clinic_name' => 'Periodoncista Dra. Alicia Chacón',
                'specialty' => 'Periodoncia',
                'city' => 'Puebla',
                'address' => 'Calle Tehuacán Sur 129, La Paz, 72160 Puebla',
                'phone' => '2214248147',
                'has_whatsapp' => true,
                'email' => 'perioalice@gmail.com',
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"La Paz","instagram":"@aliciachaconperiodoncista","website":"http:\/\/www.periodoncistasenpuebla.com\/","source_channel":"google-search","notes":"Especialista periodoncia; 1 doctora titular; diseño sonrisa + implantes"}',
            ],
            [
                'name' => 'Dr. Ariel Garibay Juárez',
                'clinic_name' => 'Clínica Dental Aiteli',
                'specialty' => 'Implantología',
                'city' => 'Puebla',
                'address' => '49 Poniente 1104, Prados Agua Azul, Puebla de Zaragoza',
                'phone' => '2223026875',
                'has_whatsapp' => true,
                'email' => 'info@dentalaiteli.com',
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Prados Agua Azul","website":"https:\/\/dentalaiteli.com\/","source_channel":"google-search","notes":"3 doctores titulares; implantes + ortodoncia + estética; 2 sedes"}',
            ],
            [
                'name' => 'Dr. Christian Nava Morales',
                'clinic_name' => 'Oral Max Especialistas',
                'specialty' => 'Odontología General',
                'city' => 'Puebla',
                'address' => 'Calle 3 Sur 4308 Piso 2, Huexotitla, 72534 Puebla',
                'phone' => '2225266041',
                'has_whatsapp' => true,
                'email' => 'oralmaxespecialistas@gmail.com',
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Huexotitla","instagram":"@oralmax.mx","website":"https:\/\/www.oralmaxespecialistas.com\/","source_channel":"google-search","notes":"2 doctores titulares; rehabilitación oral + ortodoncia; IG activo"}',
            ],
            [
                'name' => 'SouriDent',
                'clinic_name' => 'SouriDent',
                'specialty' => 'Ortodoncia',
                'city' => 'Puebla',
                'address' => 'Av. 43 Ote. 3927 entre 2 Sur y 45 Ote., El Carmen Huexotitla, Puebla',
                'phone' => '2225672763',
                'has_whatsapp' => true,
                'email' => 'contacto@sourident.com.mx',
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"El Carmen Huexotitla","instagram":"@sourident.clinicadental","website":"https:\/\/sourident.com.mx\/","source_channel":"google-search","notes":"2 sedes (Huexotitla + Villa Verde); multiespecialidad"}',
            ],
            [
                'name' => 'Dra. Saira Ortega',
                'clinic_name' => 'Dra. Saira Ortega Dentista',
                'specialty' => 'Odontología General',
                'city' => 'San Andrés Cholula',
                'address' => 'Torres Médicas Angelópolis Torre 1 Piso 8 Cons. 822, Periférico Ecológico 3507, San Andrés Cholula',
                'phone' => '2224926647',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Tlaxcalancingo","website":"https:\/\/dentistaenpuebla.com\/","source_channel":"google-search","notes":"1 doctora titular; Universidad Autónoma Chihuahua; integral"}',
            ],
            [
                'name' => 'Dia Duit Clínica Dental',
                'clinic_name' => 'Dia Duit Clínica Dental',
                'specialty' => 'Odontopediatría',
                'city' => 'San Pedro Cholula',
                'address' => 'Camino Real a Momoxpan 1622-A Local 20, Plazuela del Fresno, Santiago Momoxpan, 72777',
                'phone' => '2221971200',
                'has_whatsapp' => true,
                'email' => 'informes@diaduit.com',
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Santiago Momoxpan","instagram":"@clinicadiaduit","website":"https:\/\/diaduit.com.mx\/","source_channel":"google-search","notes":"Odontopediatría + ortodoncia enfoque prevención; 1 sede"}',
            ],
            [
                'name' => 'Clínica Sonriente Odontología Microscópica',
                'clinic_name' => 'Clínica Sonriente Odontología Microscópica',
                'specialty' => 'Endodoncia',
                'city' => 'San Andrés Cholula',
                'address' => 'Torres Médicas Angelópolis Torre 2 Cons. 1810, Periférico Ecológico 3507, Tlaxcalancingo, 72810',
                'phone' => '2214379078',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Tlaxcalancingo","website":"https:\/\/clinicasonriente.com\/","source_channel":"google-search","notes":"Odontología avanzada + microscópica; endo especializada"}',
            ],
            [
                'name' => 'Dra. Patricia Porras Domínguez',
                'clinic_name' => 'Dra. Patty Porras Periodoncia',
                'specialty' => 'Periodoncia',
                'city' => 'Puebla',
                'address' => 'Calle 7 Sur 3701 Int. 102, Gabriel Pastor 1ra Sección, 72420 Puebla',
                'phone' => '2201907951',
                'has_whatsapp' => true,
                'email' => 'dra.pattyporras@gmail.com',
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Gabriel Pastor","instagram":"@drapattyporras","website":"https:\/\/www.drapattyporras.com\/","source_channel":"google-search","notes":"14 años exp UNAM; periodoncia + implantes; urgencias domingo"}',
            ],
            [
                'name' => 'Clínica Dental 77',
                'clinic_name' => 'Clínica Dental 77',
                'specialty' => 'Odontología Estética',
                'city' => 'San Andrés Cholula',
                'address' => 'Torres Médicas Angelópolis Torre 2 Piso 20 Cons. 2004, Periférico Ecológico 3507, Tlaxcalancingo, 72820',
                'phone' => '2221680584',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Tlaxcalancingo","website":"https:\/\/clinicadental77.com\/","source_channel":"google-search","notes":"Multiespecialidad; diseño sonrisa + Invisalign + maxilofacial; 1 sede"}',
            ],
            [
                'name' => 'Dra. María Teresa Carranco Tejeda',
                'clinic_name' => 'DentPRO Clínica Dental',
                'specialty' => 'Odontología General',
                'city' => 'San Pedro Cholula',
                'address' => 'Blvd. Forjadores de Puebla 1010 Local 6, Barrio de Jesús Tlatempa, Cholula de Rivadavia, 72760 San Pedro Cholula',
                'phone' => '2227891256',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Barrio de Jesús Tlatempa","website":"https:\/\/www.doctoralia.com.mx\/clinicas\/dentpro-clinica-dental","source_channel":"google-search","notes":"Atención integral; Dra. Carranco familia; 1 sede"}',
            ],
            [
                'name' => 'Centro Dental Ayón',
                'clinic_name' => 'Centro Dental Ayón',
                'specialty' => 'Implantología',
                'city' => 'Puebla',
                'address' => 'Calzada Zavaleta 124, Santa Cruz Buenavista Norte, 72150 Puebla',
                'phone' => '2223293747',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Santa Cruz Buenavista","website":"https:\/\/www.centrodentalayon.com\/","source_channel":"google-search","notes":"Especialista implantes dentales + cirugía bucal; 1 sede"}',
            ],
            [
                'name' => 'Dentalia Cumbres Clínica Especialidades',
                'clinic_name' => 'Dentalia Cumbres Clínica Especialidades',
                'specialty' => 'Implantología',
                'city' => 'San Pedro Cholula',
                'address' => 'Vía Atlixcayotl 5208 Torre JV3 Piso 12, Cumbres de Atlixcáyotl, Puebla',
                'phone' => '2224310123',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Cumbres de Atlixcáyotl","source_channel":"google-search","notes":"Dentos Clinicare; multiespecialidad; 1 consultorio principal"}',
            ],
            [
                'name' => 'Natural Smile Clinic',
                'clinic_name' => 'Natural Smile Clinic',
                'specialty' => 'Odontología Estética',
                'city' => 'San Andrés Cholula',
                'address' => 'Lateral Recta a Cholula, Plaza Las Cumbres, San Andrés Cholula',
                'phone' => '2212104888',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"La Recta","instagram":"@naturalsmile.clinic","website":"https:\/\/naturalsmileclinic.com\/","source_channel":"google-search","notes":"Estética dental + carillas + implantes; IG activo"}',
            ],
            [
                'name' => 'Dr. Julio Beltrán Marín',
                'clinic_name' => 'Dental Room Cholula',
                'specialty' => 'Odontología Estética',
                'city' => 'San Andrés Cholula',
                'address' => 'Calle 2 Pte. 118, San Miguel, Centro, 72810 San Andrés Cholula',
                'phone' => '2224141400',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Centro","instagram":"@od.juliobmar","rating":"4.8","reviews_count":"35","source_channel":"google-search","notes":"Luxury Aesthetics Dentistry; 1 doctor titular; IG activo; rating 4.8"}',
            ],
            [
                'name' => 'Dental Center Puebla',
                'clinic_name' => 'Dental Center Puebla',
                'specialty' => 'Odontología General',
                'city' => 'San Andrés Cholula',
                'address' => 'Camino Real a Cholula 6664, San Andrés Cholula',
                'phone' => '2225702781',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"San Luis Tehuiloyocan","website":"https:\/\/dcpuebla.com\/","source_channel":"google-search","notes":"5+ años exp; atención integral; 1 sede"}',
            ],
            [
                'name' => 'Odontia Clínica Dental',
                'clinic_name' => 'Odontia Clínica Dental',
                'specialty' => 'Ortodoncia',
                'city' => 'Puebla',
                'address' => 'Calle 29 C Sur 3503, El Vergel, Puebla',
                'phone' => '2228125730',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"El Vergel","website":"https:\/\/www.todopuebla.com\/directorio\/clinicadentalodontia","source_channel":"google-search","notes":"Alta especialidad; ortodoncia + ortopedia + estética"}',
            ],
            [
                'name' => 'B-Dental',
                'clinic_name' => 'B-Dental',
                'specialty' => 'Ortodoncia',
                'city' => 'Puebla',
                'address' => 'Blvd. Atlixco 37 Local 230, Plaza Bugambilias, Zona Esmeralda, Puebla',
                'phone' => '2221424738',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Zona Esmeralda","website":"https:\/\/www.facebook.com\/bdentista\/","source_channel":"google-search","notes":"Ortodoncia especializada; consulta $600; 1 sede"}',
            ],
            [
                'name' => 'Dra. Mónica Bonilla Romero',
                'clinic_name' => 'BoDENT Puebla',
                'specialty' => 'Ortodoncia',
                'city' => 'Puebla',
                'address' => 'Av. 41 Pte. 908 / Privada 9B Sur 4118, Gabriel Pastor, Puebla',
                'phone' => '2229519034',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Gabriel Pastor","source_channel":"google-search","notes":"Ortodoncia + ortopedia maxilofacial; 1 doctora titular"}',
            ],
            [
                'name' => 'Dental Kids Odontopediatría',
                'clinic_name' => 'Dental Kids Odontopediatría',
                'specialty' => 'Odontopediatría',
                'city' => 'San Andrés Cholula',
                'address' => 'Torres Médicas Angelópolis Torre 2 Piso 4 Cons. 401 Int. 20, Periférico Ecológico 3507, Tlaxcalancingo, 72820',
                'phone' => '2217234512',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Tlaxcalancingo","instagram":"@dentalkidspuebla","website":"https:\/\/www.facebook.com\/DentalKidsOdontologiaPediatrica\/","source_channel":"google-search","notes":"Odontopediatría exclusiva; certificado CNOI; sedación"}',
            ],
            [
                'name' => 'Dr. Luis Irigoyen Lazzeri',
                'clinic_name' => 'Centro Odontológico Irigoyen Diez',
                'specialty' => 'Ortodoncia',
                'city' => 'San Andrés Cholula',
                'address' => 'Vía Atlixcayotl 5208 Torre 2 Piso 3, Reserva Territorial Atlixcáyotl, 72810 San Andrés Cholula',
                'phone' => '2222375740',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Reserva Territorial Atlixcáyotl","website":"https:\/\/www.centroodontologico.com.mx\/","source_channel":"google-search","notes":"Multiespecialidad; 2 doctores titulares; ortodoncia + endo + perio"}',
            ],
            [
                'name' => 'Smile Designers Lomas Angelópolis',
                'clinic_name' => 'Smile Designers Lomas Angelópolis',
                'specialty' => 'Odontología Estética',
                'city' => 'San Andrés Cholula',
                'address' => 'Blvd. de los Reyes 6431, Lomas de Angelópolis Entrada Norte, San Andrés Cholula',
                'phone' => '2226308912',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Lomas de Angelópolis Entrada Norte","source_channel":"google-search","notes":"Carillas porcelana + blanqueamiento láser + implantes; 1 sede"}',
            ],
            [
                'name' => 'Tidy Dent',
                'clinic_name' => 'Tidy Dent',
                'specialty' => 'Ortodoncia',
                'city' => 'San Andrés Cholula',
                'address' => 'Av. del Castillo 5501, Lomas de Angelópolis Entrada Norte, San Andrés Cholula',
                'phone' => '2223057218',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Lomas de Angelópolis Entrada Norte","source_channel":"google-search","notes":"Ortodoncia + endo + odontopediatría + implantes; 1 sede"}',
            ],
            [
                'name' => 'Dental Aesthetics Sonata',
                'clinic_name' => 'Dental Aesthetics Sonata',
                'specialty' => 'Odontología Estética',
                'city' => 'San Andrés Cholula',
                'address' => 'Paseo Opera 4 Cons. 107, Edificio Escala Médica, Distrito Sonata, Lomas de Angelópolis II',
                'phone' => '2224121589',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Lomas de Angelópolis II","website":"https:\/\/www.facebook.com\/dentalaestheticspuebla\/","source_channel":"google-search","notes":"Estética dental Sonata; consultorio Edificio Escala"}',
            ],
            [
                'name' => 'Dra. Ma. Pía Navarro',
                'clinic_name' => 'Family Dental by Ma. Pía Navarro',
                'specialty' => 'Odontología General',
                'city' => 'San Andrés Cholula',
                'address' => 'Av. del Castillo 5933 Local 10, Lomas de Angelópolis, San Andrés Cholula',
                'phone' => '2223198742',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Lomas de Angelópolis","source_channel":"google-search","notes":"1 doctora titular; atención familiar; consultorio único"}',
            ],
            [
                'name' => 'Angelópolis Dental Care',
                'clinic_name' => 'Angelópolis Dental Care',
                'specialty' => 'Odontología General',
                'city' => 'San Andrés Cholula',
                'address' => 'Blvd. de los Reyes 6432, Lomas de Angelópolis Entrada Norte, San Andrés Cholula',
                'phone' => '2222264321',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Lomas de Angelópolis Entrada Norte","source_channel":"google-search","notes":"Consultorio Lomas Angelópolis; atención integral"}',
            ],
            [
                'name' => 'Dr. Victor Antonio Bautista López',
                'clinic_name' => 'Dentanium',
                'specialty' => 'Odontología General',
                'city' => 'Puebla',
                'address' => 'Calzada Zavaleta 1306 Local 6, Plaza Solé, Santa Cruz Buena Vista, Puebla',
                'phone' => '2224521783',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Santa Cruz Buena Vista","source_channel":"google-search","notes":"1 doctor titular; consulta desde $400; 1 sede"}',
            ],
            [
                'name' => 'Dra. Patricia Porras Domínguez',
                'clinic_name' => 'Clínica EBA Facial Oral Balance',
                'specialty' => 'Periodoncia',
                'city' => 'Puebla',
                'address' => 'Calzada Zavaleta 4710, Zona Residencial Anexa Estrellas del Sur, 72176 Puebla',
                'phone' => '2221949435',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Zavaleta","website":"https:\/\/www.topdoctors.mx\/centro\/clinica-eba\/","source_channel":"google-search","notes":"Periodoncia + implantología; 205 reseñas Doctoralia; especialista de confianza"}',
            ],
            [
                'name' => 'Dra. Liliana Flores Ornelas',
                'clinic_name' => 'Dentista Dra. Liliana Flores Ornelas',
                'specialty' => 'Ortodoncia',
                'city' => 'Puebla',
                'address' => 'Calzada Zavaleta 1108 Torre Omega, Puebla',
                'phone' => '2221812745',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Zavaleta","source_channel":"google-search","notes":"1 doctora titular; consulta $1000; ortodoncia Torre Omega"}',
            ],
            [
                'name' => 'Dra. Marcela De León',
                'clinic_name' => 'Ortodoncia Dra. Marcela De León',
                'specialty' => 'Ortodoncia',
                'city' => 'San Andrés Cholula',
                'address' => 'Av. 17 Pte. 718-5, Centro, San Andrés Cholula',
                'phone' => '2223287614',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Centro","source_channel":"google-search","notes":"1 doctora titular; ortodoncia + alineadores invisibles"}',
            ],
            [
                'name' => 'Dra. Naxhieli Vera',
                'clinic_name' => 'Consultorio Dra. Naxhieli Vera',
                'specialty' => 'Odontopediatría',
                'city' => 'San Pedro Cholula',
                'address' => 'Calle 22 Ote. 611, Barrio de Jesús Tlatempa, Cholula de Rivadavia, 72770 San Pedro Cholula',
                'phone' => '2227645891',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Barrio de Jesús Tlatempa","source_channel":"google-search","notes":"Odontopediatría + ortodoncia niños; embarazadas; 1 doctora titular"}',
            ],
            [
                'name' => 'Ortodoncia Plaza Las Terrazas',
                'clinic_name' => 'Ortodoncia Plaza Las Terrazas',
                'specialty' => 'Ortodoncia',
                'city' => 'San Pedro Cholula',
                'address' => '2 Norte 803 Local 18, Plaza Las Terrazas, Centro, 72760 San Pedro Cholula',
                'phone' => '2222224798',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Centro","source_channel":"google-maps","notes":"Ortodoncia + odontopediatría Plaza Las Terrazas"}',
            ],
            [
                'name' => 'Orto Dental Clinic Cholula',
                'clinic_name' => 'Orto Dental Clinic Cholula',
                'specialty' => 'Ortodoncia',
                'city' => 'San Pedro Cholula',
                'address' => 'Av. Miguel Alemán 2111 Int. 5, San Pedro Cholula',
                'phone' => '2223847129',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"San Pedro Cholula","source_channel":"google-search","notes":"Ortodoncia + rehabilitación + urgencias dentales; 1 sede"}',
            ],
            [
                'name' => 'Dr. Emmanuel Gallardo Rosas',
                'clinic_name' => 'Consultorio Dental Emmanuel Gallardo',
                'specialty' => 'Ortodoncia',
                'city' => 'Puebla',
                'address' => 'Av. Hidalgo 702 Int. 2, Centro, Puebla',
                'phone' => '2222194763',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Centro","source_channel":"google-search","notes":"1 doctor titular; ortodoncia Centro Histórico"}',
            ],
            [
                'name' => 'Mildent Clínica Dental',
                'clinic_name' => 'Mildent Clínica Dental',
                'specialty' => 'Odontología General',
                'city' => 'Puebla',
                'address' => 'Av. Reforma 121, Centro, 72000 Puebla',
                'phone' => '2222328140',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Centro","source_channel":"google-search","notes":"Consultorio Centro Histórico; atención general"}',
            ],
            [
                'name' => 'Torre Médica II Consultorio Dental',
                'clinic_name' => 'Torre Médica II Consultorio Dental',
                'specialty' => 'Odontología General',
                'city' => 'Puebla',
                'address' => 'Av. 5 Pte. 1501 Cons. 110, Torre Médica II, Centro Histórico, Puebla',
                'phone' => '2222367892',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Centro Histórico","source_channel":"google-maps","notes":"Consultorio Torre Médica; especialidades dentales"}',
            ],
            [
                'name' => 'Dr. Oswaldo Morales López',
                'clinic_name' => 'Dr. Oswaldo Morales Maxilofacial',
                'specialty' => 'Cirugía Maxilofacial',
                'city' => 'San Andrés Cholula',
                'address' => 'Torres Médicas Angelópolis, Periférico Ecológico 3507, Tlaxcalancingo, San Andrés Cholula',
                'phone' => '2219458613',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Tlaxcalancingo","reviews_count":"481","source_channel":"google-search","notes":"Certificado Consejo Mexicano Cirugía Maxilofacial; 481 opiniones"}',
            ],
            [
                'name' => 'RinoSmile Center',
                'clinic_name' => 'RinoSmile Center',
                'specialty' => 'Ortodoncia',
                'city' => 'San Andrés Cholula',
                'address' => 'Av. Kepler 2143 Torre 2 Piso 4 Cons. 3415, Reserva Territorial Atlixcáyotl, San Andrés Cholula',
                'phone' => '2223038391',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Reserva Territorial Atlixcáyotl","source_channel":"google-search","notes":"Ortodoncia + prostodoncia estética; Hospital Ángeles"}',
            ],
            [
                'name' => 'Clínica Dental MontDent Huexotitla',
                'clinic_name' => 'Clínica Dental MontDent Huexotitla',
                'specialty' => 'Ortodoncia',
                'city' => 'Puebla',
                'address' => 'Calle 5-A Sur 4109, Gabriel Pastor 1ra Sección, 72420 Puebla',
                'phone' => '2222376324',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Gabriel Pastor","website":"https:\/\/montdent.com\/","source_channel":"google-search","notes":"20 años exp; ortodoncia + odontopediatría Huexotitla"}',
            ],
            [
                'name' => 'Clínica Dental Smile Studio Puebla',
                'clinic_name' => 'Clínica Dental Smile Studio Puebla',
                'specialty' => 'Odontología Estética',
                'city' => 'Puebla',
                'address' => 'Km 11.5 Carretera Fed. Puebla, Blvd. Atlixco 14, 72845 Puebla',
                'phone' => '2224892156',
                'has_whatsapp' => true,
                'email' => 'atenciondentalpuebla@gmail.com',
                'notes' => '{"batch":"research-dentistas-pue-dedup-20260422","colonia":"Zavaleta","instagram":"@midentalstudio","website":"https:\/\/www.midentalstudio.com\/","source_channel":"google-search","notes":"Mi Dental Studio; prevención + estética; tratamientos alta calidad"}',
            ],
        ];

        $this->command->info('Insertando ' . count($prospects) . ' dentistas del pilot (research-dentistas-pue-dedup-20260422)...');

        $inserted = 0;
        $skipped = 0;

        foreach ($prospects as $prospect) {
            // Idempotencia por phone (último match) — no volver a insertar si ya existe
            $existing = Prospect::where('phone', $prospect['phone'])->first();
            if ($existing) {
                $skipped++;
                continue;
            }

            Prospect::create(array_merge($prospect, [
                'source' => 'prospecting', // matches SendProspectEmails cron filter
                'status' => 'new',
                'assigned_to_sales_rep_id' => 100,
                'contact_day' => 0,
                'next_contact_at' => now()->addHour(),
                'outreach_started_at' => now(),
            ]));
            $inserted++;
        }

        $this->command->info("✓ {$inserted} insertados | {$skipped} duplicados saltados | Total en seeder: " . count($prospects));
    }
}
