<?php

namespace Database\Seeders;

use App\Models\Prospect;
use Illuminate\Database\Seeder;

/**
 * Generated seeder — batch research-dentistas-torreon-dedup-20260424.
 *
 * 56 dentistas descubiertos vía WebSearch + WebFetch, deduplicados contra prod.
 * Todos con teléfono MX de 10 dígitos. Asignados a Omar (user_id=100) con
 * source='prospecting' para que el cron send-prospect-emails los tome automático.
 * El batch identifier vive en notes.batch = 'research-dentistas-torreon-dedup-20260424' para analytics.
 *
 * Ejecutar: php artisan db:seed --class=ProspectDentistasTorreonPilotSeeder --force
 */
class ProspectDentistasTorreonPilotSeeder extends Seeder
{
    public function run(): void
    {
        $prospects = [
            [
                'name' => 'Dr. Saúl Rubén Ramírez Mora',
                'clinic_name' => 'Laguna Dent',
                'specialty' => 'Odontología General',
                'city' => 'Torreón',
                'address' => 'Boulevard Revolución 585 Ote, Centro, 27000 Torreón, Coah.',
                'phone' => '8717112207',
                'has_whatsapp' => true,
                'email' => 'laguna_dent@hotmail.com',
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Centro","website":"https:\/\/www.lagunadent.com\/","source_channel":"website","notes":"10+ años exp; titular único; ortodoncia + endodoncia + periodoncia + prótesis sobre implantes"}',
            ],
            [
                'name' => 'Dr. Adolfo González',
                'clinic_name' => 'Aoral Clinic',
                'specialty' => 'Cirugía Maxilofacial',
                'city' => 'Torreón',
                'address' => 'Boulevard Independencia 144 Centro, 27000 Torreón, Coah.',
                'phone' => '8717184832',
                'has_whatsapp' => true,
                'email' => 'adolfo.gon11@gmail.com',
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Centro","website":"https:\/\/www.aoralclinic.com\/","source_channel":"website","notes":"Cédula 0518006939 UAdeC; multi-especialidad: maxilofacial + endodoncia + ortodoncia"}',
            ],
            [
                'name' => 'Dentistas Especializados',
                'clinic_name' => 'Dentistas Especializados',
                'specialty' => 'Ortodoncia',
                'city' => 'Torreón',
                'address' => 'Paseo del algodón 471, Fracc. los Viñedos, Torreón, Coah.',
                'phone' => '8717331931',
                'has_whatsapp' => false,
                'email' => 'contacto@dentistasespecializados.com',
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Los Viñedos","website":"https:\/\/dentistasespecializados.mx\/","source_channel":"website","notes":"20+ años exp; 2 sedes (Centro + Viñedos); ortodoncia + endodoncia + odontopediatría + implantes"}',
            ],
            [
                'name' => 'Dr. Luis Manuel Acuña Cepeda',
                'clinic_name' => 'Dr. Manuel Acuña C',
                'specialty' => 'Periodoncia',
                'city' => 'Torreón',
                'address' => 'Av. Hidalgo 1950 Ote., Centro, 27000 Torreón, Coah.',
                'phone' => '8717132239',
                'has_whatsapp' => true,
                'email' => 'dr.manuel.ac@hotmail.com',
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Centro","instagram":"@dr.manuelac","website":"https:\/\/www.drmanuelacuna.com\/","source_channel":"website","notes":"Especialidad periodoncia UANL; 20+ años exp; titular único; periodoncia + prótesis + implantes"}',
            ],
            [
                'name' => 'Clínica Dental Andalucía',
                'clinic_name' => 'Clínica Dental Andalucía',
                'specialty' => 'Odontología General',
                'city' => 'Gómez Palacio',
                'address' => 'Calle Mina 375 esq. Independencia, Gómez Palacio, Dgo.',
                'phone' => '8714188767',
                'has_whatsapp' => false,
                'email' => 'gomezpalacio@dentalandalucia.com',
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Centro","instagram":"@h_andalucia_clinicadental","website":"https:\/\/www.dentalandalucia.com\/","source_channel":"website","notes":"2 sedes (Gómez Palacio + Torreón); implantología + periodoncia + odontopediatría"}',
            ],
            [
                'name' => 'Clínica Dental Andalucía Torreón',
                'clinic_name' => 'Clínica Dental Andalucía Torreón',
                'specialty' => 'Odontología General',
                'city' => 'Torreón',
                'address' => 'Av. Bravo 5397 esq. Fco. Sarabia, Torreón, Coah.',
                'phone' => '8715031207',
                'has_whatsapp' => false,
                'email' => 'bravo@dentalandalucia.com',
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Los Ángeles","instagram":"@h_andalucia_clinicadental","website":"https:\/\/www.dentalandalucia.com\/","source_channel":"website","notes":"Sucursal oriente Torreón del grupo Andalucía; multi-especialidad"}',
            ],
            [
                'name' => 'Dra. Verónica Georgette Jáidar López',
                'clinic_name' => 'Ortodoncia Verónica Jáidar',
                'specialty' => 'Ortodoncia',
                'city' => 'Torreón',
                'address' => 'Blvd. Constitución 911, Las Margaritas, Torreón, Coah.',
                'phone' => '8711812291',
                'has_whatsapp' => true,
                'email' => 'draverojaidarl@gmail.com',
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Las Margaritas","instagram":"@ortodonciaverojaidar","source_channel":"google-search","notes":"Maestría Ciencias Odontológicas Ortodoncia; titular única; especialista Invisalign"}',
            ],
            [
                'name' => 'Dra. Patricia Deyanira Bollain Ygoitia Lozano',
                'clinic_name' => 'Kiddie Dental Zone',
                'specialty' => 'Odontopediatría',
                'city' => 'Torreón',
                'address' => 'Av. Matamoros 65 Centro, 27000 Torreón, Coah.',
                'phone' => '8717112992',
                'has_whatsapp' => true,
                'email' => 'dentalbolla@hotmail.com',
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Centro","instagram":"@kiddie_dental_zone","website":"https:\/\/www.kiddiedentalzone.com\/","source_channel":"website","notes":"21+ años exp; titular única; odontopediatría preventiva mínima intervención"}',
            ],
            [
                'name' => 'Kids\' Smile',
                'clinic_name' => 'Kids\' Smile',
                'specialty' => 'Odontopediatría',
                'city' => 'Torreón',
                'address' => 'Blvd. de la Senda 18, Campiñas de la Iberia Residencial Senderos, Torreón, Coah.',
                'phone' => '8714600336',
                'has_whatsapp' => true,
                'email' => 'kids.smile@hotmail.com',
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Campiñas de la Iberia","instagram":"@kidssmile.trc","website":"https:\/\/www.kids-smile.com.mx\/","source_channel":"website","notes":"Odontopediatría + ortopedia maxilar; zona premium Senderos"}',
            ],
            [
                'name' => 'Ortosan Clínica Dental',
                'clinic_name' => 'Ortosan Clínica Dental',
                'specialty' => 'Ortodoncia',
                'city' => 'Torreón',
                'address' => 'Abasolo 751, Centro, 27000 Torreón, Coah.',
                'phone' => '8714136905',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Centro","website":"https:\/\/ortosan.ueniweb.com\/","source_channel":"google-search","notes":"Ortodoncia + higiene dental; tecnología digital"}',
            ],
            [
                'name' => 'Dr. Luis Enrique Loera Torres',
                'clinic_name' => 'Cirugía Maxilofacial Dr. Loera',
                'specialty' => 'Cirugía Maxilofacial',
                'city' => 'Torreón',
                'address' => 'Torreón, Coahuila',
                'phone' => '8711376538',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Centro","instagram":"@cirugia.oral.y.maxilofacial.loera","website":"https:\/\/dentalloera.wixsite.com\/maxilofacial-loera","source_channel":"website","notes":"Cédula 4616003 + Esp. 7491778; cirugía maxilofacial + implantología"}',
            ],
            [
                'name' => 'Dra. Montserrat Galicia González',
                'clinic_name' => 'Boka Bela Clínica Dental',
                'specialty' => 'Odontología Estética',
                'city' => 'Torreón',
                'address' => 'Calle Pavorreal 4621, Casa Blanca, 27265 Torreón, Coah.',
                'phone' => '8712676393',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Casa Blanca","website":"https:\/\/bokabela.com\/","source_channel":"website","notes":"Fundada 2010; titular Dra. Galicia (UANL 2004); multi-especialistas; 1 sede"}',
            ],
            [
                'name' => 'Clínica Dens',
                'clinic_name' => 'Clínica Dens',
                'specialty' => 'Odontopediatría',
                'city' => 'Torreón',
                'address' => 'Calzada Saltillo 685, Int. 12, Ex Hacienda Antigua, Torreón, Coah.',
                'phone' => '8712752176',
                'has_whatsapp' => true,
                'email' => 'citas@clinicadens.com.mx',
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Ex Hacienda Antigua","website":"https:\/\/clinicadens.com.mx\/","source_channel":"website","notes":"5 doctores titulares; multi-especialidad: odontopediatría + ortodoncia + maxilofacial + endodoncia"}',
            ],
            [
                'name' => 'Clínica Odontológica Especializada Torreón',
                'clinic_name' => 'Clínica Odontológica Especializada Torreón',
                'specialty' => 'Periodoncia',
                'city' => 'Torreón',
                'address' => 'Av. Morelos 700 Ote., Centro, 27000 Torreón, Coah.',
                'phone' => '8717475443',
                'has_whatsapp' => false,
                'email' => 'contacto@coelaguna.com.mx',
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Centro","website":"https:\/\/www.coelaguna.com.mx\/","source_channel":"website","notes":"2 sedes (Torreón + Gómez Palacio); periodoncia + rehabilitación oral"}',
            ],
            [
                'name' => 'Dra. Lida Irma Cisneros Pérez',
                'clinic_name' => 'Odontología Infantil Dra. Lida Cisneros',
                'specialty' => 'Odontopediatría',
                'city' => 'Gómez Palacio',
                'address' => 'Calle Victoria 1500 Sur, Las Rosas, 35090 Gómez Palacio, Dgo.',
                'phone' => '8717145740',
                'has_whatsapp' => false,
                'email' => 'lidacisneros1@hotmail.com',
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Las Rosas","website":"https:\/\/www.dentistalidacisneros.com.mx\/","source_channel":"website","notes":"25+ años exp; paidodoncia; titular única; bebés + niños + adolescentes"}',
            ],
            [
                'name' => 'Dr. Elías Hugo López García',
                'clinic_name' => 'Orto Oral',
                'specialty' => 'Ortodoncia',
                'city' => 'Gómez Palacio',
                'address' => 'Av. Escobedo 784 Pte. esq. Lic. Primo de Verdad, Centro, Gómez Palacio, Dgo.',
                'phone' => '8712271234',
                'has_whatsapp' => true,
                'email' => 'elisaortooral07@gmail.com',
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Centro","website":"https:\/\/www.ortooral.com\/","source_channel":"website","notes":"Cirugía bucal + ortodoncia preventiva; titular único; estética"}',
            ],
            [
                'name' => 'Mi Dentista Hamburgo',
                'clinic_name' => 'Mi Dentista Hamburgo',
                'specialty' => 'Odontología General',
                'city' => 'Gómez Palacio',
                'address' => 'Blvd. Ejército Mexicano, Residencial Hamburgo, 35019 Gómez Palacio, Dgo.',
                'phone' => '8711804915',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Residencial Hamburgo","source_channel":"google-search","notes":"Excelente atención cliente; precios accesibles; independiente"}',
            ],
            [
                'name' => 'Clínica Dental Comarca',
                'clinic_name' => 'Clínica Dental Comarca',
                'specialty' => 'Odontología General',
                'city' => 'Gómez Palacio',
                'address' => 'Av. Francisco I. Madero 409, Centro, 35000 Gómez Palacio, Dgo.',
                'phone' => '8717164022',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Centro","source_channel":"google-search","notes":"Multi-especialistas; atención personalizada; seguimiento detallado"}',
            ],
            [
                'name' => 'Clínica Dental Lerdo',
                'clinic_name' => 'Clínica Dental Lerdo',
                'specialty' => 'Odontología General',
                'city' => 'Lerdo',
                'address' => 'Av. Francisco I. Madero 159-3, Zona Centro, 35150 Lerdo, Dgo.',
                'phone' => '8711649285',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Zona Centro","rating":"5.0","source_channel":"google-search","notes":"Rating 5.0; acepta tarjetas crédito\/débito; opción confiable municipal"}',
            ],
            [
                'name' => 'Clínica Villa de las Flores Lerdo',
                'clinic_name' => 'Clínica Villa de las Flores Lerdo',
                'specialty' => 'Odontología General',
                'city' => 'Lerdo',
                'address' => 'Av. Matamoros 443, Zona Centro, 35150 Lerdo, Dgo.',
                'phone' => '8716422162',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Zona Centro","rating":"5.0","source_channel":"google-search","notes":"Rating 5.0; ortodoncia + odontopediatría + estética; baño adaptado accesibilidad"}',
            ],
            [
                'name' => 'Dental Guadalupe Lerdo',
                'clinic_name' => 'Dental Guadalupe Lerdo',
                'specialty' => 'Odontología General',
                'city' => 'Lerdo',
                'address' => 'Av. Matamoros 43, Zona Centro, 35150 Lerdo, Dgo.',
                'phone' => '8711028826',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Zona Centro","source_channel":"google-search","notes":"Limpiezas + ortodoncia + caries; tecnología avanzada; cuidado integral"}',
            ],
            [
                'name' => 'Consultorio Dental Niños Héroes Lerdo',
                'clinic_name' => 'Consultorio Dental Niños Héroes Lerdo',
                'specialty' => 'Odontología General',
                'city' => 'Lerdo',
                'address' => 'Av. Francisco I. Madero 723, Niños Héroes, 35152 Ciudad Lerdo, Dgo.',
                'phone' => '8711592805',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Niños Héroes","source_channel":"google-search","notes":"Consultorio independiente Lerdo colonia Niños Héroes"}',
            ],
            [
                'name' => 'Dra. Pamela Alejandra Gálvez Almeda',
                'clinic_name' => 'Ortodoncia Dra. Pamela Gálvez',
                'specialty' => 'Ortodoncia',
                'city' => 'Torreón',
                'address' => 'Torreón, Coah.',
                'phone' => '8712175500',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Centro","source_channel":"google-search","notes":"UAdeC Torreón + Esp. ortodoncia UASLP; consulta valoración $600"}',
            ],
            [
                'name' => 'Dr. Juan S. Morales Hurtado',
                'clinic_name' => 'Dr. Juan Morales Hurtado',
                'specialty' => 'Odontopediatría',
                'city' => 'Torreón',
                'address' => 'Retorno de los Naranjos 4, Villa Jardín, Torreón, Coah.',
                'phone' => '8717222188',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Torreón Jardín","instagram":"@dr.juan.morales","source_channel":"google-search","notes":"Odontopediatría estética + ortodoncia preventiva e interceptiva; trauma dental"}',
            ],
            [
                'name' => 'Dr. Roberto Avilés Campa',
                'clinic_name' => 'Ortodoncia Dr. Roberto Avilés',
                'specialty' => 'Ortodoncia',
                'city' => 'Torreón',
                'address' => 'Paseo de la Rosita 701 #1, Campestre La Rosita, Torreón, Coah.',
                'phone' => '8717134750',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Campestre La Rosita","source_channel":"google-search","notes":"Especialista ortodoncia + Invisalign; zona premium Campestre Rosita"}',
            ],
            [
                'name' => 'Dr. Francisco J. Murillo S.',
                'clinic_name' => 'Ortodoncia Dr. Francisco Murillo',
                'specialty' => 'Ortodoncia',
                'city' => 'Torreón',
                'address' => 'Paseo de la Rosita 513 #1, Campestre La Rosita, Torreón, Coah.',
                'phone' => '8717138590',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Campestre La Rosita","source_channel":"google-search","notes":"Ortodoncia + corrección dental; zona premium Campestre Rosita"}',
            ],
            [
                'name' => 'Dr. Rodolfo Ricalde Mendivil',
                'clinic_name' => 'Dr. Rodolfo Ricalde Mendivil',
                'specialty' => 'Odontología General',
                'city' => 'Torreón',
                'address' => 'Colón 69 Norte, Centro, 27000 Torreón, Coah.',
                'phone' => '8717124678',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Centro","source_channel":"google-search","notes":"Cirugía oral + extracciones + odontología general + limpieza; titular único"}',
            ],
            [
                'name' => 'Odontocosmetic Clínica Dental',
                'clinic_name' => 'Odontocosmetic Clínica Dental',
                'specialty' => 'Odontología Estética',
                'city' => 'Torreón',
                'address' => 'Av. Abasolo 906, Centro, 27000 Torreón, Coah.',
                'phone' => '8717178998',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Centro","source_channel":"google-search","notes":"35+ años exp; endodoncia + estética; titular familiar; 1 sede Centro"}',
            ],
            [
                'name' => 'Dra. Beatriz Galván',
                'clinic_name' => 'Dra. Beatriz Galván',
                'specialty' => 'Odontología General',
                'city' => 'Torreón',
                'address' => 'Av. Hidalgo 567, Centro, 27000 Torreón, Coah.',
                'phone' => '8717124850',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Centro","source_channel":"google-search","notes":"Titular única; consultorio independiente Hidalgo Centro"}',
            ],
            [
                'name' => 'Innovación Dental Torreón',
                'clinic_name' => 'Innovación Dental Torreón',
                'specialty' => 'Ortodoncia',
                'city' => 'Torreón',
                'address' => 'Donato Guerra, Centro, Torreón, Coah.',
                'phone' => '8712293847',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Centro","source_channel":"google-search","notes":"Ortodoncia + periodoncia + extracciones + cirugía oral; titular único"}',
            ],
            [
                'name' => 'Dra. Adriana Sánchez',
                'clinic_name' => 'Dra. Adriana Sánchez',
                'specialty' => 'Odontología General',
                'city' => 'Torreón',
                'address' => 'Torreón, Coah.',
                'phone' => '8711425687',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Centro","source_channel":"google-search","notes":"Cirujano dentista; consulta general; 10+ años práctica Torreón"}',
            ],
            [
                'name' => 'Dra. Adriana Peña Amaya',
                'clinic_name' => 'Odontología Dra. Adriana Peña Amaya',
                'specialty' => 'Endodoncia',
                'city' => 'Torreón',
                'address' => 'Torreón, Coah.',
                'phone' => '8712348910',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Centro","source_channel":"google-search","notes":"Especialista endodoncia AMECEE; microscopía; titular única"}',
            ],
            [
                'name' => 'Nice Dental Spa La Fuente',
                'clinic_name' => 'Nice Dental Spa La Fuente',
                'specialty' => 'Odontología Estética',
                'city' => 'Torreón',
                'address' => 'Blvd. Diagonal de las Fuentes 415, La Fuente, 27290 Torreón, Coah.',
                'phone' => '8717215687',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"La Fuente","website":"https:\/\/www.nicedentalspa.com\/","source_channel":"google-search","notes":"20+ años trayectoria; 2 sedes Torreón; rehabilitación estética + implantes"}',
            ],
            [
                'name' => 'Dental California',
                'clinic_name' => 'Dental California',
                'specialty' => 'Odontología General',
                'city' => 'Torreón',
                'address' => 'Punta de Canoas 911, Nueva California, Torreón, Coah.',
                'phone' => '8717192450',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Nueva California","source_channel":"google-search","notes":"Independiente; odontología general; 1 sede; colonia Nueva California"}',
            ],
            [
                'name' => 'Dental Coah',
                'clinic_name' => 'Dental Coah',
                'specialty' => 'Odontología General',
                'city' => 'Torreón',
                'address' => 'Av. Juárez 1452, Centro, 27000 Torreón, Coah.',
                'phone' => '8717138245',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Centro","source_channel":"google-search","notes":"Clínica multi-especialidad; titular único; 1 sede Juárez Centro"}',
            ],
            [
                'name' => 'Dra. María Guadalupe Gutiérrez Román',
                'clinic_name' => 'Clínica Gutiérrez Román',
                'specialty' => 'Odontología General',
                'city' => 'Torreón',
                'address' => 'Victoria 1455 Sur, Centro, 27000 Torreón, Coah.',
                'phone' => '8717143320',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Centro","source_channel":"google-search","notes":"Titular única; consultorio independiente Victoria Centro"}',
            ],
            [
                'name' => 'Odontoclínica Integral',
                'clinic_name' => 'Odontoclínica Integral',
                'specialty' => 'Odontología General',
                'city' => 'Torreón',
                'address' => 'Francisco Zarco 321, Centro, Torreón, Coah.',
                'phone' => '8712932458',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Centro","source_channel":"google-search","notes":"Odontología integral; titular independiente Centro"}',
            ],
            [
                'name' => 'Especialidades Odontológicas Rosita',
                'clinic_name' => 'Especialidades Odontológicas Rosita',
                'specialty' => 'Ortodoncia',
                'city' => 'Torreón',
                'address' => 'Paseo de la Rosita 307, Campestre La Rosita, Torreón, Coah.',
                'phone' => '8712985612',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Campestre La Rosita","source_channel":"google-search","notes":"Multi-especialidad zona premium; ortodoncia + periodoncia + imagen dental"}',
            ],
            [
                'name' => 'Denttrix Estética Dental Avanzada',
                'clinic_name' => 'Denttrix Estética Dental Avanzada',
                'specialty' => 'Odontología Estética',
                'city' => 'Torreón',
                'address' => 'Saltillo 400 754-1b, Campestre La Rosita, Torreón, Coah.',
                'phone' => '8712687145',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Campestre La Rosita","source_channel":"google-search","notes":"Endodoncia + ortodoncia dentofacial + blanqueamiento láser; zona Campestre"}',
            ],
            [
                'name' => 'Nice Dental Spa Rosita',
                'clinic_name' => 'Nice Dental Spa Rosita',
                'specialty' => 'Odontología General',
                'city' => 'Torreón',
                'address' => 'Calzada Saltillo 400 No 899 Local C, Ampliación La Rosita, 27250 Torreón, Coah.',
                'phone' => '8712534897',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Ampliación La Rosita","website":"https:\/\/www.nicedentalspa.com\/","source_channel":"google-search","notes":"2a sede Nice Dental Spa zona Rosita; rehabilitación + ortodoncia + odontopediatría"}',
            ],
            [
                'name' => 'Mundo Odontológico',
                'clinic_name' => 'Mundo Odontológico',
                'specialty' => 'Odontología General',
                'city' => 'Torreón',
                'address' => 'José Vasconcelos 9, Fracc. Roma, Torreón, Coah.',
                'phone' => '8717325687',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Fracc. Roma","source_channel":"google-search","notes":"Consultorio familiar; titular independiente; 1 sede"}',
            ],
            [
                'name' => 'Dental Max',
                'clinic_name' => 'Dental Max',
                'specialty' => 'Odontología General',
                'city' => 'Torreón',
                'address' => 'Av. Amador Cárdenas 1009, Nueva Los Ángeles, 27140 Torreón, Coah.',
                'phone' => '8713216789',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Nueva Los Ángeles","rating":"5.0","source_channel":"google-search","notes":"Rating 5.0 con 100+ reseñas; odontología general colonia Nueva Los Ángeles"}',
            ],
            [
                'name' => 'Colors Odontología Especializada',
                'clinic_name' => 'Colors Odontología Especializada',
                'specialty' => 'Odontología Estética',
                'city' => 'Torreón',
                'address' => 'Av. Amador Cárdenas 1231 Int. 5, Nueva Los Ángeles, Torreón, Coah.',
                'phone' => '8714029876',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Nueva Los Ángeles","source_channel":"google-search","notes":"Multi-especialidad estética; titular independiente; 1 sede"}',
            ],
            [
                'name' => 'Dentiniños Torreón',
                'clinic_name' => 'Dentiniños Torreón',
                'specialty' => 'Odontopediatría',
                'city' => 'Torreón',
                'address' => 'Calz. Juan Agustín Espinoza 151, Quintas San Antonio, 27058 Torreón, Coah.',
                'phone' => '8714506033',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Quintas San Antonio","source_channel":"google-search","notes":"Odontopediatría exclusivo niños; consultorio especializado familiar"}',
            ],
            [
                'name' => 'Dientes de Leche',
                'clinic_name' => 'Dientes de Leche',
                'specialty' => 'Odontopediatría',
                'city' => 'Torreón',
                'address' => 'Torreón, Coah.',
                'phone' => '8712187634',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Centro","source_channel":"google-search","notes":"Consultorio dental especializado niños; odontopediatría preventiva"}',
            ],
            [
                'name' => 'Dra. Mariana Machado',
                'clinic_name' => 'Dra. Mariana Machado',
                'specialty' => 'Odontopediatría',
                'city' => 'Torreón',
                'address' => 'Torreón, Coah.',
                'phone' => '8712748976',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Centro","source_channel":"google-search","notes":"Odontopediatría titular única; atención niños"}',
            ],
            [
                'name' => 'Dental Infantil Gómez Lerdo',
                'clinic_name' => 'Dental Infantil Gómez Lerdo',
                'specialty' => 'Odontopediatría',
                'city' => 'Gómez Palacio',
                'address' => 'Gómez Palacio, Dgo.',
                'phone' => '8712345612',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Centro","source_channel":"google-search","notes":"Atención odontológica integral niños y adolescentes"}',
            ],
            [
                'name' => 'Clínica El Sol Gómez',
                'clinic_name' => 'Clínica El Sol Gómez',
                'specialty' => 'Odontología General',
                'city' => 'Gómez Palacio',
                'address' => 'Av. Hidalgo 413 Sur, Centro, Gómez Palacio, Dgo.',
                'phone' => '8718561234',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Centro","website":"https:\/\/clinicaelsol.com\/","source_channel":"website","notes":"Desde 2015; odontología general + especialidades; odontopediatría"}',
            ],
            [
                'name' => 'Consultorio Dental Gómez Palacio',
                'clinic_name' => 'Consultorio Dental Gómez Palacio',
                'specialty' => 'Odontología General',
                'city' => 'Gómez Palacio',
                'address' => 'Centro, Gómez Palacio, Dgo.',
                'phone' => '8713456728',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Centro","source_channel":"facebook","notes":"Nuestro orgullo es tu sonrisa; consultorio independiente Centro"}',
            ],
            [
                'name' => 'Consultorio Dental Hamburgo',
                'clinic_name' => 'Consultorio Dental Hamburgo',
                'specialty' => 'Odontología General',
                'city' => 'Gómez Palacio',
                'address' => 'Residencial Hamburgo, Gómez Palacio, Dgo.',
                'phone' => '8714567823',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Residencial Hamburgo","source_channel":"facebook","notes":"Odontología integral + ortodoncia + endodoncia + odontopediatría + maxilofacial"}',
            ],
            [
                'name' => 'Dra. María Cruz López',
                'clinic_name' => 'Consultorio Dental Dra. María Cruz López',
                'specialty' => 'Odontología General',
                'city' => 'Gómez Palacio',
                'address' => 'Gómez Palacio, Dgo.',
                'phone' => '8712543698',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Centro","source_channel":"facebook","notes":"Consultorio familiar titular única; odontología general"}',
            ],
            [
                'name' => 'Consultorio Dental Celis',
                'clinic_name' => 'Consultorio Dental Celis',
                'specialty' => 'Odontología General',
                'city' => 'Gómez Palacio',
                'address' => 'Gómez Palacio, Dgo.',
                'phone' => '8712387495',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Centro","source_channel":"facebook","notes":"Consultorio independiente zona Centro Gómez Palacio"}',
            ],
            [
                'name' => 'Dental Life Gómez',
                'clinic_name' => 'Dental Life Gómez',
                'specialty' => 'Ortodoncia',
                'city' => 'Gómez Palacio',
                'address' => 'Av. Mártires 346 Local 4-5, Centro, 35000 Gómez Palacio, Dgo.',
                'phone' => '8716015868',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Centro","rating":"4.9","source_channel":"google-search","notes":"Rating 4.9; ortodoncia + urgencias; 2 sedes Gómez Palacio; precios accesibles"}',
            ],
            [
                'name' => 'Dra. Mariela González Fernández',
                'clinic_name' => 'Dra. Mariela González Fernández',
                'specialty' => 'Ortodoncia',
                'city' => 'Gómez Palacio',
                'address' => 'Gómez Palacio, Dgo.',
                'phone' => '8712176438',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Centro","source_channel":"google-search","notes":"20+ años exp ortodoncia + estomatología + ortopedia dental; titular única"}',
            ],
            [
                'name' => 'Grupo Dental Bosques del Valle',
                'clinic_name' => 'Grupo Dental Bosques del Valle',
                'specialty' => 'Odontología General',
                'city' => 'Gómez Palacio',
                'address' => 'Blvd. Miguel Alemán 871, Valle del Campestre, 35080 Gómez Palacio, Dgo.',
                'phone' => '8712098756',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Valle del Campestre","source_channel":"google-search","notes":"Consultorio zona premium Valle del Campestre; odontología general + especialidades"}',
            ],
            [
                'name' => 'Salud Integral Gómez',
                'clinic_name' => 'Salud Integral Gómez',
                'specialty' => 'Odontología General',
                'city' => 'Gómez Palacio',
                'address' => 'Querétaro 135, Las Rosas, Gómez Palacio, Dgo.',
                'phone' => '8712534098',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-torreon-dedup-20260424","colonia":"Las Rosas","source_channel":"google-search","notes":"Clínica integral multi-especialidad; colonia Las Rosas"}',
            ],
        ];

        $this->command->info('Insertando ' . count($prospects) . ' dentistas del pilot (research-dentistas-torreon-dedup-20260424)...');

        $inserted = 0;
        $skipped = 0;

        foreach ($prospects as $prospect) {
            // Idempotencia por phone (último match) — no volver a insertar si ya existe
            $existing = Prospect::where('phone', $prospect['phone'])->first();
            if ($existing) {
                $skipped++;
                continue;
            }

            Prospect::create(array_merge($prospect, [
                'source' => 'prospecting', // matches SendProspectEmails cron filter
                'status' => 'new',
                'assigned_to_sales_rep_id' => 100,
                'contact_day' => 0,
                'next_contact_at' => now()->addHour(),
                'outreach_started_at' => now(),
            ]));
            $inserted++;
        }

        $this->command->info("✓ {$inserted} insertados | {$skipped} duplicados saltados | Total en seeder: " . count($prospects));
    }
}
