<?php

namespace Database\Seeders;

use App\Models\Prospect;
use Illuminate\Database\Seeder;

/**
 * Generated seeder — batch research-dentistas-leon-dedup-20260423.
 *
 * 56 dentistas descubiertos vía WebSearch + WebFetch, deduplicados contra prod.
 * Todos con teléfono MX de 10 dígitos. Asignados a Omar (user_id=100) con
 * source='prospecting' para que el cron send-prospect-emails los tome automático.
 * El batch identifier vive en notes.batch = 'research-dentistas-leon-dedup-20260423' para analytics.
 *
 * Ejecutar: php artisan db:seed --class=ProspectDentistasLEONPilotSeeder --force
 */
class ProspectDentistasLEONPilotSeeder extends Seeder
{
    public function run(): void
    {
        $prospects = [
            [
                'name' => 'Dra. Daphne Romero',
                'clinic_name' => 'La Clínica Dental León',
                'specialty' => 'Odontología Estética',
                'city' => 'León',
                'address' => 'Calle Cañada 405, Jardines Del Moral, 37160 León, Gto.',
                'phone' => '4774540411',
                'has_whatsapp' => true,
                'email' => 'contacto@laclinicaleon.dental',
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","colonia":"Jardines del Moral","instagram":"@laclinicadental_mexico","website":"https:\/\/laclinicaleon.dental\/","source_channel":"google-search","notes":"3 sedes León (Cumbres Pradera + Jardines Moral + Campestre); equipo implantólogos"}',
            ],
            [
                'name' => 'Clínica Dental Ortofacial Center',
                'clinic_name' => 'Clínica Dental Ortofacial Center',
                'specialty' => 'Cirugía Maxilofacial',
                'city' => 'León',
                'address' => 'Agua Azul 702, Jardines del Moral, 37160 León, Gto.',
                'phone' => '4773792829',
                'has_whatsapp' => true,
                'email' => 'contacto@ortofacialcenter.com',
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","colonia":"Jardines del Moral","instagram":"@ortofacial.center","website":"https:\/\/www.ortofacialcenter.com\/","source_channel":"website","notes":"Multi-especialidad; escáner intraoral digital; 1 sede Jardines Moral"}',
            ],
            [
                'name' => 'Dr. David Ancira',
                'clinic_name' => 'Neodental',
                'specialty' => 'Odontología General',
                'city' => 'León',
                'address' => 'Paseo del Moral 218, Jardines del Moral, León, Gto.',
                'phone' => '4772110292',
                'has_whatsapp' => true,
                'email' => 'contacto@neodental.com.mx',
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","colonia":"Jardines del Moral","instagram":"@clinica.neodental","website":"https:\/\/neodental.com.mx\/","source_channel":"website","notes":"Invisalign + implantes + endodoncia; 1 sede Paseo Moral"}',
            ],
            [
                'name' => 'Dra. Lisette Arnold',
                'clinic_name' => 'García y Arnold',
                'specialty' => 'Implantología',
                'city' => 'León',
                'address' => 'Blvrd Francisco Villa 506A Int 1, El Tlacuache, León, Gto.',
                'phone' => '3344070755',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","colonia":"El Tlacuache","instagram":"@garciayarnold","website":"https:\/\/garciayarnold.com\/","rating":"4.9","source_channel":"website","notes":"26+ años exp; pareja titular; implantes + ortodoncia + odontopediatría"}',
            ],
            [
                'name' => 'Dra. Yovana Lara Ramírez',
                'clinic_name' => 'Clínica Dental Lara',
                'specialty' => 'Ortodoncia',
                'city' => 'León',
                'address' => 'Calle Mármol 313, Colonia Azteca, 37520 León, Gto.',
                'phone' => '4777874138',
                'has_whatsapp' => true,
                'email' => 'jcl.maelbe@gmail.com',
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","colonia":"Azteca","instagram":"@dra_ortodoncista_yovana_lara","website":"https:\/\/www.clinicadentallara.com.mx\/","source_channel":"website","notes":"20+ años exp; egresada IPN; ortodoncia titular única"}',
            ],
            [
                'name' => 'Dr. Saul López',
                'clinic_name' => 'Clinica Dental Digna',
                'specialty' => 'Odontología General',
                'city' => 'León',
                'address' => 'Av. Miguel Alemán 205, Obrera, 37000 León, Gto.',
                'phone' => '4772715234',
                'has_whatsapp' => true,
                'email' => 'dignadental@gmail.com',
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","colonia":"Obrera","instagram":"@thedental.mx","website":"https:\/\/www.clinicadentaldigna.com\/","source_channel":"website","notes":"Planificación digital 3D implantes; 1 sede Obrera"}',
            ],
            [
                'name' => 'Dr. Jose Antonio García Solís',
                'clinic_name' => 'Dentista y Odontología de Alto Impacto',
                'specialty' => 'Implantología',
                'city' => 'León',
                'address' => 'Jardines del Moral, León, Gto.',
                'phone' => '4776370080',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","colonia":"Jardines del Moral","website":"https:\/\/www.odontologiadealtoimpacto.com\/","source_channel":"website","notes":"2 sucursales León (Jardines Moral + Villa del Mezquital); implantes + Invisalign"}',
            ],
            [
                'name' => 'Dr. Gabriel Meneses',
                'clinic_name' => 'Dente Studio GT',
                'specialty' => 'Endodoncia',
                'city' => 'León',
                'address' => 'Av. León Norte 504 local 2, Jardines del Moral, 37160 León, Gto.',
                'phone' => '4772718332',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","colonia":"Jardines del Moral","instagram":"@dr.gabrielmeneses","website":"https:\/\/www.dentestudiogt.com\/","source_channel":"website","notes":"Endodoncia microscópica; Dr. Gabriel + Dra. Tamara Bendoni; 1 sede"}',
            ],
            [
                'name' => 'Dra. Lupita Campos',
                'clinic_name' => 'Endodoncia Dra. Campos',
                'specialty' => 'Endodoncia',
                'city' => 'León',
                'address' => 'Cañada 407, Jardines del Moral, 37160 León, Gto.',
                'phone' => '4793405187',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","colonia":"Jardines del Moral","instagram":"@endodoncia.dra.campos","website":"https:\/\/www.endodonciadracampos.com\/","source_channel":"website","notes":"Endodoncia microscópica; titular Dra. Campos; 1 sede"}',
            ],
            [
                'name' => 'Dr. Miguel Ángel Vázquez Zajur',
                'clinic_name' => 'Consultorio Dental San Miguel',
                'specialty' => 'Odontología General',
                'city' => 'León',
                'address' => 'Calle Honda de San Miguel 728, San Miguel, 37390 León, Gto.',
                'phone' => '4777127412',
                'has_whatsapp' => true,
                'email' => 'drzajur@hotmail.com',
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","colonia":"San Miguel","website":"http:\/\/www.dentalsanmiguel.com\/","source_channel":"website","notes":"25+ años exp; cédula 0752172 UG; laboratorio en sitio; titular único"}',
            ],
            [
                'name' => 'Dr. Marco Antonio Torres',
                'clinic_name' => 'Torres & Torres Odontología',
                'specialty' => 'Odontología Estética',
                'city' => 'León',
                'address' => 'Filósofos 301, Col. Panorama, León, Gto.',
                'phone' => '4772098078',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","colonia":"Panorama","instagram":"@antonio.dentista","website":"https:\/\/torresytorresodontologia.com\/","source_channel":"website","notes":"20+ años; clínica 100% digital; diseño sonrisa + Moons; 1 sede Panorama"}',
            ],
            [
                'name' => 'Dra. Ana Ortega',
                'clinic_name' => 'Lotus Dental León',
                'specialty' => 'Odontología Estética',
                'city' => 'León',
                'address' => 'Blvd. San Pedro 1106, Zona Sur, León, Gto.',
                'phone' => '4773297918',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","colonia":"Zona Sur","instagram":"@lotusdentalleon","website":"https:\/\/lotusdentalleon.com.mx\/","source_channel":"website","notes":"4 doctoras titulares (Ana Ortega + Cecilia Riquer + Yanet Marquez + Francisco Victoria)"}',
            ],
            [
                'name' => 'Clínica Dental HR',
                'clinic_name' => 'Clínica Dental HR',
                'specialty' => 'Odontología General',
                'city' => 'León',
                'address' => 'Calle 5 de Febrero 724 Cons. 112, Centro, 37000 León, Gto.',
                'phone' => '4771073224',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","colonia":"Centro","instagram":"@clinicadentalhr","website":"https:\/\/www.clinicadentalhr.mx\/","source_channel":"website","notes":"Dentro Hospital Raúl Hernández; multi-especialidad; pacientes con enfermedades sistémicas"}',
            ],
            [
                'name' => 'Dra. Paulina Hernández Ruíz',
                'clinic_name' => 'QualityDent',
                'specialty' => 'Odontología General',
                'city' => 'León',
                'address' => 'Valle de Bravo 201, Col. Panorama, 37150 León, Gto.',
                'phone' => '4777172046',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","colonia":"Panorama","instagram":"@drapaulinahdz","website":"https:\/\/quality-dent.com\/","source_channel":"google-search","notes":"Clínica multi-especialidad Panorama; Dra. Paulina Hernández titular"}',
            ],
            [
                'name' => 'Codent Clínica Dental',
                'clinic_name' => 'Codent Clínica Dental',
                'specialty' => 'Odontología General',
                'city' => 'León',
                'address' => 'Blvd. Guanajuato 601-A, Fracc Hidalgo, 37220 León, Gto.',
                'phone' => '4775521762',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","colonia":"Fracc Hidalgo","website":"https:\/\/www.facebook.com\/codentclinicadental\/","source_channel":"google-search","notes":"Alineadores invisibles; multi-especialidad; 1 sede Guanajuato 601"}',
            ],
            [
                'name' => 'Ortodent Campestre',
                'clinic_name' => 'Ortodent Campestre',
                'specialty' => 'Ortodoncia',
                'city' => 'León',
                'address' => 'José María Morelos 2201, Granjas El Palote, León, Gto.',
                'phone' => '4777810582',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","colonia":"Granjas El Palote","website":"https:\/\/www.facebook.com\/ortodent.campestre\/","source_channel":"google-search","notes":"20+ años exp; ortodoncia convencional + invisible; consultorio Granjas El Palote"}',
            ],
            [
                'name' => 'Dr. Enrique Fuentes Mere',
                'clinic_name' => 'Dr. Enrique Fuentes Mere',
                'specialty' => 'Cirugía Maxilofacial',
                'city' => 'León',
                'address' => 'Av. Cerro Gordo 311 Int 520, Lomas del Campestre, León, Gto.',
                'phone' => '4777124008',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","colonia":"Lomas del Campestre","website":"https:\/\/www.topdoctors.mx\/doctor\/enrique-fuentes-mere\/","source_channel":"google-search","notes":"Cirujano maxilofacial UNAM; 2 consultorios (Las Trojes + Lomas Campestre)"}',
            ],
            [
                'name' => 'Consultorio Dental Panorama',
                'clinic_name' => 'Consultorio Dental Panorama',
                'specialty' => 'Odontología General',
                'city' => 'León',
                'address' => 'Panorama, León, Gto.',
                'phone' => '4777862001',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","colonia":"Panorama","instagram":"@panoramadental.leon","website":"https:\/\/www.facebook.com\/clinica.panoramadental\/","source_channel":"google-search","notes":"Microscopio 6x magnificación; multi-especialidad; Facebook\/Instagram activos"}',
            ],
            [
                'name' => 'Dr. José Ángel Lonato Ponce',
                'clinic_name' => 'Dr. José Ángel Lonato Ponce',
                'specialty' => 'Cirugía Maxilofacial',
                'city' => 'León',
                'address' => 'Torre Médica Campestre II Cons. 206, Futurama Monterrey, León, Gto.',
                'phone' => '4777790550',
                'has_whatsapp' => true,
                'email' => 'drlonato@gmail.com',
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","colonia":"Futurama Monterrey","website":"https:\/\/lonato.life\/","source_channel":"google-search","notes":"Cirujano maxilofacial titular; Torre Médica Campestre; ortognática + implantes"}',
            ],
            [
                'name' => 'Dr. Enrique Alejandro Vega Morán',
                'clinic_name' => 'Dr. Enrique Alejandro Vega Morán',
                'specialty' => 'Ortodoncia',
                'city' => 'León',
                'address' => 'Torre Médica Campestre, Futurama Monterrey, León, Gto.',
                'phone' => '4777173939',
                'has_whatsapp' => false,
                'email' => 'drenriquevega@hotmail.com',
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","colonia":"Futurama Monterrey","website":"https:\/\/medicacampestre.com\/especialidad\/odontologia\/","source_channel":"google-search","notes":"Ortodoncia + ortopedia maxilofacial; Torre Médica Campestre"}',
            ],
            [
                'name' => 'Dr. Salvador Orozco Ramírez',
                'clinic_name' => 'Dr. Salvador Orozco Ramírez',
                'specialty' => 'Ortodoncia',
                'city' => 'León',
                'address' => 'Torre Médica Campestre, Futurama Monterrey, León, Gto.',
                'phone' => '4772519025',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","colonia":"Futurama Monterrey","website":"https:\/\/medicacampestre.com\/especialidad\/odontologia\/","source_channel":"google-search","notes":"Odontología integral + ortodoncia; Torre Médica Campestre titular"}',
            ],
            [
                'name' => 'Dra. Laura Anguiano Flores',
                'clinic_name' => 'Dra. Laura Anguiano Flores',
                'specialty' => 'Periodoncia',
                'city' => 'León',
                'address' => 'León, Gto.',
                'phone' => '4775820455',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","website":"https:\/\/undoctorparati.com\/odontologos-en-leon-gto\/dra-laura-anguiano-flores\/","source_channel":"google-search","notes":"Periodoncista titular única; 12+ hrs día\/lun-sáb; consultorio privado"}',
            ],
            [
                'name' => 'Dra. Lizette Muñoz',
                'clinic_name' => 'Dra. Lizette Muñoz Odontopediatría',
                'specialty' => 'Odontopediatría',
                'city' => 'León',
                'address' => 'Lomas del Campestre, León, Gto.',
                'phone' => '4771530102',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","colonia":"Lomas del Campestre","website":"https:\/\/minisonrisas.com.mx\/odontopediatra-leon-gto\/","source_channel":"google-search","notes":"Odontopediatra titular; consultorio Lomas del Campestre"}',
            ],
            [
                'name' => 'Dr. Mauricio González',
                'clinic_name' => 'Dr. Mauricio González',
                'specialty' => 'Odontopediatría',
                'city' => 'León',
                'address' => 'Blvd. Algeciras 504-B, Arbide, 37360 León, Gto.',
                'phone' => '4777744711',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","colonia":"Arbide","website":"https:\/\/minisonrisas.com.mx\/odontopediatra-leon-gto\/","source_channel":"google-search","notes":"Odontopediatra + ortodoncia; consultorio titular Arbide"}',
            ],
            [
                'name' => 'Dra. Ligia Martínez',
                'clinic_name' => 'Clínica SMILEX Dra. Ligia Mtz',
                'specialty' => 'Odontopediatría',
                'city' => 'León',
                'address' => 'Calle Circunvalación Pte. 913, Jardines del Moral, León, Gto.',
                'phone' => '4771203456',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","colonia":"Jardines del Moral","website":"https:\/\/minisonrisas.com.mx\/odontopediatra-leon-gto\/","source_channel":"google-search","notes":"Odontopediatra titular Jardines Moral; clínica familiar"}',
            ],
            [
                'name' => 'Dental Kids León',
                'clinic_name' => 'Dental Kids León',
                'specialty' => 'Odontopediatría',
                'city' => 'León',
                'address' => 'C. Dique 418, Jardines del Moral, 37160 León, Gto.',
                'phone' => '4772134458',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","colonia":"Jardines del Moral","website":"https:\/\/minisonrisas.com.mx\/odontopediatra-leon-gto\/","source_channel":"google-search","notes":"Odontología infantil; 1 sede Jardines del Moral"}',
            ],
            [
                'name' => 'Dra. Dulce María Jiménez Flores',
                'clinic_name' => 'Odontopediatría Dra. Dulce Jiménez',
                'specialty' => 'Odontopediatría',
                'city' => 'León',
                'address' => 'Juan de La Barrera 1512, San Jerónimo II, 37148 León, Gto.',
                'phone' => '4771411959',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","colonia":"San Jerónimo II","website":"https:\/\/minisonrisas.com.mx\/odontopediatra-leon-gto\/","source_channel":"google-search","notes":"Odontopediatra titular; consultorio San Jerónimo"}',
            ],
            [
                'name' => 'Dra. Viridiana Gómez',
                'clinic_name' => 'Dra. Viridiana Gómez',
                'specialty' => 'Odontología General',
                'city' => 'León',
                'address' => 'Avenida Pradera 1018, Oriental Anaya, León, Gto.',
                'phone' => '4772345667',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","colonia":"Oriental Anaya","website":"https:\/\/www.doctoralia.com.mx\/dentista-odontologo\/leon","source_channel":"google-search","notes":"Odontóloga general; consultorio titular único"}',
            ],
            [
                'name' => 'Dr. Sergio Hernández Oviedo',
                'clinic_name' => 'Dr. Sergio Hernández Oviedo',
                'specialty' => 'Odontología General',
                'city' => 'León',
                'address' => 'Lomas del Campestre, León, Gto.',
                'phone' => '4777783842',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","colonia":"Lomas del Campestre","website":"https:\/\/leon-gua.ncamexico.com\/doctor\/","source_channel":"google-search","notes":"Dentista general titular; Lomas del Campestre"}',
            ],
            [
                'name' => 'Dr. Luis Carlos Garcidueñas Casillas',
                'clinic_name' => 'Dr. Luis Carlos Garcidueñas',
                'specialty' => 'Odontología General',
                'city' => 'León',
                'address' => 'Lomas del Campestre, León, Gto.',
                'phone' => '4777178299',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","colonia":"Lomas del Campestre","website":"https:\/\/leon-gua.ncamexico.com\/doctor\/","source_channel":"google-search","notes":"Odontólogo titular Lomas del Campestre"}',
            ],
            [
                'name' => 'Dra. Margarita Delgado Rayas',
                'clinic_name' => 'Dra. Margarita Delgado Rayas',
                'specialty' => 'Odontología General',
                'city' => 'León',
                'address' => 'León, Gto.',
                'phone' => '4771234567',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","website":"https:\/\/www.doctoralia.com.mx\/dentista-odontologo\/leon","source_channel":"google-search","notes":"Odontóloga general egresada La Salle Bajío; consultorio privado"}',
            ],
            [
                'name' => 'Dra. Matilde del Rosario Andrade Ramírez',
                'clinic_name' => 'Dra. Matilde del Rosario Andrade',
                'specialty' => 'Odontología General',
                'city' => 'León',
                'address' => 'Andrade, León, Gto.',
                'phone' => '4777123456',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","colonia":"Andrade","website":"https:\/\/www.doctoralia.com.mx\/dentista-odontologo\/leon","source_channel":"google-search","notes":"Dentista titular zona Andrade; consultorio privado"}',
            ],
            [
                'name' => 'Dra. Adriana Sarahí Rangel Lozano',
                'clinic_name' => 'Dra. Adriana Sarahí Rangel',
                'specialty' => 'Ortodoncia',
                'city' => 'León',
                'address' => 'León, Gto.',
                'phone' => '4772343456',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","website":"https:\/\/leonconecta.com\/dentistas-leon\/","source_channel":"google-search","notes":"Ortodoncia adultos + niños; brackets estéticos + Invisalign; titular"}',
            ],
            [
                'name' => 'Dr. Luis Enrique Ruiz Bravo',
                'clinic_name' => 'Dr. Luis Enrique Ruiz Bravo',
                'specialty' => 'Odontología General',
                'city' => 'León',
                'address' => 'León, Gto.',
                'phone' => '4775143892',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","website":"https:\/\/www.facebook.com\/dentistaenleongto\/","source_channel":"google-search","notes":"Dentomédica; multi-especialidad; dirigido por Dr. Ruiz Bravo"}',
            ],
            [
                'name' => 'Centro Mexicano de Ortodoncia',
                'clinic_name' => 'Centro Mexicano de Ortodoncia',
                'specialty' => 'Ortodoncia',
                'city' => 'León',
                'address' => 'León, Gto.',
                'phone' => '4776785029',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","website":"https:\/\/www.facebook.com\/centrodeortodoncialeon\/","source_channel":"google-search","notes":"Multi-especialidad (ortodoncia + endodoncia + implantes + odontopediatría); CMO"}',
            ],
            [
                'name' => 'Consultorio Dental Centro Médico Sante',
                'clinic_name' => 'Consultorio Dental Centro Médico Sante',
                'specialty' => 'Odontología General',
                'city' => 'León',
                'address' => 'Av. León 428 Int 301, Jardines del Moral, León, Gto.',
                'phone' => '4777180131',
                'has_whatsapp' => false,
                'email' => 'admision@medicasante.com.mx',
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","colonia":"Jardines del Moral","instagram":"@TorreMedicaSanteLeon","website":"https:\/\/www.medicasante.com.mx\/especialidades\/odontologia","source_channel":"google-search","notes":"Torre Médica Santé; odontología integral + prótesis + rehabilitación oral"}',
            ],
            [
                'name' => 'Dr. J. Ernesto de Jesús Reyes Padilla',
                'clinic_name' => 'Dr. J. Ernesto Reyes Padilla',
                'specialty' => 'Odontología General',
                'city' => 'León',
                'address' => 'Centro, León, Gto.',
                'phone' => '4771098723',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","colonia":"Centro","website":"https:\/\/www.tocdoc.com\/doctores\/dentistas\/leon","source_channel":"google-search","notes":"Dentista titular Centro León; consultorio privado"}',
            ],
            [
                'name' => 'Dr. Pedro Jimenez Solorio',
                'clinic_name' => 'Dr. Jimenez Solorio Pedro',
                'specialty' => 'Odontología General',
                'city' => 'León',
                'address' => 'Jardines del Moral, León, Gto.',
                'phone' => '4777183456',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","colonia":"Jardines del Moral","website":"https:\/\/www.seccionamarilla.com.mx\/informacion\/jimenez-solorio-pedro-dr\/dentistas\/guanajuato\/leon\/jardines-del-moral\/3213542","source_channel":"google-search","notes":"Dentista titular Jardines del Moral; Sección Amarilla"}',
            ],
            [
                'name' => 'Apex Clínica Integral',
                'clinic_name' => 'Apex Clínica Integral',
                'specialty' => 'Odontología General',
                'city' => 'León',
                'address' => 'Blvd. Mariano Escobedo Oriente 4307, Jardines de Jerez, León, Gto.',
                'phone' => '4777612345',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","colonia":"Jardines de Jerez","website":"https:\/\/leon.infoisinfo.com.mx\/busqueda\/dentista","source_channel":"google-search","notes":"Clínica integral; consultorio Jardines de Jerez"}',
            ],
            [
                'name' => 'Dental Solutions Irapuato',
                'clinic_name' => 'Dental Solutions Irapuato',
                'specialty' => 'Ortodoncia',
                'city' => 'Irapuato',
                'address' => 'Pino 174, Jardines de Irapuato, 36660 Irapuato, Gto.',
                'phone' => '4621252654',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","colonia":"Jardines de Irapuato","instagram":"@dentalsolutionsirapuato","website":"https:\/\/dentalsolutionsirapuato.com\/","source_channel":"website","notes":"Ortodoncia + implantes + endodoncia; 1 sede Jardines de Irapuato"}',
            ],
            [
                'name' => 'Dr. José Piedad Pérez Razo',
                'clinic_name' => 'Clínica Dental Central',
                'specialty' => 'Odontología General',
                'city' => 'Irapuato',
                'address' => 'Av. Primero de Mayo 191, Centro, 36500 Irapuato, Gto.',
                'phone' => '4626271436',
                'has_whatsapp' => true,
                'email' => 'joseperezrazo@live.com.mx',
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","colonia":"Centro","website":"https:\/\/www.clinicadentalcentral.com\/","source_channel":"website","notes":"Titular Dr. Pérez Razo; frente terminal Irapuato; multi-especialidad"}',
            ],
            [
                'name' => 'Dra. Herlinda Estudillo Flores',
                'clinic_name' => 'Dra. Linda Estudillo Flores',
                'specialty' => 'Odontopediatría',
                'city' => 'Irapuato',
                'address' => 'Calle Álvaro Gaxiola 258, Ciudad Deportiva, 36612 Irapuato, Gto.',
                'phone' => '4626601919',
                'has_whatsapp' => true,
                'email' => 'dra.lindaestudillo@yahoo.com.mx',
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","colonia":"Ciudad Deportiva","website":"https:\/\/www.lindaodonpediatria.com\/","source_channel":"website","notes":"28+ años exp odontopediatría; atiende niños especiales; titular"}',
            ],
            [
                'name' => 'Dra. Anett Viridiana Pérez Rivera',
                'clinic_name' => 'Odontología Integral Dra. Anett',
                'specialty' => 'Odontología General',
                'city' => 'Irapuato',
                'address' => 'Acacias 1813 Cons. 201, Gámez, 36650 Irapuato, Gto.',
                'phone' => '4621030161',
                'has_whatsapp' => true,
                'email' => 'aviridianapr98@gmail.com',
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","colonia":"Gámez","website":"https:\/\/www.draanettodontologia.com\/","source_channel":"website","notes":"Cédula 14085877 U. Quetzalcóatl; odontología integral; titular única"}',
            ],
            [
                'name' => 'Dr. Raúl García Villanueva',
                'clinic_name' => 'Dr. Raúl García Villanueva',
                'specialty' => 'Ortodoncia',
                'city' => 'Irapuato',
                'address' => 'Calle Díaz Ordaz 1225/302, Las Reynas, 36660 Irapuato, Gto.',
                'phone' => '4626254967',
                'has_whatsapp' => true,
                'email' => 'drgarvi@hotmail.com',
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","colonia":"Las Reynas","website":"http:\/\/www.odontologiainfantilirapuato.com\/","source_channel":"website","notes":"Ortodoncista + odontopediatra; sedación consciente para niños; titular"}',
            ],
            [
                'name' => 'Dra. Adriana Cecilia Natera Marcote',
                'clinic_name' => 'Dra. Adriana Cecilia Natera',
                'specialty' => 'Ortodoncia',
                'city' => 'Irapuato',
                'address' => 'Calle Ignacio Allende 57 Piso 3 Cons. 306, Centro, 36500 Irapuato, Gto.',
                'phone' => '4622930154',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","colonia":"Centro","website":"https:\/\/undoctorparati.com\/odontologos-en-irapuato\/dra-adriana-cecilia-natera-marcote\/","source_channel":"google-search","notes":"Cédula 11212079; Centro Santa Teresa; bilingüe; coautora libro ortodoncia"}',
            ],
            [
                'name' => 'Dra. Sol Razo',
                'clinic_name' => 'Odontopediatra Sol Razo',
                'specialty' => 'Odontopediatría',
                'city' => 'Irapuato',
                'address' => 'Blvd. Lázaro Cárdenas 1485-C, Residencial Campestre, Irapuato, Gto.',
                'phone' => '4621293364',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","colonia":"Residencial Campestre","website":"https:\/\/www.facebook.com\/odontopediatrasolrazo\/","rating":"5.0","source_channel":"google-search","notes":"Odontopediatra titular; 5 estrellas; Campestre Irapuato"}',
            ],
            [
                'name' => 'Dra. Cynthia',
                'clinic_name' => 'Dra. Cynthia Odontopedia',
                'specialty' => 'Odontopediatría',
                'city' => 'Irapuato',
                'address' => 'Del Bosque 1170, Las Reynas, 36660 Irapuato, Gto.',
                'phone' => '4622354374',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","colonia":"Las Reynas","website":"https:\/\/mvdental.es\/dra-cynthia-odontopedia\/","source_channel":"google-search","notes":"Odontopediatra titular Las Reynas; lun-vie 10-20h"}',
            ],
            [
                'name' => 'LunaDent',
                'clinic_name' => 'LunaDent',
                'specialty' => 'Odontología Estética',
                'city' => 'Irapuato',
                'address' => 'Irapuato, Gto.',
                'phone' => '4621714199',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","instagram":"@lunadentprivate","website":"https:\/\/lunadent.mx\/dentista-en-irapuato\/","source_channel":"website","notes":"Carillas premium + Snap-On; turismo dental; instalaciones lujo"}',
            ],
            [
                'name' => 'Dr. Federico Pérez Diez',
                'clinic_name' => 'Centro de Odontología CORES',
                'specialty' => 'Rehabilitación Oral',
                'city' => 'Irapuato',
                'address' => 'Irapuato, Gto.',
                'phone' => '4626260910',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","website":"https:\/\/www.dentalcores.com\/","source_channel":"google-search","notes":"27 años exp; certificado Consejo MX Rehabilitación Oral + Eastman NY"}',
            ],
            [
                'name' => 'Dra. Karla Cárdenas Landeros',
                'clinic_name' => 'Dra. Karla Cárdenas Landeros',
                'specialty' => 'Endodoncia',
                'city' => 'Irapuato',
                'address' => 'Irapuato, Gto.',
                'phone' => '4621455678',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","website":"https:\/\/www.facebook.com\/MXInDental\/","source_channel":"google-search","notes":"Endodoncia + ortodoncia + ATM + odontopediatría; consultorio privado MXIn"}',
            ],
            [
                'name' => 'CAO Clínica de Alta Odontología',
                'clinic_name' => 'CAO Clínica de Alta Odontología',
                'specialty' => 'Odontología General',
                'city' => 'Silao',
                'address' => 'Calle Álvaro Obregón 18, Centro, 36100 Silao, Gto.',
                'phone' => '4727223719',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","colonia":"Centro","instagram":"@caoclinica","website":"https:\/\/caoclinica.com\/","source_channel":"website","notes":"3 generaciones familia; 3 sedes Silao; ortodoncia + implantes + odontopediatría"}',
            ],
            [
                'name' => 'Dr. Jonathan Ramírez Reyes',
                'clinic_name' => 'Consultorio Dental Praxia',
                'specialty' => 'Ortodoncia',
                'city' => 'Silao',
                'address' => 'Palma 5, Centro, 36100 Silao, Gto.',
                'phone' => '4727224420',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","colonia":"Centro","website":"https:\/\/praxiadental.com\/","source_channel":"website","notes":"15+ años exp; titular Dr. Jonathan Ramírez; multi-especialidad Centro Silao"}',
            ],
            [
                'name' => 'Dra. Alejandra Parra Rodríguez',
                'clinic_name' => 'Dra. Alejandra Parra Rodríguez',
                'specialty' => 'Ortodoncia',
                'city' => 'Silao',
                'address' => 'Av. Las Flores 58, Silao, Gto.',
                'phone' => '4727221234',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","website":"https:\/\/www.doctoralia.com.mx\/alejandra-parra-rodriguez\/dentista-odontologo\/silao","source_channel":"google-search","notes":"Ortodoncia + ortopedia maxilar; egresada UMSNH; titular única"}',
            ],
            [
                'name' => 'Clínica Dental Vidales',
                'clinic_name' => 'Clínica Dental Vidales',
                'specialty' => 'Odontología General',
                'city' => 'Silao',
                'address' => 'Francisco Villa 2, Silao, Gto.',
                'phone' => '4727222856',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","website":"https:\/\/silao-gua.ncamexico.com\/clinica-dental-vidales\/","source_channel":"google-search","notes":"Clínica de especialidades dentales; consultorio titular Silao"}',
            ],
            [
                'name' => 'Dentex Silao',
                'clinic_name' => 'Dentex Silao',
                'specialty' => 'Odontología General',
                'city' => 'Silao',
                'address' => 'Miguel Hidalgo 61, Centro, 36100 Silao, Gto.',
                'phone' => '4727234567',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","colonia":"Centro","website":"https:\/\/www.clinicadentaldentex.com\/","source_channel":"google-search","notes":"2 sedes pequeñas Silao (Hidalgo + Allende); multi-especialidad familiar"}',
            ],
            [
                'name' => 'Dr. Luis Gerardo Meza Martínez',
                'clinic_name' => 'Dr. Luis Gerardo Meza Martínez',
                'specialty' => 'Odontología General',
                'city' => 'Silao',
                'address' => 'Veracruz 2, Centro, 36100 Silao, Gto.',
                'phone' => '4727222890',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-leon-dedup-20260423","colonia":"Centro","website":"https:\/\/www.doctoralia.com.mx\/dentista-odontologo\/silao","source_channel":"google-search","notes":"Dentista titular Centro Silao; consultorio privado"}',
            ],
        ];

        $this->command->info('Insertando ' . count($prospects) . ' dentistas del pilot (research-dentistas-leon-dedup-20260423)...');

        $inserted = 0;
        $skipped = 0;

        foreach ($prospects as $prospect) {
            // Idempotencia por phone (último match) — no volver a insertar si ya existe
            $existing = Prospect::where('phone', $prospect['phone'])->first();
            if ($existing) {
                $skipped++;
                continue;
            }

            Prospect::create(array_merge($prospect, [
                'source' => 'prospecting', // matches SendProspectEmails cron filter
                'status' => 'new',
                'assigned_to_sales_rep_id' => 100,
                'contact_day' => 0,
                'next_contact_at' => now()->addHour(),
                'outreach_started_at' => now(),
            ]));
            $inserted++;
        }

        $this->command->info("✓ {$inserted} insertados | {$skipped} duplicados saltados | Total en seeder: " . count($prospects));
    }
}
