<?php

namespace Database\Seeders;

use App\Models\Prospect;
use Illuminate\Database\Seeder;

/**
 * Generated seeder — batch research-dentistas-mid-dedup-20260422.
 *
 * 60 dentistas descubiertos vía WebSearch + WebFetch, deduplicados contra prod.
 * Todos con teléfono MX de 10 dígitos. Asignados a Omar (user_id=100) con
 * source='prospecting' para que el cron send-prospect-emails los tome automático.
 * El batch identifier vive en notes.batch = 'research-dentistas-mid-dedup-20260422' para analytics.
 *
 * Ejecutar: php artisan db:seed --class=ProspectDentistasMIDPilotSeeder --force
 */
class ProspectDentistasMIDPilotSeeder extends Seeder
{
    public function run(): void
    {
        $prospects = [
            [
                'name' => 'Dra. Georgina Flores Avalos',
                'clinic_name' => 'Smile Center Mérida',
                'specialty' => 'Ortodoncia',
                'city' => 'Mérida',
                'address' => 'Centro Médico Pensiones Cons. 319, Calle 7 #215A, García Ginerés, 97070 Mérida',
                'phone' => '9999439183',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"García Ginerés","instagram":"@smilecentermerida","website":"https:\/\/smilecentermerida.com\/","source_channel":"google-search","notes":"Ortodoncia + Invisalign; egresada UADY + Maestría UAdeC; IG activo"}',
            ],
            [
                'name' => 'Dr. Carlos Humberto Alayola Cáceres',
                'clinic_name' => 'Ortodoncia Alayola',
                'specialty' => 'Ortodoncia',
                'city' => 'Mérida',
                'address' => 'Calle 7 #552 int.5 x 24A y 24B, Col. Maya, 97134 Mérida',
                'phone' => '9992479443',
                'has_whatsapp' => true,
                'email' => 'carlos.alayola@ortodonciaenmerida.com',
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"Maya","instagram":"@alayola.ortodoncista","website":"https:\/\/www.ortodonciaenmerida.com\/","source_channel":"google-search","notes":"Invisalign + Spark + brackets; consultorio titular solo; frente Hospital Alta Especialidad"}',
            ],
            [
                'name' => 'Dra. Mónica I. Souza Paz',
                'clinic_name' => 'Consultorio Dra. Mónica Souza Paz',
                'specialty' => 'Ortodoncia',
                'city' => 'Mérida',
                'address' => 'Hospital Star Médica, Consultorio 618, Altabrisa, Mérida',
                'phone' => '9991960687',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"Altabrisa","source_channel":"google-search","notes":"30+ años exp; alineadores + apnea del sueño; consultorio titular"}',
            ],
            [
                'name' => 'Dr. Francisco Ku Carrillo',
                'clinic_name' => 'Ortodoncia Dr. Ku Carrillo',
                'specialty' => 'Ortodoncia',
                'city' => 'Mérida',
                'address' => 'Calle 35 #418, Col. López Mateos, Mérida',
                'phone' => '9999271460',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"López Mateos","source_channel":"google-search","notes":"18 años exp; Invisalign certificado; dos sedes pequeñas"}',
            ],
            [
                'name' => 'Dra. Carolina Gutiérrez Alférez',
                'clinic_name' => 'COSMODENTAL',
                'specialty' => 'Ortodoncia',
                'city' => 'Mérida',
                'address' => 'Calle 50 #122-C x 39-C y 41, Francisco de Montejo, Mérida',
                'phone' => '9992893863',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"Francisco de Montejo","source_channel":"google-search","notes":"Brackets cerámica + zafiro + Invisalign; multiespecialidad pareja de doctores"}',
            ],
            [
                'name' => 'Dr. César M. Delgado Campos',
                'clinic_name' => 'CLINI DENT',
                'specialty' => 'Ortodoncia',
                'city' => 'Mérida',
                'address' => 'Calle 21 #103-C, Col. Chuburná de Hidalgo, Mérida',
                'phone' => '9992417227',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"Chuburná de Hidalgo","source_channel":"google-search","notes":"Brackets linguales + ortodoncia funcional; incluye odontopediatra Dra. Falcón"}',
            ],
            [
                'name' => 'Dra. Ana María Puc Tun',
                'clinic_name' => 'Consultorio Dra. Ana María Puc',
                'specialty' => 'Ortodoncia',
                'city' => 'Mérida',
                'address' => 'Mérida Centro',
                'phone' => '9991680354',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"Centro","source_channel":"google-search","notes":"Ortodoncista independiente; consultorio único"}',
            ],
            [
                'name' => 'Dra. Cielo Ivette Bautista Rojas',
                'clinic_name' => 'Consultorio Dra. Cielo Bautista',
                'specialty' => 'Ortodoncia',
                'city' => 'Mérida',
                'address' => 'Torre Cénit, Calle 15 #501 x 18 y 22, Piso 7, Fracc. Altabrisa, 97130 Mérida',
                'phone' => '9992853559',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"Altabrisa","source_channel":"google-search","notes":"Ortodoncia adultos y adolescentes; Torre Cénit Altabrisa"}',
            ],
            [
                'name' => 'Dr. Esteban Novelo Canto',
                'clinic_name' => 'Consultorio Dr. Esteban Novelo',
                'specialty' => 'Ortodoncia',
                'city' => 'Mérida',
                'address' => 'Centro Médico Pensiones, García Ginerés, Mérida',
                'phone' => '9991923826',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"García Ginerés","source_channel":"google-search","notes":"Ortodoncista titular solo; CMP"}',
            ],
            [
                'name' => 'Dr. Ferdy Gallegos',
                'clinic_name' => 'Galo Ortodoncia',
                'specialty' => 'Ortodoncia',
                'city' => 'Mérida',
                'address' => 'Calle 40 #515-A x 29 y 31, Residencial Los Pinos, Mérida',
                'phone' => '9992270030',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"Los Pinos","source_channel":"google-search","notes":"Consultorio pequeño Los Pinos; brackets + alineadores"}',
            ],
            [
                'name' => 'M.O.I. Georgina Lugo Cabrera',
                'clinic_name' => 'Happy Dent',
                'specialty' => 'Odontopediatría',
                'city' => 'Mérida',
                'address' => 'Calle 22 #81 x 7 y 9, San Antonio Cinta, Mérida',
                'phone' => '9999484247',
                'has_whatsapp' => true,
                'email' => 'happydent@live.com.mx',
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"San Antonio Cinta","website":"http:\/\/happydent.com.mx\/","source_channel":"google-search","notes":"Odontopediatría + ortopedia + ortodoncia infantil; dos doctores titulares"}',
            ],
            [
                'name' => 'Dra. Martha Leslie Herrera Zetina',
                'clinic_name' => 'Consultorio Dra. Martha Herrera',
                'specialty' => 'Odontopediatría',
                'city' => 'Mérida',
                'address' => 'Calle 24 #97G x 19 y 21, Col. Itzimná, 97100 Mérida',
                'phone' => '9992894584',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"Itzimná","source_channel":"google-search","notes":"Odontopediatra titular; consultorio Itzimná"}',
            ],
            [
                'name' => 'Dra. Stephanie León Bolaños',
                'clinic_name' => 'Consultorio Dra. Stephanie León',
                'specialty' => 'Endodoncia',
                'city' => 'Mérida',
                'address' => 'The White Loft, Av. Cámara de Comercio #266 x 34 y 36, San Ramón Norte, 97117 Mérida',
                'phone' => '9994819776',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"San Ramón Norte","source_channel":"google-search","notes":"Endodoncista + odontopediatría; WhiteLoft San Ramón Norte"}',
            ],
            [
                'name' => 'Dra. Estefanía González Mendiburu',
                'clinic_name' => 'Consultorio Dra. Estefanía González',
                'specialty' => 'Odontopediatría',
                'city' => 'Mérida',
                'address' => 'Av. Remigio Aguilar #256 x 26 y 28, Col. Miguel Alemán, Mérida',
                'phone' => '9992236080',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"Miguel Alemán","source_channel":"google-search","notes":"Odontopediatra titular; Miguel Alemán"}',
            ],
            [
                'name' => 'Dr. Alejandro Pérez Reyes',
                'clinic_name' => 'Infantident',
                'specialty' => 'Odontopediatría',
                'city' => 'Mérida',
                'address' => 'Torre Médica Cénit, Calle 15 x 18 y 22, Consultorio 1002, Fracc. Altabrisa, 97130 Mérida',
                'phone' => '9992520209',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"Altabrisa","website":"http:\/\/infantident.blogspot.com\/","source_channel":"google-search","notes":"Maestro Odontopediatría UADY; Torre Cénit"}',
            ],
            [
                'name' => 'Dra. Yarieli Ramírez Reyes',
                'clinic_name' => 'Dentikids',
                'specialty' => 'Odontopediatría',
                'city' => 'Mérida',
                'address' => 'Calle 35 No. 346 x 26 y 28, Col. Tanlum, Mérida',
                'phone' => '9991303839',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"Tanlum","instagram":"@dentikidsmid","source_channel":"google-search","notes":"Odontopediatra titular; IG activo dentikidsmid"}',
            ],
            [
                'name' => 'Smile Kids',
                'clinic_name' => 'Smile Kids',
                'specialty' => 'Odontopediatría',
                'city' => 'Mérida',
                'address' => 'Calle 5 #313 x 10 y 12, Col. San Carlos, Mérida',
                'phone' => '9992588650',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"San Carlos","source_channel":"google-search","notes":"Consultorio odontopediátrico pequeño"}',
            ],
            [
                'name' => 'Clínica Dental For Kids',
                'clinic_name' => 'Clínica Dental For Kids',
                'specialty' => 'Odontopediatría',
                'city' => 'Mérida',
                'address' => 'Calle 67-B #181 x 120 y 122, Col. Yucalpetén, Mérida',
                'phone' => '9993932102',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"Yucalpetén","source_channel":"google-search","notes":"Odontopediatría; consultorio barrio medio"}',
            ],
            [
                'name' => 'Dra. Alejandra Medina Alamilla',
                'clinic_name' => 'Consultorio Dra. Alejandra Medina',
                'specialty' => 'Odontopediatría',
                'city' => 'Mérida',
                'address' => 'Calle 1-D #247 entre 36 y 38, Col. Campestre, Mérida',
                'phone' => '9993868589',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"Campestre","source_channel":"google-search","notes":"Odontopediatra titular; colonia Campestre"}',
            ],
            [
                'name' => 'Dr. Víctor Manuel Novelo Álvarez',
                'clinic_name' => 'Consultorio Dr. Víctor Novelo',
                'specialty' => 'Endodoncia',
                'city' => 'Mérida',
                'address' => 'Calle 31-A #237, Mérida Centro',
                'phone' => '9999288390',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"Centro","source_channel":"google-search","notes":"Endodoncista titular; consultorio Centro"}',
            ],
            [
                'name' => 'Dr. Javier A. Flores Suárez',
                'clinic_name' => 'CEDIMMONT Endodoncia',
                'specialty' => 'Endodoncia',
                'city' => 'Mérida',
                'address' => 'CEDIMMONT, Francisco de Montejo, Mérida',
                'phone' => '9999250262',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"Francisco de Montejo","source_channel":"google-search","notes":"C.D.E.E. endodoncia; consultorio en Francisco de Montejo"}',
            ],
            [
                'name' => 'Dra. Ana Karen Basulto Cruz',
                'clinic_name' => 'Consultorio Dra. Ana Karen Basulto',
                'specialty' => 'Endodoncia',
                'city' => 'Mérida',
                'address' => 'Mérida Centro',
                'phone' => '9991090910',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"Centro","source_channel":"google-search","notes":"Endodoncista titular"}',
            ],
            [
                'name' => 'Dr. José J. Rivera Maldonado',
                'clinic_name' => 'Consultorio Dr. José Rivera',
                'specialty' => 'Endodoncia',
                'city' => 'Mérida',
                'address' => 'Mérida Centro',
                'phone' => '9993387901',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"Centro","source_channel":"google-search","notes":"Endodoncista titular"}',
            ],
            [
                'name' => 'Dra. Mirely Noemi Ucan López',
                'clinic_name' => 'Especialidades Dentales Mid',
                'specialty' => 'Endodoncia',
                'city' => 'Mérida',
                'address' => 'Calle 76 No. 455 x Bis, Centro, 97000 Mérida',
                'phone' => '9999289368',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"Centro","source_channel":"google-search","notes":"Endodoncia + odontopediatría + implantes; UADY"}',
            ],
            [
                'name' => 'Dr. Pedro Hernán Rosel Quijano',
                'clinic_name' => 'Clínica Dental Rosel Quijano',
                'specialty' => 'Implantología',
                'city' => 'Mérida',
                'address' => 'Calle 7 No. 544 x 24 y 24a, Av. Altabrisa, Col. Maya, 97134 Mérida',
                'phone' => '9992760615',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"Maya","website":"https:\/\/dentalrosel.com\/","source_channel":"website","notes":"30+ años; ortodoncia + implantes + endo familia Rosel; frente Hospital Alta Especialidad"}',
            ],
            [
                'name' => 'Dra. Arelly Carrillo',
                'clinic_name' => 'HC Odontólogos',
                'specialty' => 'Periodoncia',
                'city' => 'Mérida',
                'address' => 'Col. Montes de Amé, Mérida',
                'phone' => '9991991384',
                'has_whatsapp' => true,
                'email' => 'citas@hcodontologos.com',
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"Montes de Amé","instagram":"@dra.arellycarrillo","website":"https:\/\/www.hcodontologos.com\/","source_channel":"website","notes":"Equipo multidisciplinario; 20+ años; periodoncia + orto + estética"}',
            ],
            [
                'name' => 'Dra. Cynthia Watson',
                'clinic_name' => 'Consultorio Dra. Cynthia Watson',
                'specialty' => 'Periodoncia',
                'city' => 'Mérida',
                'address' => 'Calle 16 #237 x 5 y 7, Fracc. Vista Alegre Norte, Mérida',
                'phone' => '9901913966',
                'has_whatsapp' => true,
                'email' => 'drawatsonp@gmail.com',
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"Vista Alegre Norte","instagram":"@drawatson_periodoncia","source_channel":"google-search","notes":"Periodoncista UNITEC + diplomado medicina bucal; IG activo"}',
            ],
            [
                'name' => 'Dra. Lourdes Becerril',
                'clinic_name' => 'Consultorio Dra. Lourdes Becerril',
                'specialty' => 'Periodoncia',
                'city' => 'Mérida',
                'address' => 'Mérida Centro',
                'phone' => '9993742028',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"Centro","source_channel":"google-search","notes":"Periodoncista titular"}',
            ],
            [
                'name' => 'Dra. Debra Baqueiro',
                'clinic_name' => 'Consultorio Dra. Debra Baqueiro',
                'specialty' => 'Periodoncia',
                'city' => 'Mérida',
                'address' => 'Mérida Centro',
                'phone' => '9992920825',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"Centro","source_channel":"google-search","notes":"Periodoncista titular"}',
            ],
            [
                'name' => 'Dra. Paola Haydee Cedillo de la Peña',
                'clinic_name' => 'Consultorio Dra. Paola Cedillo',
                'specialty' => 'Periodoncia',
                'city' => 'Mérida',
                'address' => 'Mérida Centro',
                'phone' => '9992890790',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"Centro","source_channel":"google-search","notes":"Periodoncista titular"}',
            ],
            [
                'name' => 'Dr. Juan Simón Gómez Vera',
                'clinic_name' => 'Consultorio Dr. Juan Simón Gómez',
                'specialty' => 'Periodoncia',
                'city' => 'Mérida',
                'address' => 'Mérida Centro',
                'phone' => '9992334400',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"Centro","source_channel":"google-search","notes":"Periodoncista titular"}',
            ],
            [
                'name' => 'Dr. Rodrigo Flores Flores',
                'clinic_name' => 'Consultorio Dr. Rodrigo Flores',
                'specialty' => 'Cirugía Maxilofacial',
                'city' => 'Mérida',
                'address' => 'Hospital Star Médica, Consultorio 720, Altabrisa, Mérida',
                'phone' => '9999436010',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"Altabrisa","source_channel":"google-search","notes":"Implantes + terceros molares + ATM + ortognática; Star Médica"}',
            ],
            [
                'name' => 'Dr. Alejandro López Pascual',
                'clinic_name' => 'Consultorio Dr. Alejandro López Pascual',
                'specialty' => 'Cirugía Maxilofacial',
                'city' => 'Mérida',
                'address' => 'Calle 29 #210 x 20, García Ginerés, Mérida',
                'phone' => '9999208683',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"García Ginerés","source_channel":"google-search","notes":"Cirugía maxilofacial integral + implantes + labio hendido"}',
            ],
            [
                'name' => 'Dr. Juan José Castro Mosqueda',
                'clinic_name' => 'Consultorio Dr. Juan José Castro',
                'specialty' => 'Cirugía Maxilofacial',
                'city' => 'Mérida',
                'address' => 'Av. Yucatán #351 x 23 y 40, Col. Los Pinos, Mérida',
                'phone' => '9996025731',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"Los Pinos","source_channel":"google-search","notes":"Cirujano maxilofacial; consultorio Los Pinos"}',
            ],
            [
                'name' => 'Dra. Leticia Medina Esquivel',
                'clinic_name' => 'Consultorio Dra. Leticia Medina',
                'specialty' => 'Cirugía Maxilofacial',
                'city' => 'Mérida',
                'address' => 'Col. México Norte, Mérida',
                'phone' => '9995934003',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"México Norte","source_channel":"google-search","notes":"Maxilofacial México Norte zona media-alta"}',
            ],
            [
                'name' => 'DENTIUM',
                'clinic_name' => 'DENTIUM',
                'specialty' => 'Cirugía Maxilofacial',
                'city' => 'Mérida',
                'address' => 'Calle 61 #275 entre 34 y 36, Local #5, San Ramón Norte, Mérida',
                'phone' => '9993162066',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"San Ramón Norte","source_channel":"google-search","notes":"Cirugía maxilofacial + implantes; consultorio local"}',
            ],
            [
                'name' => 'DENTALCOE NORTE',
                'clinic_name' => 'DENTALCOE NORTE',
                'specialty' => 'Cirugía Maxilofacial',
                'city' => 'Mérida',
                'address' => 'Av. Líbano #51-A int 6 x 1H y 3, México Norte, Mérida',
                'phone' => '9993142360',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"México Norte","source_channel":"google-search","notes":"Maxilofacial norte; consultorio pequeño"}',
            ],
            [
                'name' => 'David',
                'clinic_name' => 'Yucatan Dental Clinic',
                'specialty' => 'Implantología',
                'city' => 'Mérida',
                'address' => 'Calle 24 97E x 19 y 21, Col. Itzimná, 97100 Mérida',
                'phone' => '9991447409',
                'has_whatsapp' => true,
                'email' => 'david@yucatandentalclinic.com',
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"Itzimná","website":"https:\/\/yucatandentalclinic.com\/","source_channel":"website","notes":"All-On-4 + zirconia + carillas; bilingüe ES\/EN; turismo dental expats"}',
            ],
            [
                'name' => 'Dra. Herrera',
                'clinic_name' => 'Sanchez & Herrera Ortodoncia',
                'specialty' => 'Ortodoncia',
                'city' => 'Mérida',
                'address' => 'Calle 77 #210, Col. Montes de Amé, 97115 Mérida',
                'phone' => '9994587644',
                'has_whatsapp' => true,
                'email' => 'shortodoncia00@gmail.com',
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"Montes de Amé","instagram":"@sanchezherreraortodoncia","website":"https:\/\/www.ortodonciayucatan.com\/","source_channel":"website","notes":"Autoligado + linguales + alineadores; pareja de ortodoncistas"}',
            ],
            [
                'name' => 'Sonrisa de Angle',
                'clinic_name' => 'Sonrisa de Angle',
                'specialty' => 'Ortodoncia',
                'city' => 'Mérida',
                'address' => 'Calle 51 #337, Col. Xcumpich, Mérida',
                'phone' => '9993172240',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"Xcumpich","website":"https:\/\/sonrisadeangle.com\/","source_channel":"website","notes":"Ortodoncia especializada Xcumpich zona norte"}',
            ],
            [
                'name' => 'Dra. Beatriz Barceló',
                'clinic_name' => 'BB Dental',
                'specialty' => 'Odontopediatría',
                'city' => 'Mérida',
                'address' => 'Calle 24 No. 97-G entre 17 y 21, Col. Itzimná, Mérida',
                'phone' => '9992716620',
                'has_whatsapp' => true,
                'email' => 'bbarcelo42@gmail.com',
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"Itzimná","source_channel":"google-search","notes":"Odontopediatría desde bebés + ortopedia dentofacial; Itzimná"}',
            ],
            [
                'name' => 'Dr. Pedro Durán Sosa',
                'clinic_name' => 'Dr. Pedro Durán Smile Designer',
                'specialty' => 'Odontología Estética',
                'city' => 'Mérida',
                'address' => 'Calle 23 No. 320, Plaza Town Square Local 28, Col. San Ramón, 97138 Mérida',
                'phone' => '9994067404',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"San Ramón","source_channel":"google-search","notes":"Diseño sonrisa + carillas + Invisalign; imagen premium estética"}',
            ],
            [
                'name' => 'Dr. Javier Cámara Patrón',
                'clinic_name' => 'Quality Dental Services García Ginerés',
                'specialty' => 'Odontología General',
                'city' => 'Mérida',
                'address' => 'Calle 17 x 8 y 10, Col. García Ginerés, Mérida',
                'phone' => '9999253399',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"García Ginerés","website":"https:\/\/www.qualitydental.mx\/","source_channel":"website","notes":"Multiespecialidad familiar; orto + perio + endo + pediátrica"}',
            ],
            [
                'name' => 'DTDental Chenkú',
                'clinic_name' => 'DTDental Chenkú',
                'specialty' => 'Odontología General',
                'city' => 'Mérida',
                'address' => 'Calle 19 #201 por 34 y 34-A, Residencial del Norte Chenkú, Mérida',
                'phone' => '9991128075',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"Chenkú","website":"https:\/\/dtdental.com.mx\/","source_channel":"website","notes":"Consultorio accesible zona norte Chenkú"}',
            ],
            [
                'name' => 'Dra. Cecilia Pérez',
                'clinic_name' => 'Dentaly',
                'specialty' => 'Odontología General',
                'city' => 'Mérida',
                'address' => 'C. 50 657H entre 95 y 97, Dolores Otero, 97270 Mérida',
                'phone' => '9999606652',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"Dolores Otero","website":"https:\/\/dentaly.website\/","source_channel":"website","notes":"Odontología integral + perio + orto; Dr. Cecilia Pérez titular"}',
            ],
            [
                'name' => 'Dental System MID',
                'clinic_name' => 'Dental System MID',
                'specialty' => 'Implantología',
                'city' => 'Mérida',
                'address' => 'Calle 39 #336 x 52, Col. Francisco de Montejo, 97203 Mérida',
                'phone' => '9999470405',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"Francisco de Montejo","website":"https:\/\/www.dentalsystemmid.com\/","source_channel":"website","notes":"26+ años exp; libre de metal; 3 años de garantía"}',
            ],
            [
                'name' => 'Unidad Médica García Ginerés',
                'clinic_name' => 'Unidad Médica García Ginerés',
                'specialty' => 'Odontología General',
                'city' => 'Mérida',
                'address' => 'Calle 27, Col. García Ginerés, Mérida',
                'phone' => '9999259614',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"García Ginerés","source_channel":"google-search","notes":"Unidad médica pequeña con endodoncista; 6-10 empleados"}',
            ],
            [
                'name' => 'Consultorio Dental del Norte',
                'clinic_name' => 'Consultorio Dental del Norte',
                'specialty' => 'Odontología General',
                'city' => 'Mérida',
                'address' => 'Calle 17 #278 por 20H y 20I, Jardines del Norte, 97139 Mérida',
                'phone' => '9999438437',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"Jardines del Norte","source_channel":"google-search","notes":"Consultorio privado Jardines del Norte zona norte"}',
            ],
            [
                'name' => 'Dra. Joanna Lucely Pérez Peraza',
                'clinic_name' => 'Consultorio Dra. Joanna Pérez',
                'specialty' => 'Odontopediatría',
                'city' => 'Mérida',
                'address' => 'Av. Remigio Aguilar No. 256 entre 26 y 28, Col. Miguel Alemán, Mérida',
                'phone' => '9992875905',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"Miguel Alemán","source_channel":"google-search","notes":"Odontología + odontopediatría; Miguel Alemán"}',
            ],
            [
                'name' => 'Dr. José David Lara Montejo',
                'clinic_name' => 'Consultorio Dr. José David Lara',
                'specialty' => 'Odontología General',
                'city' => 'Mérida',
                'address' => 'Mérida Centro',
                'phone' => '9999282528',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"Centro","source_channel":"google-search","notes":"Odontólogo general titular"}',
            ],
            [
                'name' => 'Diseño Dental Profesional',
                'clinic_name' => 'Diseño Dental Profesional',
                'specialty' => 'Odontología Estética',
                'city' => 'Mérida',
                'address' => 'Calle 39 No. 320B x 34 y 32A, Col. San Ramón Norte, Mérida',
                'phone' => '9999489001',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"San Ramón Norte","website":"http:\/\/www.disenodental.com\/","source_channel":"website","notes":"Diseño digital sonrisa; zona San Ramón Norte"}',
            ],
            [
                'name' => 'Clínica Dental Campestre',
                'clinic_name' => 'Clínica Dental Campestre',
                'specialty' => 'Endodoncia',
                'city' => 'Mérida',
                'address' => 'Calle 1D #247, Col. Campestre, Mérida',
                'phone' => '9995014177',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"Campestre","source_channel":"google-search","notes":"Endodoncia + consulta $300; Campestre"}',
            ],
            [
                'name' => 'B Médica',
                'clinic_name' => 'B Médica',
                'specialty' => 'Implantología',
                'city' => 'Mérida',
                'address' => 'Edificio 33.16, Calle 16 #481 x 33, Dpto. 3C, Montebello, 97113 Mérida',
                'phone' => '9991653330',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"Montebello","source_channel":"google-search","notes":"57 opiniones implantes; zona Montebello premium"}',
            ],
            [
                'name' => 'Grupo Dental Bosques',
                'clinic_name' => 'Grupo Dental Bosques',
                'specialty' => 'Odontología General',
                'city' => 'Mérida',
                'address' => 'Calle 36 Diagonal #306, Col. Montebello, Mérida',
                'phone' => '9999242710',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"Montebello","source_channel":"google-search","notes":"Consulta privada + seguros; zona residencial Montebello"}',
            ],
            [
                'name' => 'Dr. Alejandro Mompeller Rivero',
                'clinic_name' => 'Clínica Dental Conkal',
                'specialty' => 'Odontología General',
                'city' => 'Conkal',
                'address' => 'Calle 22 #401 c x 57, Local 9, Conkal, Yucatán',
                'phone' => '9991263380',
                'has_whatsapp' => true,
                'email' => 'dralemompe@gmail.com',
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"Conkal Centro","instagram":"@dental_conkal","website":"https:\/\/clinicadentalconkal.mx\/","rating":"4.9","source_channel":"website","notes":"Titular único; 4.9 rating; IG activo; egresado UCM Habana"}',
            ],
            [
                'name' => 'Ocaña Clínica Dental Conkal',
                'clinic_name' => 'Ocaña Clínica Dental Conkal',
                'specialty' => 'Ortodoncia',
                'city' => 'Conkal',
                'address' => 'Calle 20 #106 entre 21 y 23, Centro, 97345 Conkal',
                'phone' => '9994329109',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"Conkal Centro","source_channel":"google-search","notes":"Ortodoncia accesible; consultorio Conkal centro"}',
            ],
            [
                'name' => 'Dr. Javier Cámara Patrón',
                'clinic_name' => 'Quality Dental Altabrisa',
                'specialty' => 'Odontología Estética',
                'city' => 'Mérida',
                'address' => 'Calle 26 x 7 y 15, Altabrisa Med Plaza frente a Star Médica, Altabrisa, Mérida',
                'phone' => '9991679444',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"Altabrisa","website":"https:\/\/www.qualitydental.mx\/","source_channel":"website","notes":"Sede Altabrisa Med Plaza; diseño sonrisa + orto + pediátrica"}',
            ],
            [
                'name' => 'Dental Clinic Progreso',
                'clinic_name' => 'Dental Clinic Progreso',
                'specialty' => 'Odontología General',
                'city' => 'Progreso',
                'address' => 'Clínica PROMEDICA, Calle 29 consultorio #204 entre 76 y 78, Col. Centro, 97320 Progreso',
                'phone' => '9991366406',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"Progreso Centro","source_channel":"google-search","notes":"Consultorio Progreso centro zona turística"}',
            ],
            [
                'name' => 'Dr. Gibran Zapata Ceballos',
                'clinic_name' => 'Dentista Gibran Zapata',
                'specialty' => 'Odontología General',
                'city' => 'Progreso',
                'address' => 'Calle 29 #197A, Progreso Centro, Yucatán',
                'phone' => '9993633522',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"Progreso Centro","source_channel":"google-search","notes":"Odontólogo titular solo; horario extendido sábados"}',
            ],
            [
                'name' => 'Dental Care Center Progreso',
                'clinic_name' => 'Dental Care Center Progreso',
                'specialty' => 'Odontología General',
                'city' => 'Progreso',
                'address' => 'Calle 29 #149, Progreso, Yucatán',
                'phone' => '9994918772',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mid-dedup-20260422","colonia":"Progreso Centro","source_channel":"google-search","notes":"Consultorio dental Progreso centro"}',
            ],
        ];

        $this->command->info('Insertando ' . count($prospects) . ' dentistas del pilot (research-dentistas-mid-dedup-20260422)...');

        $inserted = 0;
        $skipped = 0;

        foreach ($prospects as $prospect) {
            // Idempotencia por phone (último match) — no volver a insertar si ya existe
            $existing = Prospect::where('phone', $prospect['phone'])->first();
            if ($existing) {
                $skipped++;
                continue;
            }

            Prospect::create(array_merge($prospect, [
                'source' => 'prospecting', // matches SendProspectEmails cron filter
                'status' => 'new',
                'assigned_to_sales_rep_id' => 100,
                'contact_day' => 0,
                'next_contact_at' => now()->addHour(),
                'outreach_started_at' => now(),
            ]));
            $inserted++;
        }

        $this->command->info("✓ {$inserted} insertados | {$skipped} duplicados saltados | Total en seeder: " . count($prospects));
    }
}
