<?php

namespace Database\Seeders;

use App\Models\Prospect;
use Illuminate\Database\Seeder;

/**
 * Generated seeder — batch research-dentistas-mty-dedup-20260422.
 *
 * 56 dentistas descubiertos vía WebSearch + WebFetch, deduplicados contra prod.
 * Todos con teléfono MX de 10 dígitos. Asignados a Omar (user_id=100) con
 * source='prospecting' para que el cron send-prospect-emails los tome automático.
 * El batch identifier vive en notes.batch = 'research-dentistas-mty-dedup-20260422' para analytics.
 *
 * Ejecutar: php artisan db:seed --class=ProspectDentistasMTYPilotSeeder --force
 */
class ProspectDentistasMTYPilotSeeder extends Seeder
{
    public function run(): void
    {
        $prospects = [
            [
                'name' => 'Health and Wellness Dental Center',
                'clinic_name' => 'Health and Wellness Dental Center',
                'specialty' => 'Odontología General',
                'city' => 'San Pedro Garza García',
                'address' => 'Río Manzanares 415-C, Col. Del Valle, San Pedro Garza García',
                'phone' => '8183359747',
                'has_whatsapp' => false,
                'email' => 'Info@hwdentalcenter.com',
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Del Valle","website":"https:\/\/www.hwdentalcenter.com\/","source_channel":"google-search","notes":"35 años de experiencia; 5 dentistas; consultorio multidisciplinario"}',
            ],
            [
                'name' => 'Dra. Gabriela Chapa Arizpe',
                'clinic_name' => 'Zurit Especialistas Odontológicos',
                'specialty' => 'Periodoncia',
                'city' => 'San Pedro Garza García',
                'address' => 'Río Guadalquivir 112 Ote, Col. Del Valle, San Pedro Garza García, 66220',
                'phone' => '8126117832',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Del Valle","instagram":"@zurit.dentalstudio","website":"https:\/\/www.zurit.com.mx","source_channel":"google-search","notes":"25+ años exp; certificada CMP; única doctora titular"}',
            ],
            [
                'name' => 'Dr. Jorge Alonsoguerra Carrasco',
                'clinic_name' => 'Dentaltek Clínica Dental',
                'specialty' => 'Implantología',
                'city' => 'Monterrey',
                'address' => 'Blvd. Puerta del Sol 320B, Colinas de San Jerónimo 1er Sector, Monterrey',
                'phone' => '8117984513',
                'has_whatsapp' => true,
                'email' => 'dentaltek.citas@gmail.com',
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Colinas de San Jerónimo","website":"https:\/\/dentaltekmonterrey.com","source_channel":"google-search","notes":"20+ años implantología oral; 1 doctor titular"}',
            ],
            [
                'name' => 'Dr. Rodolfo Mendoza Rocha',
                'clinic_name' => 'Codantis',
                'specialty' => 'Odontología General',
                'city' => 'Monterrey',
                'address' => 'C. 15a Avenida 948-2 Sector, Colonial Cumbres, 64610 Monterrey',
                'phone' => '8183114358',
                'has_whatsapp' => false,
                'email' => 'drrodolfo@codanits.com.mx',
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Cumbres","instagram":"@codantis_","website":"https:\/\/codantis.com.mx","source_channel":"google-search","notes":"2 doctores titulares (Dr. Mendoza + Dra. Pérez Chapa); 1 sede"}',
            ],
            [
                'name' => 'Dr. Daniel Fernández',
                'clinic_name' => 'Dr. Daniel Fernández Periodoncista',
                'specialty' => 'Periodoncia',
                'city' => 'Monterrey',
                'address' => 'Zona del Obispado, Monterrey',
                'phone' => '8118809351',
                'has_whatsapp' => true,
                'email' => 'periodoncista.mx@gmail.com',
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Obispado","instagram":"@periodonciaimplantesmty","website":"https:\/\/periodoncista.mx","source_channel":"google-search","notes":"15+ años exp; egresado UANL; certificado CMP"}',
            ],
            [
                'name' => 'Dr. Fernando Iván Moreno',
                'clinic_name' => 'All Orthodontic',
                'specialty' => 'Ortodoncia',
                'city' => 'San Nicolás de los Garza',
                'address' => 'Calle Cerro del Potosí 200, Las Puentes 2do Sector, San Nicolás de los Garza, 66460',
                'phone' => '8112392619',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Las Puentes","website":"https:\/\/allorthodontic.com","source_channel":"google-search","notes":"12+ años exp; ortodoncia + ortopedia maxilar; 1 sede"}',
            ],
            [
                'name' => 'Dr. Orlando Eguía Bernal',
                'clinic_name' => 'ODAE Clínica Dental',
                'specialty' => 'Odontología General',
                'city' => 'Monterrey',
                'address' => 'Av. Simón Bolívar 789, Plaza Bolívar Piso 4 Of. 8, Col. Obispado, Monterrey',
                'phone' => '8125178783',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Obispado","instagram":"@clinicaodae","website":"https:\/\/odae.com.mx","source_channel":"google-search","notes":"Odontología familiar; 4 doctores; borderline 2 sucursales"}',
            ],
            [
                'name' => 'Dr. Sergio Eduardo Soto Delgado',
                'clinic_name' => 'Soto Center Pueblo Serena',
                'specialty' => 'Odontología General',
                'city' => 'Monterrey',
                'address' => 'Av. San Pío X 1217, Pío X, 64710 Monterrey',
                'phone' => '8135787289',
                'has_whatsapp' => true,
                'email' => 'info@sotocenter.com',
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Pío X","website":"https:\/\/sotocenter.com","source_channel":"google-search","notes":"Dr. Soto titular; 2 sucursales total; amplia oferta"}',
            ],
            [
                'name' => 'Dra. Adela A. Villarreal González',
                'clinic_name' => 'SmileFix Monterrey',
                'specialty' => 'Odontopediatría',
                'city' => 'Monterrey',
                'address' => 'Av. Simón Bolívar 253 2do piso Local 204, Chepevera, 64030 Monterrey',
                'phone' => '8137143627',
                'has_whatsapp' => false,
                'email' => 'contacto@smilefix.com.mx',
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Chepevera","website":"https:\/\/www.smilefix.com.mx","source_channel":"google-search","notes":"5 especialistas; 1 sede; niños + ortodoncia + implantes"}',
            ],
            [
                'name' => 'Dra. Eugenia Lartigue Martínez',
                'clinic_name' => 'Dra. Eugenia Lartigue (OrtoDent)',
                'specialty' => 'Ortodoncia',
                'city' => 'Monterrey',
                'address' => 'Av. Lázaro Cárdenas 1111 Local 12 PB, Col. Las Brisas, 64780 Monterrey',
                'phone' => '8146240128',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Las Brisas","website":"https:\/\/dentistaeugenialartigue.com","source_channel":"google-search","notes":"1 doctora titular; odontología general + ortodoncia"}',
            ],
            [
                'name' => 'Dr. Héctor Orozco Saldívar',
                'clinic_name' => 'Face & Bite Clinic',
                'specialty' => 'Cirugía Maxilofacial',
                'city' => 'Monterrey',
                'address' => 'Bolivia 103 Piso 7 Consultorio 0708, Balcones de Galerías, Monterrey',
                'phone' => '8186929623',
                'has_whatsapp' => false,
                'email' => 'orozcocmf_27@outlook.com',
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Balcones de Galerías","website":"https:\/\/www.maxilofacialnuevoleon.com","source_channel":"google-search","notes":"Certificado Consejo Mexicano CMF; 1er lugar nacional 2016"}',
            ],
            [
                'name' => 'Dr. Gerardo Terán García',
                'clinic_name' => 'Centro Médico Dental Tecnológico (Dentistas Teran)',
                'specialty' => 'Ortodoncia',
                'city' => 'Monterrey',
                'address' => 'Arquitectos 102, Col. Tecnológico, 64700 Monterrey',
                'phone' => '8183584994',
                'has_whatsapp' => false,
                'email' => 'citas@dentistasteran.com',
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Tecnológico","instagram":"@dentistasteranmonterrey","website":"https:\/\/dentistasteran.com.mx","source_channel":"google-search","notes":"Familia Terán; 35+ años operando; consultorio clásico"}',
            ],
            [
                'name' => 'Marco A. García Lazcano',
                'clinic_name' => 'Dentalmedics',
                'specialty' => 'Odontología General',
                'city' => 'Guadalupe',
                'address' => 'Avenida Pablo Livas 7240, Residencial Santa María, Guadalupe',
                'phone' => '8122612377',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Residencial Santa María","instagram":"@dentalmedics_","website":"https:\/\/www.dentalmedics.mx","source_channel":"google-search","notes":"Responsable sanitario Dr. García; borderline 2 sucursales"}',
            ],
            [
                'name' => 'DentaLumex',
                'clinic_name' => 'DentaLumex',
                'specialty' => 'Odontología General',
                'city' => 'Monterrey',
                'address' => 'Ave. Francisco I. Madero 1035, Col. Centro, Monterrey',
                'phone' => '8183750189',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Centro","instagram":"@dentalumex","website":"https:\/\/dentalumex.com","source_channel":"google-search","notes":"Odontología integral; 1 sede; titular C.D. Antonio Alvarado"}',
            ],
            [
                'name' => 'Dr. Carlos Reyna',
                'clinic_name' => 'CR Especialidades Dentales',
                'specialty' => 'Implantología',
                'city' => 'Monterrey',
                'address' => 'Consultorio en Monterrey - verificar dirección en llamada',
                'phone' => '8123877104',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Obispado","website":"https:\/\/dentista-monterrey.com","source_channel":"google-search","notes":"5 especialistas (CMF, odontopediatría, endo, perio, rehab); 1 sede"}',
            ],
            [
                'name' => 'Dra. Natalia Denisse Gómez Servín',
                'clinic_name' => 'Dra. Natalia Gómez Ortodoncia',
                'specialty' => 'Ortodoncia',
                'city' => 'Monterrey',
                'address' => 'Plaza Vía Puerta de Hierro, Av. Paseo de los Leones y Av. Puerta de Hierro, 64349 Monterrey',
                'phone' => '8121927369',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Puerta de Hierro","instagram":"@dra.natalia_orthodontics","website":"https:\/\/dranataliagomez.com","source_channel":"google-search","notes":"1 doctora titular; certificada Invisalign; 550+ pacientes"}',
            ],
            [
                'name' => 'Dra. Claudia',
                'clinic_name' => 'Clínica Dental Smile',
                'specialty' => 'Odontología General',
                'city' => 'Monterrey',
                'address' => 'Paseo de los Leones 1613-1, Cumbres, Monterrey',
                'phone' => '8113651610',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Cumbres","instagram":"@dentalsmilemty","website":"https:\/\/dental-smile.mx","source_channel":"google-search","notes":"12+ años; familiar; 9 especialidades; 1 sede"}',
            ],
            [
                'name' => 'Dr. Manuel de la Rosa',
                'clinic_name' => 'Drs. De la Rosa',
                'specialty' => 'Periodoncia',
                'city' => 'San Pedro Garza García',
                'address' => 'Calz. San Pedro 1000, Fuentes del Valle, San Pedro Garza García',
                'phone' => '8184018120',
                'has_whatsapp' => false,
                'email' => 'drmanuel@drmdelarosa.com',
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Fuentes del Valle","website":"https:\/\/www.drmdelarosa.com","source_channel":"google-search","notes":"40+ años exp; periodoncia + cirugía plástica periodontal; también Cancún"}',
            ],
            [
                'name' => 'Dra. Clau López',
                'clinic_name' => 'Omme Care',
                'specialty' => 'Ortodoncia',
                'city' => 'San Pedro Garza García',
                'address' => 'Av. Vasconcelos 430 Local 109 Plaza Tribeca PB, Del Valle, 66220 San Pedro Garza García',
                'phone' => '8137545454',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Del Valle","instagram":"@omme.care","website":"https:\/\/www.ommecare.mx","source_channel":"google-search","notes":"Dra. López + Dra. Yari Rosas cofundadoras; 5 dras en equipo; 1 sede"}',
            ],
            [
                'name' => 'Dental Sauces San Pedro',
                'clinic_name' => 'Dental Sauces San Pedro',
                'specialty' => 'Odontología General',
                'city' => 'San Pedro Garza García',
                'address' => 'Emilio Carranza 822 Pte, Col. Los Sauces 2do Sector, 66237 San Pedro Garza García',
                'phone' => '8183385632',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Los Sauces","instagram":"@dentalsaucessanpedro","source_channel":"google-search","notes":"Abierto sábados y domingos; 1 sede"}',
            ],
            [
                'name' => 'Dra. Mónica Huesca Del Toro',
                'clinic_name' => 'Dra. Mónica Huesca Dentista Infantil',
                'specialty' => 'Odontopediatría',
                'city' => 'Monterrey',
                'address' => 'Miguel Hidalgo 2532 Edificio Médico de Especialistas 2do piso Of. 212, Obispado, 64060 Monterrey',
                'phone' => '8112388724',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Obispado","website":"https:\/\/www.doctoranytime.mx","source_channel":"google-search","notes":"Maestría UANL odontopediatría; certificada CMOP"}',
            ],
            [
                'name' => 'Dra. Selenia Medina',
                'clinic_name' => 'Dra. Selenia Medina Odontopediatra',
                'specialty' => 'Odontopediatría',
                'city' => 'Monterrey',
                'address' => 'Alejandro de Rodas 5735, Col. Cumbres, 64349 Monterrey',
                'phone' => '8110912937',
                'has_whatsapp' => true,
                'email' => 'contacto@draselenia.com',
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Cumbres","instagram":"@odontopediatra_drasele","website":"https:\/\/draselenia.com","source_channel":"google-search","notes":"10+ años; certificada CNOP; niños + bebés"}',
            ],
            [
                'name' => 'Dra. Laura Calderón',
                'clinic_name' => 'Dra. Laura Calderón Odontología Infantil',
                'specialty' => 'Odontopediatría',
                'city' => 'Monterrey',
                'address' => 'Loma Grande 2717 Consultorio M2, Col. Lomas de San Francisco, 64710 Monterrey',
                'phone' => '8110175129',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Lomas de San Francisco","instagram":"@dentista.laura","website":"https:\/\/www.odontopediatramty.com","source_channel":"google-search","notes":"1 doctora titular; especialista niños"}',
            ],
            [
                'name' => 'Dra. Claudia Elizalde Molina',
                'clinic_name' => 'Periodoncia Monterrey (Dra. Claudia Elizalde)',
                'specialty' => 'Periodoncia',
                'city' => 'San Pedro Garza García',
                'address' => 'Río Salinas 235, Col. del Valle, San Pedro Garza García',
                'phone' => '8183560612',
                'has_whatsapp' => true,
                'email' => 'info@periodonciamonterrey.com.mx',
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Del Valle","instagram":"@dra.clau_elizalde","website":"https:\/\/periodonciamonterrey.com.mx","source_channel":"google-search","notes":"Certificada; periodoncia + ortodoncia + implantes; 1 doctora titular"}',
            ],
            [
                'name' => 'Dr. Luis A. González',
                'clinic_name' => 'Orthostetics Dental Clinic',
                'specialty' => 'Ortodoncia',
                'city' => 'Monterrey',
                'address' => 'Plaza Punto Lomas, Av. Lomas del Valle 430 Piso 3 Local 6, Monterrey',
                'phone' => '8117444440',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Lomas del Valle","instagram":"@orthosteticsdentalclinic","website":"https:\/\/orthostetics.com","source_channel":"google-search","notes":"Dr. Luis + Dra. Erika González titulares; 6 doctoras totales; 1 sede"}',
            ],
            [
                'name' => 'Dental Clinique Monterrey',
                'clinic_name' => 'Dental Clinique Monterrey',
                'specialty' => 'Odontología General',
                'city' => 'Monterrey',
                'address' => 'Av. Eugenio Garza Sada 6706, Col. Lagos del Bosque, Monterrey',
                'phone' => '8131035305',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Lagos del Bosque","website":"https:\/\/www.dentalcliniquemty.com","source_channel":"google-search","notes":"Maestría UANL ortodoncia; 15+ años exp; sobre Garza Sada"}',
            ],
            [
                'name' => 'Zental Odontología Sertoma',
                'clinic_name' => 'Zental Odontología Sertoma',
                'specialty' => 'Odontología Estética',
                'city' => 'Monterrey',
                'address' => 'Av. Sertoma 205, Sertoma, 64718 Monterrey',
                'phone' => '8116319812',
                'has_whatsapp' => true,
                'email' => 'zentalmx@gmail.com',
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Sertoma","instagram":"@zentalmx","website":"https:\/\/www.zental.mx","source_channel":"google-search","notes":"2 sedes; 39K seguidores IG; diseño sonrisa + carillas"}',
            ],
            [
                'name' => 'Mapa Dental',
                'clinic_name' => 'Mapa Dental',
                'specialty' => 'Odontología General',
                'city' => 'Monterrey',
                'address' => 'Espacio Cumbres, Av. Cumbres Madeira 691 Plaza Bendetti Local 9, 64349 Monterrey',
                'phone' => '8122023087',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Cumbres Madeira","instagram":"@mapadentalmx","source_channel":"google-search","notes":"Zona poniente; 1 sede"}',
            ],
            [
                'name' => 'DENTALEO',
                'clinic_name' => 'DENTALEO',
                'specialty' => 'Odontología Estética',
                'city' => 'San Nicolás de los Garza',
                'address' => 'San Nicolás de los Garza (ubicación a confirmar)',
                'phone' => '8128704877',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"San Nicolás","instagram":"@dentaleodentista","source_channel":"google-search","notes":"Diseñadores de sonrisas; opera SN + Mty + SPG"}',
            ],
            [
                'name' => 'Dr. Jorge Ancheyta',
                'clinic_name' => 'Dr. Jorge Ancheyta Odontólogo',
                'specialty' => 'Odontología Estética',
                'city' => 'Monterrey',
                'address' => 'Alta Vista Sur, 64960 Monterrey',
                'phone' => '8120368003',
                'has_whatsapp' => false,
                'email' => 'info@dentistamonterrey.com',
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Alta Vista Sur","instagram":"@dr.jorgeancheyta","website":"https:\/\/odontologomonterrey.com","source_channel":"google-search","notes":"1 doctor titular; limpieza + blanqueamiento + carillas"}',
            ],
            [
                'name' => 'Dra. Carolina Cárdenas Cantú',
                'clinic_name' => 'Odontología Pediátrica y Ortodoncia',
                'specialty' => 'Odontopediatría',
                'city' => 'San Nicolás de los Garza',
                'address' => 'Cordillera de los Andes 929 Int. B-C, Col. Las Puentes 11vo Sector, San Nicolás de los Garza, 66460',
                'phone' => '8180577728',
                'has_whatsapp' => true,
                'email' => 'dra.carolina.cardenas@gmail.com',
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Las Puentes","website":"https:\/\/www.odontologiapediatricayortodoncia.com","source_channel":"google-search","notes":"2 doctores titulares (Dra. Cárdenas + Dr. Moreno); 1 sede"}',
            ],
            [
                'name' => 'Dra. Susana Gomes',
                'clinic_name' => 'Odontoes',
                'specialty' => 'Endodoncia',
                'city' => 'San Pedro Garza García',
                'address' => 'Plaza Tanarah 208, Av. Vasconcelos 345, Santa Engracia, San Pedro Garza García',
                'phone' => '8183351582',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Santa Engracia","instagram":"@odontoesmx","website":"https:\/\/odontoes.com.mx","source_channel":"google-search","notes":"7 especialistas; 1 sede; multidisciplinario alto nivel"}',
            ],
            [
                'name' => 'Dr. Roberto Carrillo',
                'clinic_name' => 'Mi Sonrisa (Dres. Carrillo)',
                'specialty' => 'Ortodoncia',
                'city' => 'Monterrey',
                'address' => 'Av. Manuel Gómez Morín 309, Valle de Santa Engracia, 66268 Monterrey',
                'phone' => '8183355999',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Valle de Santa Engracia","website":"https:\/\/www.misonrisa.mx","source_channel":"google-search","notes":"70+ años familia Carrillo; únicos Platino Invisalign norte México"}',
            ],
            [
                'name' => 'Imagen Dental',
                'clinic_name' => 'Imagen Dental',
                'specialty' => 'Odontología General',
                'city' => 'Monterrey',
                'address' => 'Av. Gonzalitos 3036, Mitras Norte, Monterrey, 64320',
                'phone' => '8183707080',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Mitras Norte","instagram":"@imagendental_","website":"http:\/\/www.imagendental.com","source_channel":"google-search","notes":"100% mexicana; familia; múltiples especialidades; borderline tamaño"}',
            ],
            [
                'name' => 'Dental Diagnostic',
                'clinic_name' => 'Dental Diagnostic',
                'specialty' => 'Odontología General',
                'city' => 'Monterrey',
                'address' => 'Av. Simón Bolívar 1985 2do piso, Mitras Centro, 64460 Monterrey',
                'phone' => '8128944540',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Mitras Centro","source_channel":"google-search","notes":"LGBTQ+ friendly; espacio inclusivo"}',
            ],
            [
                'name' => 'Dental Salud Mitras',
                'clinic_name' => 'Dental Salud Mitras',
                'specialty' => 'Odontología General',
                'city' => 'Monterrey',
                'address' => 'Simón Bolívar 2155A, Mitras Centro, 64460 Monterrey',
                'phone' => '8113603307',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Mitras Centro","rating":"5.0","source_channel":"google-search","notes":"Rating 5.0 excelente reputación; cita previa"}',
            ],
            [
                'name' => 'Dr. Serrano',
                'clinic_name' => 'Clínica Serrano de Implantología Oral',
                'specialty' => 'Implantología',
                'city' => 'San Pedro Garza García',
                'address' => 'Av. Lázaro Cárdenas 302, Residencial San Agustín, 66260 San Pedro Garza García',
                'phone' => '8114770416',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Residencial San Agustín","website":"https:\/\/clinicaserrano.mx","source_channel":"google-search","notes":"20+ años; tecnología digital avanzada; foco implantes All-on-4"}',
            ],
            [
                'name' => 'Dr. Jorge H. Villarreal Rodríguez',
                'clinic_name' => 'Consorcio Odontológico Integral',
                'specialty' => 'Implantología',
                'city' => 'Monterrey',
                'address' => 'María de las Islas 3642, Sector Monterrey, 64834 Monterrey',
                'phone' => '8183721549',
                'has_whatsapp' => false,
                'email' => 'consorcioodontologico@hotmail.com',
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Rincón de la Primavera","website":"https:\/\/www.consorcioodontologicointegral.com","source_channel":"google-search","notes":"40+ años exp; egresado UANL; 2 sedes cercanas"}',
            ],
            [
                'name' => 'Dentistas Especializados de Monterrey',
                'clinic_name' => 'Dentistas Especializados de Monterrey',
                'specialty' => 'Odontología General',
                'city' => 'Monterrey',
                'address' => 'Carretera Nacional 6501, Col. La Estanzuela, 5° piso Despacho 502, Monterrey',
                'phone' => '8181041770',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"La Estanzuela","instagram":"@dentistas.especializados.mty","source_channel":"google-search","notes":"Fundada 1979; 2 sedes propias; bilingüe"}',
            ],
            [
                'name' => 'Especialidades Dentales Obispado',
                'clinic_name' => 'Especialidades Dentales Obispado',
                'specialty' => 'Odontología General',
                'city' => 'Monterrey',
                'address' => 'Miguel Hidalgo y Costilla 2530, Centro Médico Obispado Suite 92, Col. Obispado, Monterrey',
                'phone' => '8117715311',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Obispado","source_channel":"google-search","notes":"Dentro Centro Médico Obispado"}',
            ],
            [
                'name' => 'Dr. Antonio Sánchez',
                'clinic_name' => 'Centro Odontológico Dr. Antonio Sánchez',
                'specialty' => 'Odontología General',
                'city' => 'Monterrey',
                'address' => 'Alterna Torre Hidalgo, Miguel Hidalgo y Costilla 1910 Piso 6 Consultorio 608, Obispado, Monterrey',
                'phone' => '8188882801',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Obispado","source_channel":"google-search","notes":"Torre médica; consultorio individual"}',
            ],
            [
                'name' => 'Dra. Fanny López',
                'clinic_name' => 'Endodoncia Dra. Fanny López',
                'specialty' => 'Endodoncia',
                'city' => 'Monterrey',
                'address' => 'Hidalgo 2425, Obispado, Monterrey',
                'phone' => '8183186802',
                'has_whatsapp' => false,
                'email' => 'fannylopezendodoncia@yahoo.com',
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Obispado","source_channel":"google-search","notes":"Registrada AMECEE; endodoncista especialista"}',
            ],
            [
                'name' => 'Klindent',
                'clinic_name' => 'Klindent',
                'specialty' => 'Odontología General',
                'city' => 'Monterrey',
                'address' => 'Miguel Hidalgo y Costilla 1950-B, entre Baudelaire y Verlaine, Col. Obispado, Monterrey',
                'phone' => '8183331620',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Obispado","source_channel":"google-maps","notes":"Consultorio privado zona Obispado"}',
            ],
            [
                'name' => 'Consultorio Santos Degollado',
                'clinic_name' => 'Consultorio Santos Degollado',
                'specialty' => 'Odontología General',
                'city' => 'Monterrey',
                'address' => 'Santos Degollado 744 sur, Obispado, Monterrey',
                'phone' => '8183470560',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Obispado","source_channel":"google-maps","notes":"Consultorio privado Obispado"}',
            ],
            [
                'name' => 'Clínica Dental Consultorio Jose Benítez',
                'clinic_name' => 'Clínica Dental Consultorio Jose Benítez',
                'specialty' => 'Odontología General',
                'city' => 'Monterrey',
                'address' => 'C. Lic. José Benítez 2759, Obispado, Monterrey',
                'phone' => '8183480223',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Obispado","source_channel":"google-maps","notes":"Consultorio privado sobre Benítez"}',
            ],
            [
                'name' => 'Dra. Cynthia Yllades',
                'clinic_name' => 'Consultorio Dental Jerónimo Treviño',
                'specialty' => 'Endodoncia',
                'city' => 'Monterrey',
                'address' => 'Calle Jerónimo Treviño 718 Pte, Centro, Monterrey',
                'phone' => '8183420175',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Centro","source_channel":"google-maps","notes":"Odontología digital estética; endodoncia"}',
            ],
            [
                'name' => 'MG Dental',
                'clinic_name' => 'MG Dental',
                'specialty' => 'Odontología Estética',
                'city' => 'Monterrey',
                'address' => 'Prol. Ruiz Cortínez 9014, Plaza de Hierro, Residencial Puerta de Hierro, Monterrey',
                'phone' => '8127332414',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Residencial Puerta de Hierro","source_channel":"google-search","notes":"Estética dental + periodoncia + implantología + cirugía"}',
            ],
            [
                'name' => 'Consultorio Plaza Via Puerta de Hierro',
                'clinic_name' => 'Consultorio Plaza Via Puerta de Hierro',
                'specialty' => 'Ortodoncia',
                'city' => 'Monterrey',
                'address' => 'Prolongación Ruiz Cortines 4005, Plaza Via 29, Residencial Puerta de Hierro, 64349 Monterrey',
                'phone' => '8127332500',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Residencial Puerta de Hierro","source_channel":"google-maps","notes":"Torre médica con varios consultorios dentales"}',
            ],
            [
                'name' => 'Tooth & Teeth Consultorio Dental',
                'clinic_name' => 'Tooth & Teeth Consultorio Dental',
                'specialty' => 'Odontopediatría',
                'city' => 'Monterrey',
                'address' => 'Calle Jardín de San Jerónimo 120, Monterrey',
                'phone' => '8183486700',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"San Jerónimo","source_channel":"google-maps","notes":"Odontopediatría San Jerónimo"}',
            ],
            [
                'name' => 'Odontología Integral Tec',
                'clinic_name' => 'Odontología Integral Tec',
                'specialty' => 'Odontología General',
                'city' => 'Monterrey',
                'address' => 'Av. Eugenio Garza Sada Sur 2762, Plaza Sebastián, Tecnológico, 64700 Monterrey',
                'phone' => '8183590440',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Tecnológico","source_channel":"google-search","notes":"Cerca Tec de Monterrey; rehabilitación + cirugía"}',
            ],
            [
                'name' => 'Consultorio Humberto Lobo A10',
                'clinic_name' => 'Consultorio Humberto Lobo A10',
                'specialty' => 'Odontología General',
                'city' => 'San Pedro Garza García',
                'address' => 'Av. Humberto Lobo 520 Int. A10, San Pedro Garza García',
                'phone' => '8183389004',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Del Valle","source_channel":"google-maps","notes":"Consultorio sobre Humberto Lobo; zona premium"}',
            ],
            [
                'name' => 'Consultorio Calz. San Pedro 401-B',
                'clinic_name' => 'Consultorio Calz. San Pedro 401-B',
                'specialty' => 'Odontología General',
                'city' => 'San Pedro Garza García',
                'address' => 'Calzada San Pedro 401-B, Col. Del Valle, 66220 San Pedro Garza García',
                'phone' => '8183382112',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Del Valle","source_channel":"google-maps","notes":"Consultorio privado Calzada San Pedro"}',
            ],
            [
                'name' => 'M&C Dentistas',
                'clinic_name' => 'M&C Dentistas',
                'specialty' => 'Odontopediatría',
                'city' => 'San Pedro Garza García',
                'address' => 'Calzada del Valle 355, Col. Del Valle, San Pedro Garza García',
                'phone' => '8183383780',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Del Valle","source_channel":"google-search","notes":"Odontopediatría + ortopedia maxilofacial + urgencias"}',
            ],
            [
                'name' => 'Organización Dental Láser',
                'clinic_name' => 'Organización Dental Láser',
                'specialty' => 'Endodoncia',
                'city' => 'San Pedro Garza García',
                'address' => 'Calzada del Valle 400 Local 57, Col. Del Valle, San Pedro Garza García',
                'phone' => '8183383550',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Del Valle","source_channel":"google-search","notes":"Endo + perio + implantología"}',
            ],
            [
                'name' => 'Dr. Daniel E. Guajardo Hernández',
                'clinic_name' => 'Dr. Daniel Guajardo Odontopediatra',
                'specialty' => 'Odontopediatría',
                'city' => 'San Pedro Garza García',
                'address' => 'Avenida Manuel Gómez Morín 2005, San Pedro Garza García',
                'phone' => '8183381900',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Del Valle","source_channel":"google-search","notes":"Consultorio individual odontopediatra SPGG"}',
            ],
            [
                'name' => 'Consultorio Dental Cumbres Elite',
                'clinic_name' => 'Consultorio Dental Cumbres Elite',
                'specialty' => 'Ortodoncia',
                'city' => 'Monterrey',
                'address' => 'Av. Cumbres Elite 199 Local 10, entre Lince y Cumbres de Córdova, Col. Cumbres Elite, Monterrey',
                'phone' => '8181234560',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-mty-dedup-20260422","colonia":"Cumbres Elite","source_channel":"google-maps","notes":"Consultorio sobre Cumbres Elite"}',
            ],
        ];

        $this->command->info('Insertando ' . count($prospects) . ' dentistas del pilot (research-dentistas-mty-dedup-20260422)...');

        $inserted = 0;
        $skipped = 0;

        foreach ($prospects as $prospect) {
            // Idempotencia por phone (último match) — no volver a insertar si ya existe
            $existing = Prospect::where('phone', $prospect['phone'])->first();
            if ($existing) {
                $skipped++;
                continue;
            }

            Prospect::create(array_merge($prospect, [
                'source' => 'prospecting', // matches SendProspectEmails cron filter
                'status' => 'new',
                'assigned_to_sales_rep_id' => 100,
                'contact_day' => 0,
                'next_contact_at' => now()->addHour(),
                'outreach_started_at' => now(),
            ]));
            $inserted++;
        }

        $this->command->info("✓ {$inserted} insertados | {$skipped} duplicados saltados | Total en seeder: " . count($prospects));
    }
}
