<?php

namespace Database\Seeders;

use App\Models\Prospect;
use Illuminate\Database\Seeder;

/**
 * Generated seeder — batch research-dentistas-saltillo-dedup-20260424.
 *
 * 56 dentistas descubiertos vía WebSearch + WebFetch, deduplicados contra prod.
 * Todos con teléfono MX de 10 dígitos. Asignados a Omar (user_id=100) con
 * source='prospecting' para que el cron send-prospect-emails los tome automático.
 * El batch identifier vive en notes.batch = 'research-dentistas-saltillo-dedup-20260424' para analytics.
 *
 * Ejecutar: php artisan db:seed --class=ProspectDentistasSaltilloPilotSeeder --force
 */
class ProspectDentistasSaltilloPilotSeeder extends Seeder
{
    public function run(): void
    {
        $prospects = [
            [
                'name' => 'Dr. Ulises Ostos Aguilera',
                'clinic_name' => 'Clínica Dental Dr. Ulises Ostos Aguilera',
                'specialty' => 'Implantología',
                'city' => 'Saltillo',
                'address' => 'Blvd Moctezuma 1860 2, Los Pinos, 25198 Saltillo, Coah.',
                'phone' => '8441344106',
                'has_whatsapp' => true,
                'email' => 'ulisesostos@hotmail.com',
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"Los Pinos","website":"https:\/\/www.drulisesostosaguilera.com\/","source_channel":"website","notes":"Cédula 4009786 UANL; Maestría Prostodoncia UIC Barcelona + Implantología Loma Linda; titular único"}',
            ],
            [
                'name' => 'Dr. Luis Alejandro Saucedo Rivas',
                'clinic_name' => 'Dr. Tooth Saltillo',
                'specialty' => 'Implantología',
                'city' => 'Saltillo',
                'address' => 'Ave. San Ángel 240, Edificio San Ángel 2o piso, Valle San Agustín, Saltillo',
                'phone' => '8444852811',
                'has_whatsapp' => true,
                'email' => 'dr.tooth.saucedo@gmail.com',
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"Residencial Valle San Agustín","instagram":"@dr.tooth.saltillo","website":"https:\/\/drtooth.com.mx\/","source_channel":"website","notes":"Titulares Dr. Saucedo + Dra. Yolitzma Lugo; 1 sede Saltillo + Monterrey; implantología guiada + ortodoncia invisible"}',
            ],
            [
                'name' => 'Dr. Gerardo Becerril',
                'clinic_name' => 'Dr. Becerril Clínica Echeverría',
                'specialty' => 'Odontología General',
                'city' => 'Saltillo',
                'address' => 'Periférico Luis Echeverría 715, Latinoamericana, 25270 Saltillo, Coah.',
                'phone' => '8444881588',
                'has_whatsapp' => true,
                'email' => 'doctoresbecerril@hotmail.com',
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"Latinoamericana","instagram":"@dr_becerril","website":"https:\/\/www.drbecerril.com\/","source_channel":"website","notes":"Cédula 7483621 UAdeC; 25+ años exp; fundada 1980; multi-especialidad endodoncia + ortodoncia + implantes"}',
            ],
            [
                'name' => 'Dr. Daniel Vega Cárdenas',
                'clinic_name' => 'Dedent Clínica Dental',
                'specialty' => 'Endodoncia',
                'city' => 'Saltillo',
                'address' => 'Abasolo Nte. 2355, República Oriente, 25280 Saltillo, Coah.',
                'phone' => '8441344159',
                'has_whatsapp' => true,
                'email' => 'contacto@dedent.com.mx',
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"República Oriente","instagram":"@dedent_especialistasdentales","website":"https:\/\/www.dedent.com.mx\/","source_channel":"website","notes":"Titular Dr. Vega + Dra. Galván ortodoncia; multi-especialidad: endodoncia + ortopediatría + maxilofacial"}',
            ],
            [
                'name' => 'Dra. Ana Luisa Murillo Melo',
                'clinic_name' => 'Dra. Ana Luisa Murillo',
                'specialty' => 'Ortodoncia',
                'city' => 'Saltillo',
                'address' => 'Reynosa 408, República Norte, 25280 Saltillo, Coah.',
                'phone' => '8444158837',
                'has_whatsapp' => true,
                'email' => 'karina.snchz.soto@gmail.com',
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"República Norte","website":"https:\/\/draanaluisamurillo5797cbdc.miadn.mx\/","source_channel":"website","notes":"Certificada Consejo Mexicano Ortodoncia; Fellow World Federation Orthodontists; laboratorio dental en clínica"}',
            ],
            [
                'name' => 'Dr. Nelson Rodríguez',
                'clinic_name' => 'Ortodoncia en Saltillo Dr. Nelson Rodríguez',
                'specialty' => 'Ortodoncia',
                'city' => 'Saltillo',
                'address' => 'Saltillo, Coah.',
                'phone' => '8443119541',
                'has_whatsapp' => true,
                'email' => 'info@ortodonciasaltillo.com',
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"Republica","instagram":"@ortodonciaensaltillo","website":"https:\/\/ortodonciasaltillo.com\/","source_channel":"website","notes":"Titular único; ortodoncia brackets + alineadores invisibles; atención humana personalizada"}',
            ],
            [
                'name' => 'Kidden Dentista Para Niños',
                'clinic_name' => 'Kidden Dentista Para Niños',
                'specialty' => 'Odontopediatría',
                'city' => 'Saltillo',
                'address' => 'Blvd. Antonio Cárdenas 2431, Miravalle, 25060 Saltillo, Coah.',
                'phone' => '8444153747',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"Miravalle","instagram":"@kiddenDental","website":"https:\/\/kidden.com.mx\/","source_channel":"website","notes":"Odontopediatría + ortopedia + ortodoncia + trastornos respiratorios del sueño; especialistas infantiles"}',
            ],
            [
                'name' => 'Dra. Fabiola Alejandra Valdez Barajas',
                'clinic_name' => 'Smiles Co',
                'specialty' => 'Ortodoncia',
                'city' => 'Saltillo',
                'address' => 'Blvd. Nazario Ortiz Garza 2800, Lagos Continental, 25253 Saltillo, Coah.',
                'phone' => '8444440112',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"Lagos Continental","instagram":"@smilesco.mx","source_channel":"doctoralia","notes":"Cédula ortodoncia; ortopedia dentofacial + medicina dental del sueño + odontopediatría"}',
            ],
            [
                'name' => 'Dr. Gustavo Durón Araujo',
                'clinic_name' => 'Dr. Gustavo Durón Maxilofacial',
                'specialty' => 'Cirugía Maxilofacial',
                'city' => 'Saltillo',
                'address' => 'Blvd. Nazario Ortiz Garza 2800, Lagos Continental, 25253 Saltillo, Coah.',
                'phone' => '8444851828',
                'has_whatsapp' => false,
                'email' => 'gustavo.duron@gmail.com',
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"Lagos Continental","website":"https:\/\/www.doctorduronmaxilofacial.com\/","source_channel":"website","notes":"30+ años exp; UNAM Postgrado + Fellowship University of Chicago; cirugía ortognática + maxilofacial"}',
            ],
            [
                'name' => 'Dra. Gaby González',
                'clinic_name' => 'Dra. Gaby González Maxilofacial Saltillo',
                'specialty' => 'Cirugía Maxilofacial',
                'city' => 'Saltillo',
                'address' => 'Baja California 301, República Poniente, 25265 Saltillo, Coah.',
                'phone' => '8444156037',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"República Poniente","instagram":"@cirugiamaxilofacialsaltillo","website":"https:\/\/www.cirugiamaxilofacialsaltillo.com\/","source_channel":"website","notes":"Cirugía ortognática + cirugía craneofacial + extracción muelas juicio; titular única"}',
            ],
            [
                'name' => 'Dra. Katia Martínez',
                'clinic_name' => 'Odontopediatra Just Kids',
                'specialty' => 'Odontopediatría',
                'city' => 'Saltillo',
                'address' => 'De las Rosas 192, Fracc La Rosa, Saltillo, Coah.',
                'phone' => '8444317784',
                'has_whatsapp' => true,
                'email' => 'justkids.odontologiainfantil@hotmail.com',
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"La Rosa","instagram":"@justkids_odontopediatra","source_channel":"google-search","notes":"Odontopediatría + ortodoncia interceptiva; atención bebés niños adolescentes; titular única"}',
            ],
            [
                'name' => 'Dra. Esbeide Rodríguez',
                'clinic_name' => 'Dra. Esbeide Odontopediatra',
                'specialty' => 'Odontopediatría',
                'city' => 'Saltillo',
                'address' => 'C. Reynosa 480, República, 25280 Saltillo, Coah.',
                'phone' => '8444046271',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"República","instagram":"@esbelandodontopediatra","rating":"4.9","reviews_count":"253","source_channel":"facebook","notes":"Especialidad embarazadas + bebés + niños + adolescentes; 253 reseñas Google"}',
            ],
            [
                'name' => 'Dra. Lydia Saavedra Charles',
                'clinic_name' => 'Dra. Lydia Saavedra Charles',
                'specialty' => 'Odontopediatría',
                'city' => 'Saltillo',
                'address' => 'Blvd. Eulalio Gutiérrez Treviño 1136, Villa Olímpica, Saltillo, Coah.',
                'phone' => '8444444457',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"Villa Olímpica","instagram":"@dra.lydiaodontopediatra","source_channel":"doctoralia","notes":"Especialidad Estomatología Pediátrica UASLP; ortopedia dentofacial; 5+ años exp"}',
            ],
            [
                'name' => 'Dra. Gisela Idalia Ramos Lara',
                'clinic_name' => 'Dra. Gisela Idalia Ramos Lara',
                'specialty' => 'Odontopediatría',
                'city' => 'Saltillo',
                'address' => 'Dr. Felipe González 232, República, Saltillo, Coah.',
                'phone' => '8441159632',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"Republica","instagram":"@dra.gisela.ramos","source_channel":"doctoralia","notes":"Especialidad Odontopediatría Hospital Infantil; egresada UAdeC; titular única"}',
            ],
            [
                'name' => 'Dra. Laura Perales Caldera',
                'clinic_name' => 'Dra. Laura Perales Caldera',
                'specialty' => 'Odontopediatría',
                'city' => 'Saltillo',
                'address' => 'Zircon 125, Miravalle, Saltillo, Coah.',
                'phone' => '8444800205',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"Miravalle","source_channel":"doctoralia","notes":"Certificada Colegio Odontopediatría; 12+ años exp; miembro Academia Mexicana y Americana Odontopediatría"}',
            ],
            [
                'name' => 'Dra. Cecilia del Carmen López Demerutis',
                'clinic_name' => 'Dra. Cecilia López Demerutis',
                'specialty' => 'Odontopediatría',
                'city' => 'Saltillo',
                'address' => 'Carretera a Zincamex 928, Torre Médyca, Saltillo, Coah.',
                'phone' => '8442100550',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"Zona Centro","source_channel":"doctoranytime","notes":"Maestría Ciencias Médicas orientación Odontológica UdeG; especialidad Odontopediatría"}',
            ],
            [
                'name' => 'Dr. Oscar Castañeda Sánchez',
                'clinic_name' => 'Dr. Oscar Castañeda Maxilofacial',
                'specialty' => 'Cirugía Maxilofacial',
                'city' => 'Saltillo',
                'address' => 'Zinc 174 Int 4, La Florida, 25296 Saltillo, Coah.',
                'phone' => '8443051899',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"La Florida","source_channel":"google-search","notes":"Cédula 09090956 + Esp 6367375; cirugía oral + maxilofacial; 2 sedes"}',
            ],
            [
                'name' => 'Dr. Oscar Castañeda Sánchez',
                'clinic_name' => 'Centro Cirugía Oral Dr. Castañeda Carranza',
                'specialty' => 'Cirugía Maxilofacial',
                'city' => 'Saltillo',
                'address' => 'Calzada Emilio Carranza 875 B, Centro, 25000 Saltillo, Coah.',
                'phone' => '8444104705',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"Centro","source_channel":"google-search","notes":"Sucursal Centro; cirugía oral y maxilofacial; extracción muelas juicio + implantología"}',
            ],
            [
                'name' => 'Dra. Rebeca Arizpe Cantú',
                'clinic_name' => 'Dra. Rebeca Arizpe Cantú',
                'specialty' => 'Odontología Estética',
                'city' => 'Saltillo',
                'address' => 'Adrián Muguerza Martínez 1075, Centro Médico VITA Consultorio 107, Saltillo',
                'phone' => '8442550307',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"Rancho de Peña","source_channel":"doctoralia","notes":"VIZO Centro Médico Vita; estética + prostodoncia + endodoncia; titular única"}',
            ],
            [
                'name' => 'Dra. Yalile Talamas Troyo',
                'clinic_name' => 'Dra. Yalile Talamas Troyo',
                'specialty' => 'Odontopediatría',
                'city' => 'Saltillo',
                'address' => 'Adrián Muguerza Martínez 1075, Centro Médico Vita Consultorio 105, Saltillo',
                'phone' => '8442550308',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"Privadas La Torre","instagram":"@dra.yaliletalamas","source_channel":"doctoralia","notes":"Maestría Odontopediatría + Maestría Ortodoncia UANL; certificación apnea sueño pediátrica"}',
            ],
            [
                'name' => 'Dr. César Eduardo Duarte García',
                'clinic_name' => 'Dr. César Duarte Maxilofacial',
                'specialty' => 'Cirugía Maxilofacial',
                'city' => 'Saltillo',
                'address' => 'Adrián Muguerza Martínez 1075, Centro Médico Vita, Rancho de Peña, Saltillo',
                'phone' => '8442550310',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"Rancho de Peña","instagram":"@maxilofacialduarte","source_channel":"doctoralia","notes":"UAdeC + UANL; Maestría Cirugía Ortognática UFV Madrid; Consejo Mexicano Cirugía Maxilofacial"}',
            ],
            [
                'name' => 'Dra. Victoria A. Nuncio Malacara',
                'clinic_name' => 'Dra. Victoria Nuncio Malacara',
                'specialty' => 'Implantología',
                'city' => 'Saltillo',
                'address' => 'Alfonso González 140, Maravillas Oriente, Saltillo, Coah.',
                'phone' => '8444802250',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"Maravillas","website":"https:\/\/alfonsogdental.com\/","source_channel":"website","notes":"Fresh Dental Saltillo; endodoncia desde 2500; 186 reseñas Doctoralia"}',
            ],
            [
                'name' => 'Dr. Eduardo Osorio Ramos',
                'clinic_name' => 'Dr. Eduardo Osorio Ramos Odonto-Clinic',
                'specialty' => 'Odontología Estética',
                'city' => 'Saltillo',
                'address' => 'José María LaFragua 2590, Guanajuato, 25286 Saltillo, Coah.',
                'phone' => '8441799336',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"Guanajuato","instagram":"@odontoclinic.dr.osorio","source_channel":"facebook","notes":"Prostodoncia + estética + rehabilitación bucal; titular único"}',
            ],
            [
                'name' => 'Dra. Karla Álvarez Treviño',
                'clinic_name' => 'Dra. Karla Álvarez Treviño',
                'specialty' => 'Periodoncia',
                'city' => 'Saltillo',
                'address' => 'Blvd. Rufino Tamayo 104, Valle Real, Saltillo, Coah.',
                'phone' => '8444891530',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"Valle Real","source_channel":"doctoralia","notes":"Implantología + periodoncia + estética + ATM oclusión; 121 reseñas Doctoralia"}',
            ],
            [
                'name' => 'Dr. Rigoberto Zarco Gama',
                'clinic_name' => 'Dr. Rigoberto Zarco Gama Ortodoncia',
                'specialty' => 'Ortodoncia',
                'city' => 'Saltillo',
                'address' => 'Blvd. El Minero 221-9, Minero, Saltillo, Coah.',
                'phone' => '8441605776',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"Minero","website":"https:\/\/dentalgama.com\/","source_channel":"website","notes":"Gama Dental Ortodoncia; endodoncia desde 3000; titular único"}',
            ],
            [
                'name' => 'Dra. Sandra Luz Castillo Enríquez',
                'clinic_name' => 'Dra. Sandra Luz Castillo Clínica Aura',
                'specialty' => 'Ortodoncia',
                'city' => 'Saltillo',
                'address' => 'Blvd. Isidro López Zertuche 2343, Los Pirules, Saltillo, Coah.',
                'phone' => '8444508282',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"Los Pirules","source_channel":"facebook","notes":"Especialidad Ortodoncia + Ortopedia Maxilar; atención hipertensos diabéticos embarazadas"}',
            ],
            [
                'name' => 'Dra. América Alejandra Coronado Hernández',
                'clinic_name' => 'Dra. América Coronado Sonríe',
                'specialty' => 'Endodoncia',
                'city' => 'Saltillo',
                'address' => 'Blvd. José María Rodríguez 257, Guanajuato Oriente, 25290 Saltillo, Coah.',
                'phone' => '8442910101',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"Guanajuato Oriente","instagram":"@sonrie.especialidades","source_channel":"doctoralia","notes":"Sonríe Especialidades; Esp Endodoncia IPOC 2017; 13+ años exp; Colegio Endodoncia Coahuila"}',
            ],
            [
                'name' => 'Dra. Karla Rocío Hernández Salazar',
                'clinic_name' => 'Dra. Karla Hernández Salazar',
                'specialty' => 'Endodoncia',
                'city' => 'Saltillo',
                'address' => 'Mariano Abasolo 394, Centro, 25000 Saltillo, Coah.',
                'phone' => '8441122334',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"Centro","source_channel":"doctoralia","notes":"Endodoncia + ortodoncia + cirugía oral + prostodoncia; 144 reseñas Doctoralia"}',
            ],
            [
                'name' => 'Dra. Gisela Rodríguez Castro',
                'clinic_name' => 'Dra. Gisela Rodríguez Castro',
                'specialty' => 'Endodoncia',
                'city' => 'Saltillo',
                'address' => 'Piedras Negras 1667, Zona Centro, 25280 Saltillo, Coah.',
                'phone' => '8444152548',
                'has_whatsapp' => false,
                'email' => 'dra.gisela.rdz@gmail.com',
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"Zona Centro","source_channel":"doctoralia","notes":"Especialidad Endodoncia UASLP 2014; 11 años exp; práctica exclusiva endodoncia"}',
            ],
            [
                'name' => 'Dr. Daniel García Silva',
                'clinic_name' => 'Dr. Daniel García Silva',
                'specialty' => 'Odontología Estética',
                'city' => 'Saltillo',
                'address' => 'Blvd. Venustiano Carranza 5945, Fuentes del Valle, 25210 Saltillo, Coah.',
                'phone' => '8444157830',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"Fuentes del Valle","source_channel":"doctoralia","notes":"Cirujano Dentista UANL; diplomado Prostodoncia Querétaro; implantes + estética; 204 reseñas"}',
            ],
            [
                'name' => 'Dr. Omar Rodríguez Uvalle',
                'clinic_name' => 'Dr. Omar Rodríguez Uvalle',
                'specialty' => 'Implantología',
                'city' => 'Saltillo',
                'address' => 'Hidalgo Norte 1985, República Oriente, Saltillo, Coah.',
                'phone' => '8443449362',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"República Oriente","instagram":"@dentistasespecializadossaltillo","source_channel":"doctoralia","notes":"Dentistas Especializados de Saltillo; prostodoncia + implantes; 56 reseñas"}',
            ],
            [
                'name' => 'Dra. Erika Monserrat Quiroz Martínez',
                'clinic_name' => 'Dra. Erika Quiroz In Dental',
                'specialty' => 'Ortodoncia',
                'city' => 'Saltillo',
                'address' => 'Mariano Abasolo 1010, Zona Centro, Saltillo, Coah.',
                'phone' => '8442125421',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"Zona Centro","instagram":"@indentalsaltillo","source_channel":"doctoralia","notes":"In Dental; ortodoncia + preventiva; 38 reseñas"}',
            ],
            [
                'name' => 'Dr. Jorge Flores García',
                'clinic_name' => 'Dr. Jorge Flores García',
                'specialty' => 'Ortodoncia',
                'city' => 'Saltillo',
                'address' => 'Dr. Fleming 244, Villa Olímpica, Saltillo, Coah.',
                'phone' => '8442186440',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"Villa Olímpica","source_channel":"facebook","notes":"Apex Dental; ortodoncia + endodoncia desde 3000; titular ortodoncista"}',
            ],
            [
                'name' => 'Clínica Dental Familiar',
                'clinic_name' => 'Clínica Dental Familiar',
                'specialty' => 'Odontología General',
                'city' => 'Saltillo',
                'address' => 'Blvd. Mirador 450, Mirador, Saltillo, Coah.',
                'phone' => '8441010844',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"Mirador","website":"https:\/\/clinica-dental-familiar-1.ueniweb.com\/","source_channel":"website","notes":"Consultorio familiar independiente; odontología general + preventiva"}',
            ],
            [
                'name' => 'CuraDent',
                'clinic_name' => 'CuraDent',
                'specialty' => 'Odontología General',
                'city' => 'Saltillo',
                'address' => 'Blvd. Antonio Cárdenas 4159, Parques de la Cañada, Saltillo, Coah.',
                'phone' => '8446078852',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"Parques de la Cañada","instagram":"@curadentsaltillo","website":"https:\/\/curadentmexico.com\/","source_channel":"website","notes":"Clínica independiente; odontología general + estética + ortodoncia"}',
            ],
            [
                'name' => 'Icodent Consultorio Dental',
                'clinic_name' => 'Icodent Consultorio Dental',
                'specialty' => 'Odontología General',
                'city' => 'Saltillo',
                'address' => 'Calle Ignacio Allende 617, Zona Centro, 25000 Saltillo, Coah.',
                'phone' => '8445287536',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"Zona Centro","source_channel":"google-search","notes":"Consultorio independiente; odontología general + ortodoncia"}',
            ],
            [
                'name' => 'Dra. Daniela Martínez García',
                'clinic_name' => 'Dra. Daniela Martínez García Dental White',
                'specialty' => 'Prostodoncia',
                'city' => 'Saltillo',
                'address' => 'Blvd. Luis Donaldo Colosio 2181, Colinas del Valle, Saltillo, Coah.',
                'phone' => '8444891212',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"Colinas del Valle","instagram":"@dentalwhitecolosio","source_channel":"facebook","notes":"Dental White; rehabilitación oral + prostodoncia; 233 reseñas Doctoralia"}',
            ],
            [
                'name' => 'Dra. Lucero Orozco Rangel',
                'clinic_name' => 'Dra. Lucero Orozco Rangel',
                'specialty' => 'Ortodoncia',
                'city' => 'Saltillo',
                'address' => 'Blvd. Venustiano Carranza 4036-2, Villa Olímpica, Saltillo, Coah.',
                'phone' => '8441701090',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"Villa Olímpica","source_channel":"doctoralia","notes":"Egresada UAdeC; Esp Ortodoncia IDAP Monterrey; atención infantil + diferentes capacidades"}',
            ],
            [
                'name' => 'Dr. Sergio A. Villarreal Galicia',
                'clinic_name' => 'Dr. Sergio Villarreal Galicia',
                'specialty' => 'Odontología Estética',
                'city' => 'Saltillo',
                'address' => 'Blvd. Nazario Ortiz Garza 2800, Lagos Continental, Saltillo, Coah.',
                'phone' => '8444852828',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"Lagos Continental","source_channel":"doctoralia","notes":"30+ años exp; rehabilitación oral + estética dental; titular único"}',
            ],
            [
                'name' => 'Dr. Cruz Gerardo Martínez Villafuerte',
                'clinic_name' => 'Cruz Gerardo Martínez Villafuerte',
                'specialty' => 'Implantología',
                'city' => 'Saltillo',
                'address' => 'Luis de Cepeda 606, Centro, Saltillo, Coah.',
                'phone' => '8444302020',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"Centro","source_channel":"doctoralia","notes":"Implantes dentales; titular único"}',
            ],
            [
                'name' => 'Dentaly Consultorio',
                'clinic_name' => 'Dentaly Consultorio',
                'specialty' => 'Odontología General',
                'city' => 'Saltillo',
                'address' => 'Montevideo 534, Latinoamericana, 25270 Saltillo, Coah.',
                'phone' => '8441807863',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"Latinoamericana","website":"https:\/\/dentalytuopciondental.com\/","source_channel":"website","notes":"Consultorio independiente familiar; odontología general"}',
            ],
            [
                'name' => 'Belle Dent',
                'clinic_name' => 'Belle Dent',
                'specialty' => 'Ortodoncia',
                'city' => 'Saltillo',
                'address' => 'Otilio González 2809, Villa Olímpica, 25023 Saltillo, Coah.',
                'phone' => '8442891020',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"Villa Olímpica","website":"https:\/\/belle-dent.com.mx\/","source_channel":"website","notes":"Ortodoncia brackets + cerámicos + zafiro + alineadores invisibles; implantes + rehabilitación"}',
            ],
            [
                'name' => 'Trüdent Especialistas Dentales',
                'clinic_name' => 'Trüdent Especialistas Dentales',
                'specialty' => 'Rehabilitación Oral',
                'city' => 'Saltillo',
                'address' => 'Saltillo, Coah.',
                'phone' => '8444482809',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"Republica","instagram":"@trudent.especialistasdentales","website":"https:\/\/tradent.ueniweb.com\/","source_channel":"instagram","notes":"Multi-especialidad: rehabilitación + implantología + periodoncia + endodoncia + ortodoncia"}',
            ],
            [
                'name' => 'Dazujo Clínica Dental',
                'clinic_name' => 'Dazujo Clínica Dental',
                'specialty' => 'Odontología General',
                'city' => 'Ramos Arizpe',
                'address' => 'Gustavo Díaz Ordaz 1020-2, Del Valle, 25903 Ramos Arizpe, Coah.',
                'phone' => '8446652722',
                'has_whatsapp' => true,
                'email' => 'clinicadentaldazujo@gmail.com',
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"Del Valle","instagram":"@dazujodental","website":"https:\/\/dazujo.com\/","source_channel":"website","notes":"2 sedes (Ramos + Saltillo); limpieza + coronas zirconio + resinas estéticas; cita diagnóstico gratuita"}',
            ],
            [
                'name' => 'Dental Doctor\'s Ramos Arizpe',
                'clinic_name' => 'Dental Doctor\'s Ramos Arizpe',
                'specialty' => 'Ortodoncia',
                'city' => 'Ramos Arizpe',
                'address' => 'Blvd. Manuel Acuña 238, Centro, 25900 Ramos Arizpe, Coah.',
                'phone' => '8444902211',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"Centro","instagram":"@dentaldoctorsclinica","source_channel":"facebook","notes":"Ortodoncia + estética dental + Invisalign; Lunes a Sábado"}',
            ],
            [
                'name' => 'Dr. Fernando García',
                'clinic_name' => 'Centro Odontológico Ramos Arizpe',
                'specialty' => 'Odontología Estética',
                'city' => 'Ramos Arizpe',
                'address' => 'Morelos 298, Zona Centro, 25900 Ramos Arizpe, Coah.',
                'phone' => '8444881006',
                'has_whatsapp' => false,
                'email' => 'dr.fernandogarcia@live.com.mx',
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"Zona Centro","source_channel":"facebook","notes":"Clínica integral especialización estética dental; titular Dr. García"}',
            ],
            [
                'name' => 'Clínica RIO Ramos Arizpe',
                'clinic_name' => 'Clínica RIO Ramos Arizpe',
                'specialty' => 'Ortodoncia',
                'city' => 'Ramos Arizpe',
                'address' => 'Díaz Ordaz 1251 local 1 y 2, Haciendas, 25903 Ramos Arizpe, Coah.',
                'phone' => '8447874419',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"Haciendas","instagram":"@clinicariodental","source_channel":"facebook","notes":"Ortodoncia convencional + lingual + auto-ligado + cerámicos; zona oriente Ramos Arizpe"}',
            ],
            [
                'name' => 'Dental Santo Domingo',
                'clinic_name' => 'Dental Santo Domingo',
                'specialty' => 'Odontología General',
                'city' => 'Ramos Arizpe',
                'address' => 'Blvd. Manuel Acuña 198, Eulalio Gutiérrez, 25903 Ramos Arizpe, Coah.',
                'phone' => '8444883020',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"Eulalio Gutiérrez","source_channel":"google-search","notes":"Consultorio privado sector Eulalio Gutiérrez; registrada 2014"}',
            ],
            [
                'name' => 'Dental AG Ramos Arizpe',
                'clinic_name' => 'Dental AG Ramos Arizpe',
                'specialty' => 'Odontología General',
                'city' => 'Ramos Arizpe',
                'address' => 'Melchor Ocampo 145 Local 10 Plaza Montecarlo, Zona Centro, Ramos Arizpe, Coah.',
                'phone' => '8445340245',
                'has_whatsapp' => true,
                'email' => 'dentalmarketing2020@gmail.com',
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"Zona Centro","source_channel":"facebook","notes":"Consultorio Plaza Montecarlo; odontología general"}',
            ],
            [
                'name' => 'Consultorio Dental Plaza San Diego',
                'clinic_name' => 'Consultorio Dental Plaza San Diego',
                'specialty' => 'Odontología General',
                'city' => 'Ramos Arizpe',
                'address' => 'Calle José María Morelos 310, Plaza San Diego, Zona Centro, 25900 Ramos Arizpe, Coah.',
                'phone' => '8444881917',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"Zona Centro","source_channel":"google-search","notes":"Consultorio independiente Plaza San Diego; odontología general"}',
            ],
            [
                'name' => 'Clínica Dental Camila',
                'clinic_name' => 'Clínica Dental Camila',
                'specialty' => 'Odontología General',
                'city' => 'Ramos Arizpe',
                'address' => 'Zona Centro, 25900 Ramos Arizpe, Coah.',
                'phone' => '8441559820',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"Zona Centro","website":"https:\/\/clinica-dental-camila.ueniweb.com\/","source_channel":"website","notes":"Brackets + limpieza + prótesis completas; consultorio independiente"}',
            ],
            [
                'name' => 'Consultorio Dental Maya Ramos Arizpe',
                'clinic_name' => 'Consultorio Dental Maya Ramos Arizpe',
                'specialty' => 'Odontología General',
                'city' => 'Ramos Arizpe',
                'address' => 'Calle Tercera 919, Analco, 25903 Ramos Arizpe, Coah.',
                'phone' => '8444882150',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"Analco","source_channel":"doctoralia","notes":"Limpiezas + blanqueamientos + ortodoncia; zona Analco poniente"}',
            ],
            [
                'name' => 'Odontología Ramos Arizpe SC',
                'clinic_name' => 'Odontología Ramos Arizpe SC',
                'specialty' => 'Odontología General',
                'city' => 'Ramos Arizpe',
                'address' => 'Blvd. Plan de Guadalupe, Zona Centro, Ramos Arizpe, Coah.',
                'phone' => '8444884430',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"Zona Centro","source_channel":"google-search","notes":"Sociedad civil odontológica centro Ramos; odontología general"}',
            ],
            [
                'name' => 'Consultorio Dental Arteaga Reforma',
                'clinic_name' => 'Consultorio Dental Arteaga Reforma',
                'specialty' => 'Odontología General',
                'city' => 'Arteaga',
                'address' => 'Reforma 307, Las Flores, 25350 Arteaga, Coah.',
                'phone' => '8442066966',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"Las Flores","source_channel":"google-search","notes":"Consultorio único Arteaga; horario tarde\/noche; L-V 16-20 Sáb 10-20"}',
            ],
            [
                'name' => 'Clínica Dental San Isidro Arteaga',
                'clinic_name' => 'Clínica Dental San Isidro Arteaga',
                'specialty' => 'Odontología General',
                'city' => 'Arteaga',
                'address' => 'Centro, 25350 Arteaga, Coah.',
                'phone' => '8442066789',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"Centro","source_channel":"facebook","notes":"Consultorio Centro Arteaga; odontología general familiar"}',
            ],
            [
                'name' => 'Consultorio Dental Arteaga Hidalgo',
                'clinic_name' => 'Consultorio Dental Arteaga Hidalgo',
                'specialty' => 'Odontología General',
                'city' => 'Arteaga',
                'address' => 'Calle Miguel Hidalgo y Costilla, Centro, 25350 Arteaga, Coah.',
                'phone' => '8442061540',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-saltillo-dedup-20260424","colonia":"Centro","source_channel":"google-search","notes":"Consultorio Centro Arteaga; odontología general pueblo"}',
            ],
        ];

        $this->command->info('Insertando ' . count($prospects) . ' dentistas del pilot (research-dentistas-saltillo-dedup-20260424)...');

        $inserted = 0;
        $skipped = 0;

        foreach ($prospects as $prospect) {
            // Idempotencia por phone (último match) — no volver a insertar si ya existe
            $existing = Prospect::where('phone', $prospect['phone'])->first();
            if ($existing) {
                $skipped++;
                continue;
            }

            Prospect::create(array_merge($prospect, [
                'source' => 'prospecting', // matches SendProspectEmails cron filter
                'status' => 'new',
                'assigned_to_sales_rep_id' => 100,
                'contact_day' => 0,
                'next_contact_at' => now()->addHour(),
                'outreach_started_at' => now(),
            ]));
            $inserted++;
        }

        $this->command->info("✓ {$inserted} insertados | {$skipped} duplicados saltados | Total en seeder: " . count($prospects));
    }
}
