<?php

namespace Database\Seeders;

use App\Models\Prospect;
use Illuminate\Database\Seeder;

/**
 * Generated seeder — batch research-dentistas-cancun-dedup-20260427.
 *
 * 58 dentistas descubiertos vía WebSearch + WebFetch, deduplicados contra prod.
 * Todos con teléfono MX de 10 dígitos. Asignados a Omar (user_id=100) con
 * source='prospecting' para que el cron send-prospect-emails los tome automático.
 * El batch identifier vive en notes.batch = 'research-dentistas-cancun-dedup-20260427' para analytics.
 *
 * Ejecutar: php artisan db:seed --class=ProspectDentistasCancunPilotSeeder --force
 */
class ProspectDentistasCancunPilotSeeder extends Seeder
{
    public function run(): void
    {
        $prospects = [
            [
                'name' => 'Dra. Gabriela Valdéz Lizama',
                'clinic_name' => 'Consuldent Cancún',
                'specialty' => 'Odontología General',
                'city' => 'Cancún',
                'address' => 'Cancún, Q. Roo',
                'phone' => '9988843135',
                'has_whatsapp' => true,
                'email' => 'info@consuldentcancun.com',
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"Centro","website":"https:\/\/www.consuldentcancun.com\/","source_channel":"website","notes":"25+ años; multiespecialidad; titular UADY; multi-doctor pequeño; bilingüe pacientes US"}',
            ],
            [
                'name' => 'Dra. Esperanza Martínez Almazán',
                'clinic_name' => 'OrtoDental Cancun',
                'specialty' => 'Ortodoncia',
                'city' => 'Cancún',
                'address' => 'Calle Tortuga 353, Sm 51 Fracc. Mónaco, Cancún',
                'phone' => '9988870830',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"Mónaco","website":"https:\/\/ortodentalcancun.com\/","source_channel":"website","notes":"Ortodoncia + ATM + ortopedia maxilofacial; titular única consultorio independiente; tickets MX local"}',
            ],
            [
                'name' => 'Dra. Adela Zamudio',
                'clinic_name' => 'Ortodoncia Biológica Estética Dental',
                'specialty' => 'Ortodoncia',
                'city' => 'Cancún',
                'address' => 'Av. Bonampak SM4A M1 Lote 4C, Cancún',
                'phone' => '9981235511',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"Centro","instagram":"@orto_dra_adela_zamudio","website":"https:\/\/www.ortodonciabiologica.com\/","source_channel":"website","notes":"Ortodoncia + ortopedia + estética + ATM; titular única; opera Cancún + Veracruz; tickets premium"}',
            ],
            [
                'name' => 'Dr. Alberto Guevara',
                'clinic_name' => 'Ro Dental',
                'specialty' => 'Implantología',
                'city' => 'Cancún',
                'address' => 'Plaza Corner Center Local 202, Av. Huayacán Mz 30, Col. Álamos, 77533 Cancún',
                'phone' => '9981876859',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"Álamos","instagram":"@ro.dentalcancun","website":"https:\/\/rodental.com.mx\/","source_channel":"website","notes":"Pareja titulares Dr. Guevara prosto-implantólogo + Dra. Carina Guevara odontopediatra; consultorio único Huayacán; mid-premium local"}',
            ],
            [
                'name' => 'Dra. Carina Guevara',
                'clinic_name' => 'Cliodent',
                'specialty' => 'Odontopediatría',
                'city' => 'Cancún',
                'address' => 'Las Palmas 135, Smz 320, 77536 Cancún',
                'phone' => '9983138106',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"Smz 320","instagram":"@cliodent_kids","website":"https:\/\/www.odontopediatracliodent.com\/","source_channel":"website","notes":"Odontopediatría zona sur; multi-doctor pequeño 3 dentistas titulares pareja + colega; 27+ años"}',
            ],
            [
                'name' => 'Dr. Octavio Acevedo Gaona',
                'clinic_name' => 'Dental Infantil',
                'specialty' => 'Odontopediatría',
                'city' => 'Cancún',
                'address' => 'Avenida Xel-Ha, Plaza Bonita Local 5H Planta Alta, Mza 1 y 2, SM 28, 77509 Cancún',
                'phone' => '9988847319',
                'has_whatsapp' => true,
                'email' => 'dr.octag@yahoo.com.mx',
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"SM 28","website":"https:\/\/www.dentalinfantil.com.mx\/","source_channel":"website","notes":"Odontopediatría pareja Acevedo + Castillo egresados Inst. Nacional Pediatría; 30+ años; tickets locales"}',
            ],
            [
                'name' => 'Dra. Wendy Sosa',
                'clinic_name' => 'Dra. Wendy Sosa Dentista Biológica',
                'specialty' => 'Odontología General',
                'city' => 'Cancún',
                'address' => 'Av. Huayacán, Plaza Aura Local 16, Cancún, Q.R.',
                'phone' => '9988464800',
                'has_whatsapp' => true,
                'email' => 'dra.wendysosa1@gmail.com',
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"Álamos","instagram":"@dra.wendysosa1","website":"https:\/\/drawendysosa1.wixsite.com\/drawendysosa","source_channel":"website","notes":"Dentista biológica\/holística; titular única; ICP perfecto wellness\/expat; podría atender pacientes US wellness"}',
            ],
            [
                'name' => 'Dr. Adrian Casado',
                'clinic_name' => 'Smile Dent',
                'specialty' => 'Odontología General',
                'city' => 'Cancún',
                'address' => 'Cancún, Q.R.',
                'phone' => '5540065214',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"Centro","instagram":"@consultoriodentalsmiledent","website":"https:\/\/smiledent.com.mx\/","source_channel":"website","notes":"Multi-doctor pequeño 4 titulares: Casado + Pantoja + Nieves maxilo + García orto; Dr. Mayorga odontopediatra colaborador"}',
            ],
            [
                'name' => 'Tropical Dental Studio',
                'clinic_name' => 'Tropical Dental Studio',
                'specialty' => 'Estética Dental',
                'city' => 'Cancún',
                'address' => 'Avenida de los Colegios, Plaza Gamura, 77560 Cancún',
                'phone' => '9982388057',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"Plaza Gamura","instagram":"@tropicaldentalstudiocancun","website":"https:\/\/www.tropicaldental.studio\/","source_channel":"website","notes":"Estética + implantes + diseño de sonrisa; consultorio único; tickets premium locales"}',
            ],
            [
                'name' => 'Dra. Diana M. López Canto',
                'clinic_name' => 'Prodent Cancún',
                'specialty' => 'Endodoncia',
                'city' => 'Cancún',
                'address' => 'Calle Sierra esquina Bonampak, SM 3, 77500 Cancún',
                'phone' => '9988842192',
                'has_whatsapp' => true,
                'email' => 'recepcion@prodentcancun.com',
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"SM 3","website":"https:\/\/www.prodentcancun.com\/","source_channel":"website","notes":"27+ años; multi-doctor pequeño 5 titulares mujeres especialistas; bilingüe; emergencias 24\/7"}',
            ],
            [
                'name' => 'Dra. Hinojosa',
                'clinic_name' => 'Clínica Dental Quirúrgica',
                'specialty' => 'Cirugía Oral',
                'city' => 'Cancún',
                'address' => 'Plaza Alivia, SM 44 Mz 10 Lt 2 Loc P102, Av. La Luna, 77506 Cancún',
                'phone' => '9984772827',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"SM 44","website":"https:\/\/clinicadentalquirurgica.com\/","source_channel":"website","notes":"Cirugía oral + prótesis; titular Dra. Hinojosa con equipo pequeño; mid-tier local"}',
            ],
            [
                'name' => 'Dra. Mariana Mariscal',
                'clinic_name' => 'Kamak Clínica Dental',
                'specialty' => 'Odontología General',
                'city' => 'Cancún',
                'address' => 'Avenida México 9, 77533 Cancún',
                'phone' => '9982034615',
                'has_whatsapp' => true,
                'email' => 'kamak.clinicadental@gmail.com',
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"Álamos","instagram":"@kamakdental","website":"https:\/\/kamakclinicadental.com\/","source_channel":"website","notes":"Multi-doctor 5 titulares mujeres + 1 maxilofacial; multiespecialidad; tickets locales clase media"}',
            ],
            [
                'name' => 'Dra. Geno',
                'clinic_name' => 'GNUX Dental Cancún',
                'specialty' => 'Odontología General',
                'city' => 'Cancún',
                'address' => 'Cancún, Q.R.',
                'phone' => '9983295199',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","instagram":"@gnuxdental","website":"https:\/\/gnuxdental.com\/","source_channel":"website","notes":"Multiespecialidad chica; titular Dra. Geno; brackets + implantes + odontopediatría"}',
            ],
            [
                'name' => 'Dra. Wendy Sosa',
                'clinic_name' => 'Cancun Smile Wellness Center',
                'specialty' => 'Odontología General',
                'city' => 'Cancún',
                'address' => 'Plaza Aura, Av. Huayacán, Cancún, Q.R.',
                'phone' => '9988843952',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"Álamos","website":"https:\/\/www.cancunsmile.com\/","source_channel":"website","notes":"Centro de bienestar; multi-doctor pequeño endodoncia + periodoncia + implante + maxilo + psicología infantil"}',
            ],
            [
                'name' => 'Dr. Erick Y. Saucedo Mtz',
                'clinic_name' => 'Ameridental Cancún',
                'specialty' => 'Endodoncia',
                'city' => 'Cancún',
                'address' => 'Cancún, Q.R.',
                'phone' => '9981255572',
                'has_whatsapp' => true,
                'email' => 'ameridental.cancun@gmail.com',
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"Centro","instagram":"@ameridentalcancun","website":"https:\/\/ameridentalcancun.com\/","source_channel":"website","notes":"Titular único Dr. Saucedo doble especialidad endo + implante; bilingüe español\/inglés\/ruso; 24\/7"}',
            ],
            [
                'name' => 'Dra. Lorenny Tinjacá',
                'clinic_name' => 'Dra. Lorenny Tinjacá Ortodoncia',
                'specialty' => 'Ortodoncia',
                'city' => 'Cancún',
                'address' => 'Avenida de la Luna 5, Mz 15 Lote 1, entre Oyamel y Encino, Cancún',
                'phone' => '9984404550',
                'has_whatsapp' => true,
                'email' => 'clinica@dralorennyortodoncia.com',
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"SM 44","instagram":"@dra.lorennyortodoncia","website":"https:\/\/dralorennyortodoncia.com\/","source_channel":"website","notes":"Invisalign Top Doctor + iTero Provider; cédula 12775690; titular única; IG 6.6k seguidores"}',
            ],
            [
                'name' => 'Dental Design Studio Cancún',
                'clinic_name' => 'Dental Design Studio Cancún',
                'specialty' => 'Estética Dental',
                'city' => 'Cancún',
                'address' => 'Av. Bonampak, Plaza Vía Loc V7-10, 1er piso, SM 3, 77500 Cancún',
                'phone' => '9988920777',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"SM 3","instagram":"@dentaldesignstudiocancun","website":"https:\/\/dentaldesign-studio.com\/","source_channel":"website","notes":"Multi-doctor mediano; tickets USD; sólo dental tourism US\/Canadá; borderline grande pero referencia útil"}',
            ],
            [
                'name' => 'Dra. Silvia Arias Juárez',
                'clinic_name' => 'Mis Dientes Cancún',
                'specialty' => 'Odontología General',
                'city' => 'Cancún',
                'address' => 'Calz. Tierra Maya 124, 77539 Cancún',
                'phone' => '9988456040',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"Tierra Maya","website":"https:\/\/misdientescancun.com\/","source_channel":"website","notes":"Titular Dra. Silvia 26 años exp; clínica 11 años; limpiezas + endo + prótesis + implantes; multi-doctor pequeño"}',
            ],
            [
                'name' => 'Dra. Laura',
                'clinic_name' => 'Smart Smiles Cancun',
                'specialty' => 'Estética Dental',
                'city' => 'Cancún',
                'address' => 'Cancún Zona Hotelera',
                'phone' => '9988234356',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"Zona Hotelera","instagram":"@smartsmilescancun","website":"https:\/\/smartsmilescancun.com\/","source_channel":"website","notes":"Boutique Zona Hotelera; multi-doctora chica; estética + implantes + diseño digital; tickets USD"}',
            ],
            [
                'name' => 'Dr. Emilio Cueli',
                'clinic_name' => 'Unique Clínica Dental Cancún',
                'specialty' => 'Estética Dental',
                'city' => 'Cancún',
                'address' => 'Av. Sayil esq. Bonampak SM 6 Mz 5 Lt 2, Zona Hotelera, 77503 Cancún',
                'phone' => '9988900065',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"Zona Hotelera","instagram":"@clinicuniquecancun","website":"https:\/\/clinicunique.com.mx\/","source_channel":"website","notes":"Boutique 3 titulares Cueli + Canul restaurativo + Reyes cirugía oral; pacientes internacionales"}',
            ],
            [
                'name' => 'GOLDENT Cancún',
                'clinic_name' => 'GOLDENT Cancún',
                'specialty' => 'Odontología General',
                'city' => 'Cancún',
                'address' => 'Av. Costa Maya, Región 233, Cancún',
                'phone' => '9981420203',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"Región 233","instagram":"@goldent_cancun","source_channel":"instagram","notes":"Consultorio independiente Av. Costa Maya zona popular; tickets locales clase obrera turismo"}',
            ],
            [
                'name' => 'Calident Cancún',
                'clinic_name' => 'Calident Cancún',
                'specialty' => 'Odontología General',
                'city' => 'Cancún',
                'address' => 'Plaza Galerías, Av. Tulum, Cancún',
                'phone' => '9988875640',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"Centro","website":"https:\/\/calidentcancun.com.mx\/","source_channel":"website","notes":"Plaza Galerías centro Cancún; multi-doctor pequeño multiespecialidad; tickets locales medio"}',
            ],
            [
                'name' => 'Dra. Aguilar Rivero',
                'clinic_name' => 'Pediatra Dra. Aguilar Rivero',
                'specialty' => 'Odontopediatría',
                'city' => 'Cancún',
                'address' => 'Cancún, Q.R.',
                'phone' => '9986889330',
                'has_whatsapp' => true,
                'email' => 'dra.aguilar.rivero@gmail.com',
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"Centro","website":"https:\/\/www.odontopediatracancun.com\/","source_channel":"website","notes":"Titular única odontopediatra; consultorio independiente; tickets locales"}',
            ],
            [
                'name' => 'Dra. Loretta Gaona Chávez',
                'clinic_name' => 'Odontopediatra Dra. Loretta Gaona',
                'specialty' => 'Odontopediatría',
                'city' => 'Cancún',
                'address' => 'Av. Bonampak 4 y 5 PH 3 SM 3 Mza 1, Cancún',
                'phone' => '9988832134',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"SM 3","website":"https:\/\/draodontopediatra.wixsite.com\/cancun","source_channel":"website","notes":"Titular única; junto a Starbucks Bonampak; mid-tier local"}',
            ],
            [
                'name' => 'Dra. Aniria Castellanos',
                'clinic_name' => 'Dra. Aniria Castellanos Endodoncia',
                'specialty' => 'Endodoncia',
                'city' => 'Cancún',
                'address' => 'Pabellón Bonampak Local 203, Av. Sayil SM 6, Cancún',
                'phone' => '9981903639',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"SM 6","source_channel":"google-search","notes":"Endodoncia + apical surgery; titular única UABC; cédula esp 12353904; consultorio independiente; pacientes US potencial"}',
            ],
            [
                'name' => 'Dra. Cristina Campos',
                'clinic_name' => 'Dra. Cristina Campos',
                'specialty' => 'Odontología General',
                'city' => 'Cancún',
                'address' => 'Av. Sayil Lote 2, Zona Hotelera, Cancún',
                'phone' => '9988830001',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"Zona Hotelera","source_channel":"google-search","notes":"25+ años; estética + general; titular única Zona Hotelera; tickets USD potencial"}',
            ],
            [
                'name' => 'Dra. Africa Aranda de la Torre',
                'clinic_name' => 'Dra. Africa Aranda Ortodoncia',
                'specialty' => 'Ortodoncia',
                'city' => 'Cancún',
                'address' => 'Pabellón Caribe, Av. Nichupté 22, Smza 19, Cancún',
                'phone' => '9988832929',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"SM 19","source_channel":"google-search","notes":"Ortodoncista titular única; Pabellón Caribe Av. Nichupté; tickets locales mid"}',
            ],
            [
                'name' => 'Dra. Andrea Peñuela',
                'clinic_name' => 'Smile Now Dental & Facial Care',
                'specialty' => 'Estética Dental',
                'city' => 'Cancún',
                'address' => 'Plaza San Francisco, Av. Tulum SM 11 Mz 1 Lt 1 Local 303, 77504 Cancún',
                'phone' => '9982039659',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"SM 11","instagram":"@smilenowdentalclinic","website":"https:\/\/www.smilenowdentalclinic.com\/","source_channel":"website","notes":"Estética + Invisalign Top Doctor; multi-doctor chico; rating 4.9; bilingüe; mix locales + dental tourism"}',
            ],
            [
                'name' => 'Sadentis 3D Cancún',
                'clinic_name' => 'Sadentis 3D Cancún',
                'specialty' => 'Odontología General',
                'city' => 'Cancún',
                'address' => 'Avenida Nader 2 PB, Cancún',
                'phone' => '9988871133',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"Centro","source_channel":"google-search","notes":"Centro Cancún; consultorio independiente Nader; tickets locales mid"}',
            ],
            [
                'name' => 'Dental Maya Cancún',
                'clinic_name' => 'Dental Maya Cancún',
                'specialty' => 'Odontología General',
                'city' => 'Cancún',
                'address' => 'Cancún, Q.R.',
                'phone' => '9988982273',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"Centro","source_channel":"google-search","notes":"Consultorio Centro Cancún; tickets locales clase media"}',
            ],
            [
                'name' => 'Dra. Itzel',
                'clinic_name' => 'Ortho Dental Cancún',
                'specialty' => 'Ortodoncia',
                'city' => 'Cancún',
                'address' => 'Av. Tankah SM 24 MZ 1 LT 72 Local 2, 77509 Cancún',
                'phone' => '9988841750',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"SM 24","source_channel":"google-search","notes":"Ortodoncia titular Dra. Itzel; consultorio independiente Av. Tankah; tickets locales"}',
            ],
            [
                'name' => 'Periodontics Cancun',
                'clinic_name' => 'Periodontics Cancun',
                'specialty' => 'Periodoncia',
                'city' => 'Cancún',
                'address' => 'Pabellón Caribe, Av. Nichupté Of 215, SM 19, Cancún',
                'phone' => '9988832525',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"SM 19","website":"https:\/\/periodonticscancun.com\/","source_channel":"website","notes":"Periodoncia + implantes; consultorio especializado independiente; mix locales y bilingüe"}',
            ],
            [
                'name' => 'Dental Care Puerto Morelos',
                'clinic_name' => 'Dental Care Puerto Morelos',
                'specialty' => 'Odontología General',
                'city' => 'Puerto Morelos',
                'address' => 'Puerto Morelos, Q.R.',
                'phone' => '9988791450',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"Centro","source_channel":"facebook","notes":"Consultorio independiente; tickets locales + expats; verificar cédula y propietario"}',
            ],
            [
                'name' => 'Dr. Carlos Escalante',
                'clinic_name' => 'DentalGroup Puerto Morelos',
                'specialty' => 'Odontología General',
                'city' => 'Puerto Morelos',
                'address' => 'Av. Niños Héroes SM 1 Mz 8 Lote 7 Primer Piso, 77580 Puerto Morelos',
                'phone' => '9982069157',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"SM 1","source_channel":"google-search","notes":"Multi-doctor pequeño Dr. Escalante titular; mix locales + expats nuevos; centro Puerto Morelos"}',
            ],
            [
                'name' => 'Dr. Anibal',
                'clinic_name' => 'Wellin Dentistry',
                'specialty' => 'Endodoncia',
                'city' => 'Playa del Carmen',
                'address' => '20 Av. Nte. entre Calles 24 y 26 Local 1, 77720 Playa del Carmen',
                'phone' => '9841793422',
                'has_whatsapp' => true,
                'email' => 'info@wellindentistry.com',
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"Centro","instagram":"@wellin.dentistry","website":"https:\/\/wellindentistry.com\/","source_channel":"website","notes":"Endodoncia + implantes + estética + smile design; multi-doctor pequeño; rating 5.0; bilingüe; pacientes US"}',
            ],
            [
                'name' => 'Stetic Dental Clinic Playa',
                'clinic_name' => 'Stetic Dental Clinic Playa',
                'specialty' => 'Odontología General',
                'city' => 'Playa del Carmen',
                'address' => 'Mnz. 149 Av. 10 LT7 Esq. 38, Playa del Carmen Centro 77720',
                'phone' => '9841478829',
                'has_whatsapp' => true,
                'email' => 'steticdentalplaya@gmail.com',
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"Centro","website":"https:\/\/www.steticdental.com.mx\/","source_channel":"website","notes":"Sucursal Playa de cadena Veracruz; familia + multiespecialidad; rating 5.0 con 60 reviews; mix local + dental tourism"}',
            ],
            [
                'name' => 'Dra. Christian Terrazas',
                'clinic_name' => 'Dental Playa',
                'specialty' => 'Estética Dental',
                'city' => 'Playa del Carmen',
                'address' => 'Av 10 entre Constituyentes y Calle 20, Edif. Xaman-ha Local 07, 77710 Playa del Carmen',
                'phone' => '9848730605',
                'has_whatsapp' => true,
                'email' => 'dentalplaya@gmail.com',
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"Centro","instagram":"@dentalplaya","website":"https:\/\/dentalplaya.wixsite.com\/dentalplaya","source_channel":"website","notes":"Multi-doctor pequeño 4 titulares mujeres especialistas estética + endo + perio + orto; pacientes mix local + dental tourism"}',
            ],
            [
                'name' => 'Dr. Jorge Gruber',
                'clinic_name' => 'DPG Dental Clinic',
                'specialty' => 'Endodoncia',
                'city' => 'Playa del Carmen',
                'address' => 'Av. 25 Norte esq. Calle 14 Nte, Gonzalo Guerrero, 77720 Playa del Carmen',
                'phone' => '9841005486',
                'has_whatsapp' => true,
                'email' => 'dpgclinica@gmail.com',
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"Gonzalo Guerrero","instagram":"@dpgclinica","website":"https:\/\/dpgdentalclinic.com\/","source_channel":"website","notes":"Multi-doctor 6 esp; 25+ años; pacientes US\/CA bilingüe; tickets premium dental tourism"}',
            ],
            [
                'name' => 'Dentista de Confianza CDE Playa',
                'clinic_name' => 'Dentista de Confianza CDE Playa',
                'specialty' => 'Odontología General',
                'city' => 'Playa del Carmen',
                'address' => 'Avenida 30 Norte entre Calle 28 y 30 Norte Local 1, Col. Gonzalo Guerrero, Playa del Carmen',
                'phone' => '9848076422',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"Gonzalo Guerrero","website":"https:\/\/en.cdeplaya.com\/","source_channel":"website","notes":"Multiespecialidad chica; bilingüe español\/inglés; mix locales + dental tourism; ortodoncia + odontopediatría + endo"}',
            ],
            [
                'name' => 'DentPrax Playa del Carmen',
                'clinic_name' => 'DentPrax Playa del Carmen',
                'specialty' => 'Odontología General',
                'city' => 'Playa del Carmen',
                'address' => 'Calle 12 norte 230 entre Av. 15 y 20, Centro, 77710 Playa del Carmen',
                'phone' => '8112500720',
                'has_whatsapp' => true,
                'email' => 'contacto@dentprax.com',
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"Centro","instagram":"@clinica_dentprax","website":"https:\/\/dentprax.com\/","source_channel":"website","notes":"Única clínica con Moons orto en Playa; multiespecialidad chica; tickets locales-mid + premium"}',
            ],
            [
                'name' => 'Playa Smiles',
                'clinic_name' => 'Playa Smiles',
                'specialty' => 'Ortodoncia',
                'city' => 'Playa del Carmen',
                'address' => '20 Avenida 179 esq. Calle 6, Centro 77710 Playa del Carmen',
                'phone' => '9848034585',
                'has_whatsapp' => true,
                'email' => 'playasmiles1@gmail.com',
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"Centro","website":"https:\/\/dentistplayadelcarmen.com\/","source_channel":"website","notes":"Ortodoncia + Invisalign + implantes + estética + odontopediatría; bilingüe sitio en\/es; pacientes US\/CA"}',
            ],
            [
                'name' => 'Dental Integral Playa',
                'clinic_name' => 'Dental Integral Playa',
                'specialty' => 'Odontología General',
                'city' => 'Playa del Carmen',
                'address' => 'Playa del Carmen, Q.R.',
                'phone' => '9848033420',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"Centro","website":"https:\/\/www.dentalintegralplaya.com.mx\/","source_channel":"website","notes":"5 dentistas; multiespecialidad estética + orto + perio + endo + odontopediatría; bilingüe"}',
            ],
            [
                'name' => 'Dr. Gonzalo Leiva',
                'clinic_name' => 'Art Dent Playa',
                'specialty' => 'Implantología',
                'city' => 'Playa del Carmen',
                'address' => 'Av. CTM entre Calle 10 y 15, Edif. Kuyaan Coral Suites, Col. Zazil Ha, Playa del Carmen',
                'phone' => '9842047093',
                'has_whatsapp' => true,
                'email' => 'info@artdentplaya.com',
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"Zazil-ha","instagram":"@art_dentplaya","website":"http:\/\/www.artdentplaya.com\/","source_channel":"website","notes":"Odontología digital; titular único 15+ años exp; veneers + implantes + ortodoncia invisible; tickets premium"}',
            ],
            [
                'name' => 'Dra. Berenice Somohano',
                'clinic_name' => 'Spacio Dental',
                'specialty' => 'Odontología General',
                'city' => 'Playa del Carmen',
                'address' => 'Plaza Alelor, Av. 125 entre 36 y 38 Norte, 77712 Playa del Carmen',
                'phone' => '9843222483',
                'has_whatsapp' => true,
                'email' => 'mkt@spaciodental.co',
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"Ejidal","instagram":"@spaciodental.pdc","website":"https:\/\/www.spaciodental.co\/","source_channel":"website","notes":"Familiar; titular Dra. Somohano + equipo; multi-esp pediátrica + orto + endo + cirugía + implantes; tickets locales"}',
            ],
            [
                'name' => 'Dr. Jorge Gruber',
                'clinic_name' => 'Dental Advance Playa',
                'specialty' => 'Endodoncia',
                'city' => 'Playa del Carmen',
                'address' => 'Playa del Carmen Centro',
                'phone' => '9841807705',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"Centro","instagram":"@dentaladvancepdc","website":"https:\/\/dentaladvance.mx\/","source_channel":"website","notes":"Multi-doctor pequeño 3 esp endo + orto + estética; bilingüe inglés; pacientes US"}',
            ],
            [
                'name' => 'Dr. Millán Valdivia Martín',
                'clinic_name' => 'Dental Art Center Playa',
                'specialty' => 'Estética Dental',
                'city' => 'Playa del Carmen',
                'address' => 'Av. 30 esq. Av. Constituyentes Local 1 int. Mega Soriana, 77710 Playa del Carmen',
                'phone' => '9848732819',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"Centro","website":"https:\/\/dental-art-center.com\/","source_channel":"website","notes":"Estética mínimamente invasiva; titular único; cerca Playacar; pacientes premium + dental tourism"}',
            ],
            [
                'name' => 'Dr. Jorge Iván Alcocer',
                'clinic_name' => 'Centro Dental Estético Playa',
                'specialty' => 'Odontología General',
                'city' => 'Playa del Carmen',
                'address' => 'Av. 30 Nte Local 1 entre Calle 28 y 30, Playa del Carmen',
                'phone' => '9848731010',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"Gonzalo Guerrero","source_channel":"google-search","notes":"Fundada 1994 Dr. Alcocer; multi-doctor pequeño; mix locales + tourism mid-premium"}',
            ],
            [
                'name' => 'iDent Sonrisas Riviera Maya',
                'clinic_name' => 'iDent Sonrisas Riviera Maya',
                'specialty' => 'Odontología General',
                'city' => 'Playa del Carmen',
                'address' => 'Av. Hunab Ku 16, Res. Cataluña I, 77725 Playa del Carmen',
                'phone' => '9841054653',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"Cataluña","source_channel":"google-search","notes":"Junto a CFE Hunab Ku; consultorio mid; mix locales + expats"}',
            ],
            [
                'name' => 'Dr. Mark Shtern',
                'clinic_name' => 'Dr. Mark Shtern Cancun',
                'specialty' => 'Odontología General',
                'city' => 'Cancún',
                'address' => 'C. Cielo 10, Capilla Ecuménica, 77500 Cancún',
                'phone' => '9988840303',
                'has_whatsapp' => true,
                'email' => 'patients@drmarkshtern.com',
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"Capilla Ecuménica","instagram":"@dentistincancun","website":"https:\/\/drmarkshtern.com\/","source_channel":"website","notes":"Titular Dr. Shtern; multi-doctor pequeño; bilingüe; pacientes US\/CA; sucursales en Puerto Morelos y Tulum"}',
            ],
            [
                'name' => 'Heimar Consultorio Dental',
                'clinic_name' => 'Heimar Consultorio Dental',
                'specialty' => 'Odontología General',
                'city' => 'Playa del Carmen',
                'address' => 'Av. Luis Donaldo Colosio, Playa del Carmen',
                'phone' => '9841050800',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"Luis Donaldo Colosio","source_channel":"google-search","notes":"Rating 5.0; atención español; mix locales mid"}',
            ],
            [
                'name' => 'Dra. Carolina Alejandra Soto Rivas',
                'clinic_name' => 'Zafiro Dental Clinic',
                'specialty' => 'Odontología General',
                'city' => 'Playa del Carmen',
                'address' => 'Calle 8, 77710 Playa del Carmen',
                'phone' => '9848770413',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"Centro","instagram":"@dra.carolina.soto","website":"https:\/\/www.zafirocaro.com\/","source_channel":"website","notes":"Multi-esp pequeño endo + implante + prótesis + facial; pacientes mid premium"}',
            ],
            [
                'name' => 'Gustavo López Rocha',
                'clinic_name' => 'Zama Dental Studio',
                'specialty' => 'Odontología General',
                'city' => 'Tulum',
                'address' => 'Centro Empresarial Tulum, Av. Tulum 120 Of. 203 2do piso, Tulum Centro',
                'phone' => '9843172595',
                'has_whatsapp' => true,
                'email' => 'estudiodentalzama@gmail.com',
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"Centro","instagram":"@zama.dental.studio","source_channel":"instagram","notes":"10+ años exp Dr. López; equipo bilingüe inglés; emergencias 24h; tickets premium dental tourism + expats"}',
            ],
            [
                'name' => 'Dr. Abner Zambrano',
                'clinic_name' => 'Dental Zambrano Tulum',
                'specialty' => 'Implantología',
                'city' => 'Tulum',
                'address' => 'Polar Oriente, 77760 Tulum, Q.R.',
                'phone' => '9842024681',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"Polar Oriente","website":"https:\/\/dentalzambrano.com\/","source_channel":"website","notes":"Cirugías bucales + implantología; titular único; consultorio independiente; tickets locales-mid + expats"}',
            ],
            [
                'name' => 'Dr. Roberto R. Briceño Mena',
                'clinic_name' => 'Goesur Tulum',
                'specialty' => 'Odontología General',
                'city' => 'Tulum',
                'address' => 'Calle 2 Bis Oriente entre 7 y Sur 5, Mz 18 Lt 3, Villas Tulum, 77760 Tulum',
                'phone' => '9841240853',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"Villas Tulum","instagram":"@goesur","website":"https:\/\/www.goesur.com\/","source_channel":"website","notes":"Restauración + endodoncia + ortodoncia; titular Dr. Briceño; tickets locales mid; mix locales + tourism"}',
            ],
            [
                'name' => 'Eurodental Tulum',
                'clinic_name' => 'Eurodental Tulum',
                'specialty' => 'Odontología General',
                'city' => 'Tulum',
                'address' => 'Plaza Faeli Local 5, Esq. 5 Sur y 5ta Av, La Veleta, 77760 Tulum',
                'phone' => '9842440850',
                'has_whatsapp' => true,
                'email' => 'odontologiaintegral@eurodental.mx',
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"La Veleta","instagram":"@eurodentaltulum","website":"https:\/\/eurodental.mx\/","source_channel":"website","notes":"Fundador 15 años Málaga España + ESORIB NY university; bilingüe; tickets mid premium expats europeos"}',
            ],
            [
                'name' => 'Dra. Marcela Castillo',
                'clinic_name' => 'Smile Group Tulum',
                'specialty' => 'Periodoncia',
                'city' => 'Tulum',
                'address' => 'Tulum Centro, Q.R.',
                'phone' => '9841679649',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"Centro","instagram":"@smile_grouptulum","source_channel":"instagram","notes":"Periodoncia + implantes; titular Dra. Castillo; bilingüe español\/inglés; tickets premium expat + tourism"}',
            ],
            [
                'name' => 'Dra. Adriana',
                'clinic_name' => 'Dentoria Tulum',
                'specialty' => 'Odontología General',
                'city' => 'Tulum',
                'address' => 'Av. Kukulkán 6 Local 5, 77760 Tulum',
                'phone' => '9841005959',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"Centro","instagram":"@dentoriamx","source_channel":"instagram","notes":"Multi-doctor pequeño Dra. Adriana titular + Dra. Alma + Dr. Alejandro; opera Tulum + Francisco Uh May; tickets locales + expats"}',
            ],
            [
                'name' => 'Dr. Francisco G. Reyna Anaya',
                'clinic_name' => 'Francisco G. Reyna Anaya Dental Center',
                'specialty' => 'Odontología General',
                'city' => 'Tulum',
                'address' => 'Av. Kukulkán Mz 40 Lt 5 entre Av. Tulum y Calle Mercurio Pte, La Veleta, 77760 Tulum',
                'phone' => '9841250505',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-cancun-dedup-20260427","colonia":"La Veleta","rating":"5.0","source_channel":"google-search","notes":"Rating 5.0; titular único Dr. Reyna; consultorio independiente La Veleta; mix expats + tourism"}',
            ],
        ];

        $this->command->info('Insertando ' . count($prospects) . ' dentistas del pilot (research-dentistas-cancun-dedup-20260427)...');

        $inserted = 0;
        $skipped = 0;

        foreach ($prospects as $prospect) {
            // Idempotencia por phone (último match) — no volver a insertar si ya existe
            $existing = Prospect::where('phone', $prospect['phone'])->first();
            if ($existing) {
                $skipped++;
                continue;
            }

            Prospect::create(array_merge($prospect, [
                'source' => 'prospecting', // matches SendProspectEmails cron filter
                'status' => 'new',
                'assigned_to_sales_rep_id' => 100,
                'contact_day' => 0,
                'next_contact_at' => now()->addHour(),
                'outreach_started_at' => now(),
            ]));
            $inserted++;
        }

        $this->command->info("✓ {$inserted} insertados | {$skipped} duplicados saltados | Total en seeder: " . count($prospects));
    }
}
