<?php

namespace Database\Seeders;

use App\Models\Prospect;
use Illuminate\Database\Seeder;

/**
 * Generated seeder — batch research-dentistas-qro-dedup-20260422.
 *
 * 60 dentistas descubiertos vía WebSearch + WebFetch, deduplicados contra prod.
 * Todos con teléfono MX de 10 dígitos. Asignados a Omar (user_id=100) con
 * source='prospecting' para que el cron send-prospect-emails los tome automático.
 * El batch identifier vive en notes.batch = 'research-dentistas-qro-dedup-20260422' para analytics.
 *
 * Ejecutar: php artisan db:seed --class=ProspectDentistasQROPilotSeeder --force
 */
class ProspectDentistasQROPilotSeeder extends Seeder
{
    public function run(): void
    {
        $prospects = [
            [
                'name' => 'Dr. Jorge Arias Paz',
                'clinic_name' => 'Centro Dental Querétaro',
                'specialty' => 'Odontología Estética',
                'city' => 'Santiago de Querétaro',
                'address' => 'Calz. de los Arcos 24, San Francisquito, 76058 Santiago de Querétaro',
                'phone' => '4422230199',
                'has_whatsapp' => true,
                'email' => 'contacto@centrodentalqueretaro.com',
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"San Francisquito","instagram":"@centrodentalqueretaro","website":"https:\/\/www.dentistasenqro.mx\/","source_channel":"google-search","notes":"30+ años exp; diseño sonrisa DSD; 2 sedes propias (Arcos + Juriquilla)"}',
            ],
            [
                'name' => 'Clínica Dental Juriquilla (Arte Dental)',
                'clinic_name' => 'Clínica Dental Juriquilla (Arte Dental)',
                'specialty' => 'Odontología General',
                'city' => 'Santiago de Querétaro',
                'address' => 'Clemencia Borja Taboada 512 Of. 102 Corporativo OMEGA, Juriquilla, Querétaro',
                'phone' => '4422341404',
                'has_whatsapp' => false,
                'email' => 'contacto@clinicadentaljuriquilla.com',
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Juriquilla","website":"https:\/\/www.clinicadentaljuriquilla.com\/","source_channel":"google-search","notes":"24+ años exp; clínica + laboratorio; cita previa"}',
            ],
            [
                'name' => 'Dr. Federico Chirinos',
                'clinic_name' => 'Dental Arch Clinic',
                'specialty' => 'Cirugía Maxilofacial',
                'city' => 'Santiago de Querétaro',
                'address' => 'Blvd. Universitario 560 Int. 205, Plaza Juriquilla, Jurica Acueducto, 76230 Santiago de Querétaro',
                'phone' => '4423797079',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Jurica Acueducto","instagram":"@dentalarch_juriquilla","website":"https:\/\/dentalarchclinic.com\/","source_channel":"google-search","notes":"7 doctores equipo; multidisciplinario; 1 sede"}',
            ],
            [
                'name' => 'Dr. Diego',
                'clinic_name' => 'AlineaPro Dental Querétaro',
                'specialty' => 'Ortodoncia',
                'city' => 'Santiago de Querétaro',
                'address' => 'P.º Jurica 110, Business Corner, Jurica, 76100 Santiago de Querétaro',
                'phone' => '4424952935',
                'has_whatsapp' => false,
                'email' => 'dr_diego@alineamex.com',
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Jurica","instagram":"@alineapro.dental","website":"https:\/\/www.alineamex.com\/","source_channel":"google-search","notes":"Odontología contemporánea; minimamente invasiva; 1 sede"}',
            ],
            [
                'name' => 'Dra. Maria Fernanda Islas Blas',
                'clinic_name' => 'Dentalib',
                'specialty' => 'Odontología General',
                'city' => 'Santiago de Querétaro',
                'address' => 'Calle Circuito Jdn. 16, Álamos 3ra Sección, 76160 Santiago de Querétaro',
                'phone' => '4428672226',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Álamos 3ra Sección","website":"https:\/\/dentalib.mx\/","rating":"5.0","reviews_count":"100","source_channel":"google-search","notes":"5 estrellas 100+ reseñas; 1 doctora titular; WhatsApp activo"}',
            ],
            [
                'name' => 'Dra. Maripaz Aguilar',
                'clinic_name' => 'Dentnuvó',
                'specialty' => 'Ortodoncia',
                'city' => 'Santiago de Querétaro',
                'address' => 'Av. Colinas del Cimatario 401 Consultorio 303, Torre Médica del Sur, Colinas del Cimatario, 76090 Santiago de Querétaro',
                'phone' => '4426884902',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Colinas del Cimatario","instagram":"@dentnuvo_dent","website":"https:\/\/dentnuvo.com\/","source_channel":"google-search","notes":"5 especialistas; 1 sede; ortodoncia titular"}',
            ],
            [
                'name' => 'Dr. Alain Regalado',
                'clinic_name' => 'Clínica Dental Centro Sur',
                'specialty' => 'Ortodoncia',
                'city' => 'Santiago de Querétaro',
                'address' => 'Av. Fray Luis de León 7072 Cons. 410 Torre A, Médica Momentum, Colinas del Cimatario, 76090 Santiago de Querétaro',
                'phone' => '4421798909',
                'has_whatsapp' => true,
                'email' => 'citas@clinicadentalcentrosur.com',
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Colinas del Cimatario","website":"https:\/\/clinicadentalcentrosur.com\/","source_channel":"google-search","notes":"Atención personalizada; ortodoncia + endodoncia + implantes"}',
            ],
            [
                'name' => 'Dra. Graciela Sevilla Mendoza',
                'clinic_name' => 'Dentina',
                'specialty' => 'Odontopediatría',
                'city' => 'Santiago de Querétaro',
                'address' => 'Av. Colinas del Cimatario 401 Int. 06 y 07, Torre Médica del Sur II, Colinas del Cimatario, 76090 Santiago de Querétaro',
                'phone' => '4422306860',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Colinas del Cimatario","instagram":"@dentinaqro","website":"https:\/\/dentina.mx\/","source_channel":"google-search","notes":"4 doctores titulares; odontopediatría + ortodoncia + maxilofacial"}',
            ],
            [
                'name' => 'Dra. Iveth Ramírez',
                'clinic_name' => 'Esthetic Dental Center',
                'specialty' => 'Odontología Estética',
                'city' => 'Santiago de Querétaro',
                'address' => 'Blvd. Bernardo Quintana Arrioja 15 Int. 15-2, Bosques del Acueducto, 76020 Santiago de Querétaro',
                'phone' => '4421790418',
                'has_whatsapp' => true,
                'email' => 'contacto@estheticdentalcenter.com.mx',
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Bosques del Acueducto","instagram":"@estheticdentalcentermx","website":"https:\/\/estheticdentalcenter.com.mx\/","source_channel":"google-search","notes":"All-on-X + diseño sonrisa; laboratorio propio; 1 sede"}',
            ],
            [
                'name' => 'Dr. Federico Baena',
                'clinic_name' => 'Grupo Dental Antea (Dres. Baena)',
                'specialty' => 'Implantología',
                'city' => 'Santiago de Querétaro',
                'address' => 'Centro Médico Querétaro, Santiago de Querétaro',
                'phone' => '4425955125',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Centro","instagram":"@drfedericobaenaq","website":"https:\/\/www.baenadentistaqueretaro.com\/","source_channel":"google-search","notes":"Odontología biológica integral holística; rehabilitación + implantes"}',
            ],
            [
                'name' => 'Dra. Nicole Cruz Hinojosa',
                'clinic_name' => 'Tand Clínica Dental Querétaro',
                'specialty' => 'Odontología General',
                'city' => 'Santiago de Querétaro',
                'address' => 'Violetas 50 Interior 5, Jardines de Querétaro, Santiago de Querétaro',
                'phone' => '4422410284',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Jardines de Querétaro","website":"https:\/\/tand.mx\/","source_channel":"google-search","notes":"Multiespecialidad; sede Arcos + sede Centro Santa Rosa Viterbo"}',
            ],
            [
                'name' => 'OralmaxQ Clínica Dental',
                'clinic_name' => 'OralmaxQ Clínica Dental',
                'specialty' => 'Cirugía Maxilofacial',
                'city' => 'Santiago de Querétaro',
                'address' => 'Privada Ignacio Zaragoza 16-B, Hospital H+ Torre III Piso 10 Cons. 1011-1012, Centro, 76000 Santiago de Querétaro',
                'phone' => '4422276120',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Centro","instagram":"@oralmaxqdental","website":"https:\/\/clinicaoralmaxq.com\/","source_channel":"google-search","notes":"Multiespecialidad; Hospital H+; WhatsApp activo; borderline CDMX"}',
            ],
            [
                'name' => 'Dr. Raúl José Vives Serrano',
                'clinic_name' => 'Dr. Raúl José Vives Maxilofacial',
                'specialty' => 'Cirugía Maxilofacial',
                'city' => 'Santiago de Querétaro',
                'address' => 'Av. Industrialización 7, Fraccionamiento Álamos 2a Sección, 76160 Santiago de Querétaro',
                'phone' => '4427552731',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Álamos 2a Sección","instagram":"@dr.raulvives","website":"https:\/\/www.maxilovives.com\/","source_channel":"google-search","notes":"Cirugía ortognática + trauma facial + implantes; 2 consultorios"}',
            ],
            [
                'name' => 'Dra. Miriam Morales',
                'clinic_name' => 'Odontopediatría Querétaro Dra. Miriam Morales',
                'specialty' => 'Odontopediatría',
                'city' => 'Santiago de Querétaro',
                'address' => 'Privada Ignacio Zaragoza 16, Hospital H+ Torre III Cons. 1203, Centro, Santiago de Querétaro',
                'phone' => '4421851020',
                'has_whatsapp' => false,
                'email' => 'citas@odontopediatriaqueretaro.com',
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Centro","website":"https:\/\/odontopediatraenqueretaro.com\/","source_channel":"google-search","notes":"18 años exp; certificada CNOI; 1 doctora titular"}',
            ],
            [
                'name' => 'Dra. Itzuri Herrera',
                'clinic_name' => 'HR Dental',
                'specialty' => 'Odontopediatría',
                'city' => 'El Marqués',
                'address' => 'Prol. Constituyentes Ote, Vía Catania 42, 76240 El Marqués',
                'phone' => '4425957696',
                'has_whatsapp' => true,
                'email' => 'hr.dentalop@gmail.com',
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"El Marqués","instagram":"@draitzuriherrera","website":"https:\/\/hrdental.com.mx\/","source_channel":"google-search","notes":"2 doctoras titulares; odontopediatría + ortodoncia; IG activo"}',
            ],
            [
                'name' => 'Dra. Andrea Mondragón',
                'clinic_name' => 'Thedek Zibatá',
                'specialty' => 'Odontología Estética',
                'city' => 'El Marqués',
                'address' => 'Av. Paseo de las Pitahayas A1 Local 216, Plaza Xentric Anáhuac, Zibatá, 76269 El Marqués',
                'phone' => '4428122380',
                'has_whatsapp' => true,
                'email' => 'info@thedek.mx',
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Zibatá","instagram":"@thedekmx","website":"https:\/\/thedek.mx\/","source_channel":"google-search","notes":"Boutique dental Zibatá; 6 especialistas; Invisalign; 1 sede"}',
            ],
            [
                'name' => 'Dra. María del Refugio León Rodríguez',
                'clinic_name' => 'Estética Dental Querétaro',
                'specialty' => 'Odontología Estética',
                'city' => 'Santiago de Querétaro',
                'address' => 'Av. Colinas del Cimatario 401 Piso 2 Cons. 207, Colinas del Cimatario, 76090 Santiago de Querétaro',
                'phone' => '4422482123',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Colinas del Cimatario","instagram":"@estetica_dental_queretaro","website":"https:\/\/esteticadentalqro.com.mx\/","source_channel":"google-search","notes":"19+ años exp; rehabilitación + estética + implantología"}',
            ],
            [
                'name' => 'Implantoperio',
                'clinic_name' => 'Implantoperio',
                'specialty' => 'Implantología',
                'city' => 'Santiago de Querétaro',
                'address' => 'Monjes 301 esq. Santo Domingo, Col. Carretas, Santiago de Querétaro',
                'phone' => '4422253873',
                'has_whatsapp' => false,
                'email' => 'contacto@implantoperio.com',
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Carretas","website":"https:\/\/www.implantoperio.com\/","source_channel":"google-search","notes":"Clínica exclusiva implantes + periodoncia; 1 sede"}',
            ],
            [
                'name' => 'Dr. Hugo Pacheco',
                'clinic_name' => 'Dental Mas Querétaro',
                'specialty' => 'Odontología General',
                'city' => 'Santiago de Querétaro',
                'address' => 'Av. Plateros 104, Col. Carretas, 76050 Santiago de Querétaro',
                'phone' => '4891162885',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Carretas","website":"https:\/\/dental-mas.com.mx\/","source_channel":"google-search","notes":"1 doctor titular; 2 consultorios (QRO + Chichimequillas)"}',
            ],
            [
                'name' => 'Dra. Ursula Sánchez',
                'clinic_name' => 'Dra. Ursula Sánchez Odontología Integral',
                'specialty' => 'Odontología General',
                'city' => 'Santiago de Querétaro',
                'address' => 'Paseo Constituyentes 1009 esq. Río Lerma, Corporativo Constituyentes Piso 3 Cons. 15, Santiago de Querétaro',
                'phone' => '4423671260',
                'has_whatsapp' => true,
                'email' => 'dra.ursulaso@gmail.com',
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Las Campanas","instagram":"@dra.ursulaso","website":"https:\/\/draursulasanchez.com\/","source_channel":"google-search","notes":"Odontología integral 360; IG activo; 1 doctora titular"}',
            ],
            [
                'name' => 'Clínica Wow Dental',
                'clinic_name' => 'Clínica Wow Dental',
                'specialty' => 'Odontología General',
                'city' => 'San Juan del Río',
                'address' => 'Blvrd Pablo Cabrera 60-A, Centro, 76800 San Juan del Río',
                'phone' => '4272728762',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Centro","website":"https:\/\/clinicawowdental.com\/","source_channel":"google-search","notes":"20+ años exp; multiespecialidad; 2 sedes SJR"}',
            ],
            [
                'name' => 'CD Arturo Mendoza',
                'clinic_name' => 'Clínica Dental Mendoza',
                'specialty' => 'Odontología Estética',
                'city' => 'San Juan del Río',
                'address' => 'Av. de los Patos Local 239-B, Col. Indeco, 76806 San Juan del Río',
                'phone' => '4272199311',
                'has_whatsapp' => true,
                'email' => 'citas@dentistaensjr.com.mx',
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Indeco","website":"https:\/\/dentistaensjr.com.mx\/","source_channel":"google-search","notes":"Diplomado estética dental; rehabilitación oral; 1 sede"}',
            ],
            [
                'name' => 'Orthomax Ortodoncia y Estética Dental',
                'clinic_name' => 'Orthomax Ortodoncia y Estética Dental',
                'specialty' => 'Ortodoncia',
                'city' => 'San Juan del Río',
                'address' => 'Río Moctezuma 266 Local 2-48, San Cayetano, 76806 San Juan del Río',
                'phone' => '4272742671',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"San Cayetano","website":"https:\/\/orthomax.mx\/","source_channel":"google-search","notes":"Ortodoncia + estética + endodoncia microscópica; 1 sede"}',
            ],
            [
                'name' => 'Smile Factory Corregidora',
                'clinic_name' => 'Smile Factory Corregidora',
                'specialty' => 'Ortodoncia',
                'city' => 'Corregidora',
                'address' => 'Paseo de Amsterdam 141-B, El Pueblito, Corregidora',
                'phone' => '4425384893',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"El Pueblito","website":"https:\/\/smilefactoryqro.com\/","source_channel":"google-search","notes":"Ortodoncia + urgencias + estética; 1 sede; tecnología reciente"}',
            ],
            [
                'name' => 'Ortho Q Clínica Dental',
                'clinic_name' => 'Ortho Q Clínica Dental',
                'specialty' => 'Ortodoncia',
                'city' => 'Corregidora',
                'address' => 'Lote 147 San Gabriel, San Miguelito, 76900 El Pueblito',
                'phone' => '4422538500',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"San Miguelito","rating":"5.0","source_channel":"google-search","notes":"Ortodoncia accesible; rating 5.0; 1 sede"}',
            ],
            [
                'name' => 'Dental Corregidora',
                'clinic_name' => 'Dental Corregidora',
                'specialty' => 'Odontología General',
                'city' => 'Corregidora',
                'address' => 'Gral. Pedro Lascurain 38, Centro, 76906 Corregidora',
                'phone' => '4422289020',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Corregidora","website":"https:\/\/www.dentalcorregidora.com\/","source_channel":"google-search","notes":"25+ años exp; ortodoncia + implantes; 1 sede"}',
            ],
            [
                'name' => 'Dental Center Constituyentes',
                'clinic_name' => 'Dental Center Constituyentes',
                'specialty' => 'Odontología General',
                'city' => 'Corregidora',
                'address' => 'Av. Paseo Constituyentes Pte 13-20, Pueblo Nuevo, 76900 Corregidora',
                'phone' => '4422378431',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Pueblo Nuevo","source_channel":"google-search","notes":"Consultorio privado sobre Constituyentes Corregidora"}',
            ],
            [
                'name' => 'Cedenti Dental',
                'clinic_name' => 'Cedenti Dental',
                'specialty' => 'Odontología General',
                'city' => 'Corregidora',
                'address' => 'Zona centro Corregidora',
                'phone' => '4425927213',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Corregidora","source_channel":"google-search","notes":"Dentista de confianza Corregidora; 1 sede"}',
            ],
            [
                'name' => 'Clínica Dental Smile Forever Center',
                'clinic_name' => 'Clínica Dental Smile Forever Center',
                'specialty' => 'Ortodoncia',
                'city' => 'Corregidora',
                'address' => 'Av. Candiles 615 Local L, Plaza Mariana, Misión Mariana II, 76903 Candiles, Corregidora',
                'phone' => '4429620504',
                'has_whatsapp' => true,
                'email' => 'contacto.smile.forever.center@gmail.com',
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Candiles","website":"https:\/\/www.smileforevercenter.com\/","source_channel":"google-search","notes":"Multiespecialidad; acepta seguro dental; 1 sede"}',
            ],
            [
                'name' => 'Dental Cumbres',
                'clinic_name' => 'Dental Cumbres',
                'specialty' => 'Odontología General',
                'city' => 'Santiago de Querétaro',
                'address' => 'Lago Cuitzeo 305 Int. 5, Plaza Cumbres, Cumbres del Lago, 76230 Juriquilla',
                'phone' => '4422534091',
                'has_whatsapp' => false,
                'email' => 'dentalcumbres@gmail.com',
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Cumbres del Lago","source_channel":"google-search","notes":"Consultorio Juriquilla; reseñas positivas; 1 sede"}',
            ],
            [
                'name' => 'Smile Studio Centro Odontológico Juriquilla',
                'clinic_name' => 'Smile Studio Centro Odontológico Juriquilla',
                'specialty' => 'Ortodoncia',
                'city' => 'Santiago de Querétaro',
                'address' => 'Clemencia Borja Taboada 512 Corporativo Omega 2do piso, Jurica Acueducto, Juriquilla',
                'phone' => '5539995923',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Jurica Acueducto","source_channel":"google-search","notes":"Consultorio Juriquilla; ortodoncia + integral"}',
            ],
            [
                'name' => 'Clínica de Especialidades Dentales Milenio',
                'clinic_name' => 'Clínica de Especialidades Dentales Milenio',
                'specialty' => 'Odontología General',
                'city' => 'Santiago de Querétaro',
                'address' => 'Camino Real de Carretas 211, Fracc. Milenio III, 76060 Santiago de Querétaro',
                'phone' => '4421982148',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Milenio III","source_channel":"google-search","notes":"Multiespecialidad; periodoncia + implantes + estética"}',
            ],
            [
                'name' => 'Keiko Dental House',
                'clinic_name' => 'Keiko Dental House',
                'specialty' => 'Odontología General',
                'city' => 'Santiago de Querétaro',
                'address' => 'Camino Real de Carretas 179, Milenio III, 76060 Santiago de Querétaro',
                'phone' => '4421982322',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Milenio III","instagram":"@keikodental","source_channel":"google-search","notes":"Consultorio Milenio III; zona residencial"}',
            ],
            [
                'name' => 'Bloom Dental',
                'clinic_name' => 'Bloom Dental',
                'specialty' => 'Ortodoncia',
                'city' => 'Santiago de Querétaro',
                'address' => 'Senda del Carruaje 92 Int. 3-4, Milenio III, Santiago de Querétaro',
                'phone' => '4422952121',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Milenio III","source_channel":"google-search","notes":"Ortodoncia + ATM + ortopedia maxilofacial; Milenio III"}',
            ],
            [
                'name' => 'Dra. Iris Gabriela García Delgadillo',
                'clinic_name' => 'Odontología Infantil ATN',
                'specialty' => 'Odontopediatría',
                'city' => 'Santiago de Querétaro',
                'address' => 'Senda Eterna 351, Milenio 3a Sección, 76060 Santiago de Querétaro',
                'phone' => '4421981273',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Milenio III","source_channel":"google-search","notes":"1 doctora titular; odontopediatría Milenio III"}',
            ],
            [
                'name' => 'Smile Solution Querétaro',
                'clinic_name' => 'Smile Solution Querétaro',
                'specialty' => 'Odontología General',
                'city' => 'Santiago de Querétaro',
                'address' => 'Anillo Vial Fray Junípero Serra 9390 Local 21, Plaza Quiwi Center, 76146 Santiago de Querétaro',
                'phone' => '4423793134',
                'has_whatsapp' => false,
                'email' => 'smilesolution.cafetales@gmail.com',
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"El Refugio","instagram":"@smilesolutionn","website":"https:\/\/www.smilesolution-dental.com\/","source_channel":"google-search","notes":"Servicio integral; implantes + ortodoncia + diseño sonrisa"}',
            ],
            [
                'name' => 'Dental 360°',
                'clinic_name' => 'Dental 360°',
                'specialty' => 'Odontología General',
                'city' => 'Santiago de Querétaro',
                'address' => 'Campo Real 1606, El Refugio, 76146 Santiago de Querétaro',
                'phone' => '4424714066',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"El Refugio","source_channel":"google-search","notes":"Consultorio El Refugio; amplia oferta"}',
            ],
            [
                'name' => 'Dra. Karen Moncas',
                'clinic_name' => 'Dental Happy Dek',
                'specialty' => 'Odontología General',
                'city' => 'Santiago de Querétaro',
                'address' => 'Pie de la cuesta 2111, Lomas de San Pedrito, Peñuelas, 76148 Santiago de Querétaro',
                'phone' => '4428741027',
                'has_whatsapp' => false,
                'email' => 'info@dentalhappydek.com',
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Lomas de San Pedrito","website":"https:\/\/dentalhappy.com.mx\/","source_channel":"google-search","notes":"3 doctoras titulares; integral; 1 sede"}',
            ],
            [
                'name' => 'Dra. Mariana Rodríguez Álvarez',
                'clinic_name' => 'Dra. Mariana Rodríguez Periodoncia',
                'specialty' => 'Periodoncia',
                'city' => 'Santiago de Querétaro',
                'address' => 'Av. Colinas del Cimatario 401 Cons. 204, Torre Médica del Sur, Colinas del Cimatario, 76090 Santiago de Querétaro',
                'phone' => '4426881913',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Colinas del Cimatario","instagram":"@dra.marianaroal","website":"https:\/\/periodonciaqueretaro.com.mx\/","source_channel":"google-search","notes":"Especialista periodoncia + implantología; 1 doctora titular; IG activo"}',
            ],
            [
                'name' => 'Dra. Claudia Magaly Gómez Garay',
                'clinic_name' => 'Endoperiodontología Querétaro',
                'specialty' => 'Endodoncia',
                'city' => 'Santiago de Querétaro',
                'address' => 'Cándido Avilés 107, Retablo, Constituyentes Fovissste, 76150 Santiago de Querétaro',
                'phone' => '4421266285',
                'has_whatsapp' => false,
                'email' => 'clausma2612@hotmail.com',
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Constituyentes Fovissste","website":"https:\/\/periodonciaqro.com\/","source_channel":"google-search","notes":"Endo + perio; 1 doctora titular; consultorio independiente"}',
            ],
            [
                'name' => 'Dr. Roberto Javier Ramirez Cantú',
                'clinic_name' => 'AlignUp Studio',
                'specialty' => 'Ortodoncia',
                'city' => 'Santiago de Querétaro',
                'address' => 'Anillo Vial Fray Junípero Serra 3034 Piso 9 Suite 906, Jurica Pueblo, 76100 Juriquilla',
                'phone' => '4426020635',
                'has_whatsapp' => false,
                'email' => 'dr.ramirezcantu@outlook.com',
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Jurica Pueblo","instagram":"@dr.robcantualignupstudio","website":"https:\/\/www.alignupstudio.com\/","source_channel":"google-search","notes":"1 doctor titular; ortodoncia digital + alineadores; IG activo"}',
            ],
            [
                'name' => 'Dr. Arturo Adrián Vera Velázquez',
                'clinic_name' => 'Centro de Endodoncia y Especialidades Dentales',
                'specialty' => 'Endodoncia',
                'city' => 'Santiago de Querétaro',
                'address' => '1a Calle del Laurel 123, El Laurel, 76046 Santiago de Querétaro',
                'phone' => '4422137144',
                'has_whatsapp' => true,
                'email' => 'contacto@centrodeendodoncia.com.mx',
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"El Laurel","instagram":"@centrodendodonciayespecialidad","source_channel":"google-search","notes":"4 doctores titulares (familia Vera); endo + rehab + cirugía"}',
            ],
            [
                'name' => 'Dr. J. Carlos García',
                'clinic_name' => 'Orthocreations',
                'specialty' => 'Ortodoncia',
                'city' => 'Santiago de Querétaro',
                'address' => 'Virrey de Valladolid 208 PB, Lo Virreyes, 76175 Santiago de Querétaro',
                'phone' => '4424525567',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Lo Virreyes","instagram":"@orthocreations_","website":"https:\/\/orthocreations.mx\/","source_channel":"google-search","notes":"7 doctores especialistas; multidisciplinario; 1 sede"}',
            ],
            [
                'name' => 'Orthodent Querétaro',
                'clinic_name' => 'Orthodent Querétaro',
                'specialty' => 'Ortodoncia',
                'city' => 'Santiago de Querétaro',
                'address' => 'Circuito Jardín 11 Local 1, Plaza Cobá, Álamos 3ra Sección, Santiago de Querétaro',
                'phone' => '4422429255',
                'has_whatsapp' => false,
                'email' => 'hola@orthodentqro.com',
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Álamos 3ra Sección","instagram":"@orthodentclinicadental","website":"https:\/\/orthodentqro.com\/","source_channel":"google-search","notes":"Integra todas especialidades; ortodoncia + maxilofacial"}',
            ],
            [
                'name' => 'Nelly Aide Lotina Hernández',
                'clinic_name' => 'Club Dentaloth',
                'specialty' => 'Odontología General',
                'city' => 'Santiago de Querétaro',
                'address' => 'Circuito Álamos 80 L-1, Álamos 2da Sección, 76574 Santiago de Querétaro',
                'phone' => '4423258885',
                'has_whatsapp' => true,
                'email' => 'info@dentaloth.com.mx',
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Álamos 2da Sección","instagram":"@denta_loth","website":"https:\/\/dentaloth.com.mx\/","source_channel":"google-search","notes":"Planes mensuales; diseño sonrisa + implantes; 1 sede"}',
            ],
            [
                'name' => 'Dra. Claudia Vanessa Álvarez García',
                'clinic_name' => 'Molarth Dentistas',
                'specialty' => 'Ortodoncia',
                'city' => 'Santiago de Querétaro',
                'address' => 'Sierra de Tilaco 131, Villas del Sol, Santiago de Querétaro',
                'phone' => '4421822462',
                'has_whatsapp' => true,
                'email' => 'citas@dentistasmolarth.com.mx',
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Villas del Sol","website":"https:\/\/dentistasmolarth.com.mx\/","source_channel":"google-search","notes":"2 doctores titulares; ortodoncia ULA 23 años exp; WhatsApp"}',
            ],
            [
                'name' => 'Dra. Alejandra Dorantes',
                'clinic_name' => 'Dientes & Co',
                'specialty' => 'Ortodoncia',
                'city' => 'Santiago de Querétaro',
                'address' => 'Prol. Constituyentes Ote. 5 Local 46, Plaza Mirador, El Mirador, Santiago de Querétaro',
                'phone' => '4424633383',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"El Mirador","instagram":"@dientes_co","website":"https:\/\/dientesco.com\/","source_channel":"google-search","notes":"9 doctores especialistas; multidisciplinario; 3 sedes QRO"}',
            ],
            [
                'name' => 'Dra. Alexandra Morales Santos',
                'clinic_name' => 'Alexandra Morales Odontología Integral',
                'specialty' => 'Odontología General',
                'city' => 'Santiago de Querétaro',
                'address' => 'Av. Fray Luis de León 7092 Int. 36, Plaza Nazas, Colinas del Cimatario, Santiago de Querétaro',
                'phone' => '4422218909',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Colinas del Cimatario","source_channel":"google-search","notes":"1 doctora titular; integral; consulta $750"}',
            ],
            [
                'name' => 'Dra. Tisbe Oliver Mendoza',
                'clinic_name' => 'Dra. Tisbe Oliver Mendoza',
                'specialty' => 'Odontología General',
                'city' => 'Santiago de Querétaro',
                'address' => 'Anillo Vial Fray Junípero Serra 9390, 76146 Santiago de Querétaro',
                'phone' => '4422168898',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"El Refugio","source_channel":"google-search","notes":"1 doctora titular; sala de espera cómoda; El Refugio"}',
            ],
            [
                'name' => 'Dra. Vanessa Torres',
                'clinic_name' => 'Consultorio Dental Dra. Vanessa Torres',
                'specialty' => 'Odontología General',
                'city' => 'Santiago de Querétaro',
                'address' => 'Zona Centro, Santiago de Querétaro',
                'phone' => '4424599397',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Centro","source_channel":"google-search","notes":"1 doctora titular; atención integral; consultorio privado"}',
            ],
            [
                'name' => 'Consultorio Dental Ortodoncia Luan',
                'clinic_name' => 'Consultorio Dental Ortodoncia Luan',
                'specialty' => 'Ortodoncia',
                'city' => 'Santiago de Querétaro',
                'address' => 'Cerro de la Estrella 103, Colinas del Cimatario, 76090 Santiago de Querétaro',
                'phone' => '4421831845',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Colinas del Cimatario","source_channel":"google-maps","notes":"Consultorio ortodoncia Colinas Cimatario"}',
            ],
            [
                'name' => 'Clínica Ortho Care Cimatario',
                'clinic_name' => 'Clínica Ortho Care Cimatario',
                'specialty' => 'Ortodoncia',
                'city' => 'Santiago de Querétaro',
                'address' => 'Av. Colinas del Cimatario 401 Int. 402, Colinas del Cimatario 3ra Sección, 76090 Santiago de Querétaro',
                'phone' => '4422120315',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Colinas del Cimatario","source_channel":"google-maps","notes":"Consultorio Torre Médica Colinas Cimatario"}',
            ],
            [
                'name' => 'Dra. Perea',
                'clinic_name' => 'Dentista Odontóloga Perea',
                'specialty' => 'Odontología General',
                'city' => 'Santiago de Querétaro',
                'address' => 'Colinas del Cimatario 28 A, Colinas del Cimatario, 76090 Santiago de Querétaro',
                'phone' => '4424520211',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Colinas del Cimatario","source_channel":"google-maps","notes":"Consultorio independiente Colinas Cimatario"}',
            ],
            [
                'name' => 'Centro de Especialidades Dentales Acordada',
                'clinic_name' => 'Centro de Especialidades Dentales Acordada',
                'specialty' => 'Odontología General',
                'city' => 'Santiago de Querétaro',
                'address' => 'Acordada 604, Col. Carretas, 76040 Santiago de Querétaro',
                'phone' => '4422134674',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Carretas","source_channel":"google-maps","notes":"Consultorio privado Carretas; especialidades"}',
            ],
            [
                'name' => 'Kid Y Dental',
                'clinic_name' => 'Kid Y Dental',
                'specialty' => 'Odontopediatría',
                'city' => 'San Juan del Río',
                'address' => 'Av. Universidad S/N, Hospital Omega Centro Cons. 3 Piso 3, Granjas Banthi, 76804 San Juan del Río',
                'phone' => '4271045512',
                'has_whatsapp' => true,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Granjas Banthi","website":"https:\/\/kidydental.com\/","source_channel":"google-search","notes":"Odontopediatría exclusiva; 1 sede; dentro Hospital Omega"}',
            ],
            [
                'name' => 'DentoKids San Juan del Río',
                'clinic_name' => 'DentoKids San Juan del Río',
                'specialty' => 'Odontopediatría',
                'city' => 'San Juan del Río',
                'address' => 'Av. Mármol 51, Pedregal de San Juan, 76806 San Juan del Río',
                'phone' => '4271625620',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Pedregal de San Juan","rating":"5.0","source_channel":"google-search","notes":"Odontopediatría + ortodoncia niños; rating 5.0"}',
            ],
            [
                'name' => 'Teeth-e Care Clínica',
                'clinic_name' => 'Teeth-e Care Clínica',
                'specialty' => 'Odontopediatría',
                'city' => 'San Juan del Río',
                'address' => 'Av. Lomas de San Juan 139, Lomas de San Juan, 76806 San Juan del Río',
                'phone' => '4273183962',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Lomas de San Juan","rating":"4.9","source_channel":"google-search","notes":"Odontopediatría; rating 4.9; Jardines de San Juan"}',
            ],
            [
                'name' => 'DentalPro SJR',
                'clinic_name' => 'DentalPro SJR',
                'specialty' => 'Odontología General',
                'city' => 'San Juan del Río',
                'address' => 'C. Corregidora 19, Centro, 76800 San Juan del Río',
                'phone' => '4271613370',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Centro","rating":"5.0","source_channel":"google-search","notes":"Rating 5.0; atención personalizada; acepta tarjeta"}',
            ],
            [
                'name' => 'Consultorio Dental Médica Lomas',
                'clinic_name' => 'Consultorio Dental Médica Lomas',
                'specialty' => 'Odontología General',
                'city' => 'San Juan del Río',
                'address' => 'Av. Lomas de San Juan 51, Lomas de San Juan, 76806 San Juan del Río',
                'phone' => '4272642812',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Lomas de San Juan","source_channel":"google-search","notes":"Enfoque precio-calidad; consultorio Lomas San Juan"}',
            ],
            [
                'name' => 'Clínica Dental San Martín SJR',
                'clinic_name' => 'Clínica Dental San Martín SJR',
                'specialty' => 'Odontología General',
                'city' => 'San Juan del Río',
                'address' => 'Zona centro, San Juan del Río',
                'phone' => '4272740628',
                'has_whatsapp' => false,
                'email' => null,
                'notes' => '{"batch":"research-dentistas-qro-dedup-20260422","colonia":"Centro","source_channel":"google-search","notes":"Consultorio privado SJR centro"}',
            ],
        ];

        $this->command->info('Insertando ' . count($prospects) . ' dentistas del pilot (research-dentistas-qro-dedup-20260422)...');

        $inserted = 0;
        $skipped = 0;

        foreach ($prospects as $prospect) {
            // Idempotencia por phone (último match) — no volver a insertar si ya existe
            $existing = Prospect::where('phone', $prospect['phone'])->first();
            if ($existing) {
                $skipped++;
                continue;
            }

            Prospect::create(array_merge($prospect, [
                'source' => 'prospecting', // matches SendProspectEmails cron filter
                'status' => 'new',
                'assigned_to_sales_rep_id' => 100,
                'contact_day' => 0,
                'next_contact_at' => now()->addHour(),
                'outreach_started_at' => now(),
            ]));
            $inserted++;
        }

        $this->command->info("✓ {$inserted} insertados | {$skipped} duplicados saltados | Total en seeder: " . count($prospects));
    }
}
